### ISSUE TITLE
Installation Page : Consider moving bootstrap command further down the page

### ISSUE THREAD

**Issue by alisondy** [fluxcd/flux2#1013]
when presented with the first command at 
https://toolkit.fluxcd.io/guides/installation/#bootstrap

flux bootstrap <GIT-PROVIDER> \
  --components=source-controller,kustomize-controller,helm-controller,notification-controller \
  --components-extra=image-reflector-controller,image-automation-controller \
  --path=clusters/my-cluster
  
  The user could preemptively try to run the command and get a failing result, as there is no previous mention on the page of exporting git tokens, potentially leading to errors. see below

  ```
  flux bootstrap github \                                      
  --components=source-controller,kustomize-controller,helm-controller,notification-controller \
  --components-extra=image-reflector-controller,image-automation-controller \
  --path=clusters/my-cluster
✗ name required
```
  Potential Solutions?
  
  - Append a warning that the command is not complete, you need to go to examples to find out specific flags
  - Replace the initial command with links for each variant of bootstrap so users can find the bootstrap best suited for their needs, ex gitlab personal, github personal. github org
 
  Thoughts?

**Comment by stealthybox** [comment]
If `--name` is not part of the example, that should be fixed.
Prefacing the example to mention the `--personal` flag or adding a shell comment could be another good solution.

I'm not sure how to call out the `gitlab` provider. Maybe we'd also preface that.

For generic repos that can't use bootstrap, we have a separate guide.

It's also worth noting that we have the terraform bootstrap provider, so how do we help people discover that?

**Comment by stefanprodan** [comment]
> It's also worth noting that we have the terraform bootstrap provider, so how do we help people discover that?

@stealthybox https://toolkit.fluxcd.io/guides/installation/#bootstrap-with-terraform

@alisondy the bootstrap docs are structured like this:
- intro (explains what it does and what are the common args such as components)
- GitHub
- GitLab
- Terraform

Maybe we should make it clear that the first section is an introduction? 

After @hiddeco implements the `ssh` bootstrap, I think is best to present that first as at will work no matter which Git provider you use.
