### ISSUE TITLE
Bootstrap process relies on kubectl's internal kustomize

### ISSUE THREAD

**Issue by jbergler** [fluxcd/flux2#1020]
Hi there :wave:

I'm running into an issue that is preventing me re-installing flux from a repo that was previously quite happy and working.

```
► applying sync manifests
error: rawResources failed to read Resources: Load from path helm-repositories failed: 'helm-repositories' must be a file (got d='/private/var/folders/0f/tm7986qx7l7gzn68fkwmrql80000gn/T/flux-system281569697/cluster/flux-system/helm-repositories')
```

I believe the issue stems from the following factors
- I added a directory `flux-system/helm-repositories` with a `kustomization.yaml` and included the directory as a resource in `flux-system/kustomization.yaml`
- kustomize only added support for directories as resources in v3 (when `bases` was deprecated)
- kubectl currently ships with kustomize 2.0.3
- bootstrap calls `kubectl apply -k` in [applySyncManifests](https://github.com/fluxcd/flux2/blob/main/cmd/flux/bootstrap.go#L234)

I think this raises two potential concerns:
1. `flux bootstrap` can't deploy a repo that the KustomizationController could otherwise happily apply.
2. Will flux break if kubectl 1.21 ships with kustomize v4 (see kubernetes-sigs/kustomize#1500 and kubernetes/kubernetes#98946) before the work in fluxcd/flux2#918 is complete?

**Comment by stefanprodan** [comment]
As described in the installation guide,  customising the Flux components can be done by creating a `kustomization.yaml` outside of the `flux-sytem` dir: https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

**Comment by jbergler** [comment]
That's a fair point, I hadn't connected the dots that this section of the docs might be implying that "modifications to the flux-system namespace should be done by flux itself post installation".

I'm happy for the issue to be closed if that's expected, at least it can serve as documentation if someone else runs into this.

**Comment by jbergler** [comment]
I'll go ahead and close this, I see you're the one actively working on #918 anyway so it doesn't feel like this ticket adds any value. Thanks for the quick response yesterday!

**Comment by Legion2** [comment]
In many demos of flux, flux related manifests are places into the `flux-systems` directory, so I assumed this is common practice and placed an `image-updates` directory in there, which hosts all image update automation manifests. But flux bootstrap didn't like it:
```
error: rawResources failed to read Resources: Load from path image-updates failed: 'image-updates' must be a file (got d='/tmp/flux-bootstrap-252380526/clusters/internal/flux-system/image-updates')
```

**Comment by stefanprodan** [comment]
The flux-system dir is generated by bootstrap along with a Kustomize overlay, place your custom files one level up, e.g. clusters/staging. See how to structure your repose here: https://github.com/fluxcd/flux2-kustomize-helm-example

**Comment by Legion2** [comment]
OK I see, this will be a bigger repo refactoring.

Current structure of `clusters/internal`:
```
├── autoscaler
├── aws
├── bar
├── cert-manager
├── contour
├── external-dns
├── flux-system
├── foo
├── monitoring
...
```

Current structure of `flux-systems` directory:
```
├── flux-system-patch.yaml
├── gitlab-alert.yaml
├── gitlab-notification.yaml
├── gitlab-webhook-receiver.yaml
├── gotk-components.yaml
├── gotk-sync.yaml
├── image-update-automation.yaml
├── image-updates
│   ├── image-updates-foo.yml
│   ├── image-updates-bar.yaml
│   ├── ...
│   └── kustomization.yaml
├── kustomization-configuration.yaml
├── kustomization.yaml
└── pod-monitors.yaml
```

Everything is hold together by many `kustomize.config.k8s.io/v1beta1` and only the one `kustomize.toolkit.fluxcd.io/v1beta1` in `clusters/internal/flux-systems/gotk-sync.yaml`.
