### ISSUE TITLE
Grafana Dashboards Using k8s <1.16 Metrics Labels

### ISSUE THREAD

**Issue by robert-ovens** [fluxcd/flux2#1092]
I've had problems using the GitOps Control Plane dashboard in our kube-prometheus-stack - the gauges or panels do not display data. Hunting around I found a [stackoverflow question](https://stackoverflow.com/questions/59625516/grafana-dashboard-not-displaying-pod-name-instead-pod-name) that relates to the same issue.

I'm running k8s v1.20 and the metrics used in the dashboard were removed with k8s v1.16.

https://github.com/fluxcd/flux2/blob/022576697f723667e627a0e07c1a0aec25d1b432/manifests/monitoring/grafana/dashboards/control-plane.json#L70

Replacing `kubernetes_pod_name` with `pod` and `kubernetes_namespace_name` with `namespace` fixed the dashboard.

The new metric names were [added to k8s 1.14](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#action-required-2). @stefanprodan, are you with dropping GitOps Control Plane dashboard support for K8s < 1.14? If you are, I'll submit a pull request.

Robert.

**Comment by stefanprodan** [comment]
Changing those labels would break the dashboard, see https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/prometheus/prometheus.yml#L48 

We could normalise our Prom config with kube-prometheus-stack, but will this break the dashboards for other users?

**Comment by pierluigilenoci** [comment]
@stefanprodan K8s v1.16 is EOL since 2020-09-02, it is time to move on. ;) 
Ref: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history

**Comment by xtalkme** [comment]
Also ran into this issue yesterday, it would be great to have recent labels.

**Comment by SomtochiAma** [comment]
I will pick up this issue
