### ISSUE TITLE
flux v0.9.1 installation fails on openshift 4.7

### ISSUE THREAD

**Issue by waseem-h** [fluxcd/flux2#1110]
### Describe the bug

Hi,
I'm trying to install flux v0.9.1 that deploys the source-controller as well. The problem is that the `fsGroup: 1337` in securityContext is hardcoded in both source-controller as well as kustomize-controller manifests. This makes it harder for us to deploy it via the flux install command directly. A workaround is to export the manifests and change the value but its hard to do that if we're installing it via a CI/CD pipeline or similar. Would it be possible to have a flag that allows to customize the initial manifests? Because it will be an egg chicken problem if I try to do it via Kustomize as both kustomie-controller and source-controller won't be running initially.

### To Reproduce

Steps to reproduce the behaviour:

flux install --version v0.9.1

### Expected behavior

Installation on openshift should succeed by default

### Additional context

- Kubernetes version: 1.20
- Git provider: github
- Container registry provider:

Below please provide the output of the following commands:

```cli
flux --version
flux check
kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```

**Comment by stefanprodan** [comment]
Duplicate of: https://github.com/fluxcd/flux2/discussions/1051
