### ISSUE TITLE
Add frontmatter to cli reference

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux2#1123]
For the new website we are going to need frontmatter added to the cli reference. @hiddeco already found this possible to implement using https://github.com/spf13/cobra/blob/master/doc/md_docs.md#customize-the-output

Frontmatter entries should roughly look like this:

https://github.com/fluxcd/website/pull/98/files#diff-2d810b85b1bef829d62f2e710c8c804d66d876243ca6e23fbd19513fd63a1b07

**Comment by hiddeco** [comment]
Do you have an idea how `mkdocs` reacts to frontmatter being present in a Markdown document?

**Comment by dholbach** [comment]
Looks like it's fine. I just tested it copying the `guides/notification.md` doc from fluxcd/website#98 over and  running `mkdocs serve` locally.
