### ISSUE TITLE
`flux create source git` sshkeyscan struggles with split DNS

### ISSUE THREAD

**Issue by stealthybox** [fluxcd/flux2#1125]
As seen on https://tgik.io/149, if a user is using an in-cluster repo, the outside and inside DNS names may not match.
In the demo the Windows System32 `hosts` file could have been used to make the port-forwarded DNS name match the in-cluster Service but this wasn't done.

It seems like the `flux create source git` command generates the known_hosts file for the in-cluster Secret from the host (which is the easiest way to do it).

It would be possible to exec into one of the flux controller pods, to output the `known_hosts`, and use that instead? This means the `create source git`'s generation features would rely on that particular controller running, and we'd have to consider supporting a non-default controller-namespace or even Deployment name.

We could use a Job instead, but that would have similar concerns and necessitate that an image is pullable for air-gapped env's. (could just use a flux controller image)

Alternatively, an `--extra-known-hosts` flag that could duplicate the remote public key for multiple host-names to support. This would allow the kind of create->edit hostname workflow in the demo to work since the hosts file wouldn't be messed up.
This is a very incomplete solution that I don't think we should do, and it doesn't answer for why you wouldn't just edit the hosts field in the Secret yourself aside from how inconvenient that is.

**Comment by stealthybox** [comment]
I was able to reproduce this.
You can create a source and generate a deploy key using the local DNS name, but the in cluster names for the `GitRepository` and `known_hosts` secret data field need to be fixed manually afterward.

I can confirm this workaround fixes the problem:
```shell
# install gitea in the default NS -- https://docs.gitea.io/en-us/install-on-kubernetes/
helm repo add gitea-charts https://dl.gitea.io/charts/
helm install gitea gitea-charts/gitea

# forward the web and ssh ports
kubectl port-forward sts/gitea 3000 2222:22

# create an account @ localhost:3000, then configure personal SSH/GPG keys
# create a new repo and initialize/clone it
```
```shell
# here we make the broken GitRepository related to this issue

# this fails to keyscan
flux create source git flux-system --url ssh://gitea-ssh.default/stealthybox/fleet --ssh-key-algorithm ed25519 --ssh-ecdsa-curve p521 --branch main

# this succeeds with keyscan, creating the GitRepo and Secret, but fails to fetch the repo naturally
flux create source git flux-system --url ssh://127.0.0.1:2222/stealthybox/fleet --ssh-key-algorithm ed25519 --ssh-ecdsa-curve p521 --branch main

# fix url hostname in-cluster to gitea-ssh.default
kubectl edit gitrepository -n flux-system flux-system

# get the proper known_hosts public key, copy it
kubectl get secret -n flux-system flux-system -o jsonpath={.data.known_hosts} | base64 -d

# now remove the existing `known_hosts` field and add a `stringData` field that fixes the value:
kubectl edit secret -n flux-system flux-system
```
```yaml
stringData:
  known_hosts: gitea-ssh.default ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOS1y5IKCgrkz/NjdOx6vaPpVQMBm77aJtcp3mt0Fp0EUpxIrpcoDYvi6Rd+LEtnkGH7jpPQwl5dA9gZ8VV3qyI=
```

Running `flux reconcile source git flux-system` now properly auth's and clones from gitea.

**Comment by stealthybox** [comment]
source-controller currently doesn't have `ssh-keyscan`, but kustomize-controller does:
```
k exec -it -n flux-system deploy/source-controller -- ssh-keyscan
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "8d6c2103f832e551ce202978ab48305b6c8d5603f5d8c71ea9441e5876f89d66": OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"ssh-keyscan\": executable file not found in $PATH": unknown


k exec -it -n flux-system deploy/kustomize-controller -- ssh-keyscan
usage: ssh-keyscan [-46cDHv] [-f file] [-p port] [-T timeout] [-t type]
                   [host | addrlist namelist]
command terminated with exit code 1
```

**Comment by hiddeco** [comment]
Running the command in the cluster does not seem like an option to me as it assumes that the `flux` user has access to the controller deployments, which may not be true in all scenarios (e.g. when a user is making use of _just_ `flux create source git`).

I also think this is an extreme edge-case issue that mostly (if not only) exists for demo setups, given running your Git server in the same cluster does not seem like the right thing to do with an eye on availability and disaster recoveries.

**Comment by stefanprodan** [comment]
> I also think this is an extreme edge-case issue that mostly (if not only) exists for demo setups

For edge-cases like this, people should run the flux CLI in a pod inside the cluster, we just need to document this.

I'm not for adding so much complexity to bootstrap, especially now when we are overloaded with feature requests that are way more critical than fixing some edge-case.

**Comment by stefanprodan** [comment]
Starting with flux2 v0.12.0 we publish container images with `flux` and `kubectl` on DockerHub and GitHub so people can run the bootstrap from inside the cluster.
