### ISSUE TITLE
Move toolkit.fluxcd.io to netlify

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux2#1135]
In preparation for moving the docs into `f/website`, @stefanprodan suggested we move the docs to Netlify, so we can fix up redirects between the sites within Netlify more easily.

**Comment by dholbach** [comment]
The Netlify app needs access to `f/flux2` - I just sent a request.

**Comment by hiddeco** [comment]
Your request has been approved.

**Comment by dholbach** [comment]
- [ ] change the netlify dns settings
- [ ] stop the deploy to gh-pages
- [ ] update GH settings accordingly
