### ISSUE TITLE
feat: helm chart for flux2 / gitops-toolkit stack and components

### ISSUE THREAD

**Issue by dmccaffery** [fluxcd/flux2#1136]
For larger enterprises and teams with centrally managed governance models, helm has become a preferred mechanism for managing and maintaining deployments of infrastructure-level components such as flux, prometheus, grafana, etc. We require all third-party images to be pulled, scanned, and pushed to internal repositories for security and continuity reasons (as an example). We also deploy some of these components to separate namespaces with different deployment governance.

While we could pull this off in some form with self-hosted kustomizations it would require change in our workflow and close adherence to upstream changes; neither of which is ideal at scale.

I'm happy to contribute to and help maintain these charts. I've actually done so for the source-controller repository and will be submitting a WIP PR shortly to support further collaboration and discussion on the approach.

At a high level, my current methodology is:

1. chart should be derived from the existing kustomization (rbac, crds, etc) as much as possible to avoid duplicate work / maintenance overhead
2. e2e tests should evaluate charts in addition to kustomization-based deploy
3. charts should follow best practices for service account / rbac configuration (no default sa)
4. charts should follow best practices for label/annotations
5. charts should support node selectors / affinity

Are there any thoughts around this from the maintainers / community where helm is intentionally being avoided? Some outstanding questions are:

1. should the "rollup" stack chart live in flux2 repository, or elsewhere?
2. where should we publish the charts -- should this be a registry in GitHub pages somewhere?
3. should pod security policy / network policy support be part of the chart(s)? -- what about pod disruption budgets?

**Comment by dmccaffery** [comment]
Draft PR (for reference): https://github.com/fluxcd/source-controller/pull/314

**Comment by stefanprodan** [comment]
Installing Flux with Helm is not something that we are considering at this point, see https://github.com/fluxcd/flux2/discussions/431
