### ISSUE TITLE
Automation Controller not shown in Grafana Dashboard

### ISSUE THREAD

**Issue by Legion2** [fluxcd/flux2#1172]
### Describe the bug

The Grafana Dashboards provided [here](https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/grafana/dashboards) do not show the image automation controller and the image reflector controller.
This is because both do not provide the `process_cpu_seconds_total` prometheus metric when installed with the `flux bootstrap` command.

### To Reproduce

Steps to reproduce the behaviour:

1. run `flux bootstrap` with `--components-extra=image-reflector-controller,image-automation-controller`
2. import the "GitOps Toolkit Control Plane" grafana dashboards into existing grafana which is connected to an existing prometheus instance
3. open the dashboard
4. see that only 4 controllers are displayed, but with the image automation it should be 6

### Expected behavior

All controllers of the GitOps Toolkit should be shown in the grafana dashboard

### Additional context

- Kubernetes version: `v1.18.9-eks-d1db3c`
- Git provider: gitlab
- Container registry provider: -

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.11.0
flux check
► checking prerequisites
✔ kubectl 1.19.7 >=1.18.0-0
✔ Kubernetes 1.18.9-eks-d1db3c >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.7.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.7.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.10.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.11.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.10.0
✔ all checks passed

kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```

**Comment by nomeelnoj** [comment]
Not sure what you are seeing, I am definitely getting all 6 controllers with the default "control plane" dashboard.  As you can see in this example grafana query: https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/grafana/dashboards/control-plane.json#L70, the queries all filter objects based on the `flux-system` namespace and the pod name `.*-controller-.*`, which are the defaults.  The dashboard works as designed for me.

**Comment by Legion2** [comment]
Oh, I forgot to add the `PodMonitor` for the image automation controllers.
