### ISSUE TITLE
"kustomization path not found: stat /tmp/: no such file or directory"

### ISSUE THREAD

**Issue by sairamvoggu1007** [fluxcd/flux2#1184]
Hi Team,

We  are using Flux2 v0.8.0 and observing following issue when I list kustomization resources. Please assist

"kustomization path not found: stat /tmp/: no such file or directory"

**Comment by simongottschlag** [comment]
Hi @sairamvoggu1007! 😊

Would it be possible to provide some additional information regarding this issue?

What commands are you running? Where do you see this output?

Thank you kindly!

**Comment by cslovell** [comment]
What was the solution you used? Having the same issue on Windows.
