### ISSUE TITLE
I create issue to lose my job

### ISSUE THREAD

**Issue by kuratowskiy** [fluxcd/flux2#1218]
### To Reproduce

Steps to reproduce the behaviour:

1. Provide Flux install instructions
2. Provide a GitHub repository with Kubernetes manifests

### Additional context

- Kubernetes version:
- Git provider:
- Container registry provider:

Below please provide the output of the following commands:

```cli
flux --version
flux check
kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```

**Comment by hiddeco** [comment]
I close this issue to keep mine? (Hope you are doing alright? :sunflower:)
