### ISSUE TITLE
Things to do post docs-move

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux2#1221]
Once tasks like #1135 (plus redirects) and fluxcd/website#110, etc are handled, we will be in a position to remove the docs from this repository. 

BUT we should

- [x] explain in our docs and code where to address docs fixes, etc.
- [x] add "how to do docs" to contributors guide
- [x] ensure we DO NOT delete https://github.com/fluxcd/flux2/blob/main/docs/internal/release.md (linked to in the CII bits)
- [x] make sure we at the very least keep deploying the `_redirects` file

**Comment by hiddeco** [comment]
We have stopped automatically deploying the `_redirects` file, but it can always be triggered manually using the Netlify UI (including builds for branches). Question is if we can remove almost all of the static site build logic so that only the `_redirects` remains.

**Comment by dholbach** [comment]
https://github.com/fluxcd/flux2/pull/1363 - wdyt?
