### ISSUE TITLE
Computing Status with kstatus gives misleading Result

### ISSUE THREAD

**Issue by jonathan-innis** [fluxcd/flux2#1254]
### Describe the bug

`kstatus` package provides a way to `status.Compute` the `status.Result` of a given CR. When performing `status.Compute` on the Gitops Toolkit CR `conditions`, `status.Compute` returns `InProgress` when the resource appears to be in a failed state. 

kstatus checks the `Ready` condition. If the resource does not have this set to `true`, kstatus is unable to compute a status and returns `InProgress` for the Result which seems different than the expected Result `Failed`

kstatus docs include this bit about the ready condition being false
```
// - There is no way to determine if a resource with the Ready condition
// set to False is making progress or is doomed.
```

### To Reproduce

Steps to reproduce the behaviour:

1. Deploy a GitRepository CR with a repo url that doesn't exist (or any other scenario that would lead to a Gitops Toolkit CR to be in failed state)
2. Run the following on the CR:
```go
content, _  := runtime.DefaultUnstructuredConverter.ToUnstructured(obj)
unstructured := unstructured.Unstructured{}
unstructured.SetUnstructuredContent(content)
res, _ := status.Compute(&unstructured)
```

### Expected behavior

kstatus's `status.Compute` should return `Failed` when the Gitops Toolkit CR is in a failed state (i.e. unable to clone the repo, unable to apply the kustomization, etc.)

```bash
joinnis@DESKTOP-PMUFP6M:~$ flux --version
flux version 0.12.1
joinnis@DESKTOP-PMUFP6M:~$ flux check
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0-0
✔ Kubernetes 1.19.1 >=1.16.0-0
► checking controllers
✔ all checks passed
```

**Comment by stefanprodan** [comment]
Use this package to determine the Flux CRs status https://github.com/fluxcd/flux2/blob/main/pkg/status/status.go

**Comment by squaremo** [comment]
Forgive me if I'm putting words in your mouth @jonathan-innis, but I think the issue is specifically about being compatible with kstatus, rather than not being able to determine status at all.

kstatus is (becoming) the standard, general-purpose means of determining resource status. If Flux v2 were compatible with kstatus, rather than having its own way of doing things, then it would work with things that use kstatus and not require people to make a special case for it.

**Comment by jonathan-innis** [comment]
@squaremo that's correct. I can roll my own status checker as well based on what I assume to be the status standard for Flux; however, there seems to be some gap between what kstatus expects and what Flux CRs are sending

**Comment by stefanprodan** [comment]
> If Flux v2 were compatible with kstatus, rather than having its own way of doing things, then it would work with things that use kstatus and not require people to make a special case for it.

Flux is compatible with kststus in the same way Kubernetes Pods are. The link I posted above is an example of how we use kststus, also kustomize-controller uses kststus for health checking of other Flux CRs.

**Comment by stefanprodan** [comment]
One way to avoid relying on the timeout (like we do in [here](https://github.com/fluxcd/flux2/blob/main/pkg/status/status.go)) is by introducing two new conditions Reconciling and Stalled. We've discussed this before and to me they seem redundant, also updating the status while reconciling means we'll be running into more generation conflicts. Anyway I'm not going to fight this if @squaremo and @hiddeco vote for this change.

**Comment by squaremo** [comment]
The problem is that a Ready condition on its own is ambiguous, if you are only looking at whether it's present and what the value is, as kstatus does. Using a `Stalled` condition when application fails would 1. not add to the number of updates, since the ready condition is already updated in the same places; and 2. not be redundant, since it distinguishes between "not ready yet" and "failed".

**Comment by stefanprodan** [comment]
@squaremo are you saying that `Stale` alone would work with kstatus without `Reconciling`?

**Comment by squaremo** [comment]
> are you saying that `Stale` alone would work with kstatus without `Reconciling`?

Honestly I don't know -- I'm interpreting [what kstatus say about abnormal-true conditions](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#conditions), but it's a bit vague there. I think it's worth a quick experiment to see -- @jonathan-innis maybe you could try adding a `Stalled` condition in kustomize-controller to see if kstatus draws the right conclusions?

**Comment by SomtochiAma** [comment]
@squaremo @stefanprodan  `Stalled` works with `kstatus` without `Reconciling`.

**Comment by SomtochiAma** [comment]
Starting off with the kustomize-controller @ [kustomize-controller#325](https://github.com/fluxcd/kustomize-controller/pull/325)
