### ISSUE TITLE
Support strict semver ranges

### ISSUE THREAD

**Issue by jagguli** [fluxcd/flux2#1298]
### Describe the bug

imagepolicy using  semver does not support build numbers

### To Reproduce

Steps to reproduce the behaviour:
1. Create a imagepolicy with 
```
semver:
  range: '>=2.0.300'
```
2. tag image with `2.0.330-63-gc1cfb6864`
3. flux get images shows `no image found for policy`

### Expected behavior

flux get images should  show `2.0.330-63-gc1cfb6864`

`2.0.330-63-gc1cfb6864`  a valid semver
https://jubianchi.github.io/semver-check/#/constraint/2.0.330-63-gc1cfb6864

### Additional context

- Kubernetes version: 
- Git provider: gitlab
- Container registry provider: azure conntainer registry

Below please provide the output of the following commands:

```cli
flux --version
flux check
flux version 0.12.3
► checking prerequisites
✔ kubectl 1.20.5 >=1.18.0-0
✔ Kubernetes 1.17.13 >=1.16.0-0
► checking controllers
✔ all checks passed

kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```

**Comment by stefanprodan** [comment]
Please read the semver spec: https://semver.org/

`2.0.330-63-gc1cfb6864` is a prerelease according to semver spec so you need to define the range like so `>=2.0.300-0`, more examples here: https://toolkit.fluxcd.io/components/image/imagepolicies/#examples

**Comment by jagguli** [comment]
I'm still havving issues.

current lates image tag inn repo is 

`3.1.1-2-g21b6e017a`

range is 

`>=3.1.1-1`

but flux still resolves to 

`3.1.1`

**Comment by stefanprodan** [comment]
Yes because that’s how semver works, please read the spec https://semver.org/

**Comment by jagguli** [comment]
Ah so I would need to tag 3.1.2-0 to get it to resolve 

pre-release has a lower precedence ... duh
https://semver.org/#spec-item-11

thanks!
