### ISSUE TITLE
Any plan on supporting passphrase protected ssh keys

### ISSUE THREAD

**Issue by ayushghosh** [fluxcd/flux2#1401]
most of our team's ssh keys have to be password protected.  Any plans on supporting password-protected ssh keys in the future.

Or any tricks, best practices

**Comment by hiddeco** [comment]
We do support SSH keys with passphrases, see #1314.

**Comment by ayushghosh** [comment]
@hiddeco Sorry for the confusion, I was looking to use an ssh key with a passphrase for the bootstrap process.  

It gives me the error "✗ ssh: this private key is passphrase protected"

**Comment by stefanprodan** [comment]
@ayushghosh can you specify the flux version you’re using? it’s `flux -v`

**Comment by hiddeco** [comment]
Can you provide the full output of the command? In addition, is this command targeted against an already bootstrapped cluster or a completely new one?

**Comment by ayushghosh** [comment]
@hiddeco "✗ ssh: this private key is passphrase protected" is the complete output.

It's a new cluster in k3d, created flux-system namespace with secret "credential" with ssh key and password. Then the bootstrap command. It fails irrespective of the cluster has the initial flux commits in bootstrap. Works fine if a passwordless ssh key is used in bootstrap arg --private-key-file .
