### ISSUE TITLE
bug: MacOS gpg 2.3.1, sops 3.6.1/3.7.1, and flux versions "invalid key size 0" failure

### ISSUE THREAD

**Issue by neoakris** [fluxcd/flux2#1414]
NOTE: This might not be a flux issue. Maybe it's a gpg upstream issue, but I want to document it here for future googlers. 

### Describe the bug
1. A Mac user runs `brew install gnupg` version 2.3.1 gets installed.

2. User creates a gpg keypair
```
gpg --batch --gen-key <<EOF
    %echo Generating a gpg key
    Key-Type: RSA
    Key-Length: 4096
    Subkey-Type: RSA
    Subkey-Length: 4096
    Name-Real: $NAME
    Name-Comment: for use in $NAME's big bang dev environment
    Name-Email: $NAME@bigbang.dev
    Expire-Date: 0
    %no-ask-passphrase
    %no-protection
    %commit
    %echo done
EOF
```

3. User exports the keypair and turns it into a secret for flux to use for decryption.
`gpg --armor --export-secret-keys $KEYPAIR_FINGERPRINT > ~/$NAME-bigbang-gpg-keypair.dev`
```
... (some steps ommited) ...
temp="""
kind: Secret
metadata:
  name: sops-gpg
  namespace: bigbang
type: Opaque
apiVersion: v1
data:
  bigbangkey: $base64ed_gpgkeypair
"""
echo "$temp" | kubectl apply -f -
```

4. When flux tries to leverage this for decryption operations They'll see this error message:
```
Bash# kubectl get kustomization environment -n=bigbang
# NAME          READY   STATUS                                                                                                                                   AGE
# environment   False   decryption failed for 'common-bb-4g47bgmkdb': AES decrypt: Error walking tree: Could not decrypt value: crypto/aes: invalid key size 0   30s
```

If Mac user downgrades to gpg 2.2.27 (the LTS version of gpg), and uses sops to permanently decrypt file being referenced, permenently reencrypt file being referenced, push reencrypted file to git repo, and flux reconcile --with-source, the issue remains. 

If Mac user downgrades to gpg 2.2.27 and recreates the gpg keypair using 2.2.27, edits the .sops.yaml to reference the new gpg keypair, leverages sops reencrypt/rotate credentials, and updates the gpg keypair secret in kubernetes to use a gpg key pair that was generated with mac gpg 2.2.27 (instead of mac gpg 2.3.1), then it works fine. (I'm not sure if it's a gpg 2.3.1 issue or a mac gpg 2.3.1 issue as linux distros don't seem to have that as an easy option.) 

Note: I suspect that if the gpg keypair was generated by gpg 2.0.x or 2.2.x, and then gpg 2.3.1 was just used for importing the keypair, it might be ok. (Just a theory atm, but if that works then maybe it'd be a good idea to create a tool like a docker container that generates a gpg keypair)

Note: I haven't seen any issues with gpg keypairs created using the version of gpg that ships with:      
* Ubuntu 20.04 LTS  --> gpg 2.2.19
* RHEL7 --> gpg 2.0.22
* RHEL8 --> gpg 2.2.20        
(These OS's don't seem to even offer gpg 2.3.x, w/o jumping through hoops)

### To Reproduce
Steps to reproduce the behaviour:
(would require too many steps I'm hoping the above gives enough details)

### Expected behavior
Flux to be able to decrypt gpg encrypted secrets using a gpgkey pair loaded as a secret. 

### Additional context
- Git provider: pure cli/ssh based git repo (no web gui), just a git repo in the form of files and folders on disk in the git users home directory. 
- Container registry provider: registry1.dso.mil (A copy of flux exists in here, the container image versions are listed in the following link)
https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/1c3a523a5ebc6654a98d7326668c1a6cb02c0727/scripts/deploy/flux.yaml

Below please provide the output of the following commands:
```cli
flux --version
flux check

flux cli version 0.13.1
registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.9.0
registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.9.3
registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.12.0
registry1.dso.mil/ironbank/fluxcd/source-controller:v0.9.1

kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
# Didn't capture when the issue occured
```

**Comment by sc250024** [comment]
I'm having the same problem:

- `sops 3.7.1 (latest)`
- `flux version 0.15.2`
- `k3d version v4.4.6`

I also tried with Docker Desktop with the same error.

@neoakris Did you find the source of the error? I suspect it's a misconfiguration on my side, but based on your example, it might also not be.

**Comment by jarrettprosser** [comment]
I'm seeing the same issue. I'm creating encrypted files on Mac with `sops 3.7.1` and `gpg 2.3.1`. When I try to decrypt them using a container that has `gpg 2.2.20`, I get `crypto/aes: invalid key size 0`.

As @neoakris said, downgrading my local gpg version to 2.2, creating a new key, reencrypting the files using the new key, and pushing the updated files would get the decryption working again. 

Perhaps the underlying issue is related to the change in `gpg 2.3` which [switched the default key](https://lists.gnupg.org/pipermail/gnupg-announce/2021q2/000458.html) to ed25519/cv25519. All of my previous encryption keys had been created as rsa key?

**Comment by neoakris** [comment]
Also noteworthy is it seems a new version of flux requires the key to have .asc extension

**Comment by neoakris** [comment]
I forgot about Jarrett's post above, and just kind of retried as it'd been a while and flux had received lots of updates. 

**Mini status update since it's been ~10 months:** 
latest versions still result in (almost) the exact same original error. 
Mac gpg version 2.3.4 
sops 3.7.1
flux 0.27.2 

```shell
Bash# kubectl get kustomization environment -n=bigbang
# NAME          READY   STATUS                                                                                                                                          AGE
# environment   False   decryption failed for 'public-cert': DataWithFormat: AES decrypt: Error walking tree: Could not decrypt value: crypto/aes: invalid key size 0   15h
```

Also Mozilla's been having funding issues so the issue in the sops project is unlikely to get attention anytime soon. For now I'll stay pinned to old versions (or use the Mac gpg 2.3.x workaround mentioned [here in the thread jarrettprosser shared above](https://github.com/mozilla/sops/issues/896#issuecomment-915347995)) and eventually plan to transition to AGE. 
(AGE: Actually Good Encryption) 
https://nixfaq.org/2021/01/age-the-modern-alternative-to-gpg.html

Age seems future proof/less likely to have bugs in the future since it has a go and rust implementation, where as gpg is written in c. 

I'm going to close this issue though as I now realize that it's not a flux issue/they won't be able to fix it if I leave it open/it's more of an issue with flux's upstream dependencies: sops & gpg

**Comment by neoakris** [comment]
gpg 2.3.x keygen workaround is documented here: 
https://github.com/mozilla/sops/issues/896#issuecomment-1059263577
