### ISSUE TITLE
Insufficent Error Messaging

### ISSUE THREAD

**Issue by jared-wilkinson** [fluxcd/flux2#1426]
### Describe the bug

When using a token for GitLab (or presumably any other git source with token auth), if the token is revoked or expires, the error message in the `Gitrepositories` object is `error: repository not found`. It would be way more helpful if the error indicated an authentication issue and not something with the path to the repo. Not sure though if that error message is coming directly from the `git clone` or if this is something that can be fixed in the flux code.

### To Reproduce

Steps to reproduce the behaviour:

1. Use token auth when bootstrapping a cluster.
2. Revoke the token so it's no longer valid.
3. See the error message in the flux-system Gitrepositories CRD.
4. 
### Expected behavior

When an authentication error happens with git, return a message indicating an authentication issue in the Gitrepository object condition message.

### Additional context

- Kubernetes version: 1.18
- Git provider: GitLab
- Container registry provider: GitLab

Below please provide the output of the following commands:

```cli
flux version 0.9.1

flux check
► checking prerequisites
✗ flux 0.9.1 <0.13.4 (new version is available, please upgrade)
✔ kubectl 1.18.6 >=1.18.0-0
✔ Kubernetes 1.18.9-eks-d1db3c >=1.16.0-0
► checking controllers
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.8.1
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.9.2
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.9.0
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.9.0
✔ all checks passed

kubectl -n <namespace> get all
NAME                                           READY   STATUS    RESTARTS   AGE
pod/helm-controller-5cf7d96887-wjsq2           1/1     Running   0          63d
pod/kustomize-controller-8584bbcd7-xlzkn       1/1     Running   0          63d
pod/notification-controller-769876bb9f-k88w8   1/1     Running   0          63d
pod/source-controller-c55db769d-4rc5p          1/1     Running   0          63d

NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/notification-controller   ClusterIP   172.20.87.11     <none>        80/TCP    63d
service/source-controller         ClusterIP   172.20.58.140    <none>        80/TCP    63d
service/webhook-receiver          ClusterIP   172.20.158.140   <none>        80/TCP    63d

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/helm-controller           1/1     1            1           63d
deployment.apps/kustomize-controller      1/1     1            1           63d
deployment.apps/notification-controller   1/1     1            1           63d
deployment.apps/source-controller         1/1     1            1           63d

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/helm-controller-5cf7d96887           1         1         1       63d
replicaset.apps/kustomize-controller-689774778b      0         0         0       63d
replicaset.apps/kustomize-controller-8584bbcd7       1         1         1       63d
replicaset.apps/notification-controller-769876bb9f   1         1         1       63d
replicaset.apps/source-controller-c55db769d          1         1         1       63d
```

**Comment by kingdonb** [comment]
This is tricky, typically you will see this kind of behavior when "revealing the existence of the protected resource" is considered a failure to protect the private resource.

If you try to access a private resource with an invalid auth credential, and the response is anything but "404", this can potentially reveal the existence of the secret thing. I suspect this is the error that Flux shows in this case, simply because that's exactly how GitLab responds.

**Comment by jared-wilkinson** [comment]
Ah ok, that makes sense. I'll close this. Thanks for the quick response!
