### ISSUE TITLE
Combined changelog

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux2#143]
It'd be great to have a combined changelog of what's been happening in the GitOps Toolkit parts, so you don't have to go around chase in all `*-controller` projects.

**Comment by stefanprodan** [comment]
The automation could follow the links that FluxBot creates in the update PR, parse each `CHANGELOG.md` and extract the version specified in the link. Much bash needed...

**Comment by hiddeco** [comment]
Think it would be more sustainable to not go the bash-scripted route and instead figure out how we want to create the changelog in a more automated way for sub-projects, and how this information can be re-used when the changelog for the binary is generated.
