### ISSUE TITLE
Automated image updates are not possible trough kustomize

### ISSUE THREAD

**Issue by Troyhy** [fluxcd/flux2#1460]
Kustomize will strip out all line-comments and  `# {"$imagepolicy": "flux-system:podinfo:name"}` gets removed

The documentation states that it should work:
https://fluxcd.io/docs/guides/image-update/#configure-image-update-for-custom-resources
but I see no way this can work.

Is there any fallback to annotation-based image replacement?

**Comment by stefanprodan** [comment]
Flux run the kustomize build for you, in Git you should store the Kustomize config file and the overlays, not the final YAML generated with kustomize build.

**Comment by Troyhy** [comment]
I'm storing only kustomize config and overlays in git. After I push flux2 detects new a version and generates resources.

When I look at generated resources in the cluster the comment is missing. 

 Am I missing something here?

**Comment by stefanprodan** [comment]
> When I look at generated resources in the cluster the comment is missing.

This has no relevance to Flux, Flux looks at the files in Git not in-cluster.

**Comment by Troyhy** [comment]
Ok, Thanks for the support @stefanprodan got it working now..  I got mixed up when the comments were not visible :disappointed:
