### ISSUE TITLE
"flux install" overrides existing service account

### ISSUE THREAD

**Issue by artem-nefedov** [fluxcd/flux2#1485]
My case is to give source controller an access to S3 bucket through IAM role associated with service account, for which purpose I create iam serviceaccount with `eksctl` before installing flux. It sort-of works, because `flux install` doesn't override `eks.amazonaws.com/role-arn` annotation, but I get the `Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply`. A better way would be to disable creation of a service account and use existing one instead. As an additional note, it's very common pattern in `helm` charts to have the feature of using existing service account.

**Comment by stefanprodan** [comment]
That's just an warning from kubectl, why are you saying that it doesn't work?

**Comment by artem-nefedov** [comment]
It does "work", but `flux install` ignores the fact that service account already existed and claims it as its own. This causes the problems beside kubectl warnings: when you run `flux uninstall`, it will delete that service account. If service account was created by another tool like `eksctl`, it's expected that it will be managed by that tool.

**Comment by stefanprodan** [comment]
You can do `flux install --export > install.yaml` then use a Kustomize patch to remove the service account from the manifests before you apply them with kubectl.
