### ISSUE TITLE
Graceful handle github ratelimiting.

### ISSUE THREAD

**Issue by rverma-nsl** [fluxcd/flux2#1487]
Sometime for same strange reason when using raw urls from git,  the response yaml are being throttled and we receive a github response body in place of actual yaml. 

in that case flux will show message like
```
observability   observability      False   kustomize build failed: accumulating resources: 2 errors occurred:
                * accumulateFile error: "accumulating resources from 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml': YAML file [https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml] encounters a format error.\nerror converting YAML to JSON: yaml: line 13: mapping values are not allowed in this context\n"
                * loader.New error: "git cmd = '/usr/bin/git fetch --depth=1 origin HEAD': exit status 128"

```

Inplace of these ,it would be nice to simply ignore the reconcile, sleep and retry after sometime.
One awesome feature would be to in the cli show throttling as a status :)

**Comment by stefanprodan** [comment]
Instead of using remote bases you could use a GitRepository object, this way the manifests are cached in-cluster by Flux.

**Comment by stefanprodan** [comment]
Going to close this, this is kustomize issue so reach out to them.
