### ISSUE TITLE
Flux to skip reconciliation based on namespace tag or provide ability to avoid reconciliation of replicas.

### ISSUE THREAD

**Issue by rverma-nsl** [fluxcd/flux2#1513]
We are using https://codeberg.org/hjacobs/kube-downscaler to downscale our cluster in non working hours. Although if someone is working in weekend they can manually bringup a particular namespace by annotating that namespace like forced-uptime = true.

One of the major challenge is that when the downscaler has scaled down we need to scaledown flux too since otherwise flux is continuously trying to bringup replicas to the initial values. Now if some team need to work on weekend, as soon as he bringup flux, it create a race condition where flux is continuously scaling to specified replicas and downscaler is scaling down to zero.

To avoid this, we are thinking if flux can also read the namespace annotation whose kustomization or helmrelease it is syncing and skip the reconciliation if the namespace contains the tag.

**Comment by hiddeco** [comment]
Flux does not overwrite and/or reset what isn't declared. This means that if you do not provide replica counts in your manifest, Flux will not scale up (or down) your cluster.

**Comment by stefanprodan** [comment]
You can suspend the reconciliation of both Flux Kustomization and Helm Releases with `spec.suspend` during non working hours.
