### ISSUE TITLE
ACR credentials sync: Can't create secret due to the default role setup

### ISSUE THREAD

**Issue by molszews** [fluxcd/flux2#1524]
### Describe the bug

https://github.com/fluxcd/flux2/blob/main/manifests/integrations/registry-credentials-sync/_base/sync.yaml#L104

This should not be enabled by default as:
```
Note: You cannot restrict create or deletecollection requests by resourceName. For create, this limitation is because the object name is not known at authorization time.
```
(https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources)

The effect is k8s can't create such secret due to insufficient privileges (it took me some time to figure out the real reason)

`error: failed to create secret secrets is forbidden: User "system:serviceaccount:flux-system:default" cannot create resource "secrets" in API group "" in the namespace "flux-system"`

**Comment by NissesSenap** [comment]
I will take a stab at a fix for it
