### ISSUE TITLE
Bootstrap ignores the `reconcile` flag

### ISSUE THREAD

**Issue by rhart** [fluxcd/flux2#1533]
### Describe the bug

When trying to boostrap into an existing GitHub repo, even when supplying the `reconcile` flag, I get an error because the repo already exists.

```
✗ failed to create new Git repository "https://github.com/****/****": multiple errors occurred:
- POST https://api.github.com/orgs/****/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]
- resource already exists, cannot create object. Use Reconcile() to create it idempotently
```

### To Reproduce

Steps to reproduce the behaviour:

1. Create a GitHub repo e.g. foo/bar
2. Run `flux bootstrap github --owner=foo --repository=bar --private=true --path=clusters/my-cluster --reconcile="true"`

### Expected behavior

Bootstrap should use the existing repo and not try to create a new one.

### Additional context

- Git provider: GitHub

Below please provide the output of the following commands:

```cli
flux version 0.15.0
```

**Comment by stefanprodan** [comment]
I can't reproduce your error, as a workaround you can use `flux bootstrap git`, that assumes the repository is created in advance.

**Comment by rhart** [comment]
Thanks for the quick response @stefanprodan. I'll double check my issue then and use the workaround if I need to.

**Comment by stefanprodan** [comment]
Every commit in this repo is being tested against GitHub and we do test bootstrap against an existing repo, see https://github.com/fluxcd/flux2/blob/main/.github/workflows/bootstrap.yaml#L54

**Comment by rhart** [comment]
My problem seems to be permissions related. I created a new access key with full repo permissions, and everything now works as expected.
