### ISSUE TITLE
Image Automation Does not work in specific case (if there is submodule)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluxcd/flux2#1546]
### Describe the bug

Image Automation does not work.

Seems it happens when automation and kustomization have same target. I was able to image automate public podinfo container which was put raw into folder, not kustomize(kustomize of kustomize, not flut) file.

### To Reproduce

Steps to reproduce the behaviour:

1. Same instruction as on flux pages
2. Repo is private and registry

### Expected behavior

```
{"level":"error","ts":"2021-06-18T20:20:49.697Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"gameserver" ││ ,"namespace":"flux-system","error":"worktree contains unstaged changes"}                                                                                                                                                                                        ││                                                                              
````

### Additional context

https://github.com/fluxcd/flux2/issues/1545

**Comment by dzmitry-lahoda** [comment]
```
```
NAME                            READY   MESSAGE                         LAST SCAN                       SUSPENDED 
imagerepository/gameserver  True    successful scan, found 25 tags  2021-06-19T15:41:32+03:00       False

NAME                                    READY   MESSAGE                                                                                 LATEST IMAGE
imagepolicy/staging-image-policy        True    Latest image tag for 'gameserver.azurecr.io/gameserver' resolved to: 32871      gameserver.azurecr.io/gameserver:32871

NAME                                    READY   MESSAGE                                 LAST RUN        SUSPENDED 
imageupdateautomation/gameserver    False   worktree contains unstaged changes                      False
```

Downgraded to 0.14.2, same issue

**Comment by dzmitry-lahoda** [comment]
flux delete iamge automation, added back - same issue.

**Comment by dzmitry-lahoda** [comment]
Once I saw it worked, changed fully repo, not sure what changed.

**Comment by dzmitry-lahoda** [comment]
Looped image reconcilation and copied git from flux tmp into local
```
C:\Users\dz\flux-system-flux-system074686607 [master ≡]> git st
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
C:\Users\dz\flux-system-flux-system074686607 [master ≡]>
``
No changes.

**Comment by dzmitry-lahoda** [comment]
I am stuck here...

**Comment by dzmitry-lahoda** [comment]
@stefanprodan got it, if there is git submodule in git repo which is target to reconcilation - than got that error - removed and all got fine. Because kustomize does not have module system, and only way to share (without CRDT) is submodules - than it can be good bug to fix:)

**Comment by stefanprodan** [comment]
Instead of Git submodules use Flux's `include` feature https://fluxcd.io/docs/components/source/gitrepositories/#including-gitrepository

**Comment by dzmitry-lahoda** [comment]
Hm, what about better error message? I mean it VERY unclear what is it...

**Comment by stefanprodan** [comment]
That error message comes from https://github.com/go-git/go-git/blob/master/worktree.go#L266 Please open an issue here https://github.com/fluxcd/image-automation-controller I guess we could detect git submodes and reject the repo all together instead of trying to work with it.
