### ISSUE TITLE
flux2 not satisfying semver creates problems for package management

### ISSUE THREAD

**Issue by shibumi** [fluxcd/flux2#1549]
Dear Flux staff,

I am the package maintainer of flux in Arch Linux and I have a question
regarding your deprecation plan. I even consider this as a "bug", because it
actually breaks a few workflows on different systems:

If you deprecate flux1 and let people move to flux2 with version 0.15
this breaks many Linux distribution package management systems, because
version 0.15 is smaller than 1.22.

How do you plan to fix this? Will you release a version starting with 2 when flux2 is ready? Do you want to rename the package on Linux distributions?

I am really afraid that your current migration plan does not cover this and in the end the flux package will end up with a different name on different Linux distributions. I don't think this is in your interest if you have a situation like this:

* Debian: flux2 (0.15)
* Arch Linux: fluxctl (1:0.15)
* CentOS: flux (0.15)
* NixOS: fluxctl2 (0.15)

Note: This is just an example how the world **could** look like without a decision from you :)

As far as I know: the old flux binary has been called `fluxctl`, the new one is called `flux`.

So it would be possible on Arch to ship a package called `flux` with version 0.15 and just replacing `fluxctl`. But I don't know if this is in your interest.

Can you give us (package maintainers) a hint on what you want? 

I am fine with your decision, I just don't want to come up with a solution you don't like, because in the end the people will look in our package repositories first before downloading the binary manually.

**Comment by stefanprodan** [comment]
> Will you release a version starting with 2 when flux2 is ready?

Yes, flux2 GA will be versioned as 2.0.0, similar to what Linkerd did with linkerd (v1.x.x) and linkerd2 (v2.x.x).

**Comment by shibumi** [comment]
@stefanprodan thank you for your answer. Do you have a schedule for the 2.0.0 release? So, in the meanwhile the flux1 is still considered as supported and stable?

**Comment by kingdonb** [comment]
The schedule is not fixed yet, Flux v1 is considered supported and stable, as discussed here: https://github.com/fluxcd/flux/issues/3320

We are encouraging migration away from old versions of Flux ahead of GA wherever possible because of reasons described in the maintenance issue, and the FAQ docs.

Meanwhile, some users may have to support both Flux v2 and v1 at the same time or on the same clusters.

**Comment by shibumi** [comment]
@kingdonb  thanks. Your message is really helpful. :heart: 

At Arch Linux we have the following status quo right now:

Package name: `fluxctl`
Version: `1.22.0`

According to your advice I would just push flux2 as the following package to our repositories:

Package Name: `flux`
Version: `0.15..`

This should be fine, because we have two complete separate packages then. 

My questions have been answered. Do we want to compile a best packaging guide or something out of this? Can I help in any way? Shall I write something in your Wiki/Repository/You name it?

**Comment by hiddeco** [comment]
Our "best packaging guide" at the moment is how we package and publish our binary releases ourselves, see for example the automated package releases in the AUR: https://aur.archlinux.org/packages/?O=0&SeB=m&K=fluxcdbot&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by shibumi** [comment]
@hiddeco  this AUR package would disappear btw when I push flux to community (of course this doesn't mean that I wouldn't listen to your advices for packaging flux)

**Comment by hiddeco** [comment]
How is community kept up-to-date? We have a very aggressive release cycle at the moment, at times doing several releases a week, and judging by the latest release of `fluxctl`, it lags behind at least one month (our release was on April 28, release update in the community repository was on May 30).

Given our AUR package releases are integrated into our release pipeline, I would rather like to keep AUR packages that seasoned Arch users know how to work with anyway, than have an "official community" package that is always outdated.

**Comment by shibumi** [comment]
@hiddeco  Arch Linux is very fast with package releases. We are a rolling release distribution. You can expect that the new flux version will be in the community repositories in under 24 hours.. I have a release watcher on the repository, hence I get notified if you do a new release. Of course, this means, that I am not as fast as your build pipeline.

**Comment by shibumi** [comment]
Closing this, because the question has been answered.
