### ISSUE TITLE
Connections to notification-controller on port 9292 not allowed by AzureCNI

### ISSUE THREAD

**Issue by ellieayla** [fluxcd/flux2#1580]
### Describe the bug

With AzureCNI and flux 0.16.0, connections from another namespace (eg ingress-nginx, or `curl` inside an ingress-nginx pod) to the notification-controller pod on port 9292 fails.

The NetworkPolicy resources `allow-webhooks` and `allow-scraping` appear to combine to allow connections to port 8080 and disallow connections on all other not-explicitly-listed ports.

### To Reproduce

Steps to reproduce the behaviour:

1. Install flux 0.16.0 on AKS with AzureCNI
2. create service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-exposed
  namespace: flux-system
spec:
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 9292
      protocol: TCP
      targetPort: 9292
```
3. From a pod in another namespace, `curl http://webhook-receiver-exposed.flux-system.svc.cluster.local:9292/` - no connection
4. From a pod in another namespace, `curl http://webhook-receiver-exposed.flux-system.svc.cluster.local:8080/` - 404 (good)
5. create this NetworkPolicy
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks-explicit-port
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 9292
      protocol: TCP
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
```
5. From a pod in another namespace, `curl http://webhook-receiver-exposed.flux-system.svc.cluster.local:9292/` - 404 (good)
6. From a pod in another namespace, `curl http://webhook-receiver-exposed.flux-system.svc.cluster.local:8080/` - 404 (good)

### Expected behavior

Flux ships NetworkPolicy resources which allow connections to notification-controller pods on needed ports.

Without the NetworkPolicy `allow-scraping` present, connections to port 8080 and 9292 work. With the NetworkPolicy 
`allow-scraping` present, connections to port 8080 works but 9292 does not work. It *appears* like the NetworkPolicy `allow-scraping` allowing port 8080 prevents connections to port 9292 *even when another NetworkPolicy tries to allow connections on all ports (to pods matching a label selector)*.

Maybe the NetworkPolicy `allow-webhooks` should explicitly list all ports it wants to allow. Maybe there's a bug in AzureCNI. I do not know.

I have created the above NetworkPolicy `allow-webhooks-explicit-port` in production for now.

### Additional context

- Kubernetes version: AKS v1.18.14
- Git provider: Github
- Container registry provider: Azure

Below please provide the output of the following commands:

```cli
flux --version

flux version 0.16.0
```

```cli
flux check

► checking prerequisites
✔ kubectl 1.21.2 >=1.18.0-0
✔ Kubernetes 1.18.14 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed
```

```cli
kubectl -n <namespace> get all

NAME                                               READY   STATUS    RESTARTS   AGE
pod/helm-controller-b5c45677f-vjck7                1/1     Running   0          173m
pod/image-automation-controller-57f8bf65c7-hmg7s   1/1     Running   0          173m
pod/image-reflector-controller-558c56b989-m84tc    1/1     Running   0          173m
pod/kustomize-controller-7fd4d6b4c8-nl4vl          1/1     Running   0          173m
pod/notification-controller-66545867f4-9725h       1/1     Running   0          173m
pod/source-controller-5d469c75b6-jlkgh             1/1     Running   0          173m

NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/notification-controller    ClusterIP   10.0.154.15    <none>        80/TCP     104d
service/source-controller          ClusterIP   10.0.79.237    <none>        80/TCP     104d
service/webhook-receiver           ClusterIP   10.0.121.50    <none>        80/TCP     104d
service/webhook-receiver-exposed   ClusterIP   10.0.206.112   <none>        9292/TCP   172m

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/helm-controller               1/1     1            1           104d
deployment.apps/image-automation-controller   1/1     1            1           173m
deployment.apps/image-reflector-controller    1/1     1            1           173m
deployment.apps/kustomize-controller          1/1     1            1           104d
deployment.apps/notification-controller       1/1     1            1           104d
deployment.apps/source-controller             1/1     1            1           104d

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/helm-controller-5cf7d96887               0         0         0       104d
replicaset.apps/helm-controller-b5c45677f                1         1         1       173m
replicaset.apps/image-automation-controller-57f8bf65c7   1         1         1       173m
replicaset.apps/image-reflector-controller-558c56b989    1         1         1       173m
replicaset.apps/kustomize-controller-689774778b          0         0         0       104d
replicaset.apps/kustomize-controller-7fd4d6b4c8          1         1         1       173m
replicaset.apps/notification-controller-66545867f4       1         1         1       173m
replicaset.apps/notification-controller-769876bb9f       0         0         0       104d
replicaset.apps/source-controller-5d469c75b6             1         1         1       173m
replicaset.apps/source-controller-c55db769d              0         0         0       104d
```

Related to #703 and fluxcd/website#359

**Comment by stefanprodan** [comment]
Please raise this issue with Azure support, the Flux network policies have been tested with Calico, Cilium and WeaveNet.

**Comment by kingdonb** [comment]
I'd like to find out if there is still an open issue at https://github.com/Azure/azure-container-networking related to this.

I have had related issues with Flannel, which was not on the testing list mentioned, but does implement network policy.

I think the situation is unfortunately a bit broader, that networkpolicy is not reliably consistent from one CNI implementation to the next. (I don't know much about it, but was hoping to learn more through tools like https://networkpolicy.io)

Assigning this to myself for follow-up, for now at least.

**Comment by alanjcastonguay** [comment]
> I'd like to find out if there is still an open issue at https://github.com/Azure/azure-container-networking related to this.

No. I opened a support ticket with Azure. It initially generated pushback - any issue with NetworkPolicy & Azure CNI must be a user/Flux problem. I don't have enough experience with NetworkPolicy to refute that well. The ticket is still open, though I don't think it's making forward progress.

**Comment by alanjcastonguay** [comment]
I wonder whether Azure/azure-container-networking#870 is related. @vakalapa ?
