### ISSUE TITLE
Openshift Operator Kustomization not Fount 404

### ISSUE THREAD

**Issue by hupling** [fluxcd/flux2#1581]
### Describe the bug
I am using the Openshift Flux Operator Verision 0.16:

In the Kustomization I get the error:
> http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/podinfo/f8263ad64b651d5a201ff1942cc4c5e9220ed65d.tar.gz, status: 404 Not Found

source-controller.flux-system.svc.cluster.local. <- the problem is the last point.

Can you change in the deployment from `source-controller` the arguments:

From:
```yml
          args:
            - >-
              --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
```
To:
```yml
          args:
            - >-
              --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local
```

Below please provide the output of the following commands:
> flux version 0.16.0

**Comment by stefanprodan** [comment]
> . <- the problem is the last point.

Removing this is not an option for us, either fix it in CoreDNS or make your own Flux patch.

**Comment by hiddeco** [comment]
For some background information: http://www.dns-sd.org./trailingdotsindomainnames.html
