### ISSUE TITLE
Add --status-selector to flux get commands

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#1587]
We could add a field called `status-selector` to Flux get commands so that users can specify the status condition name and the desired state to filter the result.

The filter format could be `flux get <kind> --status-selector=<condition-name>=<true|false|unknown>` .

Print sources that are not ready:

```
flux get source all --status-selector=ready=false
``` 

Print Kustomizations with failing health checks:

```
flux get kustomizations --status-selector=healthy=false
``` 

### Discussed in https://github.com/fluxcd/flux2/discussions/1578

<div type='discussions-op-text'>

<sup>Originally posted by **eloo** July  1, 2021</sup>
Hi,

i would like to suggest a filter function for the flux cli. 
In my current situation i would like to have an option to filter for all flux resources in a specific state.. for example ready==false

</div>

**Comment by chanwit** [comment]
I'm looking at this feature, and I think `cmd/flux/get.go` would be the best place (most generalized) to add this flag.

**Comment by stefanprodan** [comment]
@chanwit yes we need skip the header here https://github.com/fluxcd/flux2/blob/main/cmd/flux/get.go#L120

**Comment by chanwit** [comment]
Thanks @stefanprodan  
I'll work on this issue then.

**Comment by chanwit** [comment]
```
listOpts = append(listOpts, client.MatchingFields{...}
```
Matching fields for the list operator works only with labels?
If so, this implementation would retrieve the results, then apply the manual filtering?

**Comment by chanwit** [comment]
I would learn more how the `kubectl wait` command work.

**Comment by stefanprodan** [comment]
@chanwit the `client.MatchingFields` accepts a json path, so you can map the condition there I think.

**Comment by chanwit** [comment]
> @chanwit the `client.MatchingFields` accepts a json path, so you can map the condition there I think.

I tried that. It didn't work. It seems the path is used to evaluate only for

- metadata
- labels

but not fields under status.

**Comment by stefanprodan** [comment]
Ok maybe we can use the https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Object to decode each object in the list into a generic type that has status conditions, then filter the result.

**Comment by chanwit** [comment]
yeah I planned to do similar.
We already have a function to retrieve and process `conditions`. I think we could make use of it.

https://github.com/fluxcd/flux2/blob/main/cmd/flux/get.go#L62

**Comment by chanwit** [comment]
```
❯ bin/flux get source all
NAME                    READY   MESSAGE                                                                                         REVISION                                        SUSPENDED
gitrepository/source    True    Fetched revision: master/24124f7cd110605f97442455aa1e6264f32590ed                               master/24124f7cd110605f97442455aa1e6264f32590ed False
gitrepository/source-a  False   unable to clone 'https://github.com/chanwit/test-flux-a', error: authentication required                                                        False
gitrepository/source-b  True    Fetched revision: master/24124f7cd110605f97442455aa1e6264f32590ed                               master/24124f7cd110605f97442455aa1e6264f32590ed False

❯ bin/flux get source all --status-selector=ready=true
NAME                    READY   MESSAGE                                                                 REVISION                                        SUSPENDED
gitrepository/source    True    Fetched revision: master/24124f7cd110605f97442455aa1e6264f32590ed       master/24124f7cd110605f97442455aa1e6264f32590ed False
gitrepository/source-b  True    Fetched revision: master/24124f7cd110605f97442455aa1e6264f32590ed       master/24124f7cd110605f97442455aa1e6264f32590ed False

❯ bin/flux get source all --status-selector=ready=false
NAME                    READY   MESSAGE                                                                                         REVISION        SUSPENDED
gitrepository/source-a  False   unable to clone 'https://github.com/chanwit/test-flux-a', error: authentication required                        False
```

**Comment by stefanprodan** [comment]
@chanwit please create a Kustomization that has a health check to a non existing object, then do `flux get ks --status-selector=healthy=false`.

PS. Great progress so far 🏅

**Comment by stefanprodan** [comment]
@chanwit that looks great 💯

**Comment by chanwit** [comment]
I'm making a PR. a sec please.
