### ISSUE TITLE
Porting e2e tests to Bats

### ISSUE THREAD

**Issue by chanwit** [fluxcd/flux2#1596]
Bats, https://bats-core.readthedocs.io/en/stable/usage.html, is a stable & general purpose test framework.
It fits nicely to test Flux CLI commands, together with `kubectl` and others.

For example,  the following test case is use to verify the correctness of `flux check --pre` by obtaining version infos from `kubectl` first, then matching output of the Flux command with them line-by-line.

```
#!/usr/bin/env bats

diag() {
	echo "# DEBUG $@" >&3
}

@test "flux check --pre" {
	run bash -c 'kubectl version --short | cut -d" " -f3 | cut -d"v" -f2'
	client_version=${lines[0]}
	server_version=${lines[1]}
	
	# diag "$client_version"
	# diag "$server_version"
	
	run flux check --pre
	[ "$status" -eq 0 ]
	[ "${lines[0]}" = "► checking prerequisites" ]
	[ "${lines[1]}" = "✔ kubectl ${client_version} >=1.18.0-0" ]
	[ "${lines[2]}" = "✔ Kubernetes ${server_version} >=1.16.0-0" ]
	[ "${lines[3]}" = "✔ prerequisites checks passed" ]
}
```

My proposal is to rewrite what we already have in the e2e pipeline using Bats.

@hiddeco @stefanprodan wdyt?

**Comment by hiddeco** [comment]
As discussed in private but for public visibility: we used Bats for `fluxcd/flux` and never were really happy with it.

If we want to strengthen our test suite, it is best to port as many tests as possible to Go, and add additional ones.

**Comment by chanwit** [comment]
Closing this as we agreed to use Go instead of Bats.
