### ISSUE TITLE
Bootstrap fails with Azure DevOps

### ISSUE THREAD

**Issue by Tuhis** [fluxcd/flux2#1597]
### Describe the bug

Flux bootstrapping fails with Azure DevOps Git repository.

### To Reproduce

1. Running ```flux bootstrap git --url=ssh://*****@vs-ssh.visualstudio.com/v3/*****/*****/reponame --path=./path/to/dir --branch=main``` produces ```✗ failed to clone repository: empty git-upload-pack given```

### Expected behavior

Successful bootstrap process.

### Additional context

- Kubernetes version: 1.20.7-gke.2200
- Git provider: Azure DevOps
- Container registry provider: Google

Below please provide the output of the following commands:

```cli
flux --version
flux check
kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```
Output:
```cli
❯ flux --version
flux version 0.16.0
```
```cli
❯ flux check
► checking prerequisites
✔ kubectl 1.20.7 >=1.18.0-0
✔ Kubernetes 1.20.7-gke.2200 >=1.16.0-0
► checking controllers
✔ all checks passed
```

Not pasting kubectl outputs as nothing is deployed on the cluster yet.

If there's any further information I could provide please let me know! :+1:

**Comment by stefanprodan** [comment]
Please see https://fluxcd.io/docs/use-cases/azure/#flux-installation-for-azure-devops

**Comment by Tuhis** [comment]
Thanks! I saw those instructions, but there were no mention that bootstrapping is not working. Anyhow, I'll proceed with those.

**Comment by zzvara** [comment]
This is still a problem with _Azure DevOps_ and the linked guide refers to `bootstrap`, which does not work.

**Comment by aryan9600** [comment]
@zzvara please open a new issue with steps to reproduce and information about your environment.
