### ISSUE TITLE
Support flux installation via helm chart

### ISSUE THREAD

**Issue by tsahiduek** [fluxcd/flux2#1641]
Hi,
Is there any reason why flux2 doesn't have an helm chart to bootstrap itself to a cluster?
Using CLI tool is somewhat hard to use when managing the cluster/infra creation via IaC (like CDK in my case), whereas helm installation will be much easier to manage

Thanks

**Comment by kingdonb** [comment]
Sorry for the inconvenience.

This has been explained in https://github.com/fluxcd/flux2/issues/1136, see also the discussion in #431 

The short version is that Helm is not an ideal solution for deployment of CRDs, as it has limited support for upgrading them. Flux now leans heavily on the Custom Resource Definition feature for Kubernetes API extensibility, and this is a major pain point for us as the APIs are frequently being upgraded with a new release.

**Comment by kingdonb** [comment]
Though it is not a Helm chart, HTH - the Infrastructure as Code solution we recommend is our Terraform provider:

https://github.com/fluxcd/terraform-provider-flux

**Comment by tsahiduek** [comment]
Have you considered support for CDK?

**Comment by squaricdot** [comment]
@kingdonb  i thought i cought some discussion on slack that you made some way to use OLM to maintain the operator ?

**Comment by kingdonb** [comment]
There is an OLM method for installing Flux, yes:

https://operatorhub.io/operator/flux

I think it works best with OpenShift from what I have heard, although I use vanilla k8s. There are some issues I ran into using OLM standalone, (they should be filed separately, I haven't got around to it yet) but from what I understand I think these can mostly be overcome easily, when using OLM standalone + OpenShift Console. (I haven't quite got there yet myself, either...)

**Comment by stgrace** [comment]
I understand the difficulty of managing CRD's with Helm and not wanting to do that.
However, using the provided installation methods available now there is no way to customize RBAC for Flux components. By default cluster-admin privileges are bound to kustomize and helm controller, which is not allowed in a lot of production environments.
Ideally there would be a way to specify the privileges for each Flux component in an automated way, maintained by Flux itself.

**Comment by pierluigilenoci** [comment]
@stgrace I totally agree!

**Comment by stefanprodan** [comment]
> Ideally there would be a way to specify the privileges for each Flux component in an automated way, maintained by Flux itself.

Please take a look at: https://github.com/fluxcd/flux2-multi-tenancy

**Comment by stefanprodan** [comment]
An unofficial Helm chart for flux is being developed here https://github.com/fluxcd-community/helm-charts
