### ISSUE TITLE
Remove deprecated `io/ioutil` from projects

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#1658]
All of our projects make use of Go 1.16, and `io/ioutil` has been deprecated since this version: https://golang.org/doc/go1.16#ioutil

We should remove all traces in our projects and replace them with the suggestions from the deprecation notice.

https://github.com/search?q=ioutil+org%3Afluxcd&type=code

**Comment by krishnaindani** [comment]
Are there still changes to be made with this issue, could I work on this?

**Comment by JosephWoodward** [comment]
Judging by the merged pull requests above, this issue is no longer relevant and can be closed?

**Comment by allenporter** [comment]
There are still many to cleanup: https://github.com/search?q=ioutil+org%3Afluxcd&type=code

**Comment by dholbach** [comment]
- [ ] source-watcher + website: (https://github.com/fluxcd/source-watcher/blob/bebe0f5f4265f9ae7fce90770322b571bb28f324/controllers/gitrepository_watcher.go and https://github.com/fluxcd/website/blob/ea2ccb00003611ec9062a5466e060d5114a3f4d7/content/en/docs/gitops-toolkit/source-watcher.md)
- [ ] flux2: https://github.com/fluxcd/flux2/blob/789aa322f19307054d595371934eb555954312ab/cmd/flux/tree_kustomization.go
- [ ] go-git-providers: https://github.com/fluxcd/go-git-providers/blob/5539357bac43be3035cb347eac103c25418b2597/stash/integration_suite_test.go and https://github.com/fluxcd/go-git-providers/blob/cda93bf5a5fa65bd994a60d6d3ef9ad119cfb684/gitlab/integration_test.go and https://github.com/fluxcd/go-git-providers/blob/cda93bf5a5fa65bd994a60d6d3ef9ad119cfb684/github/integration_test.go

**Comment by dholbach** [comment]
Everything else is `flux`, `flux-recv` and `helm-operator` from what I can see.

**Comment by dholbach** [comment]
`source-watcher` and `website` should be fixed separately - anyone interested in picking this up?
