### ISSUE TITLE
Upgrade of flux marks all helmreleases as unreconciled

### ISSUE THREAD

**Issue by brujoand** [fluxcd/flux2#1698]
### Describe the bug

When I upgrade the flux version in my cluster by running a new bootstrap every helmrelease will be unreconciled until manually reconciled. 

### Steps to reproduce

1. Upgrade flux version by rerunning the bootstrap command
2. Wait for it to complete successfully
3. Notice that all helmreleases are now unreconciled
4. Write bash script to iterate through all helmreleasese an ask flux to reconcile them

### Expected behavior

All helmreleases which where reconciled before the bootstrap should stay reconciled after the bootstrap.

### OS / Distro

Ubuntu 20.04

### Flux version

0.16.2, just upgraded from 0.16.1

### Flux check

► checking prerequisites
✔ kubectl 1.21.1 >=1.18.0-0
✔ Kubernetes 1.20.5 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Git provider

Github

### Additional context

This has happened for a while now after upgrades, and I can't find anything interesting in the logs. But it might help if I had some pointers on what to look for. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Can you notice a difference in the `Status` of a `HelmRelease` object post-upgrade?

**Comment by brujoand** [comment]
The status just changes to `'namespace/release' is not ready'

**Comment by stefanprodan** [comment]
Fixed by https://github.com/fluxcd/helm-controller/pull/738
