### ISSUE TITLE
[Feature] flux get commit message and time

### ISSUE THREAD

**Issue by arash-bizcover** [fluxcd/flux2#1737]
It would be very helpful if the `flux get ...` command was also showing us the **commit message** and the **time** of the commit.
Because right now by looking at the output I don't know if my last change was reconciled already or not, and also don't know what the SHA refers to unless I copy that and come back to Github and see what it is. 
![image](https://user-images.githubusercontent.com/62287461/130385523-80c59425-8004-4f1d-a18e-e742bc68590a.png)

**Comment by stefanprodan** [comment]
The commit message is now included in the Kubernetes event that source-controller emits after a a git pull. We have no plans on storing commit messages in etcd. Best way to view the commit messages is to setup notifications https://fluxcd.io/docs/guides/notifications/
