### ISSUE TITLE
"flux reconcile helmrelease" does not display error on upgrade failure

### ISSUE THREAD

**Issue by artem-nefedov** [fluxcd/flux2#1760]
### Describe the bug

When running `flux reconcile helmrelease` for the chart with upgraded version (`spec.chart.spec.version` field), if the new revision isn't successfully applied, but previous revision exists, the command will simply show prevision revision as applied one, and will not show any error, nor will it exit with non-zero code.

```
► annotating HelmRepository bld in flux-system namespace
✔ HelmRepository annotated
◎ waiting for HelmRepository reconciliation
✔ HelmRepository reconciliation completed
✔ fetched revision d267a31e4795f5cefd83939297111dd850d75638
► annotating HelmRelease test-app in dev-test-app namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✔ HelmRelease reconciliation completed
✔ applied revision <OLD-REVISION-NUMBER>
```

In my case, this is reproduced for the chart that fails due to timeout. In fact, it looks like MESSAGE reported by `flux get hr` still says "Reconciliation in progress" when `flux reconcile hr` command have already reported success.

### Steps to reproduce

1. Install HelmRelease and wait for successful reconciliation
2. Bump chart version of HelmRelease to the one that will fail reconciliation
3. Run `flux reconcile hr your-hr --with-source`

### Expected behavior

Tool returns an error and exits with non-zero code.

### OS / Distro

Linux

### Flux version

0.16.2

### Flux check

➜ flux check
► checking prerequisites
✗ flux 0.16.2 <0.17.0 (new version is available, please upgrade)
✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.16.0-0
► checking controllers
✗ helm-controller: deployment not ready
► my-repo.com/fluxcd/helm-controller:v0.11.2
✗ kustomize-controller: deployment not ready
► my-repo.com/fluxcd/kustomize-controller:v0.13.3
✗ notification-controller: deployment not ready
► my-repo.com/fluxcd/notification-controller:v0.15.1
✗ source-controller: deployment not ready
► my-repo.com/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artem-nefedov** [comment]
Seems to be fixed in `0.17.0`

**Comment by artem-nefedov** [comment]
Nevermind, I incorrectly closed the issue because I've observed that sometimes it does actually fail with "context deadline exceeded" (which I assumed to be a correct behavior), but other times it will still report success with `✔ HelmRelease reconciliation completed ✔ applied revision 6.78.1-test.37` even though the actual upgrade fails.

**Comment by artem-nefedov** [comment]
I have found a workaround: If i specify `--timeout` value lower than an actual timeout used by controller, I can consistently get `context deadline exceeded` error (e.g. timeout for controller is `5m0s` and timeout for `flux reconcile` is `4m30s`). This way, I can get desired behavior, but it's still weird that flux cli itself cannot recognize that Helmrelease is not reconciled correctly without this workaround.

**Comment by patrikbeno** [comment]
in my case, `flux reconcile hr` exits after 26-30 seconds, event with explicit `--timeout=5m0s`:

```
◎ waiting for HelmRelease reconciliation
✔ HelmRelease reconciliation completed
✔ applied revision 0.1.1-update.70

real    0m26.524s
```

Hovever, reconciliation is still inprogress according to `kubectl get hr`, and this report refers to old version

Running `flux reconcile hr` again quits again after 30s with the same false report.
Reconciliation is still in progress.

I need to do something like:

```
# wait for reconciliation
$ kubectl wait hr $name --for=condition=ready 
# get flux status report
$ flux get hr $name 
# get helm status report
$ helm history $name --max=2 
```

**Comment by SomtochiAma** [comment]
Hey, I am trying to reproduce the error on my end. Do you have an example of the helm release/ helm chart that you used?

**Comment by patrikbeno** [comment]
I don't know about OP, but I don't have anything to share.

However, it could be easily simulated as follows:
- create a helm chart with a single `Job` annotated `helm.sh/hook`: `post-install,post-upgrade`
- in this job, execute some `sleep 3m` command

`HelmRelease` will wait for job to complete and will succeed. `flux reconcile` will not wait for completion, not configured timeout.

**Comment by patrikbeno** [comment]
I have another cluster where i don't observe the error I described, i.e. `flux reconcile` properly waits for reconciliation, times out after the specified timeout, and properly reports failure.

Ideas:
- this may have to do something with some internal API calls and socket timeouts on some infra layer (like ingress or load balancer)
- flux assumes this API call completed successfully and just reports `last applied revision`. Which is incorrect because the reconciliation is still in progress.

My failing cluster is RKE1 with Rancher 2.6 HA as API gateway behind Nginx ingress. 

My working cluster is a Rancher 2.5 single node behind simple TCP proxy (Fortigate)

I will do some more tests when I have a chance, and will come back with results.
