### ISSUE TITLE
Helm controller change tag to 0 with '881869e-202108031402' defined in kustomization patch.

### ISSUE THREAD

**Issue by TOHUHM** [fluxcd/flux2#1784]
### Describe the bug

Hello Team

Not sure if I found a bug for helmRelease type resource creation from Flux controller

helm controller version: "helm-controller:v0.11.1"
API Version:  helm.toolkit.fluxcd.io/v2beta1
Kustomization: kustomize.toolkit.fluxcd.io/v1beta1

we use Kusktomization patch to replace the tag, here is what  I defined
![image](https://user-images.githubusercontent.com/46467718/131822382-930649f1-1cc2-45ce-a965-82ed37a15b8b.png)

but when I go to the cluster, it changed, what a magic! it becomes 0, which cause image pull error
![image](https://user-images.githubusercontent.com/46467718/131822495-a3efe743-928d-4d0b-8add-e6349607acae.png)

the tag number is "881869e-202108031402"
not sure what happened when we use this string,
other applications and tags work well by this method, re-generate new tag, work well

### Steps to reproduce

helm controller version: "helm-controller:v0.11.1"
API Version:  helm.toolkit.fluxcd.io/v2beta1
Kustomization: kustomize.toolkit.fluxcd.io/v1beta1

### Expected behavior

the tag can use any string  include '881869e-202108031402'

### OS / Distro

Ubuntu 18.04.5 LTS

### Flux version

0.12.3

### Flux check

✗ flux 0.12.3 <0.17.0 (new version is available, please upgrade)
✔ kubectl 1.20.4 >=1.18.0-0
✔ Kubernetes 1.20.7 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
►image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
►fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
►fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
►fluxcd/source-controller:v0.15.3
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
The problem is likely that there are no quotes around your `value` value which would force it into a string. Due to this, the value is seen as an integer. Illustrative Go example: https://play.golang.org/p/3pqa1ejugBB
