### ISSUE TITLE
Sops-based secrets regenerated despite exactly same content

### ISSUE THREAD

**Issue by pefeigl** [fluxcd/flux2#1785]
### Describe the bug

We have a script that generates all our sops-encoded secrets. Right now all our secrets are generated automatically on the deployment machine, so every time we check in some code, all sops secrets are regenerated, which leads to lots of kubernetes secrets being regenerated, which again leads to many containers (needlessly) restarting.

Is there a reason why the hash for the kubernetes secrets is done by flux for the *encrypted* content and not the *decrypted* content (which is exactly the same)?

### Steps to reproduce

1) Encrypt a secret with sops
2) Run it through flux
3) Freshly encrypt the exact same secret with sops
4) Run it through flux again
5) Notice that the hash has changed, leading to container restarts

### Expected behavior

The secret should be decrypted *before* running it through kustomize, so re-encoding with sops should lead to no new secret being created unless the actual secret content changes, not just the encrypted text.

### OS / Distro

N/A

### Flux version

0.16

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pefeigl** [comment]
Sorry for the noise, turns out *kustomize* creates the secret suffix hash, so nothing flux2 can do about this :-/

**Comment by stefanprodan** [comment]
Does this happen with flux2 0.21?

**Comment by stefanprodan** [comment]
> it seems if flux decoded the secrets before running kustomize

Yes decryption is the last step before apply, we don't write secrets in plain text on disk. This behaviour is not going to change in the future.

**Comment by pefeigl** [comment]
Do you have any idea how to solve our problem? I've tried raising an
issue with SOPS to make it support reproducibly generating the exact
same content each time it is run, but nothing except for crickets there
;-/

https://github.com/mozilla/sops/issues/931

I'll try with flux2 0.21 asap.

**Comment by stefanprodan** [comment]
The only workaround I can think of is to disable kustomize secret generator hash with `disableNameSuffixHash: true` and use a controller that restarts deployments: https://github.com/stakater/Reloader

**Comment by pdf** [comment]
> I've tried raising an issue with SOPS to make it support reproducibly generating the exact same content each time it is run, but nothing except for crickets there

This will depend on how the encryption is being done, and you probably don't actually want that

> Do you have any idea how to solve our problem? 

You need to fix this part of your process, to only modify secrets when they actually change:
> Right now all our secrets are generated automatically on the deployment machine, so every time we check in some code, all sops secrets are regenerated

I don't think there's really anything for flux to do here.
