### ISSUE TITLE
Kustomize Create Failed Error

### ISSUE THREAD

**Issue by m477r1x** [fluxcd/flux2#1788]
### Describe the bug

For some reason when installing fluxv2 on my local kind cluster, and our company staging EKS cluster, I get the same error. During the completion checks of the bootstrap i see 

```kustomize create failed: failed to decode Kubernetes YAML from /tmp/flux-system171464111/.yamllint.yaml: missing Resource metadata```

These errors are also visible with a `kubectl get events`. 

Upon checking the gitrepository custom resource which is created, `kubectl get gitrepositories` I can see the repo and branch are correct, and if i make a commit to that branch i can watch the commit hash update correctly on the gitrepository resource. However no new resources are deployed into the cluster no matter what i commit to the branch. I am only using standard yaml manifest files, not kustomize manifests. However as I understand it, Fluxv2 will generate kustomize manifests for those vanilla yaml files? In which case it makes sense that things aren't being deployed if kustomize is not installed correctly.

### Steps to reproduce

Run the `flux bootstrap` command with correct options for our github repo and test branch.

### Expected behavior

Flux is installed and begins syncing from the specified repo and branch and deploying resources into the cluster.

### OS / Distro

OSX 11.5.2 (Big Sur)

### Flux version

flux version 0.16.0

### Flux check

► checking prerequisites
✗ flux 0.16.0 <0.17.0 (new version is available, please upgrade)
✔ kubectl 1.18.5 >=1.18.0-0
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Git provider

GitHub

### Additional context

Flux logs are just full of:

```
2021-09-03T10:15:18.134Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.418796492s, next run in 1m0s
2021-09-03T10:16:19.558Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.422838276s, next run in 1m0s
2021-09-03T10:17:21.011Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.452697127s, next run in 1m0s
2021-09-03T10:18:22.528Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.516866852s, next run in 1m0s
2021-09-03T10:19:23.930Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.401436963s, next run in 1m0s
2021-09-03T10:20:25.357Z info GitRepository/flux-system.flux-system - Reconciliation finished in 1.425885091s, next run in 1m0s
```

Also, when performing `kubectl get kustomizations` you can see the same error in the outputs

```
NAME          READY   STATUS                                                                                                                               AGE
flux-system   False   kustomize create failed: failed to decode Kubernetes YAML from /tmp/flux-system881552979/.yamllint.yaml: missing Resource metadata   24h
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see the docs on how to exclude files: https://fluxcd.io/docs/components/source/gitrepositories/#excluding-files

**Comment by m477r1x** [comment]
> Please see the docs on how to exclude files: https://fluxcd.io/docs/components/source/gitrepositories/#excluding-files

Hi thanks for your suggestion. I did already know about this however I didn't think it was relavent? There are no files in the repo apart from kubernetes manifest files so they should all be fine right?

**Comment by m477r1x** [comment]
> Please see the docs on how to exclude files: https://fluxcd.io/docs/components/source/gitrepositories/#excluding-files

In fact even when using a completely empty repository, the bootstrap still outputs the same error:

```
✔ configured deploy key "flux-system-do-not-merge-fluxv2-testing-flux-system-./" for "https://github.com/limejump/k8s-gitops-staging"
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ kustomize create failed: failed to decode Kubernetes YAML from /tmp/flux-system291216466/.yamllint.yaml: missing Resource metadata
```

**Comment by politician** [comment]
The problem is clearly stated in the error message, it’s trying to read .yamllint.yaml as a K8s manifest.

**Comment by m477r1x** [comment]
so upon further testing with the kind help of @kingdonb it seems that using the `--private` option, causes flux to create a new branch with `--private` on the end of the name of the branch. This does get rid of the kustomization error. However this is obviously not ideal because I don't want to bootstrap with a new empty branch, i would like to use our existing master branch eventually for production. 

I have looked everywhere for what might be causing this phantom `.yamllint.yaml` file in the /tmp directory which @kingdonb kindly advised me is on the pod not on the local machine running flux CLI so that helped me greatly in not looking in the wrong place. I would like to try to find out how this file is getting created in the /tmp directory of the pod so that i can try to stop that from happening. 

I am just adding this comment in case this is possibly some sort of bug. I will in the mean time try to do some more troubleshooting and if you guys have any suggestions i am happy to try them.

**Comment by m477r1x** [comment]
OK I was being unbelivably dumb and this issue is resolved.

**Comment by kingdonb** [comment]
(UX issue: it's not always completely obvious to new users that `spec.path` refers to a path relative to the root of the GitRepo. Since `flux` cli is executed on the user machine, but with the context of the gitrepo... and some users will be working in a subdirectory of a clone of an existing repo, the expression `path: ./` may not always expand to what one might have thought.)
