### ISSUE TITLE
EKS: CRD validation error

### ISSUE THREAD

**Issue by m477r1x** [fluxcd/flux2#1794]
### Describe the bug

When bootstrapping fluxv2 I received a few api resource errors for things which were using outdated api references. However after resolving most of them within our manifests, there are 2 errors remaining which I am unsure how to troubleshoot.

```
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ validation failed: error: error validating "b8be6b65-e30a-4183-9495-e21925577c22.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

I have tried searching our manifests for things such as `CustomResourceDefinitionSpec` and `apiserver` expecting to come accross some CRD definitions somewhere. But nothing has come back and now I am a little confused where these errors are coming from. 

### Steps to reproduce

`flux bootstrap github --owner=company --repository=k8s-gitops-staging --branch=flux-v2-testing --path=environments/aws`

### Expected behavior

flux installs successfully.

### OS / Distro

OSX 11.5.2 (Big Sur)

### Flux version

flux version 0.16.0

### Flux check

```
► checking prerequisites
✔ kubectl 1.18.5 >=1.18.0-0
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed
```

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by m477r1x** [comment]
i have also tried as the error suggests to disable validation and manually create the kustomization however i get the below out put (i could be doing this wrong though).

```
mlove@C02C20P6LVDL k8s-gitops-staging %   flux create kustomization flux-system \
    --source=GitRepository/flux-system \
    --path="/environments/aws" \
    --prune=true \
    --interval=10m \
    --validate=false
✗ unknown flag: --validate
```

**Comment by stefanprodan** [comment]
I guess you have CRDs that you've renamed to v1 without migrating the spec. This is not related to Flux but to Kubernetes, as in 1.21 the CRD v1beta1 is no longer supported.

**Comment by m477r1x** [comment]
I was suspecting something like this, however im not trying to figure out if there is a way to identify which ones they might be. Since every CRD has a different spec, I am not sure how i am going to figure out which one in all of our deployments is causing the issue 😆

**Comment by stefanprodan** [comment]
Use kubeval to validate your manifests before they reach Flux, here is an example script: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh

Can you please code this issue? If it's not the Flux CRDs resulting in this error then it's not a Flux bug. Thanks.

**Comment by kingdonb** [comment]
We are not sure there is an issue here, please provide feedback or we will go ahead and close it out.
