### ISSUE TITLE
CRD dependency not resolved correctly

### ISSUE THREAD

**Issue by pkit** [fluxcd/flux2#1806]
### Describe the bug

Trying to install tekton-triggers from scratch (as a part of a bootstrap) leads to:

```
unable to recognize "31accc8d-6b77-4813-8d51-27b7dda7db90.yaml": no matches for kind "ClusterInterceptor" in version "triggers.tekton.dev/v1alpha1"
```
Although `kustomize.yaml` was correctly configured with `dependsOn`
And it does work if bootstrapped **first** and **then** the yaml for the triggers is pushed (see the gist below for the reference).

### Steps to reproduce

1. Bootstrap flux from repo with the following https://gist.github.com/pkit/99d8823a904175ff62032d771fc89740
*Note*: `/` are changed to `_` because of braindead gist rules
*Note2*: the entry point is: `tekton-triggers.yaml`

### Expected behavior

Applies cleanly

### OS / Distro

Ubuntu 20.04

### Flux version

0.17.0

### Flux check

► checking prerequisites
✔ kubectl 1.21.2-13+d2965f0db10712 >=1.18.0-0
✔ Kubernetes 1.20.7-eks-d88609 >=1.16.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Can you please create a repository that can be forked, so that we can reproduce the exact steps in which you perform the bootstrap? That would help me better understand what mechanics come into play (as directory structure may play a part), which I can't do 1:1 based on your gist.

**Comment by pkit** [comment]
Yup, will single it out into own repo. Cool.

**Comment by pkit** [comment]
Cannot reproduce it in a singled-out repo.
See here: https://github.com/pkit/tekton-test
But I've disabled the alert engine (see the [alert_fail](https://github.com/pkit/tekton-test/tree/alert_fail) branch)
So it may be that the failure was related to the `alert-provider` setup and not actually the `tekton-trigger` setup.
