### ISSUE TITLE
Flux multitenancy - a tenant repository can create kustomization & deploy to another namespace outside Serviceaccounts scope

### ISSUE THREAD

**Issue by swapnild2111** [fluxcd/flux2#1829]
### Describe the bug

We have been experimenting with fluxcd multi tenancy. And we observed below:

Setup multi tenancy as per: https://github.com/fluxcd/flux2-multi-tenancy
Then in tenant repository (where we had our deployment yamls), create a flux kustomization object which refers to external repository & different namespace.

Now as per multi-tenancy we specify a serviceAccountName + targetNamespace in our Admin repository. Then in tenants repository - we have different service account & namespace. And that way we can kill purpose of having original SA restrictions.

We have tested this on our test k8s cluster & its possible.
Do you think it's an issue?

### Steps to reproduce

Setup multi tenancy as per: https://github.com/fluxcd/flux2-multi-tenancy
Then in tenant repository (where we had our deployment yamls), create a flux kustomization object which refers to external repository & different namespace.

### Expected behavior

FluxCD should not allow deployments going to namespace other than namespace specified in Admin repo.

### OS / Distro

macos + k8s 1.22 aks cluster

### Flux version

0.17.0

### Flux check

❯ flux check                                                                                                                                                                                                 (tooling-test-west-1-sa-clusteradmin/thorin-dev)
► checking prerequisites
✗ flux 0.17.0 <0.17.1 (new version is available, please upgrade)
✔ kubectl 1.21.4 >=1.18.0-0
✔ Kubernetes 1.20.7 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> Then in tenant repository (where we had our deployment yamls), create a flux kustomization object which refers to external repository & different namespace.

Have you setup the Kyveron polices like showed in  https://github.com/fluxcd/flux2-multi-tenancy? Kyverno should reject the
kustomization object if doesn't have a service account specified.

**Comment by swapnild2111** [comment]
I haven't setup Kyverno or OPA yet, will add those soon.
However, in my tenant repo I have this - 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hack
  namespace: dev
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev
  prune: true
  validation: client
  serviceAccountName: hack-dev
  targetNamespace: hack
  path: ./sandbox
```

Here am using a service account (different than flux admin repo) and different target namespace (different than flux admin repo) ... and application got deployed.

**Comment by stefanprodan** [comment]
A tenant as defined in the docs is allowed to use any service account in its namespace. A cluster admin must create a cluster role binding to grant a tenant’s SA access to a different namespace.

**Comment by andrey-dubnik** [comment]
Is there an opportunity to introduce an enhancement into the flux in a way tenant can't get out of jail? E.g. if Kustomization in the OPS repository mandates the namespace and/or the service account via {spec.serviceAccountName, spec.targetNamespace}  then it gets enforced on the tenant repository  Kustomization attributes below 

```
spec.serviceAccountName
spec.targetNamespace
sourceRef.namespace
```

Also for the HelmRelease

```
metadata.targetNamespace
spec.serviceAccountName
```

**Comment by spennymac** [comment]
I haven't thought this fully through yet... but could there potentially be a feature where you could set a flag on a flux CRD that states 'any objects created from this resource (flux- kustomization, helmrelease,etc...) will 'inherit' the initial service account' so any child objects will be reconciled impersonating as the original service account. And, any objects that set the serviceAccountName will result in an error.

**Comment by stefanprodan** [comment]
You can enforce a specific `spec.serviceAccountName` with Kyverno see https://github.com/fluxcd/flux2-multi-tenancy/blob/main/infrastructure/kyverno-policies/flux-multi-tenancy.yaml#L22

Going to close this as enforcing a specific SA is out of scope for Flux.

**Comment by spennymac** [comment]
> You can enforce a specific `spec.serviceAccountName` with Kyverno see https://github.com/fluxcd/flux2-multi-tenancy/blob/main/infrastructure/kyverno-policies/flux-multi-tenancy.yaml#L22
> 
> Going to close this as enforcing a specific SA is out of scope for Flux.

Thanks.
