### ISSUE TITLE
flux alert: slack message/payload formatting

### ISSUE THREAD

**Issue by amjad489** [fluxcd/flux2#1876]
### Describe the bug

we have multiple clusters running and we send alert to one slack channel. Alert notification is working fine without any issues.
But the real issue is we don't have any way to identify from the cluster this slack alert came.

is it possible to format slack message/payload?

### Steps to reproduce

1. Bootstrap flux.
    ```
    flux bootstrap github \
    --components-extra=image-reflector-controller,image-automation-controller \
    --owner someone \
    --repository githubrepo \
    --branch main \
    --path=clusters/dev \
    --log-level info 
    ```
2. Create source and kustomize as per the official documentation.
3. create alert-prodiver as slack
4. Create alert.
    ```
      eventSeverity: info
      eventSources:
      - kind: Kustomization
        name: '*'
      ```  

### Expected behavior

slack message should have option to format message/payload

### OS / Distro

macOS BigSur 11.5

### Flux version

flux version 0.17.2

### Flux check

► checking prerequisites
✔ kubectl 1.21.1 >=1.18.0-0
✔ Kubernetes 1.20.7-eks-d88609 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Git provider

Github

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You can add the cluster name and any other env specific info to the alert body with `.spec.summary`. Please see the docs here: https://fluxcd.io/docs/components/notification/alert/

**Comment by amjad489** [comment]
thanks @stefanprodan  works fine.
