### ISSUE TITLE
flux is throwing a connection refused error

### ISSUE THREAD

**Issue by vivekgkwd** [fluxcd/flux2#1888]
### Describe the bug

Hi

I am observing the following error on all flux commands 

`➜  ~ flux get helmrelease -A --kubeconfig ~/.kube/config --context arn:aws:eks:us-east-1:xxxxxxxxx:cluster/cluster_name
✗ kubernetes client initialization failed: Get "https://xxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp: lookup xxxxxxxx.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:56552->[::1]:53: read: connection refused`

with the same config file and context, kubectl is working is fine

`➜  ~ flux --version
flux version 0.17.0`

It was working fine for me and suddenly I have started seeing this error

Things I have tried until now 
upgrading/downgrading the flux cli version
uninstall and install flux and kubectx 
system reboot

We faced this a few days back on my colleague's machine, it was then resolved with a system reboot.

Stuck on this for a week now

### Steps to reproduce

I don't have these 

### Expected behavior

flux doesn't throw an error

### OS / Distro

macOS Big Sur 11.6

### Flux version

0.17.0

### Flux check

`➜  ~ flux check
► checking prerequisites
✔ kubectl 1.22.2 >=1.18.0-0
✗ Kubernetes API call failed: Get "https://XXXXXXXXXXX.gr7.us-east-1.eks.amazonaws.com/version?timeout=32s": dial tcp: lookup XXXXXXXXXX.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:55189->[::1]:53: read: connection refused
► checking controllers`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vivekgkwd** [comment]
PS: this is happening irrespective of the target cluster

**Comment by squaremo** [comment]
> read udp [::1]:55189->[::1]:53:

This part of the error shows that it's trying and failing to use DNS to IPv6 localhost to resolve a hostname. Is that what you expect in your local setup?

**Comment by vivekgkwd** [comment]
This is resolved post restoring the /etc/resolv.conf
Had delete this earlier while debugging undesired entries in the resolv.conf, expecting it to be auto restored which didn't happen
Populated the file manually and flux is working fine now.
Although rest all applications were working fine with blank /etc/resolv.conf

Thanks , closing this issue
