### ISSUE TITLE
Document `ReconcileStrategy` field for `HelmRelease`

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#1911]
The upcoming CLI release will include controller versions that supports the `ReconcileStrategy` field via https://github.com/fluxcd/source-controller/pull/308 and https://github.com/fluxcd/helm-controller/pull/329.

The `HelmRelease` documentation (including the migration guide) should document this new capability, as at present it documents a limitation:

```
**There is one caveat you should be aware of:** to make the
source-controller produce a new chart artifact, the `version` in the
`Chart.yaml` of the chart must be bumped.
```

**Comment by arbourd** [comment]
https://github.com/fluxcd/website/pull/516
