### ISSUE TITLE
[0.18.0] flux check shows components as not ready

### ISSUE THREAD

**Issue by tbondarchuk** [fluxcd/flux2#1921]
### Describe the bug

Updated 4 clusters from 0.17.2 to 0.18.0, flux check now shows some components as not ready, even though everything seems to be running just fine - all pods were updated and are up and running.

two clusters managed from same repo on gitlab:
```sh
► checking prerequisites
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.19.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed
```

two clusters managed from another repo on github:
```sh
► checking prerequisites
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.19.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✗ kustomize-controller: deployment not ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.1
✗ notification-controller: deployment not ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✗ source-controller: deployment not ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed
```

flux binary installed by brew.
Can provide additional info if needed.

### Steps to reproduce

1. update existing cluster by running `flux bootstrap`
2. run `flux check` 

### Expected behavior

all components shown as 'ready'

### OS / Distro

MacOS 11.6 (x86_64)

### Flux version

0.18.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.19.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aliusmiles** [comment]
Thanks!

> Compute function that takes a single resource and computes the status for this resource based on the fields in the status object for the resource

So if I got it right, I'd need to collect `status` field from `kubectl describe deployments|rs|pods` and compare them between clusters?

**Comment by aliusmiles** [comment]
works with 5sec, everything below - starting to fail, especially for US-west cluster (farthest from me)

I guess ideally that polling duration should be configurable, plus check should produce an error message not fail readiness status? Though 5sec sounds like a safe middle ground to work in most cases.

**Comment by Meghavardhinik** [comment]
Hi,

When i'm trying to bootstrap it's showing me the following error
checking prerequisites
✔ Kubernetes 1.27.4 >=1.25.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.36.1
✗ image-automation-controller: deployment not ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1

And my flux version is flux: v2.1.1

And I'm trying to bootstrap the flux in minikube with the version v1.27.4

Can anyone suggest me how to resolve this?
