### ISSUE TITLE
Kustomization reconciliation failed since 0.18

### ISSUE THREAD

**Issue by L3o-pold** [fluxcd/flux2#1922]
### Describe the bug

```shell
flux reconcile kustomization prometheus-base
► annotating Kustomization prometheus-base in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: APIService/v1beta1.custom.metrics.k8s.io dry-run failed, error: Patch "https://*:6443/apis/apiregistration.k8s.io/v1/apiservices/v1beta1.custom.metrics.k8s.io?dryRun=All&fieldManager=kustomize-controller&force=true": stream error: stream ID 677; INTERNAL_ERROR
```

### Steps to reproduce

1. Install flux
2. Use Kustomization with CRD

### Expected behavior

Kustomize reconciliation without error

### OS / Distro

Debian 10

### Flux version

flux version 0.18.1

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.21.5 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Git provider

Gitlab

### Additional context

```shell
flux-system 	prometheus-base              	False	APIService/v1beta1.custom.metrics.k8s.io dry-run failed, error: Patch "https://*:6443/apis/apiregistration.k8s.io/v1/apiservices/v1beta1.custom.metrics.k8s.io?dryRun=All&fieldManager=kustomize-controller&force=true": stream error: stream ID 1403; INTERNAL_ERROR    	master/6bc06666adcd6e3d6040a6a51d13de1779732d80 	False   
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by L3o-pold** [comment]
Seems an issue with Kubernetes 1.18 itself.

**Comment by stefanprodan** [comment]
@L3o-pold that issues was fixed in 1.18.18, looks like we got the check wrong...

**Comment by L3o-pold** [comment]
@stefanprodan no problem, we are currently updating to latest 1.18 👍

**Comment by stefanprodan** [comment]
I have updated the upgrade guide with a workaround for metrics-server https://github.com/fluxcd/flux2/discussions/1916#discussioncomment-1458041
