### ISSUE TITLE
[0.18.1] admission webhook "elastic-es-validation-v1.k8s.elastic.co" does not support dry run

### ISSUE THREAD

**Issue by ambis** [fluxcd/flux2#1927]
### Describe the bug

After installing 0.18.1 (from 0.17.1) we started receiving the following errors:

```
Elasticsearch/logging/elasticsearch dry-run failed, reason: BadRequest, error: admission webhook "elastic-es-validation-v1.k8s.elastic.co" does not support dry run
```

We are running ECK (Elastic Cloud on Kubernetes v1.5) https://www.elastic.co/guide/en/cloud-on-k8s/1.5/index.html

We'll start upgrading ECK from our 1.5 to 1.8, in case it has added a dry-run support. But in case it hasn't, you guys should be aware that this could be a thing. 

### Steps to reproduce

1. Install ECK 1.5
2. Install flux 0.18.1
3. Observe this error

### Expected behavior

No such error would occur.

### OS / Distro

MacOS 11.6

### Flux version

0.18.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.4 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ambis** [comment]
Ok, looks like upgrade to ECK 1.8 fixed this problem: https://github.com/elastic/cloud-on-k8s/pull/3834

**Comment by zzvara** [comment]
I'm using Flux 0.20.1 and ECK 1.8.0 and it is still a problem.

**Comment by ringerc** [comment]
Great, the FAQ for that is gone now...
