### ISSUE TITLE
Potential race condition during flux bootstrap

### ISSUE THREAD

**Issue by ghost** [fluxcd/flux2#1980]
### Describe the bug

A `flux bootstrap` will fail if the repository already exists and contains:

* previously generated SealedSecret Controller HelmRelease
* HelmReleases using a SealedSecret

This results in:

```
✗ SealedSecret/postgres/postgresql-configs dry-run failed, error: no matches for kind "SealedSecret" in version "bitnami.com/v1alpha1"
```

This is because the first round of Kustomize apply cannot complete since the CRD is missing but the CRD will be there only after SealedSecret HelmRelease is applied. This will prevent Kustomize to reconcile.

This is the bootstrap output:

```
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ SealedSecret/postgres/postgresql-configs dry-run failed, error: no matches for kind "SealedSecret" in version "bitnami.com/v1alpha1"

► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 1 health check failure(s)
```

### Steps to reproduce

Doing a `flux bootstrap` on a repository already containing the SealedSecret HelmRelease and another HelmRelease using a SealedSecret CRD.

### Expected behavior

Kustomize during bootstrap should proceed even if dry-run fails to enable Helm controller to deploy helm releases.

### OS / Distro

N/A

### Flux version

flux: v0.19.0 helm-controller: v0.12.1 kustomize-controller: v0.16.0 notification-controller: v0.18.0 source-controller: v0.16.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by comminutus** [comment]
@valeriano-manassero how did you actually solve this? Seems like adding Flux kustomization resources with `dependsOn` references doesn't solve the problem.
