### ISSUE TITLE
Kustomization with long name fails to create any resources

### ISSUE THREAD

**Issue by andyspiers** [fluxcd/flux2#2004]
### Describe the bug

Kubernetes resources generally accept a `metadata.name` field of up to 253 characters.

However, a Kustomization with a `metadata.name` field longer than 63 characters cannot create any resources.

This is because it attempts to label every resource created with `kustomize.toolkit.fluxcd.io/name: <value of metadata.name>` and the maximum length for a _label value_ is 63 characters.

### Steps to reproduce

I prepared a small test repo with some test files to demonstrate fully how this bug can be reproduced: https://github.com/andyspiers/flux-bug-test

In summary:
Define a Kustomization with a short name and it will function fine
Define a Kustomization with a name longer than 63 characters and observe that it fails to create any resources

```shell
$ kubectl get kustomization -A
NAMESPACE     NAME                                                                   READY   STATUS   AGE
flux-system   long-name-which-goes-on-and-on-and-on-until-it-exceeds-63-characters   False   ConfigMap/default/test-long dry-run failed, reason: Invalid, error: ConfigMap "test-long" is invalid: metadata.labels: Invalid value: "long-name-which-goes-on-and-on-and-on-until-it-exceeds-63-characters": must be no more than 63 characters
              14s
flux-system   short-name                                                             True    Applied revision: main/625dab6516a942ca3067300b14d20b37861d2244   14s
```

I can confirm this behaviour exists in the latest fluxv2 release (0.19.1)

### Expected behavior

That either I should not be permitted to create a Kustomization with a name longer than 63 characters or, preferably, that Flux correctly tracks ownership of resources with long names by somehow _abbreviating_ the label value.

To abbreviate the label value I can think of a few possible options:

1. if metadata.name > 63 characters, calculate a hash of the whole metadata.name, truncate the value from the middle and insert the hash into it
   - example input: my-kustomization-starts-here-and-then-goes-on-until-its-really-long-and-then-reaches-the-end (92 chars)
   - calculate a hash, e.g. first 7 chars of sha256sum: `38d06e5`
   - take first and last 27 chars of full name, then insert hash into the middle surrounded by `-`
   - example output:`my-kustomization-starts-her-38d06e5-ng-and-then-reaches-the-end`

2. instead of reproducing metadata.name in the label value, use a hash of it. For human convenience store the original metadata.name value in an annotation

### OS / Distro

Linux via Docker Desktop / Kind

### Flux version

0.19.1

### Flux check

```
$ flux check
► checking prerequisites
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.1
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Closing this as `wontfix`, the labels are used in tracing, garbage collection and to determine ownership, changing them to a SHA sum would break all of Flux.

**Comment by andyspiers** [comment]
@stefanprodan, I appreciate that to a SHA is a bigger change, but there is another suggestion in the issue which is to prevent creation of a Kustomization with a name longer than 63 characters - is this possible, e.g. by changing the CRD of Kustomization to validate the contents of metadata.name?

**Comment by stefanprodan** [comment]
> is this possible, e.g. by changing the CRD of Kustomization to validate the contents of metadata.name?

I'm not sure it's possible since we use controller-gen to automatically generate the CRDs from source code. But please open an issue in kustomize-controller and we can try it there.
