### ISSUE TITLE
Implement defaulting of observedGeneration to -1 in all controllers

### ISSUE THREAD

**Issue by makkes** [fluxcd/flux2#2007]
This is a follow-up to fluxcd/kustomize-controller#387 for aligning the behaviour implemented in the fix to that issue to all other controllers:

* fluxcd/image-automation-controller#275
* ~image-reflector-controller (ImageRepository, ImagePolicy)~
* ~source-controller (HelmRepository, HelmChart, GitRepository, Bucket)~

**Comment by sbernheim** [comment]
@makkes - I'm planning to submit PR for the `image-automation-controller` ImageUpdateAutomation type as a classroom example to demonstrate the process for first-time contributors.  Feel free to assign it to me if you have no objection.

**Comment by makkes** [comment]
Thanks @sbernheim. I assigned you.
