### ISSUE TITLE
How to deploy multiple operator on one cluster

### ISSUE THREAD

**Issue by mhsh64** [fluxcd/flux2#2012]
Here is the plan

Flux namespace1: flux-system

Flux namespace2: flux-system-dedicated

In each namespace we are deploying source and kustomize operators.
We also deployed kustomization and gitrepositories under flux-system namespace,

But we observed even the operators in flux-system-dedicated are monitoring those crds in flux-system namespace

Is this possible to have multiple fluxv2 operators on one cluster dedicated with their own kustomization and gitrepositories crds?

**Comment by davinkevin** [comment]
I have the same needs as the title describes, but for other purpose. 

As cluster maintainers, we try to keep all our system available during "upgrades", simple to rollback for us and our users. 
So, our simplest (and best?) solution is to deploy some tools "twice" and switch namespace a version is responsible of, on demand. 

To detail it, it would look like that for Flux: 

* install Flux vX
* Use it on every namespace
* Flux vY is released
* Install Flux vY without any responsibility, vX is still here and responsible for everything
* We *choose* to use Flux vY on namespace *A*
* We check everything is ok. If something goes wrong, we can go back and use flux vX for namespace *A*. 
* When every NS are migrated, we can remove Flux vX

This is like what [Istio provides for Canary release](https://istio.io/latest/docs/setup/upgrade/canary/) by the way, which is very helpful, especially for a so critical things like network or, in flux context, application delivery.

**Comment by stefanprodan** [comment]
@davinkevin you could do a canary deployment of Flux using RBAC to restrict what a Flux instance can see in the cluster. For example, deny the installed version access to some namespace, then deploy the new Flux instance with RBAC that can access only that namespace.

**Comment by davinkevin** [comment]
Thanks @stefanprodan ! It's a good trick to achieve that. 

To be able to delegate this operation (service account RBAC modification) to (human) namespace operator, we have to create a set of role attached to each namespace. It's possible, but hard to manage at scale. 

Do you think this is something possible at flux level to use some labels to do that at application level? Exactly like istio is doing? It's a powerful solution and really simple to delegate in a "shared clusters" with hundreds of teams. 

But again, thank you for the intermediate solution, it can help 👍

**Comment by nikodemjedynak-dnv** [comment]
@stefanprodan How would you recommend achieving the RBAC separation on what Flux instance can see in the cluster? I have reused the ClusterRole from RBAC from the community supported helm chart and role-binded it to the namespaces that I would prefer to use, however, all of the controllers seem to be seeking the ability to view CRDs on the cluster scope. Is it possible to override such behaviour? 
Thanks for any tips!

**Comment by stefanprodan** [comment]
We now support deploying multiple Flux controllers via sharding, docs here: https://fluxcd.io/flux/cheatsheets/sharding/
