### ISSUE TITLE
Flux components Go v1.17 upgrade

### ISSUE THREAD

**Issue by relu** [fluxcd/flux2#2016]
This is an umbrella issue to keep track of the Go version upgrade work across all of the Flux components.

* [x] pkg https://github.com/fluxcd/pkg/pull/175
* [x] go-git-providers: https://github.com/fluxcd/go-git-providers/pull/139
* [x] notification-controller https://github.com/fluxcd/notification-controller/pull/279
* [x] source-controller https://github.com/fluxcd/source-controller/pull/473
* [x] kustomize-controller https://github.com/fluxcd/kustomize-controller/pull/478
* [x] image-reflector-controller https://github.com/fluxcd/image-reflector-controller/pull/190
* [x] image-automation-controller https://github.com/fluxcd/image-automation-controller/pull/248
* [x] helm-controller https://github.com/fluxcd/helm-controller/pull/348
* [x] flux2 https://github.com/fluxcd/flux2/pull/2271
* [x] terraform-provider-flux https://github.com/fluxcd/terraform-provider-flux/pull/210

**Comment by stefanprodan** [comment]
Let's block this until Kubernetes client-go and controller-runtime switch to Go 1.17 https://github.com/kubernetes-sigs/controller-runtime/blob/master/go.mod

**Comment by relu** [comment]
Sounds good to me.

**Comment by stefanprodan** [comment]
So Kubernetes has switched to Go 1.17 for compiling but go.mod is still on 1.16 format. I propose we do the same, bump Go in CI and in the Dockerfiles to 1.17, leave go.mod as it.

**Comment by relu** [comment]
@stefanprodan I'm not sure if that applies to our repos. I tried to search for a reason why they decided to do that and found two relevant comments [here](https://github.com/kubernetes/kubernetes/pull/106596#issuecomment-976936028) and [here](https://github.com/kubernetes/kubernetes/pull/106665#issuecomment-978877834). It looks like this is just because the reporting tools they use are not (yet?) supporting the dependency graph information that go mod 1.17 handles.

On a side note, controller-runtime has the mod changes in place in [master](https://github.com/kubernetes-sigs/controller-runtime/blob/master/go.mod) right now but there's not yet a released version containing the change if we're still waiting for that to happen.

**Comment by stefanprodan** [comment]
controller-runtime with Go .1.7 has been released https://github.com/kubernetes-sigs/controller-runtime/blob/v0.11.0/go.mod#L3

@relu Can update controller-runtime in fluxcd/pkg and rebase your PR? I'm for getting this in now.

**Comment by relu** [comment]
@stefanprodan definitely, I'll get to it.
