### ISSUE TITLE
flux bootstrap git doesn't work with GitHub SSH format

### ISSUE THREAD

**Issue by devmattrick** [fluxcd/flux2#2029]
### Describe the bug

I wanted to avoid using GitHub Personal Access tokens for this because I was lazy and didn't necessarily want to give access to all of my repos so I decided to try to use the git subcommand and just create the repo beforehand instead of github. Unfortunately, it seems like flux doesn't work when trying to use an SSH connection:

```sh
matt@hydrogen:~$ flux bootstrap git --url=ssh://git@github.com:devmattrick/flux-test.git
✗ parse "ssh://git@github.com:devmattrick/flux-test.git": invalid port ":devmattrick" after host
```

I also tried using the `--username` flag but it also doesn't work:
```sh
matt@hydrogen:~$ flux bootstrap git --url=ssh://git@github.com/flux-test.git --username=devmattrick
► cloning branch "main" from Git repository "ssh://git@github.com/flux-test.git"
✗ failed to clone repository: repository not found
```

I think a simple solution would be to just support the format commonly used in "git clone" (omitting the `ssh://`):
```sh
flux bootstrap git --url=git@github.com:devmattrick/flux-test.git
```

The obvious workaround for GitHub/ GitLab is to use the `github` and `gitlab` suncommands, but this wouldn't work for other Git repository hosting providers like Gitea, for example.

Thanks for reading!

### Steps to reproduce

1. Install Flux using the script
2. Create a new repo on GitHub
3. Attempt to run `flux bootstrap git --url=ssh://<github repo ssh url>`

### Expected behavior

Should properly bootstrap the repository using git.

### OS / Distro

Windows 10 WSL - Ubuntu 20.04.3

### Flux version

0.20.0

### Flux check

N/A but for completion's sake:
```sh
matt@hydrogen:~$ flux check
► checking prerequisites
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ all checks passed
```

### Git provider

git

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
As documented here https://fluxcd.io/docs/installation/#generic-git-server the URL format for SSH is: `flux bootstrap git --url=ssh://git@github.com/devmattrick/flux-test.git `

**Comment by stefanprodan** [comment]
> I wanted to avoid using GitHub Personal Access tokens for this because I was lazy and didn't necessarily want to give access to all of my repos 

The PAT is used to generate a SSH deploy key that gives Flux access only to that repo, Flux does not stores the PAT on your cluster unless you tell it to. Please see the docs https://fluxcd.io/docs/installation/#github-and-github-enterprise

**Comment by devmattrick** [comment]
> As documented here https://fluxcd.io/docs/installation/#generic-git-server the URL format for SSH is: `flux bootstrap git --url=ssh://git@github.com/devmattrick/flux-test.git `

Ah I hadn't seen it because I was looking at the Flux CLI documentation page [here](https://fluxcd.io/docs/cmd/flux_bootstrap_git/). It may be worth documenting it there as well. I also think it may be worth supporting that format in general but that's up to the maintainers, of course. If not, feel free to close this issue.

> > I wanted to avoid using GitHub Personal Access tokens for this because I was lazy and didn't necessarily want to give access to all of my repos
> 
> The PAT is used to generate a SSH deploy key that gives Flux access only to that repo, Flux does not stores the PAT on your cluster unless you tell it to. Please see the docs https://fluxcd.io/docs/installation/#github-and-github-enterprise

Yeah that's what I ended up doing, it was just more convenient for me to use SSH because I already had my SSH key set up and stuff.

**Comment by stefanprodan** [comment]
The `bootstrap git` examples are for a generic Git server, `<org>/<repo>` format is specific to GitHub. Going to close this, thanks.
