### ISSUE TITLE
GitHub bootstrap: You're using an RSA key with SHA-1, which is no longer allowed.

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#2040]
The default SSH deploy key setting used by `flux bootstrap` no longer works with GitHub.

Relevant changes: https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by HeroCC** [comment]
I started getting this error, what is the recommended way to resolve the error? Is re-running the entire bootstrap safe, or is there a way to force it to just regenerate the SSH key?

**Comment by tellisnz-shift** [comment]
> I started getting this error, what is the recommended way to resolve the error? Is re-running the entire bootstrap safe, or is there a way to force it to just regenerate the SSH key?

@HeroCC @AnkurJain10 @dexoid - as per https://cloud-native.slack.com/archives/CLAJ40HV3/p1641866183079500?thread_ts=1641866131.079300&cid=CLAJ40HV3 - upgrade flux, delete the flux-system secret, and re bootstrap worked for me and seemed non detructive

**Comment by or-shachar** [comment]
What should we do if we don't use the flux bootstrap command line but the Terrraform provider?

Seems like something has changed today:
![image](https://user-images.githubusercontent.com/2962963/148966307-50add1ec-3f2f-467d-ab0f-0fa076ab9504.png)

The thing is - the `known_hosts` field in the secret was updated months ago to the right value:
```
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
```

Maybe we should be using the `Ed25519` key?

**Comment by snahelou** [comment]
With Terraform provider @or-shachar  you just have to create a new key 
`
resource "tls_private_key" "main" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}
`

instead of RSA. Apply and modify git repo if not managed by TF

**Comment by or-shachar** [comment]
Was just about to post that the problem was not in the known_hosts but with our deploy key.
The solution it to replace: 
```terraform
resource "tls_private_key" "main" {
  algorithm   = "RSA"
  ecdsa_curve = "4096"
}
```
with:
```terraform
resource "tls_private_key" "main" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}
```

Just like @snahelou mentioned 🙏
