### ISSUE TITLE
Add a note to YAML files which should not be changed manually

### ISSUE THREAD

**Issue by rombert** [fluxcd/flux2#2049]
### Describe the bug

Certain files created by `flux bootstrap` will be overwritten if manually changed. This is not immediately obvious and can lead to confusing situations.

I suggest that these files have a comment that explains this, something along the line of

```yaml
# Do not make changes to this file, it will be overwritten if you run flux bootstrap again 
```

### Steps to reproduce

1. Install Flux (`flux bootstrap`)
2. Change the `gotk-sync.yaml` file
3. Run Flux bootstrap again

### Expected behavior

I should be made aware of the fact that the file will be overwritten when opening it.

See also https://github.com/fluxcd/flux2/discussions/1967 .

### OS / Distro

openSUSE Tumbleweed

### Flux version

0.19.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I propose a shorter comment (similar to what controller-gen does):

```
# This manifest was generated by flux bootstrap. DO NOT EDIT.
```

**Comment by rombert** [comment]
Awesome, thanks for the quick turnaround!
