### ISSUE TITLE
internal/docs: document libgit2 update procedure

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#2052]
We have documented the outline of releasing (and updates) in https://github.com/fluxcd/flux2/blob/main/docs/internal/release.md#upgrade-kubernetes-modules. This document could be enriched with a reference to updating `libgit2` as part of a source-controller or image-automation-controller update, which is documented (partly) here: https://github.com/fluxcd/golang-with-libgit2#contributing

**Comment by pjbgf** [comment]
Put this on hold as `libgit2` may be decommissioned soon.
