### ISSUE TITLE
[IMPROVEMENT] Unspecific error mesages in flux get

### ISSUE THREAD

**Issue by tnet-ag** [fluxcd/flux2#2055]
### Describe the bug

Had a nasty bug in a external  Helm Release YAML File which I had trouble to find.
(the values YAML is integrated as a regular file in the release directory via kustomization)

in 

`flux get helmreleases -n default  `

and after manual reconciliation

I just got the Error:

`install retries exausted`

The Information for fixing this error i got by checking the helm controller logs 
-> 

`kubectl logs -f -n flux-system helm-controller-`

The reason was that I had used a Int for a ENV instead of an String.

### Steps to reproduce

-

### Expected behavior

Would be be great to have that information in the 

`flux get helmreleases -n default  `

Not the first time I ran into this

### OS / Distro

-

### Flux version

v0.19.1

### Flux check

► checking prerequisites
✗ flux 0.19.1 <0.21.1 (new version is available, please upgrade)
✔ Kubernetes 1.19.13-gke.1900 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.11.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.12.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.11.0
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see the FAQ on how to debug helm errors: https://fluxcd.io/docs/faq/#how-to-debug-not-ready-errors
