### ISSUE TITLE
Impossible to bootstrap without push

### ISSUE THREAD

**Issue by chaholl** [fluxcd/flux2#2073]
### Describe the bug

Let's say I have a gitops repo with a `main` branch and a bunch of development clusters synchronized with that repo via flux. I don't want to allow changes to the `main` branch without some kind of review process.

Generally, I'd do that by using a pull request and apply the appropriate policies/pipelines. However, I can't find a way to do that with flux2. 

If I create a feature branch and sync it using `flux bootstrap` it makes a commit to update the GitRepository `spec.ref.branch`. Now, when I merge that feature branch into 'main', it still has the old feature branch in the GitRepository config. Since I don't allow direct changes to 'main', I can't fix this without a whole load of hassles. That means I can't use flux to sync the feature branch, and therefore can't test that flux sync works as expected without merging to 'main'

Long story short - is there some way to bootstrap without pushing back to the repo? If not, why not? Will you accept a PR with a new flag that allows that behaviour?

### Steps to reproduce

1. Create a basic repo
2. Sync it to a cluster
3. Prevent commits directly to `main`
4. Create another cluster for feature development
5. Create a new feature branch in the repo
6. Use `flux bootstrap` to sync the feature branch with the new cluster
7. Merge the feature branch into `main`
8. Try to reconcile the original cluster

### Expected behavior

Clusters syncing with the 'main' branch should continue to work as normal. Picking up the new changes from the merged feature branch.

### OS / Distro

N/A

### Flux version

v0.20.1

### Flux check

► checking prerequisites
✗ flux 0.21.1 <0.22.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.2 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Bootstrap without git push can be done with:
- flux install
- flux create source git flux-system
- flux create kustomization flux-system

**Comment by chaholl** [comment]
Thanks @stefanprodan 

I'd thought about doing it all manually as suggested, but it's not very user friendly. Manually setting up credentials for git repo access adds even more steps

My aim is to ease the pain of developers moving to Kubernetes by using Flux to manage things centrally so they don't have to. If they have to jump through all these hoops it starts to become a pain again! `flux bootstrap` is nice and easy. All it needs is a nice `no-push` flag :) Happy to work on a PR if it's something you'd consider including in the product.

**Comment by stefanprodan** [comment]
@chaholl `flux bootstrap` is meant for cluster admins not for devs and their app repos, installing Flux more than once on a cluster is not supported. The app onboarding process is described here: https://github.com/fluxcd/flux2-multi-tenancy#onboard-tenants

**Comment by chaholl** [comment]
Thanks for that, but I'm not looking for anything as complicated as multi-tenancy. I'm using the same simple gitops repo to create minikube clusters on multiple developers local machines. Flux is only installed once in the minikube cluster.

**Comment by stefanprodan** [comment]
Ok if this is for local clusters, then devs can use their GitHub PATs, to avoid adding deploy keys manually to the repo:
```
flux create source git repo-name \
--url=https://github.com/<org>/<repo>.git \
--username=$GITHUB_USERNAME \
--password=$GITHUB_TOKEN
```

**Comment by chaholl** [comment]
Ok, no bootstrap flag then :)

Maybe I can just use `flux bootstrap` on the main branch then patch the branch config on the `GitRespository` to whatever feature branch I need. As long as I don't run `bootstrap` again it won't mess with my repo. That keeps the happy path simple.

I'll post the steps here in a bit in case they're useful for anybody else and close the issue.  

Thanks for giving it some thought @stefanprodan

**Comment by chaholl** [comment]
So, this isn't as painless as I'd hoped. 

Patching the `GitRepository` works as expected but, the next time you sync `flux-system`, it overwrites the patch. As a result, you need to disable sync for `flux-system` and then manually sync any underlying customizations. For example:

```sh
# Disable automatic sync
flux suspend kustomization flux-system

# Set the branch option to whatever branch you want to connect to   
export BRANCH_NAME=feature/some-new-feature

kubectl patch gitrepo -n flux-system flux-system --type merge --patch "{\"spec\":{\"ref\":{\"branch\":\"$BRANCH_NAME\"}}}"

# Manually sync the config
flux reconcile kustomization infrastructure
flux reconcile kustomization apps
```

Happy to hear of a better solution, but closing for now.
