### ISSUE TITLE
get images policy not display latest image tag

### ISSUE THREAD

**Issue by fgrelaud** [fluxcd/flux2#2081]
### Describe the bug

Upgrade flux version 0.16.1 to 0.22.1 (with Upgrade Flux to the v1beta2 API #1916).

Till 0.16.1, image policy and automation did the trick.
Now, flux get image policy display not the last tag but the one before.

In our container registry (harbor), we can see the image:
<img width="882" alt="Capture d’écran 2021-11-12 à 14 59 37" src="https://user-images.githubusercontent.com/15818887/141479029-f8130134-d43b-452f-8c6f-7fed53692336.png">

> flux get images policy | grep gof-referentiel-backend
gof-referentiel-backend    	True 	Latest image tag for 'harbor-registry.srv.u-bordeaux.fr/gof-referentiel-backend/gof-referentiel-backend' resolved to: dev-754ad08f-1636564064  	harbor-registry.srv.u-bordeaux.fr/gof-referentiel-backend/gof-referentiel-backend:dev-754ad08f-1636564064

All 1mn (image repository interval) i receive notification (on rocketchat) for update to the new image then to previous image and i got a loop.
In my repository gitlab, i can see the infinite commits, change image for new image then for previous image and again and again
![gitlab-commits](https://user-images.githubusercontent.com/15818887/141477985-268a8ece-35a5-4270-99fd-d41c4c8cd037.png)
![previous](https://user-images.githubusercontent.com/15818887/141478022-25f3475d-2205-4b49-b5e3-35a2f4f7c975.png)
![new](https://user-images.githubusercontent.com/15818887/141478045-edc4085e-1cb4-454e-81b1-4ababcbc25a4.png)

.
The policy is as follow:
```apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: gof-referentiel-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gof-referentiel-backend
  filterTags:
    pattern: '^dev-[a-fA-F0-9]+-(?P<ts>[1-9][0-9]*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
``` 

Is this a bug or a misconfiguration from my side ?

### Steps to reproduce

1. install flux with image automation
2. define an imageautomation, imagerepository and imagepolicy
3. flux reconcile image repository got-referentiel-backend
4. flux get images policy | grep gof-referentiel-backend

Error: the latest image display is not the latest but the previous image

And got upgrade to new image then previous then new etc...

### Expected behavior

I expect to see the latest tag.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.22.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.7 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.17.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.17.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.2
✔ all checks passed

### Git provider

gitlab

### Container Registry provider

harbor

### Additional context

image automation:
``` apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@u-bordeaux.fr
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    strategy: Setters
``` 

irepository
``` apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: gof-referentiel-backend
  namespace: flux-system
spec:
  image: harbor-registry.srv.u-bordeaux.fr/gof-referentiel-backend/gof-referentiel-backend
  interval: 1m0s
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
We had a regression bug in flux 0.22.1 for image updates, we'll publish today a new release with a fix.

**Comment by fgrelaud** [comment]
Perfect. Thank you for the quick feedback.

**Comment by fgrelaud** [comment]
Release 0.23 fix the issue for me.
