### ISSUE TITLE
Flux2 Image Automation Update does not work with ECDSA ssh key

### ISSUE THREAD

**Issue by Willem1987** [fluxcd/flux2#2094]
### Describe the bug

After re-bootstrapping flux from 0.16 to 0.22 (and 0.23) i have issue with the ImageAutomationUpdate object. I deleted the flux-system secret ssh key and it got regenerated with default type ECDSA.

The image-automation-controller logs this:
{"level":"error","ts":"2021-11-16T09:34:15.910Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"cluster-image-update-automation","namespace":"f
lux-system","error":"unable to clone: ssh: not an encrypted key"}

After re-bootstrapping with --ssh-key-algorithm=ed25519 and adding that key to gitlab, the Automation worked again.

I found this post on ECDSA:
https://fluxcd.io/blog/2021/10/october-2021-update/#better-transport-and-crypto-support-for-libgit2

But I'm unsure what to make of it.

According to the flux bootstrap git reference ECDSA is now default:
      --ssh-key-algorithm publicKeyAlgorithm   SSH public key algorithm (rsa, ecdsa, ed25519) (default ecdsa)

The key works with the source-controller fine. It only breaks when used with image-automation-controller. I think i read somewhere one controller uses libgit2 (image-automation) and the other(source-controller) might use  go-git?

### Steps to reproduce

Bootstrap flux with additional components --components-extra=image-reflector-controller,image-automation-controller usinga ECDSA ssh key for git repository.
Create an ImageUpdateAutomation.

### Expected behavior

The ImageUpdateAutomation works without errors

### OS / Distro

N/A

### Flux version

flux: v0.23.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.18.14-mirantis-2 >=1.18.4-0 <=1.18.20-0
► checking controllers
✔ helm-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/helm-controller:v0.13.0
✔ image-automation-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/image-automation-controller:v0.17.1
✔ image-reflector-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/image-reflector-controller:v0.13.2
✔ kustomize-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/kustomize-controller:v0.18.0
✔ notification-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► nexus3:8060/ghcr.io/fluxcd/source-controller:v0.18.0
✔ all checks passed

### Git provider

Gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@Willem1987 I can't reproduce this in our e2e test suite. I've asked @SomtochiAma to try it on GitLab as our e2e tests are using GitHub.

**Comment by Willem1987** [comment]
@stefanprodan I don't know if it matters, but i saw in your test set-up that you call bootstrap github specifically.

flux bootstrap github --manifests ./manifests/install/ \
          --owner=fluxcd-testing \
          --repository=${{ steps.vars.outputs.test_repo_name }} \
          --branch=main \
          --path=test-cluster \
          --team=team-z

We run the following generic git bootstrap against gitlab:
flux bootstrap git --url= --components-extra=image-reflector-controller,image-automation-controller --secret-name= --branch=master --path=. --registry= --image-pull-secret=

So there is a difference in the command as wel as the backend used in this case. I wonder is flux bootstrap git would have different behaviour than flux bootstrap github?

**Comment by stefanprodan** [comment]
Both commands generate SSH keys and known host keys in the same way. Do you let Flux generate the key or you've used a pre-generated one?

**Comment by Willem1987** [comment]
I let flux generate the key. And after changing to --ssh-key-algorithm=ed25519 my issues were solved.

**Comment by SomtochiAma** [comment]
Hey @Willem1987 ,
I tried it with a GitLab repo and it worked okay. I was unable to reproduce this on my end.

**Comment by Willem1987** [comment]
Any idea where the issue could lie then? The underlaying OS ("Red Hat Enterprise Linux Server 7.9 (Maipo)) The kubernetes distribution?

**Comment by Willem1987** [comment]
We eventually switched from deploy key to access token because the deploy key seemed to be coupled to the creating user in write acces. Due to protected branches this was an issue.
