### ISSUE TITLE
flux bootstrap git stop working with a github

### ISSUE THREAD

**Issue by alllexandrz** [fluxcd/flux2#2098]
### Describe the bug

Today on all our projects flux bootstrap git stop working with a github

### Steps to reproduce

flux bootstrap git --url=ssh://git@github.com/deployments.git --branch=fluxcd --path=clusters/staging --private-key-file=./private_key --components-extra=image-reflector-controller,image-automation-controller

got error:
► cloning branch "fluxcd" from Git repository "ssh://git@github.com/deployments.git"
✗ failed to clone repository: ssh: handshake failed: knownhosts: key mismatch

the same situation with all existings GitRepository
 Normal  error   8m7s (x33 over 3h55m)  source-controller  unable to clone 'ssh://git@github.com/deploy', error: ssh: handshake failed: knownhosts: key mismatch

### Expected behavior

Flux should boostrap

### OS / Distro

Ubuntu

### Flux version

v0.23.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.10-gke.1600 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.18.0
✔ all checks passed

### Git provider

github

### Container Registry provider

ECR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see https://github.com/fluxcd/flux2/discussions/2097

**Comment by alllexandrz** [comment]
Thanks for a fast response
