### ISSUE TITLE
Kustomziation: Unable to use the pipe sign in patches

### ISSUE THREAD

**Issue by guidoffm** [fluxcd/flux2#2103]
### Describe the bug

`patches` in Kustomization is a list of strings in contrast to `patchesStrategicMerge` that used objects for patching.

Why did you move to just strings?

What I want to do is this:

```yaml
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        spec:
          values:
            server:
              ha:
                config: |
                  ui = true
                  listener "tcp" {
                    address = "0.0.0.0:8200"
                    cluster_address = "0.0.0.0:8201"
                    tls_cert_file = "/etc/certs/vault.crt"
                    tls_key_file  = "/etc/certs/vault.key"
                    tls_client_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                  }

                  storage "dynamodb" {
                    ha_enabled = "true"
                    region     = "eu-central-1"
                    table      = "vault"
                  }
                  
                  seal "awskms" {
                    region     = "eu-central-1"
                    kms_key_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  }

                  service_registration "kubernetes" {} 

```

We have another pipe sign here after `config:`. It seems this breaks the kustomization.

Maybe just a yaml  issue.

### Steps to reproduce

Use the example given above.

### Expected behavior

It should be possible to use multiline string characters in patches.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.21.1

### Flux check

► checking prerequisites
✗ flux 0.21.1 <0.23.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► docker-hub-remote.bahnhub.tech.rz.db.de/fluxcd/helm-controller:v0.12.1
✔ kustomize-controller: deployment ready
► docker-hub-remote.bahnhub.tech.rz.db.de/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► docker-hub-remote.bahnhub.tech.rz.db.de/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► docker-hub-remote.bahnhub.tech.rz.db.de/fluxcd/source-controller:v0.17.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@guidoffm the `patchesStrategicMerge` still works, it hasn't been removed but just deprecated. If `patches` are not a suitable replacement we could consider preserving the the deprecated fields in future API versions.

**Comment by guidoffm** [comment]
What was the motivation to go from YAML to string for the patches? Is there a chance to go to YAML again since it is more clear to have real YAML here and it is much easier to find errors. YAML can be checked for syntax errors. Strings can not.

**Comment by stefanprodan** [comment]
> What was the motivation to go from YAML to string for the patches?

I expect people to use `kustomization.yaml` for creating overlays and validate those in CI before they reach Flux (as showed [here](https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh)).  The Flux Kustomization patches are more of workaround for when you want to patch something urgent (e.g. bump some container tag to fix a CVE).

**Comment by guidoffm** [comment]
You mean it would be better to use the standard k8s kustomization for this `kustomize.config.k8s.io/v1beta1`?
But when I use the main Flux kustomization (e.g. https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/clusters/production/infrastructure.yaml) I can make use of a ConfigMap `cluster-vars` to define variables the can be referenced in other files. If I call standard k8s kustomization for this `kustomize.config.k8s.io/v1beta1` from the Flux kustomization I do not have the chance to use these variables, right?

**Comment by stefanprodan** [comment]
>  If I call a standard k8s kustomization (kustomize.config.k8s.io/v1beta1) from the Flux kustomization I do not have the chance to use these variables, right?

Variables are a post-build action and they work no matter if you use a kustomize config or not.

**Comment by guidoffm** [comment]
Got it
