### ISSUE TITLE
Flux and Helm

### ISSUE THREAD

**Issue by tcheronneau** [fluxcd/flux2#2124]
Hey there, 

We are using Flux since a moment now and it was working quite great with kustomize so far. 
We've decided to move to Helm and the migration is really not as smooth as expected compared to what we were getting with Kustomize. 

Our Helm controller is 0.12.1 and kubernetes version is 1.20.11. 

We had several issues : 
- If we delete a deployment which is part of a helm release it's not put back by Flux (only if you modify the helmrelease file). 
- I just hit something quite weird today when deleted all pod from a namespace deployed by a helm release : it deleted also service account and configmaps. 
- If I override a version of a chart which is deployed by Flux it's not detected and so not redeployed. 

I think it's all the issues / complains we had so far if we compare to kustomize (maybe helm is requiring more configuration that I did not notice so sorry if it's the case). 

Thanks,
Thomas.

**Comment by hiddeco** [comment]
> - If we delete a deployment which is part of a helm release it's not put back by Flux (only if you modify the helmrelease file).

This is a known limitation, see: https://github.com/fluxcd/helm-controller/issues/186#issuecomment-932107655

> - I just hit something quite weird today when deleted all pod from a namespace deployed by a helm release : it deleted also service account and configmaps. 

Without providing precise instructions about the actions you took, and how they are related to a chart, it is hard to say anything useful about this. However, you generally should not manage namespaces through charts.

> - If I override a version of a chart which is deployed by Flux it's not detected and so not redeployed.

What version did you overwrite? As this can refer to multiple things. Generally, the helm-controller should perform an upgrade if you perform a manual `helm upgrade` (which overwrites the version).

**Comment by stefanprodan** [comment]
> We've decided to move to Helm and the migration is really not as smooth as expected compared to what we were getting with Kustomize.

You can't fully replace kustomize overlays with Helm charts. Many things do no belong in a Helm chart, such as namespace, CRDs and other cluster-wide resources.
