### ISSUE TITLE
monitoring-config/podmonitor.yaml only pulls data from image-reflector-controller

### ISSUE THREAD

**Issue by ajrpayne** [fluxcd/flux2#2150]
### Describe the bug

Of the controllers listed, only the last controller in the list has any data in Prometheus. If I change the list, it will always pull data from the final controller listed only.

 selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller

### Steps to reproduce

Follow steps listed here deploying in kind. https://fluxcd.io/docs/guides/monitoring/

### Expected behavior

I would expect to see data from all controllers not just one.

### OS / Distro

arch linux using kind

### Flux version

flux version --client flux: v0.23.0

### Flux check

flux check
► checking prerequisites
✗ flux 0.23.0 <0.24.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by piermotte** [comment]
I have the same problem, there is no active targets if i use flux `podmonitor.yaml`

**Comment by kingdonb** [comment]
We found two ways to solve this:

Either pin kube-prometheus-operator at 19.3.0 as in:
* https://github.com/fluxcd/flux2/pull/2194

or upgrade to prometheus-operator v0.52.1 or greater. This should happen naturally as soon as a release of kube-prometheus-operator includes the v0.52.1 or greater appVersion.

https://github.com/kingdonb/flux2/commit/bcaa4c692881e0be24cd18ea44630b4d10b2b132

Here's an example of how to resolve it without downgrading in the mean-time. (Set values invoking the new prom-operator)

```
prometheusOperator:
  image:
    tag: v0.52.1
  prometheusConfigReloader:
    image:
      tag: v0.52.1
```

**Comment by piermotte** [comment]
After setting prometheusOperator image, it works !  thx @kingdonb !
