### ISSUE TITLE
flux cli should return correct exit code

### ISSUE THREAD

**Issue by yuriydzobak** [fluxcd/flux2#2184]
### Describe the bug

Flux cli don't return correct exit code when it has `stderr`

### Steps to reproduce

```sh
# ./flux --version
flux version 0.24.0
# ./flux get hr -A --no-header
✗ no HelmRelease objects found in flux-system namespace
root@ip-10-255-242-96:/home/ubuntu# echo $?
0
```
```sh
# ./flux get hr -A --no-header |grep -v "Helm"
✗ no HelmRelease objects found in flux-system namespace
# ./flux get hr -A --no-header 2>&1 |grep -v "Helm"
```

### Expected behavior

exit code should be `1`

### OS / Distro

linux,macOS

### Flux version

v0.24.0

### Flux check

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Flux CLI behaves the same as kubectl:

```console
$ kubectl get pods
No resources found in default namespace.

$ echo $?
0
```

**Comment by yuriydzobak** [comment]
Hi,
got it, I thought, flux 0.17 version had issue with kustomization when `grep` didn't work because stdout was in stderr, i thought the issue is same
thank you
