### ISSUE TITLE
flux get kustomizations revision short commit sha instead full commit sha

### ISSUE THREAD

**Issue by jurabek** [fluxcd/flux2#2186]
### Describe the bug

When you have a small monitor and when you call `flux get kustomizations`
it shows `MESSAGE` and `REVISION` columns which contain `branch_name/full_sha` that is pretty long and does not fit to a single row, it is a bit harder when you have errors in specific customizations.

### Steps to reproduce

1. `flux get kustomizations`
2. check MESSAGE and REVISION columns it is very long.
```
NAME                          	READY	MESSAGE                                                                                                                            	REVISION                                                     	SUSPENDED
alb-ingress-controller        	True 	Applied revision: immediate-deployment/a40d363e5270cea36d0743d9fedaa5dd7a567dc5                                                    	immediate-deployment/a40d363e5270cea36d0743d9fedaa5dd7a567dc5	False
```

### Expected behavior

it should show like that
```                                                                                                                          	
alb-ingress-controller   True 	Applied revision: immediate-deployment/a40d363    immediate-deployment/a40d363	False
```

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/8397056/145017724-3b221824-4b40-48ac-bc3b-20846b8be119.png)

### OS / Distro

macOS 12.0.1

### Flux version

flux version 0.17.2

### Flux check

N/A

### Git provider

Github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
I have a wide terminal (176x37) with a very tall/skinny font and it barely fits the output of `flux get ks` on a single screen. FWIW, I agree with this! Unless you use very long branch names or very long kustomization names (or both), with a 7 character SHA this information all fits in a 110 character wide term:

<img width="896" alt="Screen Shot 2021-12-15 at 4 37 35 PM" src="https://user-images.githubusercontent.com/3286998/146268870-0548727b-e7a7-4e82-b556-b753b7707a55.png">

Here's what it would look like ☝️ 

(Compare to:)
<img width="1424" alt="Screen Shot 2021-12-15 at 4 38 26 PM" src="https://user-images.githubusercontent.com/3286998/146268960-1575db83-9075-41b7-b4fe-ff856443c386.png">

So, can there be consumers of the flux cli that depend on this particular formatting, and will we break their scripts by changing this? (I certainly hope not, if there are such consumers that depend on the flux CLI, I hope they use or would ask for a json or yaml output format for any such information they need...)
