### ISSUE TITLE
Bootstrap with http instead of ssh

### ISSUE THREAD

**Issue by plockaby** [fluxcd/flux2#2201]
### Describe the bug

Right now when using flux bootstrap github it will always bootstrap using SSH. This is great because keys are easy to work with. However, the github SSH endpoints timeout pretty frequently and I end up with all this crap in Slack telling me "could not connect to github SSH" which are just transient.

I changed the the GitRepository configuration to use the https endpoint instead of the SSH endpoint and the timeout errors are way way down to like once per week which makes Slack a lot less noisy :)

However, every time I upgrade Flux using "flux bootstrap github", it changes it back to SSH. I don't see any option to force it to use https or to have it leave it alone.

### Steps to reproduce

1. Use flux bootstrap
2. GitRepository settings are reverted.

### Expected behavior

I would expect flux bootstrap to respect the existing GitRepository changes or I would hope that there might be a flag on flux bootstrap to use https instead of ssh.

### OS / Distro

Linux

### Flux version

0.24.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.4+k3s1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see the docs: https://fluxcd.io/docs/installation/#github-and-github-enterprise

PS. using `bootstrap github --token-auth` does what you want. You need to delete the `flux-system` secret before rerunning bootstrap and flux will generate the secret with https credentials.

**Comment by plockaby** [comment]
Thank you for suffering my ignorance. :(

I was looking for HTTP somewhere and didn't think to look for PAT. I appreciate the pointer.
