### ISSUE TITLE
Broken "edit this page" links in Flux CLI section

### ISSUE THREAD

**Issue by SamLR** [fluxcd/flux2#2203]
The "edit this page" links in the right-hand sidebar go to 404 github pages.

I assume this is a hangover of the move to auto-generating these pages from the binary's `help` output

## Steps to reproduce

1. Navigate to any page in the 'Flux CLI' section
2. Click on 'Edit this page' in the right hand side bar

For example, under ['Flux CLI' > 'Flux'](https://fluxcd.io/docs/cmd/flux/) 'Edit this page' links to https://github.com/fluxcd/website/edit/main/content/en/docs/cmd/flux.md which is a 404. 

## Potential solutions

(I have no idea how feasible any of these are, sorry)

* Disable this link on these pages
* Link to the appropriate file in https://github.com/fluxcd/flux2

**Comment by dholbach** [comment]
This
  
```md
importedDoc: true
```

needs to be added in

https://github.com/fluxcd/flux2/blob/37b60666c439dc823af33dc35162de38d5380883/cmd/flux/docgen.go#L59

**Comment by michaelmwangi** [comment]
Hi I would like to work on this if no one has picked it up yet. Thanks

**Comment by ilanpillemer** [comment]
@dholbach if I send a PR would you review it?

**Comment by dholbach** [comment]
@ilanpillemer For sure, yes! <3
