### ISSUE TITLE
Bootstrapping Bitbucket Server always uses port 22

### ISSUE THREAD

**Issue by wpbeckwith** [fluxcd/flux2#2207]
### Describe the bug

When bootstrapping the latest flux (v0.24.1) to a BitBucket 6.10 server
```
flux bootstrap bitbucket-server \
  --owner=foo.user \
  --repository=flux-infra \
  --branch=main \
  --path=clusters/valhalla \
  --ssh-hostname='stash.company.com:7999' \
  --hostname=stash.company.com \
  --personal
```

The logs for the deployed source-controller show that the git clone fails because it is trying to connect to our server on port 22 and not port 7999.

```
{"level":"info","ts":"2021-12-12T15:42:02.590Z","logger":"controller.helmchart","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","worker count":2}
{"level":"error","ts":"2021-12-12T15:44:24.170Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"flux-system","namespace":"flux-system","error":"unable to clone 'ssh://git@stash.company.com/~foo.user/flux-infra': dial tcp 12.34.56.78:22: connect: connection timed out"}
```

It should be trying to clone from `ssh://git@stash.company.com:7999/~foo.user/flux-infra`

### Steps to reproduce

1. Execute the following to a server on a non-standard ssh port
```
flux bootstrap bitbucket-server \
  --owner=foo.user \
  --repository=flux-infra \
  --branch=main \
  --path=clusters/valhalla \
  --ssh-hostname='stash.company.com:7999' \
  --hostname=stash.company.com \
  --personal
```
2. Watch the logs for the sorce-controller pod after it comes up.

### Expected behavior

A successful post bootstrap sync.

### OS / Distro

macOS 11.6

### Flux version

v0.24.1

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.21.2-eks-06eac09 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

BitBucket Server 6.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by achetronic** [comment]
May be you are suffering the same issue but in another .go file
https://github.com/fluxcd/flux2/pull/2216

**Comment by souleb** [comment]
I think it is slightly different as only the `sshHostname` is impacted. The url for non ssh operation is fine.
