### ISSUE TITLE
flux does not delete unmanaged namespace in the cluster

### ISSUE THREAD

**Issue by himani-dangwal** [fluxcd/flux2#2209]
### Discussed in https://github.com/fluxcd/flux2/discussions/2134

<div type='discussions-op-text'>

<sup>Originally posted by **himani-dangwal** November 24, 2021</sup>
We are using Flux2 and helm3 for our deployment. Previously when we deleted the kustomization files from the Git repo then after the sync the namespace and its corresponding objects started getting delete from the cluster. But recently it has stopped working. 
 Even if we delete the files from the git repo the namespace and its objects are there in the cluster . If we have to delete them, we manually delete the helmrelease files from the cluster.  
  Is there any change in the implementation recently or we are missing something ?</div>

**Comment by stefanprodan** [comment]
Have you updated the API version of all Flux Kustomizations to `v1beta2`? Is the namespace manifest in Git?
