### ISSUE TITLE
pick correct flux cli version

### ISSUE THREAD

**Issue by bob-rohan** [fluxcd/flux2#2224]
### Describe the bug

This is a feature request, not a bug. Sorry if I've opened it in the wrong place. Please point me in the right direction.

There are incompatibilities found when using a flux cli version which differs to the flux-system version installed on the cluster.

It would be helpful, if the flux cli, or another tool such as offered below, were able to use meta-data to determine the relevant version of the flux cli to use for a particular cluster.

To go above and beyond, or approach in a different way, any automated introspection of the version of flux installed on a cluster, and subsequent alignment of flux clis chosen (assumes multiple version of the cli concurrently installed on one machine as demonstrated in links below),  would be great. 

https://github.com/rbenv/rbenv
https://github.com/tfutils/tfenv

### Steps to reproduce

n/a

### Expected behavior

n/a

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gecube** [comment]
> There are incompatibilities found when using a flux cli version which differs to the flux-system version installed on the cluster.

The same issue. When I tried to use different version of flux cli and flux in cluster, I can list all objects, except for Kustomization, that are not shown. It is very annoying, because with `kubectl get kustomization` I can get them...

**Comment by bob-rohan** [comment]
Think I'll give this a try

https://github.com/tablexi/asdf-flux2
