### ISSUE TITLE
Artifactory chart repo url being changed

### ISSUE THREAD

**Issue by felixtoe** [fluxcd/flux2#2226]
### Describe the bug

I experience the exact same bug that was already described and fixed in Flux 1:
https://github.com/fluxcd/flux/issues/1707

```
For a given Chart repository at "https://our.server.com/artifactory/helm-virtual" and a chart "foo" version "1.0.0", we get the following error:

Failed to fetch https://our.server.com/helm-virtual/foo-1.0.0.tgz : 404 Not Found
The "/artifactory" part of the URL is missing.
```

### Steps to reproduce

Create a HelmRepository with URL `https://our.server.com/artifactory/helm-virtual` and one HelmRelease.

### Expected behavior

HelmChart being pulled from `https://our.server.com/artifactory/helm-virtual`

### OS / Distro

Debian

### Flux version

v0.24.1

### Flux check

> flux check
► checking prerequisites
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Can you share a pseudo example of a chart that's in the "virtual" repository index YAML?

I have a vague suspicion it publishes invalid chart references, which contain a `/` in the name, which are not supported by Helm: https://helm.sh/docs/chart_best_practices/conventions/#chart-names, and is considered a historical architectural mistake from Artifactory: `https://github.com/helm/helm/issues/9017#issuecomment-728204300`.
