### ISSUE TITLE
HelmCharts error status: dependency build error: failed to add local dependency 'some-service': can't get a valid version for constraint '0.0.1'

### ISSUE THREAD

**Issue by jarzyna63** [fluxcd/flux2#2239]
We use child-charts (sub-charts) in our helm chart configuration. The sub-charts are available in the same repository as the main chart so dependencies do not need to be downloaded. Until the Flux version 0.23.0 all worked correctly, from the version 0.24.0 we receive the error:

dependency build error: failed to add local dependency 'some-service': can't get a valid version for constraint '0.0.1'

**Comment by stefanprodan** [comment]
This should be fixed long time ago. If the issue persists using the latest flux2 release please open a new issue.
