### ISSUE TITLE
Use standardized status condition schema

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/flux2#225]
The standardized status condition schema:
https://github.com/kubernetes/enhancements/pull/1624

Is available in kuberentes 1.19 libraries:
https://github.com/kubernetes/apimachinery/blob/release-1.19/pkg/apis/meta/v1/types.go

There are additionally some helper libraries which should be available in an upcoming version:
https://github.com/kubernetes/kubernetes/pull/92717
This for example handles only updating lastTransitionTime if the status actually changes, which
we are not doing currently.

Also `observedGeneration` is included as a per-condition field.

**Comment by seaneagan** [comment]
Presumably for helm-controller we'll need to wait for a helm version (likely 3.4) which supports kubernetes 1.19 libraries.

**Comment by stefanprodan** [comment]
The controller-runtime has been updated to 1.19 in master, we have to wait for a release there as well.

**Comment by hiddeco** [comment]
> Presumably for helm-controller we'll need to wait for a helm version (likely 3.4) which supports kubernetes 1.19 libraries.

Most of the time we were/are able to overwrite what Kubernetes libraries we want to use, except for the breaking change they made when `context.Context` was introduced to all methods.

**Comment by relu** [comment]
Implemented in https://github.com/fluxcd/flux2/pull/474. Can be closed.
