### ISSUE TITLE
Add Node Selector Option to Bootstrap CLI Command

### ISSUE THREAD

**Issue by sdmichelini** [fluxcd/flux2#2252]
### Describe the bug

Currently, when bootstrapping a flux installation, there is no support to specify a nodeSelector for the flux system components. 

We desire to be able to run flux on a dedicated set of highly available nodes. Currently, we have to do a manual kubectl patch deploy in order to achieve this.

### Steps to reproduce

N/A - feature gap

### Expected behavior

When running `flux bootstrap` you should be able to pass in a map of nodeSelector keys and values which will correspond to the K8s nodeSelectors which the deployment gets assigned.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
You can pass in any configuration for Flux through `kustomization.yaml` in the form of `patchesStrategicMerge`, if you pre-seed it in the path this way:

https://fluxcd.io/docs/installation/#customize-flux-manifests

I'm not sure why this wouldn't include `nodeSelector`, and I have used similar to set pod tolerations, I don't know why that wouldn't also work just as well for `nodeSelector` - https://github.com/kingdonb/bootstrap-repo/blob/f5a03305706b0f5f131bca0f1d07e73cb040f07c/apps/openvpn/helmrelease.yaml#L36-L39

Does this help at all?

**Comment by kingdonb** [comment]
It's not clear how the suggestion of using `patchesStrategicMerge` in `kustomization.yaml` is any less than fully meeting the need of this request.

I was able to use this approach to set up node affinities and force my Flux instance onto the `arm` nodes in my cluster, as an example of what is already possible. Here is my mixed arch cluster that sets node selectors using `patchesStrategicMerge`:

https://bitbucket.org/kingdonb/csh-flux/src/791d7b6ef121a2cea1589a34a0a151a39c438150/clusters/mixed-arch-k3s/flux-system/gotk-patches.yaml#lines-19:29

I have a cluster that is some ARM nodes and some intel x86-64 machines, this is an example of setting `nodeSelector` for the flux controller, and you can use it together with the same strategy that you patch other Flux manifest options, this is the same thing that is described in https://fluxcd.io/docs/installation/#customize-flux-manifests

You can make the patches inline or files, I prefer to have them as files and this one is a YAML document list. 👍

Let me know if this solves your issue.

**Comment by stefanprodan** [comment]
Closing this as it can be done before bootstrap as @kingdonb showed above.
