### ISSUE TITLE
Behavior change treats empty array as defined value

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/flux2#2257]
### Describe the bug

Flux will not reconcile and modify an object if the defined fields are not modified. Fields in the object which are not in the source / git stored version are not tracked. I recently upgraded from pre-0.18 (prior to server-side apply) to the latest 0.24.1. Existing manifests started complaining about config drift and being configured every 5 minutes.

Actual example here, the `.rules[]` array previously was not an issue, but now it is treated as a defined value and is being applied and notification generated every 5 minutes: https://github.com/knative/serving/blob/d2461492bea18cde5f9aa0419c8fee24570782aa/config/core/200-serviceaccount.yaml#L25-L38

A controller is modifying the `.rules[]` values, possibly with a mutating webhook.

### Steps to reproduce

Apply an object with an empty array, change the array in the object to be non-empty.

### Expected behavior

Flux should probably keep the old behavior, treating empty arrays as non-defined. But this leaves open the question, what does an empty string, or empty object mean?

### OS / Distro

N/A

### Flux version

v0.24.1

### Flux check

% flux check
► checking prerequisites
✔ Kubernetes 1.19.14-gke.1900 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.14.1
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

GCR

### Additional context

removing `rules: []` solves the issue - but I could see a resource where the schema requires the key to be present to pass validation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Flux has switched to kubectl to Kubernetes server-side apply, we have no control over the 3 way merge, the new behavior is dictated by Kubernetes API merge logic. The only workaround is to remove empty fields from Git, see https://fluxcd.io/docs/faq/#how-do-i-resolve-someresource-configured-events-spam

**Comment by mbrancato** [comment]
Thanks @stefanprodan. I did notice this has been fixed in the latest Knative manifests. I've just manually fixed for my use case.
