### ISSUE TITLE
Fix envtest setup and usage

### ISSUE THREAD

**Issue by aryan9600** [fluxcd/flux2#2273]
We currently have a a target `setup-envtest`  which installs the `etcd`, `kubectl` , etc for users but we don’t use it implicitly in the `test` target. We also don't seem to set the `KUBEBUILDER_ASSETS` env to the dir where the binaries are installed so that they can be found during tests.

Projects:
* [x] flux2
* [x] pkg
* [x] source-controller
* [x] image-automation-controller
* [x] image-reflector-controller
* [x] notification-controller
* [x] source-watcher
* [x] kustomize-controller

**Comment by stefanprodan** [comment]
Please use https://github.com/fluxcd/helm-controller/blob/main/Makefile as an example for all others. Note that `testbin` must be added to gitignore. Also `go get` has been deprecated for binaries, we should use `go install` starting with Go 1.17.

**Comment by stefanprodan** [comment]
We need this for fluxcd/pkg project as well.

**Comment by stefanprodan** [comment]
Thanks @aryan9600 for taking care of this 🥇
