### ISSUE TITLE
Mac shows "/dev/fd/12:type:6332: bad option: -t" when doing flux completion bash

### ISSUE THREAD

**Issue by iangregsondev** [fluxcd/flux2#2274]
### Describe the bug

Using ZSH on a Mac and this is in my .zshrc

```
command -v flux >/dev/null && . <(flux completion bash)
```

This shows the following

```
/dev/fd/12:type:6332: bad option: -t
```

### Steps to reproduce

Add this to the zshrc

```
command -v flux >/dev/null && . <(flux completion bash)
```

and run to install as per instructions.

```
brew install fluxcd/tap/flux
```

### Expected behavior

Should be no error output.

### OS / Distro

mac 12.1

### Flux version

flux: v0.24.1

### Flux check

❯ flux check
► checking prerequisites
✔ Kubernetes 1.19.7+k3s1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Git provider

github

### Container Registry provider

dokcerhub

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Why are you using bash completion to zsh?

```
lux completion zsh -h
Generates zsh completion scripts

Usage:
  flux completion zsh [flags]

Examples:
To load completion run

. <(flux completion zsh)

To configure your zsh shell to load completions for each session add to your zshrc

# ~/.zshrc or ~/.profile
command -v flux >/dev/null && . <(flux completion zsh)

or write a cached file in one of the completion directories in your ${fpath}:

echo "${fpath// /\n}" | grep -i completion
flux completion zsh > _flux

mv _flux ~/.oh-my-zsh/completions  # oh-my-zsh
mv _flux ~/.zprezto/modules/completion/external/src/  # zprezto
```

**Comment by iangregsondev** [comment]
Oppps :-) - I didn't see that.. - Thanks

**Comment by iangregsondev** [comment]
Thanks it worked, stupid mistake. Closing.
