### ISSUE TITLE
Prepare Flux v0.26.0 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#2308]
This is an overarching issue for tracking the Flux v0.26.0 release preparation.

### Catalog and sign artifacts

- [x] https://github.com/fluxcd/flux2/issues/2302
- [x] https://github.com/fluxcd/flux2/issues/2303
- [x] fluxcd.io (document the signature verification of container images, binaries and SBOM)

### Security improvements

- [x] https://github.com/fluxcd/flux2/issues/2340
- [x] https://github.com/fluxcd/flux2/issues/2337
- [x] https://github.com/fluxcd/flux2/issues/2014
- [x] flux2 (drop support for EOL Kubernetes 1.19 in `flux check`)
- [x] fluxcd.io (document the pod security standard and update Kubernetes supported versions)

### Migrate from Debian to Alpine for `libgit2` static build

- [x] https://github.com/fluxcd/source-controller/pull/558
- [x] https://github.com/fluxcd/image-automation-controller/pull/303

### Fuzzing

- [x] https://github.com/fluxcd/pkg/pull/212
- [x] https://github.com/fluxcd/kustomize-controller/pull/536
- [x] https://github.com/fluxcd/helm-controller/pull/396
- [x] https://github.com/fluxcd/notification-controller/pull/306
- [x] https://github.com/fluxcd/image-reflector-controller/pull/221

### New features and improvements 

- [x] https://github.com/fluxcd/flux2/pull/2167
- [x] https://github.com/fluxcd/notification-controller/pull/317
- [x] https://github.com/fluxcd/image-reflector-controller/pull/194
- [x] https://github.com/fluxcd/image-automation-controller/pull/299
- [x] https://github.com/fluxcd/kustomize-controller/pull/538
- [x] https://github.com/fluxcd/kustomize-controller/pull/527

### Documentation

- [ ] https://github.com/fluxcd/website/pull/727
- [ ] https://github.com/fluxcd/website/pull/702
- [ ] https://github.com/fluxcd/website/pull/713

**Comment by texasbobs** [comment]
Is there an ETA for this?  We are kind of stuck right now in our deployment process with Flux2 in test and Flux in prod.  We have been experiencing issues where a commit "works" when deployed in test with Flux2 yet fails in prod with Flux.  We're hoping to test the "revoke kubectl managed fields" change as soon as we can get this release.

**Comment by texasbobs** [comment]
Can you provide the command for `flux install`?  I'm not able to get it to work using the `--version` parm.

**Comment by texasbobs** [comment]
I found the patch command.  Testing now.

**Comment by texasbobs** [comment]
That works.  Thank you! We're going to continue to run this image in test until v0.26 comes out.  Then we can look at continuing our rollout to prod.

**Comment by stefanprodan** [comment]
All controllers have been released https://github.com/fluxcd/flux2/pull/2345
