### ISSUE TITLE
bootstrap fails on github with "failed to clone repository: unexpected client error"

### ISSUE THREAD

**Issue by beckjim** [fluxcd/flux2#2327]
### Describe the bug

I'm trying to get started with fluxcd, following the 'Get Started Guide' https://fluxcd.io/docs/get-started/

flux bootstrap fails when cloning 
✗ failed to clone repository: unexpected client error: unexpected requesting "https://github.com/XXX/fleet-infra.git/info/refs?service=git-upload-pack" status code: 400

Where XXX is my email address.

jim@nuc:~/kubernetes/flux$ flux -v
flux version 0.25.3

### Steps to reproduce

Just bootstrapping gives an error.

flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=fleet-infra \
  --branch=main \
  --path=./clusters/my-cluster \
  --personal

gives 
► connecting to github.com
✔ repository "https://github.com/XXX/fleet-infra" created
► cloning branch "main" from Git repository "https://github.com/XXX/fleet-infra.git"
✗ failed to clone repository: unexpected client error: unexpected requesting "https://github.com/XXX/fleet-infra.git/info/refs?service=git-upload-pack" status code: 400

### Expected behavior

Bootstrapping should be successful as decribed in https://fluxcd.io/docs/get-started/

### OS / Distro

Ubuntu 20.04

### Flux version

v0.25.3

### Flux check

 flux check --pre
► checking prerequisites
✔ Kubernetes 1.23.1 >=1.19.0-0
✔ prerequisites checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
GITHUB_USER should be your GitHub username, not the email address.

**Comment by beckjim** [comment]
> GITHUB_USER should be your GitHub username, not the email address.

Ooops, yes, sure. Perfect, Thanks!!!! 
Got blind ...
