### ISSUE TITLE
flux bootstrap github - Scopes

### ISSUE THREAD

**Issue by don4of4** [fluxcd/flux2#2329]
The documentation doesn't mention which scopes are needed for the Github PAT.  Is it possible to add this information?

**Comment by dholbach** [comment]
Should be fixed in `./cmd/flux/bootstrap_github.go`.

**Comment by drozzy** [comment]
The getting started guide does not mention anything about this.
https://fluxcd.io/docs/get-started
<img width="796" alt="Screen Shot 2022-03-26 at 01 14 50" src="https://user-images.githubusercontent.com/140710/160225764-87193504-9b9b-43bb-ba8d-bda9ab46fdb6.png">

**Comment by kingdonb** [comment]
@drozzy Can you please elaborate? What's missing / what did you expect to see and where?

**Comment by drozzy** [comment]
You are right, I missed that. Thanks for pointing it out.
I think perhaps "Objectives" should go first, and "Before you begin" should go second. Because the eye naturally scans the page and skips past objectives. So anything above that seems optional.

**Comment by kingdonb** [comment]
Thanks for the feedback. You're not the first person that missed this information, so it's helpful to hear! We can consider reordering the structure of the docs, that's a pretty reasonable suggestion and makes sense to me.

**Comment by drozzy** [comment]
Perhaps it would make sense to just remove "before you begin" entirely and move the mention about repo tokens into the "Export your credentials" section. Then move kubernetes cluster into its own section. E.g.:

1. Objectives
2. Export your credentials (with mention that access token should have "repo" premissions")
3. Install Kubernetes
4. Install the Flux CLI
5. Check your Kubernetes cluster
6. Install Flux onto your cluster
7. Etc.

**Comment by pkit** [comment]
Ehm, flux tries to create a deploy key which means that the token user must have **Admin** permissions.

**Comment by pkit** [comment]
@stefanprodan Is there a proper way to bootstrap with pre-existing deploy key? Without the dance of manual secret creation?

**Comment by stefanprodan** [comment]
@pkit Yes there is a `--private-key-file=<path/to/private.key>` option, see https://fluxcd.io/flux/installation/#generic-git-server

**Comment by pkit** [comment]
@stefanprodan It's not clear that it applies to github too...
Because when I tried `--token-auth=true` it was still creating a deploy key...

**Comment by stefanprodan** [comment]
It does apply to the generic bootstrap `flux bootstrap git`, git not github, not sure how to make the docs clear, the GitHub/GitLab sections are way below

**Comment by tobywan** [comment]
For fine-grained (beta) tokens, I think the minimum I need for bootstrap to github is

```
 Read access to metadata
 Read and Write access to administration and code
```
Specifically

### Administration 
_Repository creation, deletion, settings, teams, and collaborators._
`Read and Write`

### Contents 
_Repository contents, commits, branches, downloads, releases, and merges._
`Read and Write`

### Metadata  mandatory
Search repositories, list collaborators, and access repository metadata.
`Read-only`

**Comment by paulcarlton-ww** [comment]
Why do I need write access to the repo? I want to use a read only token

**Comment by dreamsavage** [comment]
There needs to be more detail on GitHub token scopes in the getting started page with a visual and/or use case example for example.  Three words in passing are not enough and assuming devs have used personal tokens with GitHub is a bad assumption.   This is the difference between a quick start and one that takes an extra half hour the the extra research involved.  Not to mention the potential mistakes for token creation if the incorrect settings are used.  Do your users a favor and stop the lazy thinking.

**Comment by makkes** [comment]
@dreamsavage we'd be really happy to take PRs improving the docs.
