### ISSUE TITLE
Allow disabling cross-namespace references

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#2337]
Given that [RFC-0002](https://github.com/fluxcd/flux2/pull/2092) and [RFC-0003](https://github.com/fluxcd/flux2/pull/2093) need more debating, I propose we add a boolean flag `--no-cross-namespace-refs` to all controllers so that users can disable cross-namespace references if they wish to do so.

This applies to:
- `GitRepository`, `Bucket` and `HelmRepository` references in `Kustomizations` and `HelmReleases`
- `ImageRepository` references in `ImagePolicies`
- `GitRepository` references in `ImageUpdateAutomations`
- `Kustomization`, `HelmRelease`, image and source references in `Alerts`

Flag spec:
```go
flag.BoolVar(&noCrossNamespaceRefs, "no-cross-namespace-refs", false,
	"When set to true, references between custom resources are allowed " +
	"only if the reference and the referee are in the same namespace.")
```

Components:
- [x] fluxcd/pkg/runtime
- [x] kustomize-controller
- [x] helm-controller
- [x] notification-controller
- [x] image-reflector-controller
- [x] image-automation-controller

**Comment by squaremo** [comment]
:+1: I think this is sensible, and has a use even if/when ACLs are also implemented in the same controllers.

**Comment by makkes** [comment]
I like the idea!

**Comment by stefanprodan** [comment]
Thanks @SomtochiAma and @squaremo for helping out implementing this on such short notice.
