### ISSUE TITLE
Bootstrap fails the first time

### ISSUE THREAD

**Issue by mibollma** [fluxcd/flux2#2351]
### Describe the bug

When running bootstrap on a github repository it seems to always fail the first time with:
```
installing components in "flux-system" namespace
Kustomization/flux-system/flux-system dry-run failed, error: no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
```
After running the exact same bootstrap command again it works as expected.
The bootstrap command is `flux bootstrap github --owner=*** --repository=*** --path=some/repo/path --personal`

Any ideas what this might be about?

### Steps to reproduce

N/A

### Expected behavior

N/A

### OS / Distro

Windows 10

### Flux version

0.25.3

### Flux check

N/A

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Can you please post the output of `flux check`

**Comment by mibollma** [comment]
```
$ flux check
checking prerequisites
Kubernetes 1.21.7 >=1.19.0-0
checking controllers
helm-controller: deployment ready
ghcr.io/fluxcd/helm-controller:v0.15.0
kustomize-controller: deployment ready
ghcr.io/fluxcd/kustomize-controller:v0.19.1
notification-controller: deployment ready
ghcr.io/fluxcd/notification-controller:v0.20.1
source-controller: deployment ready
ghcr.io/fluxcd/source-controller:v0.20.1
all checks passed
```

**Comment by falkrist** [comment]
Got the same, can't understand what is the issue.
Bootstrap with Gitlab CI:
````
    - aws eks --region eu-central-1 update-kubeconfig --name eks-cluster-name
    - curl -s "https://fluxcd.io/install.sh" | bash
    - flux check --pre
    - flux bootstrap gitlab
      --hostname=***
      --owner=***
      --repository=eks-fluxcd
      --path=./some/path
      --branch=main
      --token-auth
      --personal

**Comment by gvillafanetapia** [comment]
Same here! Any workaround (other than running twice 🥴)? Trying to automatize in a Gitlab CI/CD Pipeline.

1st run: 

```
$ flux bootstrap gitlab  --context=eks-cluster \ # collapsed multi-line command
► connecting to https://gitlab.com
► cloning branch "*****" from Git repository "https://gitlab.com/*****"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✗ Kustomization/flux-system/flux-system dry-run failed, error: no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
```

2nd run:
```
$ flux bootstrap gitlab  --context=eks-cluster \ # collapsed multi-line command
► connecting to https://gitlab.com
► cloning branch "*****" from Git repository "https://gitlab.com/*****"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✔ Kustomization reconciled successfully
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
```

**Comment by gjmveloso** [comment]
Same here on macOS 12.2

```
$ flux check
► checking prerequisites
✗ flux 0.25.3 <0.26.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.5-eks-bc4871b >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.15.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.19.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.20.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.20.1
✔ all checks passed
```

**Comment by stefanprodan** [comment]
I'm having a hard time replicating this, we do run `flux bootstrap` in CI for every commit to this repo and not once this happened.

**Comment by gvillafanetapia** [comment]
This is my script:

```
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - curl -s https://fluxcd.io/install.sh | bash
    - flux -v
    - |
      aws eks --region $(cat ${TF_ROOT}/tf_output.json | jq -r .cluster_region.value) update-kubeconfig \
        --name $(cat ${TF_ROOT}/tf_output.json | jq -r .cluster_name.value) \
        --alias eks-cluster
    - |
      flux bootstrap gitlab  --context=eks-cluster \
        --owner=$(cat ${TF_ROOT}/tf_output.json | jq -r .flux_git_owner.value) \
        --repository=$(cat ${TF_ROOT}/tf_output.json | jq -r .flux_git_repo.value) \
        --branch=$(cat ${TF_ROOT}/tf_output.json | jq -r .flux_git_branch.value) \
        --path=clusters/$(cat ${TF_ROOT}/tf_output.json | jq -r .cluster_env.value) \
        --token-auth
```

**Comment by mibollma** [comment]
For me it happens every time.
I create new clusters on Azure using terraform and run `flux bootstrap github --owner=*** --repository=*** --path=some/repo/path --personal`  against them.
I could provide the terraform description if it helps, just need to clean it up a bit.

**Comment by stefanprodan** [comment]
@mibollma we have e2e tests for Azure AKS that are run daily, there are no failures so far.

@kingdonb @SomtochiAma can you please help me out with testing bootstrap on AKS?

**Comment by knweiss** [comment]
FWIW this also happens for me on a local Minikube-based k8s on macOS (same error message).

Also, the 2nd bootstrap run always creates a new source secret public key on GitHub and succeeds.
```
$ flux check
► checking prerequisites
✔ Kubernetes 1.23.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.1
✔ all checks passed

$ flux version
flux: v0.26.1
helm-controller: v0.16.0
kustomize-controller: v0.20.0
notification-controller: v0.21.0
source-controller: v0.21.1
```

My bootstrap looks like this:
```
flux bootstrap github   --owner=$GITHUB_USER   --repository=fleet-infra   --branch=main   --path=./clusters/my-cluster   --personal
```

**Comment by superherointj** [comment]
```
 "✗ Kustomization/flux-system/flux-system dry-run failed, error: no matches for kind \"Kustomization\" in version \"kustomize.toolkit.fluxcd.io/v1beta2\""
```

I'm having same issue. And I've tried `flux version 0.26.2` and problem persisted. Should it be gone?

**Comment by gvillafanetapia** [comment]
fixed for me with version 0.26.2 😕

**Comment by mibollma** [comment]
For me it's still there with 0.26.2 just as @youwalther65 mentioned

**Comment by stefanprodan** [comment]
@mibollma I see that in your bootstrap output `component manifests are up to date`, the components YAMLs are already in Git, do you run bootstrap on an existing repo that was already bootstrapped?

**Comment by mibollma** [comment]
@stefanprodan I do. The AKS clusters for the different stages (dev, qa, prod) are created on-demand and don't run indefinitely. Every time after a cluster is created it needs to be bootstrapped again.
When I updated to 0.26.2 it also updated the component YAMLs, otherwise it prints the message you mentioned above.

**Comment by stefanprodan** [comment]
OK this is a use-case that bootstrap currently doesn't support, we assume the sync manifests are not in Git if the cluster is new. If the sync manifests are in Git, bootstrap tries to do an upgrade, but there is nothing to upgrade as the cluster doesn't even have the CRDs registered...

**Comment by stefanprodan** [comment]
@mibollma I tried this just now with two clusters, what's really strange is that for you, on the 2nd cluster it doesn't generate a public key, so either you modified the output you posted here or something else is done on that cluster that you haven't shared here. Can you please join Slack and ping me at `@stefanprodan`.

**Comment by mibollma** [comment]
@stefanprodan I'm not creating anything in parallel and I don't run two clusters using the same configuration in parallel... it's pretty much still in development so I usually setup a dev cluster, work on it a few hours and destroy it again.
The error shows up pretty consistently every time and it always works after running bootstrap a second time.
I also receive an email about a new key being added on Github every time, which seems to get overwritten every time.

**Comment by youwalther65** [comment]
@stefanprodan: I used the already existing GitHub repo with templates created by Flux 0.26.2. I am new to Flux and use flux bootstrap/uninstall a lot to get used to it. I used Terraform as well to initially create the repo. The error was encountered when I re-installed Flux using CLI with already existing GitHub repo on an already existing EKS cluster where I previously did "flux uninstall".

**Comment by poblish** [comment]
We currently bootstrap two clusters in parallel each morning and have done for several months, often with more clusters than that, something that has always worked well. Since 0.26.x both fail consistently in exactly the same way. Re-running bootstrap for each always works.

Not sure if that's helpful, but it does look like a very clear change in behaviour since 0.25.x

**Comment by stefanprodan** [comment]
Please try out Flux 0.26.3 and let me know here if it solves the issue or not. Thanks!

**Comment by youwalther65** [comment]
@stefanprodan Am I right with the assumption that this 0.26.2 change is reflected in Terraform provider 0.10.2 release 2 hours ago? If yes - very cool, thx a lot !!!

**Comment by kingdonb** [comment]
@youwalther65 You can see the difference between terraform provider v0.10.2 and v0.10.1 here:

https://github.com/fluxcd/terraform-provider-flux/compare/v0.10.1...v0.10.2

(The change is in Flux 0.26.3, which was the version that was utilized in flux-terraform-provider v0.10.2 👍 )

**Comment by mibollma** [comment]
For me it seems to work now with 0.26.3.
@stefanprodan Thank you very much for your support 👍.

**Comment by poblish** [comment]
0.26.3 worked perfectly for us this morning. Thanks again @stefanprodan !

**Comment by stefanprodan** [comment]
Great news! This was a hard bug to reproduce, thanks Weaveworks for providing me with a 64GB RAM MacBook :)) I had to run dozen Kind clusters in parallel to catch this.
