### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux2#2357]
### Describe the bug

https://fluxcd.io/docs/components/kustomize/kustomization/#generate-kustomizationyaml

mentions `spec.path` but there is no such field in the GitRepository object.

### Steps to reproduce

-

### Expected behavior

docs to match spec

### OS / Distro

all

### Flux version

all

### Flux check

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The spec.path refers to the Kustomization object, that’s where the kustomization.yaml is being generated.

**Comment by derrickburns** [comment]
Understood (now), however the context is the GitRepository object. So perhaps add a couple of words....
