### ISSUE TITLE
"flux diff" should return exit code != 0 on drift

### ISSUE THREAD

**Issue by muffl0n** [fluxcd/flux2#2365]
### Describe the bug

When using diff, a drift is reported but no exit code !=0 is returned.
```
-> % flux diff kustomization flux-system --path .
► HelmRelease/monitoring/kube-prometheus-stack drifted

metadata.generation
  ± value change
    - 4
    + 5

spec.values.grafana.enabled
  ± value change
    - false
    + true
```
```
-> % echo $?                                     
0
```

Having an exit code that is != 0 would be nice to have for CI/CD.

### Steps to reproduce

1. install kustomization on cluster
2. change kustomization local
3. run diff that reports a drift

### Expected behavior

`flux diff ...` should return an exit code != 0

### OS / Distro

macOS 11.6

### Flux version

v0.26.0

### Flux check

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
What exit code would you have? A non zero exit code signals that an error happened...

**Comment by muffl0n** [comment]
Maybe one could add a new parameter `--detailed-exitcode`, like helm-diff does it: https://github.com/databus23/helm-diff
```
--detailed-exitcode            return a non-zero exit code when there are changes
```

**Comment by stefanprodan** [comment]
We could do the same as `kubectl diff`:
>  Exit status: 0 No differences were found. 1 Differences were found. >1 Kubectl or diff failed with an error.

**Comment by souleb** [comment]
something like

```go
return Error{
  error: errors.New("identified at least one change, exiting with non-zero exit code"),
  Code:  1,
  }
```

?
