### ISSUE TITLE
Missing feature: bootstrap from a public https gitrepo URL

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux2#2371]
### Describe the bug

https://github.com/fluxcd/flux2/blob/edf15894f821055d9516362f77eb9e6aed71313f/cmd/flux/bootstrap_github.go#L61-L62

In `bootstrap_github.go` the first thing that is done in the file is checking that you have properly exported a GITHUB_TOKEN. I have thought about the reasons why it might not be supportable to allow folks to bootstrap from a public https URL too easily, since it seems like there might be some potential for abuse, but I'm not sure anyone made this decision consciously.

Should there be a way for Flux users to bootstrap using a public https URL? You can create such a configuration manually and omit `secretRef` with `flux create source git`, it's not very difficult to do this, but I wonder if this isn't an intentionally omitted feature?

### Steps to reproduce

The issue report is in the description above.

### Expected behavior

It seems like `flux bootstrap github` is missing a way to generate bootstrapped artifacts that use `https` for public URLs.

The `--token-auth` option requires a GITHUB_TOKEN but there is no reason why a public URL should require a deploy key.

### OS / Distro

N/A

### Flux version

v0.26.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
This may be covered with the generic `git` bootstrap, since at this point you wouldn't be using any GitHub API features:

```
Usage:
  flux bootstrap git [flags]

Examples:
  # Run bootstrap for a Git repository and authenticate with your SSH agent
  flux bootstrap git --url=ssh://git@example.com/repository.git

  # Run bootstrap for a Git repository and authenticate using a password
  flux bootstrap git --url=https://example.com/repository.git --password=<password>
```

...except that both examples here still require authentication, and if you fail to provide authentication details they will tell you so:

```
$ flux bootstrap git --url=https://github.com/kingdonb/fleet-testing.git --path=./clusters/example-cluster
► cloning branch "main" from Git repository "https://github.com/kingdonb/fleet-testing.git"
✗ failed to clone repository: authentication required
```

This is a public repo and the URL that I've provided doesn't require any authentication details. In my case the repo already exists, (and I wouldn't expect this method to work at all if it did not.) The result is the same if I pass `--token-auth`.

```
$ git clone https://github.com/kingdonb/fleet-testing.git
Cloning into 'fleet-testing'...
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 220 (delta 61), reused 189 (delta 30), pack-reused 0
Receiving objects: 100% (220/220), 56.11 KiB | 897.00 KiB/s, done.
Resolving deltas: 100% (61/61), done.
```

I haven't read this part of the code in full detail, but I see two branches here:

https://github.com/fluxcd/flux2/blob/edf15894f821055d9516362f77eb9e6aed71313f/cmd/flux/bootstrap_git.go#L156

one for `--token-auth` and the other without, which prepares an SSH key to use with the deployment. Neither of those seem to be what's indicated for this use case.

**Comment by stefanprodan** [comment]
Bootstrap implies pushing the Flux to the repo, so I don't see this as a missing feature. If you don't have write access to a repo, then bootstrap on a repo that you own, then add the readonly repo as a source inside your cluster. Another option, is to deploy Flux with `flux install`.
