### ISSUE TITLE
Flux kustomization is failing 

### ISSUE THREAD

**Issue by ANKAMBLE** [fluxcd/flux2#2378]
We are running flux2 v0.17.2 on Openshift V4.6,
Flux kustomization is failing with below error 
 message: >
        apply failed: Warning: resource
        customresourcedefinitions/kustomizations.kustomize.toolkit.fluxcd.io is
        missing the kubectl.kubernetes.io/last-applied-configuration annotation
        which is required by kubectl apply. kubectl apply should only be used on
        resources created declaratively by either kubectl create --save-config
        or kubectl apply. The missing annotation will be patched automatically.

        The CustomResourceDefinition
        "kustomizations.kustomize.toolkit.fluxcd.io" is invalid:
        status.storedVersions[1]: Invalid value: "v1beta2": must appear in
        spec.versions

Pleas elet me know if there is any fix for this issue

**Comment by kingdonb** [comment]
The `v1beta2` kustomization was introduced in Flux2 v0.18.0 – it should not be present on clusters which are running earlier versions. I suspect that someone tried upgrading this cluster and failed, for one reason or another, but the CRDs were applied, and now you might have a version mismatch.

I recommend you upgrade to Flux v0.26, as we cannot support older versions of Flux generally speaking, however I do not have enough information about your deployment and how you installed Flux to guide you directly with that just yet. Is there a technical reason why you have not upgraded and can we address it, so you can upgrade?

Are you using the Operator Hub entry for Flux, or have you installed Flux directly with `flux bootstrap`? (The Operator Hub does not have Flux 0.26 released yet, but Flux 0.25.3 is there.)

Flux has changed some things about how it does version accounting and reporting. Please be aware that you must use the same `flux` CLI version as the version of Flux that you bootstrapped your cluster with. If there is a mismatch, you can run into errors like this one.

**Comment by ANKAMBLE** [comment]
thankyou for your comments, yes you are right we tried to deploy 0.26 which caused issue. we are using Openshift 4.6 which does not support v 0.26 so had to revert  back upgrade

**Comment by ANKAMBLE** [comment]
the issue is resolved now

**Comment by stefanprodan** [comment]
For OpenShift  & Operator Hub flux 0.26 release is being prepared here https://github.com/weaveworks/flux2-openshift/commit/8c921f33b863308e4b7dcb4402fc8683cb00fc9c

**Comment by TOHUHM** [comment]
@ANKAMBLE 
I met the same issue as you, May I know how to revert the upgrade? as we use template to deploy kustomization resource, now our template is still using v1beta1, so I have to rollback, thanks a log!

**Comment by stefanprodan** [comment]
Flux 0.27.0 was published on [OperatorHub](https://operatorhub.io/operator/flux) with the right setting. If your using `flux bootstrap`, here is the updated configuration for OpenShift: https://fluxcd.io/docs/use-cases/openshift/#flux-installation-with-cli
