### ISSUE TITLE
For many Kustomizations, `flux resume ks --all` rarely finishes successfully

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux2#2379]
### Describe the bug

There is a usability issue between `flux suspend kustomizations --all` and `flux resume kustomizations --all` that is related to interdependency between Kustomizations.

You may run `flux suspend kustomizations --all` to avert Flux from reconciling during an incident or other times.

This works great, but the corollary to resume all kustomizations needs to be ran multiple times in order to succeed. It resumes one Kustomization serially at a time, in alphabetical order, and waits for timeout or an error before moving on to the next one. When you have many kustomizations, with inter-linked dependencies, and some kustomizations that apply others to the cluster, this basically doesn't work. I found myself resorting to `flux get kustomizations|awk '{print $1}'` type shenanigans, which did not go well because there can be multiline output in the status columns, and then I gave up to resume the kustomizations by hand in the right order instead. If there were hundreds, though, I would be in trouble.

In my experience, this rarely succeeds, as it can fail when (due to kustomizations not being correctly alphabetized in dependency order):

```
✗ dependency 'flux-system/monitoring-stack' is not ready
```

or when
```
✗ Operation cannot be fulfilled on kustomizations.kustomize.toolkit.fluxcd.io "traefik-api-crds": the object has been modified; please apply your changes to the latest version and try again
```

The operation can stall or appear to fail, and in the latter case it gives up. 

### Steps to reproduce

Because this operation takes a minute or two to enumerate all the Kustomizations on my cluster (I have about 25), by the time it gets to the end of the list, a reconciliation interval for short-set intervals like the one I have set for `infrastructure` has likely already passed. This means in my case, `infrastructure` has re-applied the `traefik-api-crds` Kustomization since the flux CLI started running, and so we get that error because it's no longer in the same state it was when we started our resume run.

This would benefit from a `--no-wait` option, so one can relatively instantly resume all Kustomizations at once without waiting for success or failure of the reconcile. Maybe an `--all-namespaces` option as well.

For example:

```
$ flux suspend hr --all -A
✗ unknown shorthand flag: 'A' in -A
```

I have helmreleases in many namespaces, there's no way to suspend and resume them all at one time. I have to iterate through all the namespaces.

Have many Kustomizations that are interrelated, like in https://github.com/kingdonb/bootstrap-repo (staging branch / moo-cluster)

Let some Kustomizations apply manifests of other Kustomizations, all should be in the `flux-system` namespace to be easily targeted at once by `resume --all` or `suspend --all`

Use `flux resume kustomizations --all` – if you have sufficient complexity and depth of dependency / enough Kustomizations in your example repo with shorter intervals on some, this will never succeed no matter how many times you try.

### Expected behavior

I would like a way to concurrently unsuspend all suspended Flux kustomizations without waiting for them to process serially. If it can be done in a synchronous way (where all Kustomizations are updated in the same apply) so that dependencies ordering are still guaranteed to be honored that would be ideal.

There should be a quick recovery path after `flux suspend kustomizations --all` when you have many Kustomizations.

### OS / Distro

N/A

### Flux version

v0.26.0

### Flux check

```
$ flux check
► checking prerequisites
✔ Kubernetes 1.23.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► fluxcd/source-controller:rc-61941672
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I'm for adding a `--wait` flag that defaults to `false`, given the async nature of Flux and dependsOn behaviour, waiting for all Kustomizations to resume is unrealistic.

**Comment by cdenneen** [comment]
@stefanprodan i know this is old issue but the request I think was for `-A` all namespaces as well in the example which `unknown shorthand flag: 'A' in -A` still isn't option. It's great you can resume all within a namespace but if they are spread out and you need to suspend globally and resume globally this would be nice.
