### ISSUE TITLE
flux install --export on v0.26.1 CLI generates the exact same output as on the v0.26.0 CLI

### ISSUE THREAD

**Issue by danports** [fluxcd/flux2#2393]
### Describe the bug

The only difference between the `flux install --export` output on the v0.26.1 CLI vs. the v0.26.0 CLI is the value of the `app.kubernetes.io/version` labels.

### Steps to reproduce

Run `flux install --export` on the v0.26.1 CLI and compare to the output from the v0.26.0 CLI.

### Expected behavior

I expected that there would be differences between the image tags, etc.

### OS / Distro

N/A

### Flux version

v0.26.1

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
v0.26.1 comes with CLI only fixes, please see the changelog https://github.com/fluxcd/flux2/releases/tag/v0.26.1

**Comment by danports** [comment]
Got it, thanks for clarifying.
