### ISSUE TITLE
flux diff could provide an inline diff for large configmap entries

### ISSUE THREAD

**Issue by rombert** [fluxcd/flux2#2400]
### Describe the bug

First of all, thanks for the rapid fixes around the `flux diff` and `flux build` commands.

I ran into a case in which I think the `flux diff` command could be even more useful. It is sometimes the case that configmap entries hold entire configuration files in formats like YAML or JSON. A one-line change in a large file is now shown by `flux diff` as a complete change of the whole key, which makes it hard to identify the exact line that has changed.

### Steps to reproduce

1. Include a configmap with a single large key in a kustomization
2. Deploy the kustomization with flux
3. Make a small change to the configmap locally, without pushinf
4. Run `flux diff`

### Expected behavior

The change should displayed inline, perhaps in the unified diff format.

### OS / Distro

openSUSE Tumbleweed

### Flux version

v0.26.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.5 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
We've just come across this at the Flux Bug Scrub and we're in agreement this would be a useful feature!

**Comment by souleb** [comment]
@rombert please test this and reopen if needed.

**Comment by rombert** [comment]
@souleb - is there a snapshot build I could use for testing?

**Comment by stefanprodan** [comment]
@rombert you can clone this repo then do `make build` then run `./bin/flux diff`.

**Comment by souleb** [comment]
Awesome! Thank you. I would like to add an `unified diff` format too, but it requires time to implement it. Maybe some time in the future.
