### ISSUE TITLE
kustomize controller dry run failure - metadata.managedFields must be nil

### ISSUE THREAD

**Issue by stevewallone** [fluxcd/flux2#2404]
### Describe the bug

When attempting to deploy a ConfigMap, the below error is logged and the deployment fails.

```
{"level":"error","ts":"2022-02-07T23:42:13.590Z","logger":"controller.kustomization","msg":"Reconciliation failed after 121.391606ms, next try in 1m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"infra-test-flux","namespace":"flux-system","revision":"feature/fluxv2/e8d1831bb89a30d83f6e80b54efa446b8c7d6866","error":"ConfigMap/default/test-cm dry-run failed, reason: BadRequest, error: metadata.managedFields must be nil\n"}

```

### Steps to reproduce

1. Add the ConfigMap manifest to a fluxv2 monitored repo.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  namespace: default
  labels:
    test-label: test
  managedFields:
  - manager: kubectl
    operation: Apply
    apiVersion: v1
    time: "2010-10-10T0:00:00Z"
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:test-label: {}
      f:data:
        f:key: {}
data:
  key: some value
  ```

### Expected behavior

The config map is created.

### OS / Distro

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1200", GitCommit:"90a16981ade07f163a0233adb631b42ac1fc53ff", GitTreeState:"clean", BuildDate:"2021-10-04T09:25:23Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

### Flux version

v0.24.1

### Flux check

```
% flux check
► checking prerequisites
✗ flux 0.24.1 <0.26.2 (new version is available, please upgrade)
✔ Kubernetes 1.21.5-gke.1200 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.18.0
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
The error is from Kubernetes server side apply. Trying to apply the manifest with
```
kubectl apply -f cm.yaml --server-side
```
will give you the same error.
Please remove the managed field in the metadata.
Your yaml should look like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  namespace: default
  labels:
    test-label: test
data:
  key: some value
```

**Comment by stefanprodan** [comment]
`managedFields` can’t be specified in Git, remove them please.

**Comment by stevewallone** [comment]
@SomtochiAma @stefanprodan thanks for the information! I was seeing this while converting from flux v1 to v2. I'm curious why it worked in v1. Any thoughts?
