### ISSUE TITLE
Flux Bootstrap for a private bitbucket repository does not pick up the Project Key correctly

### ISSUE THREAD

**Issue by jahzielHA** [fluxcd/flux2#2411]
### Describe the bug

When the bitbucket project name matches for more than one name (--owner flag) flux2 picks up the first project name match.

For example, given the two bitbucket projects:
* Name: Community ;  Key: CMT
* Name: Unity ; Key: UNITY
Trying to bootstrap the Unity project will fail since it picks up CMT first.

I think it can be related to the provider for stash used by flux2
See: https://github.com/fluxcd/go-git-providers/blob/5d558186b0/stash/projects.go#L176

Probably the owner flag should check by project key first and then try to find by name.
Thanks

### Steps to reproduce

Given the following two bitbucket projects:
* Name: Community ;  Key: CMT
* Name: Unity ; Key: UNITY

```
$ flux bootstrap bitbucket-server --owner="unity" ...
► connecting to bitbucket.*****.com
failed to create repository: create respository failed: request POST https://bitbucket.****.com/rest/api/1.0/projects/CMT/repos returned status code: 401 , unexpected status code
```
It queries by project name and the first match is the CMT project and not Unity.

### Expected behavior

Probably use the project key first and then match by name if not found

### OS / Distro

N/A

### Flux version

v0.26.2

### Flux check

N/A

### Git provider

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
thanks for reporting. We assumed unique name. We will match on name and key.

**Comment by jahzielHA** [comment]
@souleb thanks for replying back.
Oh, That was just an example, a project name "Community" with a project Key "CCT". In bitbucket project names and project keys can be different.
