### ISSUE TITLE
helm-controller error: Forbidden

### ISSUE THREAD

**Issue by cheruvu1** [fluxcd/flux2#2419]
### Describe the bug

During the reconciliation I am getting the following error, Flux is not able to connect to my GitHub giving timeout error. When I check the logs, I see the following error.  Please advice ?. 
https://xxxxx:11111/containerLogs/flux-system/helm-controller-58d73927822dbcf-q5mjd/manager: Forbidden

Thank you

### Steps to reproduce

1. Install Flux flux version 0.26.2
2. Deploy a hello world app which need to connect to GitHub to fetch helm charts 
3. run the command: flux logs --kind=Kustomization -n mynamesapce

### Expected behavior

Flux should be able to connect to GitHub without any timeout issue. 

### OS / Distro

Linux

### Flux version

0.26.2

### Flux check

► checking prerequisites
✗ flux 0.26.2 <0.26.3 (new version is available, please upgrade)
✔ Kubernetes 1.20.9 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► xxxxxx/fluxcd/helm-controller:v0.9.0
✔ kustomize-controller: deployment ready
► xxxx/fluxcd/kustomize-controller:v0.9.3
✔ notification-controller: deployment ready
► xxxxx/fluxcd/notification-controller:v0.12.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cheruvu1** [comment]
Exactly Error is below:
gitrepository.source.toolkit.fluxcd.io/xxxx-repo   https://github.com/xxxx/xxxx   False   unable to clone 'https://github.com/xxxx/xxxx', error: failed to connect to github.com: Connection timed out

**Comment by kingdonb** [comment]
Are you using k3s or have you tried disabling network policies when you bootstrap?

I am not certain but it looks like an issue related to networking. If you have issues reaching GitHub but only from within the flux-system namespace, then it is probably a problem with the NetworkPolicy resources there.

You can bootstrap Flux with `--network-policy=false` in order to remove them at install time. (If you haven't enabled pruning you may need to delete the NetworkPolicy resources in the Flux namespace after that, to see the effect clear.)

We've seen different reports depending on network. Please let us know if you're still struggling with this.

**Comment by kingdonb** [comment]
Actually not sure about the meaning of this error:

```
https://xxxxx:11111/containerLogs/flux-system/helm-controller-58d73927822dbcf-q5mjd/manager: Forbidden
```

Can you elaborate? Where did you see this error

**Comment by cheruvu1** [comment]
Thank you for your time.  Can you please show steps how can I "You can bootstrap Flux with --network-policy=false” ?.  If you have any article as a reference, do share with me please, I will read and make necessary changes.

Thank you

**Comment by kingdonb** [comment]
@cheruvu1

>       `--network-policy                         deny ingress access to the toolkit controllers from other namespaces using network policies (default true)`
https://fluxcd.io/docs/cmd/flux_bootstrap/

It is the same as a regular bootstrap, but with `--network-policy=false`

Be aware that running bootstrap normally creates three objects of resource kind `NetworkPolicy` in the `flux-system` namespace. When bootstrap is run with `--network-policy=false` they are not created, but also be aware that pruning might not be enabled, so you might have to go into the cluster and delete those resources by hand after the change.

If you just go in and delete them, it may tell you whether this change will help at all or not, but by default every `10m` I think Flux will put them back, unless the bootstrap configuration is changed.
