### ISSUE TITLE
Assign a dedicated cluster role per controller

### ISSUE THREAD

**Issue by paulcarlton-ww** [fluxcd/flux2#243]
Running the installer generates yaml that installs the source-controller with cluster admin role. As I understand it, the recommended setup is for all *.source.toolkit.fluxcd.io custom resources to be in the gitops-system namespace so the source controller should not need access to anything outside this namespace? Also, for security conscious customers it might be worth defining different roles for each toolkit component, i.e. source-controller only needs access to the  *.source.toolkit.fluxcd.io resources not *.toolkit.fluxcd.io?

**Comment by paulcarlton-ww** [comment]
As I understand it, if the source-controller is set to monitor gitops-system namespaced custom resources only (as per the default) the source-controller with use a role not a clusterrole?

**Comment by stefanprodan** [comment]
No longer true, see https://github.com/fluxcd/toolkit/pull/227

**Comment by william-salt-cko** [comment]
Has anyone got any more hints at potential permissions the components need? I was going to enable an audit policy to monitor the components and start making roles and rules and create service accounts, role bindings and roles with rules in a PR.

**Comment by stefanprodan** [comment]
We generate the required RBAC from code, see the config/rbac in each controller repo, e.g. https://github.com/fluxcd/source-controller/tree/main/config/rbac

**Comment by stefanprodan** [comment]
@william-salt-cko just be clear, we don’t want to duplicate any rbac rules in this repo, when we switch to dedicated service accounts, the rbac must come as a kustomize remote base from each controller repo based on the kubebuilder generated rules. The kubebuilder rbac doesn’t suffice right now, we need to add readonly access to secrets as most Flux objects have a secretRef field.
