### ISSUE TITLE
Invalid value: "null": spec.podDisruptionBudget in body must be of type object: "null" 

### ISSUE THREAD

**Issue by dwilliams782** [fluxcd/flux2#2435]
### Describe the bug

We have a manifest that is failing after a Flux v2 upgrade:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  ...
spec:
  version: 7.7.0
  podDisruptionBudget: {}
  nodeSets:
    - name: default
      count: 2
  ...
```

The error message is:

```
Elasticsearch/web/elasticsearch dry-run failed, reason: Invalid, error: [Elasticsearch.elasticsearch.k8s.elastic.co](http://elasticsearch.elasticsearch.k8s.elastic.co/) "elasticsearch" is invalid: spec.podDisruptionBudget: Invalid value: "null": spec.podDisruptionBudget in body must be of type object: "null"
```

The value for `podDisruptionBudget` is clearly an empty object, rather than null. I'm not sure why this is happening, we've seen this in a few places and have to remove the empty objects from the manifests to remove the error.

>Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9-gke.300", GitCommit:"d94fd1808d7f2b616f611c58f9975f41d48a4662", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:20Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

### Steps to reproduce

Apply a manifest with an empty object.

### Expected behavior

Empty objects should be considered empty objects rather than null.

### OS / Distro

Alpine Linux 3.15.0

### Flux version

v0.20.2

### Flux check

n/a (we've fixed the issue prior to raising the bug)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gberche-orange** [comment]
@stefanprodan I'm observing the same problem with

```
Kubernetes version   v1.23.5+1f952b3
OpenShift version    4.10.8
image: ghcr.io/fluxcd/kustomize-controller:v0.26.2
```

```
Dry run ControllerConfig/70-crossplane/crossplane-controller-config apply failed,
error: ControllerConfig.pkg.crossplane.io "crossplane-controller-config" is invalid: [
spec.podSecurityContext: Invalid value: "null": spec.podSecurityContext in body must be of type object: "null", spec.securityContext: Invalid value: "null": spec.securityContext in body must be of type object: "null"
```

While this seems indeed related to k8s server-side-apply bug similar to https://github.com/kubernetes/kubernetes/issues/104694 I'm unable to reproduce the SSA bug on my K8S cluster, while this reproduces with flux

controller-config.yaml :
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-controller-config
  namespace: 70-crossplane
spec:
  args:
    - --debug
  securityContext: {}
  podSecurityContext: {}
```

```bash
$ k apply --server-side --force-conflicts -f controller-config.yaml 
controllerconfig.pkg.crossplane.io/crossplane-controller-config serverside-applied

 k get ControllerConfig.pkg.crossplane.io/crossplane-controller-config --namespace 70-crossplane -o yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  creationTimestamp: "2022-07-01T13:39:03Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: 75-crossplane-providers-openstack-hws
    kustomize.toolkit.fluxcd.io/namespace: fluxcd
  name: crossplane-controller-config
  resourceVersion: "23018359"
  uid: cb035e50-f4ff-4d51-b1fb-2bb59e7b8720
spec:
  args:
  - --debug
  podSecurityContext: {}
  securityContext: {}

```

Any suggestion on how to debug or workaround the issue ?

**Comment by gberche-orange** [comment]
I was able to workaround the issue by authoring a small helm release to install the ControllerConfig with HelmController instead of KustomizeController

In this case, the following resource is properly applied by the HelmController without error
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-controller-config
spec:
  args:
    - --debug
  podSecurityContext: {}
  securityContext: {}
```
