### ISSUE TITLE
GitRepository source with "." assumes an incorrect path. 

### ISSUE THREAD

**Issue by alphabet5** [fluxcd/flux2#2438]
### Describe the bug

Flux takes the last item in a source with '.' and assumes the GitRepository path is the item after the last dot.

### Steps to reproduce

1. Create source with "." in the name.
```bash
flux create source git first.second.third --url=ssh://git@github.com/alphabet5/test.git --branch=main --private-key-file=./test-deploy-key.ssh
```

2. Create kustomization from the source.
```bash
flux create kustomization test --source="first.second.third" --path="./clusters/production" --prune=true --interval=1m
✚ generating Kustomization
► applying Kustomization
✔ Kustomization created
◎ waiting for Kustomization reconciliation
✗ Source 'GitRepository/third/first.second' not found
```

### Expected behavior

Source repo to be found.

### OS / Distro

N/A

### Flux version

v0.26.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.3-2+d441060727c463 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
That's kind of working as expected. From `flux create ks -h`:
```
      --source kustomizationSource               source that contains the Kubernetes manifests in the format '[<kind>/]<name>.<namespace>', where kind must be one of: (GitRepository, Bucket), if kind is not specified it defaults to GitRepository
```
There's two workarounds I can come up with off the top of my head:

1. Patch the resources after creation:
   ```
   k -n flux-system patch ks test --type merge -p '{"spec":{"sourceRef":{"kind":"GitRepository","name":"first.second.third","namespace":"flux-system"}}}'
   ```
2. Replace the dots in the GitRepository name by another separator.

**Comment by stefanprodan** [comment]
I think we should ban dot-separated object names.

**Comment by hiddeco** [comment]
> I think we should ban dot-separated object names.

In combination with upstream standards, there are 3 options to pick from if we would do this: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by stefanprodan** [comment]
@hiddeco I would go with "RFC 1123 Label Names" as we use the Flux Kustomization and HelmRelease name to label objects in cluster.

**Comment by stefanprodan** [comment]
@alphabet5 using dots in the Flux custom resource name will make Flux stop working, we use the custom resource name to label the objects reconciled from Git. As suggested by @makkes you should replace `.` with `-`.

**Comment by stefanprodan** [comment]
@SomtochiAma could you please write a validation for "RFC 1123 Label Names" and apply it to all `flux create` commands so that users don't end up creating invalid resources?
