### ISSUE TITLE
FluxCD v2 externalSourceRef valuesFrom 

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#2463]
### Describe the bug

We're testing the latest v2 FluxCD with our setup and we need to deploy our helmchart with external values files.
In legacy flux there was option externalSourceRef  https://fluxcd.io/legacy/helm-operator/helmrelease-guide/values/
However under v2 it is not visible and allowed flag anymore.
```
stdin - HelmRelease sde is invalid: For field spec.valuesFrom.0: kind is required - For field spec.valuesFrom.0: name is required - For field spec.valuesFrom.0: Additional property externalSourceRef is not allowed
Error: Process completed with exit code 1.
```
Is there some replacement we can use or there is no way how to specify values.yaml file from external source in v2?

Thanks in advance

### Steps to reproduce

1. Install latest FluxCD 
2. Adjust test repo https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/infrastructure/redis/release.yaml with legacy externalSourceRef and watch pipeline to fail 
```
stdin - HelmRelease sde is invalid: For field spec.valuesFrom.0: kind is required - For field spec.valuesFrom.0: name is required - For field spec.valuesFrom.0: Additional property externalSourceRef is not allowed
Error: Process completed with exit code 1.
```
### Expected behavior

We should be able to specify external values files from URL

### OS / Distro

macOS

### Flux version

v0.27.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
See https://fluxcd.io/docs/migration/helm-operator-migration/#values-from-external-source-references-urls-are-no-longer-supported, which also refers to a workaround.
