### ISSUE TITLE
force:true is not working

### ISSUE THREAD

**Issue by iheng** [fluxcd/flux2#2479]
### Describe the bug

adding force:true to Kustomize would not able to recreate job. 

### Steps to reproduce

1. add force:true to your Kustomize file
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux2-system
spec:
  interval: 2m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: *****
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux2-system
spec:
  interval: 10m0s
  path: ./
  prune: true
###   force: true
  sourceRef:
    kind: GitRepository
    name: flux-system

### Expected behavior

as it documented on wiki, should be able to recreate the job

### OS / Distro

lN?A

### Flux version

v0.21.1

### Flux check

► checking prerequisites
✗ flux 0.21.1 <0.27.2 (new version is available, please upgrade)
✔ Kubernetes 1.21.5-eks-bc4871b >=1.19.0-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Please try to reproduce this issue on the latest version of Flux. There have been major changes between Flux v0.21.x and Flux v0.27.x, the current version is Flux v0.27.2.

A server-side apply overhaul has been completed. Much of the relevant code has likely been replaced. It is possible there was a bug and that it has already been fixed, in the latest version. I can't say for sure, but if an upgrade fixes it, we shouldn't investigate any further as I'm sure you'll understand.

(If it is not possible to upgrade for some reason, please include that in the report.)

**Comment by iheng** [comment]
@kingdonb  I checked my kustomize-controller docker image version is  ghcr.io/fluxcd/kustomize-controller:v0.18.0. Do you know if I just update the kustomize-controller version to latest version, will it fix the issue or I still need to update my flux cli version.

**Comment by stefanprodan** [comment]
Flux recreates jobs only when you change immutable fields, e.g. the container image tag.
