### ISSUE TITLE
Custom namespace can't be deleted

### ISSUE THREAD

**Issue by mibollma** [fluxcd/flux2#2486]
### Describe the bug

I tried to move flux from **flux-system** to a custom namespace called **infra**. Everything works as expected, flux itself, flagger, all helm charts. However, when I try to delete the cluster terraform times out with **[ERROR] vertex "kubernetes_namespace.infra_namespace (destroy)" error: context deadline exceeded**.
When not moving flux to the custom namespace, everything can be deleted without any timeout.

In general the cluster is separated into only three namespaces for simplicity:
- kube-system
- infra //supporting infrastructure, mostly helm charts
- apps //applications being developed by the team

At the time when the deletion of the namespace fails the following resources are present in the infra namespace:

multiple **helmrelease.helm.toolkit.fluxcd.io/...**
multiple **helmchart.source.toolkit.fluxcd.io/...**
one **kustomization.kustomize.toolkit.fluxcd.io/infra**
nothing else

When trying to remove **kustomization.kustomize.toolkit.fluxcd.io/infra** manually at this point with **kubectl delete kustomization.kustomize.toolkit.fluxcd.io/infra -n infra --force=true**, kubectl just hangs till the timeout expires.

### Steps to reproduce

N/A

### Expected behavior

No timeout when trying to delete the namespace using terraform.

### OS / Distro

Windows 10

### Flux version

flux: v0.27.2

### Flux check

checking prerequisites
flux 0.27.2 <0.27.3 (new version is available, please upgrade)
Kubernetes 1.21.9 >=1.20.6-0
checking controllers
helm-controller: deployment ready
ghcr.io/fluxcd/helm-controller:v0.17.1
kustomize-controller: deployment ready
ghcr.io/fluxcd/kustomize-controller:v0.21.1
notification-controller: deployment ready
ghcr.io/fluxcd/notification-controller:v0.22.2
source-controller: deployment ready
ghcr.io/fluxcd/source-controller:v0.21.2
all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Using Terraform to uninstall Flux is not supported, Terraform has no clue about how Kubernetes works so it tries to delete all things at once resulting in stuck finalizers. You need to run `flux uninstall -n <your-namespace>`, the CLI will delete the CRDs and finalizers is the correct order.

**Comment by mibollma** [comment]
Thanks for the explanation 👍

**Comment by mibollma** [comment]
I ended up adding this to the namespace in my terraform configuration... works fine so far
```
  provisioner "local-exec" {
    when    = destroy
    interpreter = ["bash", "-c"]
    command = "flux uninstall -n infra --silent"
  }
```
