### ISSUE TITLE
Fluxv2 boot strap context deadline exceeded

### ISSUE THREAD

**Issue by youwalther65** [fluxcd/flux2#2508]
### Describe the bug

flux boot strapping does not work anymore. I haven't changed the fluxv2 repo. Using the 0.11.2 Terraform Fluxv2 provider I got the same error but for debugging purposes I show the flux CLI commands here.
The only thing which changed was that I know use "containerd" as cluster runtime for my EKS 1.21 cluster. Not sure if this is somehow related.

### Steps to reproduce

I upgraded to latest flux CLI version 

$ **flux --version**
flux version 0.27.3

$ **flux bootstrap github --owner=$GITHUB_USER --repository=fluxv2 --path=clusters/main --private=true --personal=true --branch=main**
► connecting to github.com
► cloning branch "main" from Git repository "https://github.com/youwalther65/fluxv2.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("5334327279e349acc8bb8977f9b672e98c59792d")
► pushing component manifests to "https://github.com/youwalther65/fluxv2.git"
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ecdsa-sha2-nistp384 
<readcted>
✔ configured deploy key "flux-system-main-flux-system-./clusters/main" for "https://github.com/youwalther65/fluxv2"
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ context deadline exceeded
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 1 health check failure(s)

$ **flux get sources git**
NAME            READY   MESSAGE                         REVISION        SUSPENDED
flux-system     Unknown reconciliation in progress                      False

$ **k get gitrepository -n flux-system**
NAME          URL                                        READY     STATUS                       AGE
flux-system   ssh://git@github.com/youwalther65/fluxv2   Unknown   reconciliation in progress   6m19s

$ **k describe gitrepository -n flux-system flux-system**
Name:         flux-system
Namespace:    flux-system
Labels:       <none>
Annotations:  <none>
API Version:  source.toolkit.fluxcd.io/v1beta1
Kind:         GitRepository
Metadata:
  Creation Timestamp:  2022-03-06T15:13:31Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
  Managed Fields:
    API Version:  source.toolkit.fluxcd.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:interval:
        f:ref:
          f:branch:
        f:secretRef:
          f:name:
        f:url:
    Manager:      flux
    Operation:    Apply
    Time:         2022-03-06T15:13:31Z
    API Version:  source.toolkit.fluxcd.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
      f:status:
        f:conditions:
        f:observedGeneration:
    Manager:         source-controller
    Operation:       Update
    Time:            2022-03-06T15:13:32Z
  Resource Version:  62215
  UID:               3154a7e2-70ec-43c6-aefb-65184c901884
Spec:
  Git Implementation:  go-git
  Interval:            1m0s
  Ref:
    Branch:  main
  Secret Ref:
    Name:   flux-system
  Timeout:  60s
  URL:      ssh://git@github.com/youwalther65/fluxv2
Status:
  Conditions:
    Last Transition Time:  2022-03-06T15:19:24Z
    Message:               reconciliation in progress
    Reason:                Progressing
    Status:                Unknown
    Type:                  Ready
  Observed Generation:     1
Events:
  Type    Reason  Age    From               Message
  ----    ------  ----   ----               -------
  Normal  error   4m24s  source-controller  unable to clone 'ssh://git@github.com/youwalther65/fluxv2': dial tcp 140.82.121.4:22: connect: connection timed out
  Normal  error   88s    source-controller  unable to clone 'ssh://git@github.com/youwalther65/fluxv2': dial tcp 140.82.121.3:22: connect: connection timed out

$ **flux check**
► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

Manual cloning the repo is possible
$ **git clone ssh://git@github.com/youwalther65/fluxv2**
Cloning into 'fluxv2'...
remote: Enumerating objects: 579, done.
remote: Counting objects: 100% (579/579), done.
remote: Compressing objects: 100% (414/414), done.
remote: Total 579 (delta 182), reused 255 (delta 53), pack-reused 0
Receiving objects: 100% (579/579), 75.85 KiB | 562.00 KiB/s, done.
Resolving deltas: 100% (182/182), done.

I don't know how to further debug and proceed.

### Expected behavior

flux should successfully sync flux-system GitRepository

### OS / Distro

EKS v1.21 with Amazon Linux 2, local env is WSL wuth Ubuntu 20.04 LTS

### Flux version

$ **flux --version** flux version 0.27.3

### Flux check

$ **flux check**
► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

GitHub

### Additional context

EKS cluster uses containerd as CRI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
We've had reports recently like this where it turned out to be a change in the network. The best way to debug this issue is to try creating pods in the cluster (use something like `alpine` or `debian` base, where you can install a git client) and try cloning a git repo from anywhere inside of the cluster.

```
Normal error 4m24s source-controller unable to clone 'ssh://git@github.com/youwalther65/fluxv2': dial tcp 140.82.121.4:22: connect: connection timed out
Normal error 88s source-controller unable to clone 'ssh://git@github.com/youwalther65/fluxv2': dial tcp 140.82.121.3:22: connect: connection timed out
```

For best coverage, try creating the pod inside of the flux-system repo, and also try creating it outside. There are network policies that may prevent some communication, but they should allow traffic out from the `flux-system` namespace. If any pod cannot reach the outside network, then Flux cannot reach it either.

```
> Manual cloning the repo is possible
$ git clone ssh://git@github.com/youwalther65/fluxv2
Cloning into 'fluxv2'...
remote: Enumerating objects: 579, done.
remote: Counting objects: 100% (579/579), done.
remote: Compressing objects: 100% (414/414), done.
remote: Total 579 (delta 182), reused 255 (delta 53), pack-reused 0
Receiving objects: 100% (579/579), 75.85 KiB | 562.00 KiB/s, done.
Resolving deltas: 100% (182/182), done.
```

Did you try this from your workstation, or from inside of the cluster?

The most recent report that I recall was resolved when the person figured out that AWS security groups were not permitting any traffic to leave out from the cluster.


Can you check this and let us know? It is likely to be a broader issue with cluster networking.

**Comment by RyzeNGrind** [comment]
I'm having the same issue, but I am self hosted on Raspberry Pi ARM64 nodes. I will make a new issue regarding it, but wanted to mention it here as it seems to be a wide issue affecting multiple users and devices.

**Comment by ehudyonasi** [comment]
I have the same issue happening only while bootstrapping flux. It is only happening when the network policies and services are installed and then there is no DNS resolution (using coredns). I reproduced it on my cluster with creating fresh namespace called `flux-system` and deployed a busybox pod which could fetch dns records and after flux installation it is failing.

**Comment by carlbordum** [comment]
I'm having the same issue, and I also found it to probably be because coredns is having issues.

**Comment by stefanprodan** [comment]
Flux requires a functioning cluster, so before running `flux bootstrap` you need to make sure CoreDNS and CNI are up and running, also egress to GitHub (or whatever Git service you're using) must work.

**Comment by shivani-mittal** [comment]
Hi, i am trying to setup flux in my local, while doing flux bootstrap i am getting error as : bootstrap failed with 2 health check failure(s). I am trying to use podman instead of docker as In my organization docker is licensed so need to use podman only, can you let me know what i need to do. 

Error : 
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ client rate limiter Wait returned an error: context deadline exceeded
► confirming components are healthy
✗ helm-controller: deployment not ready
✗ kustomize-controller: deployment not ready
✗ notification-controller: deployment not ready
✔ source-controller: deployment ready
✗ bootstrap failed with 2 health check failure(s)

**Comment by TOHUHM** [comment]
I met the some issue when do " flux reconcile source" , restart source-controller solved my problem.

**Comment by vyom-soft** [comment]
> Flux requires a functioning cluster, so before running `flux bootstrap` you need to make sure CoreDNS and CNI are up and running, also egress to GitHub (or whatever Git service you're using) must work.

They are working properly. Not sure why this is disappointing, client rate limiter Wait returned an error: context deadline exceeded.

**Comment by vyom-soft** [comment]
> I met the some issue when do " flux reconcile source" , restart source-controller solved my problem. "client rate limiter Wait returned an error: context deadline exceeded"

Were you able to resolve this rate limit problem? I am also seeing the same. CoreDNS & CNI are perfectly fine in my K8s 1.26.3 cluster.

**Comment by kingdonb** [comment]
> It happens because flux is sending your SSH key to the cluster.

To be a bit more specific, Flux sends a copy of the host key if it's in `.ssh/known_hosts` – it's not necessary to uninstall, you can just delete the `flux-system` secret and reinstall via bootstrap again. That will also work though, and the uninstall definitely wouldn't harm anything (unless there were Flux resources not in Git!)
