### ISSUE TITLE
Flux try to change permission of executable files in repository when re-bootstraping them same repository

### ISSUE THREAD

**Issue by duynguyende** [fluxcd/flux2#2527]
### Describe the bug

![image](https://user-images.githubusercontent.com/97506531/157794107-08075022-ad48-4538-8a4a-886149de0805.png)
In my repository there are two executable files: create-ecr-repository.sh and pants. Normally they are excuted but when I have to re-bootrap this repository, somehow these files permission are changed, so my CI/CD pipeline can not execute these files.

### Steps to reproduce

1. flux bootstrap (bootrap a repository).
2. Add some executable files.
3. flux bootstrap [created_repository_in_step_1] 

### Expected behavior

![image](https://user-images.githubusercontent.com/97506531/157794686-4d2a97b0-24c5-4689-8dea-c72b5d347ce6.png)
Permissions of pants and create-ecr-repository.sh aren't changed

### OS / Distro

Linux

### Flux version

0.27.2

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This should've been fix in Flux 0.39.0, please comment here if you still see this.
