### ISSUE TITLE
yq read git-auth.yaml 'data."identity.pub"' | base64 --decode

### ISSUE THREAD

**Issue by kbaisla31** [fluxcd/flux2#2543]
### Describe the bug

When I run these commands, it gives me this error "open git-auth.yaml: no such file or directory"

flux -n apps create secret git dev-team-auth \
    --url=ssh://git@github.com/<org>/<dev-team> \
    --export > ./tenants/base/dev-team/auth.yaml

yq read git-auth.yaml 'data."identity.pub"' | base64 --decode

### Steps to reproduce

flux -n apps create secret git dev-team-auth \
    --url=ssh://git@github.com/<org>/<dev-team> \
    --export > ./tenants/base/dev-team/auth.yaml

yq read git-auth.yaml 'data."identity.pub"' | base64 --decode

### Expected behavior

Print the SSH public key

### OS / Distro

Mac Os

### Flux version

flux: v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.11-eks-f17b81 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
yq has changed the commands in v4, see their docs here: https://mikefarah.gitbook.io/yq/

**Comment by hiddeco** [comment]
In addition, `flux secret git` creates a Secret with `.stringData`, and not `.data`.

**Comment by stefanprodan** [comment]
This is covered in the help section:

```console
$ flux create secret git -h

  # Create a Git SSH secret on disk
  flux create secret git podinfo-auth \
    --url=ssh://git@github.com/stefanprodan/podinfo \
    --export > podinfo-auth.yaml

  # Print the deploy key
  yq eval '.stringData."identity.pub"' podinfo-auth.yaml
```

**Comment by kbaisla31** [comment]
Error: unknown command "eval" for "yq"
Run 'yq --help' for usage.
2022/03/15 12:10:04 unknown command "eval" for "yq"
