### ISSUE TITLE
helm-controller fails to remove HelmRelease in multi-tenant when using ServiceAccountName

### ISSUE THREAD

**Issue by balonik** [fluxcd/flux2#2595]
### Describe the bug

I have encountered an interesting issue with the multi-tenant setup and `ServiceAccountName`.

Following the multi-tenant example https://github.com/fluxcd/flux2-multi-tenancy I have setup some test resources on my cluster.
Let's say I have a `HelmRelease` with a `ServiceAccountName` defined in my tenant's `GitRepository` where the tenant `Kustomization` points to. And this `ServiceAccountName` and respective `RoleBinding` is also defined in the tenant `rbac.yaml`.

If I remove the whole tenant `kustomize-controller` is too quick and removes all the resources including the `ServiceAccount` and `RoleBinding` before `helm-controller` can uninstall the release.

Such scenario leads to `HelmRelease` resource being stuck in `delete`, because `helm-controller` cannot remove it anymore and `finalizers` prevents from deleting the `HelmRelease` resource itself.

It also generates errors like this:
```
{"level":"error","ts":"2022-03-29T16:42:01.718Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"test-release","namespace":"test-release","error":"uninstall: Release not loaded: test-release: query: failed to query with labels: secrets is forbidden: User \"system:serviceaccount:test-release:test-release\" cannot list resource \"secrets\" in API group \"\" in the namespace \"test-release\""}
```

I suppose the same would happen if I would have another `Kustomization` using that `ServiceAccount`, but I haven't tested it.

I know that I could delete the `HelmRelease` first, wait for it to reconcile and delete the tenant afterwards, but what if I don't have access to see what kind of resources are in the tenant? At least this should be documented somewhere.

### Steps to reproduce

1. Create a multi-tenant setup following the example https://github.com/fluxcd/flux2-multi-tenancy
2. add a `HelmRelease` which uses `ServiceAccountName: dev-team`
3. remove the entire tenant at once

### Expected behavior

`HelmReleases` are uninstalled by `helm-controller` before the `ServiceAccount` and `RoleBinding` are removed by `kustomize-controller`. `HelmRelease` resource itself is deleted.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You need to point the tenant Kustomization to an empty dir, the GC will remove all things except for the SA and namespace. 
Create an empty dir in the fleet repo with a `.gitkeep` file inside, then set the path to that dir.

**Comment by balonik** [comment]
@stefanprodan thanks for the ideas. Is there any way Flux could avoid such situations like having some dependencies or something. I know this might not be in scope for Flux so feel free to close this if you think this is out of scope for Flux.
