### ISSUE TITLE
Dependency not found is considered info instead of error alert

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#2628]
### Describe the bug

I was doing some testing and could see that missing dependency is considered as info instead of error:
This error was reported to me considered as info:
```
dependencies do not meet ready condition (unable to get 'namespace/chart' dependency: HelmRelease.helm.toolkit.fluxcd.io "chart" not found), retrying in 30s
```
I agree that dependencies should be info alert when they are just waiting for others to finish. If some dependency is missing I consider it as error alert instead

### Steps to reproduce

1. Install flux
2. Configure alerts (slack f.e)
3. Deploy helmchart which will have DependsOn on non existing helmchart
4. Monitor alerts being thrown. It will report it as info/instead of error

### Expected behavior

Something missing shouldn't be reported as info but error

### OS / Distro

Ubuntu 18.04.5 LTS

### Flux version

0.28.5

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.6-gke.1503 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.5
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
We had this on error and it made on-call life really hard, due to Kubernetes asyc nature, it’s not possible to determine if a dependency will fail forever or it’s just a transient error.

**Comment by jprecuch** [comment]
Thanks @stefanprodan. If it has proper business cause then probably nothing we can do. We will adjust our monitoring to report this "not found" while other dependencies not report at all.
