### ISSUE TITLE
Update `github.com/hashicorp/terraform-exec` to `>=16.0.0`

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#2650]
In #2649, all our dependencies except this module in the [Azure related end-to-end tests](https://github.com/fluxcd/flux2/tree/0e747790f920f5d873784ddc07cbcb768d5f2873/tests/azure) were updated, as it contains a breaking change.

`tfinstall` has been removed and needs to be replaced with https://github.com/hashicorp/hc-install. We call it exactly one time in [`azure_test.go`](https://github.com/fluxcd/flux2/blob/0e747790f920f5d873784ddc07cbcb768d5f2873/tests/azure/azure_test.go#L80), which seems to pretty much equal to https://github.com/hashicorp/hc-install#find-or-install-single-version.

**Comment by gunishmatta** [comment]
@hiddeco  I would like to work on this
