### ISSUE TITLE
Push Flux CRD Schemas to another repo when release workflow is run

### ISSUE THREAD

**Issue by JJGadgets** [fluxcd/flux2#2664]
To have completion and error checking to some extent in VS Code & Emacs LSP, the CRDs are added to the JSON schemas store. The schema store can take raw file links.

However, Flux currently exports the CRD JSON schemas in a tarball when a release is made. This doesn't allow users to add a hosted version of the schemas, meaning that users have to maintain the latest versions of the files manually and locally.

I threw together a quick script over at https://github.com/JJGadgets/flux2-schemas that grabs the schemas from the latest release and extracts it, but I think it might be beneficial to have this process be integrated to a GitHub Actions workflow. 

I propose that the release workflow be modified to push the generated JSON schema files to another repo, possibly similarly named like mine (so fluxcd/flux2-schemas), rather than compressing them into a tarball. This way, users can simply input for example `https://raw.githubusercontent.com/fluxcd/flux2-schemas/main/kustomization-kustomize-v1beta2.json` into the schema store, and staying up to date with latest versions will simply be managed by the automated workflow rather than manually by users.

**Comment by JJGadgets** [comment]
Any traction on this?

**Comment by varac** [comment]
yes please!

**Comment by pl4nty** [comment]
Would also be great to include a `catalog.json`, to support dynamic schema discovery with https://github.com/redhat-developer/yaml-language-server

**Comment by Crqck3d** [comment]
Hello there, can you add the json schema in draft v7 for IDE auto-completion ?
It's actually a bloody hell to get them ...
@stefanprodan (I took the liberty of tagging you on this thread in case you didn't see it)

**Comment by kingdonb** [comment]
We are looking at this for possible inclusion in an upcoming release, or alternatively we could promote [JJGadgets/flux2-schemas](https://github.com/JJGadgets/flux2-schemas) as a project under [fluxcd-community](https://github.com/fluxcd-community/)

**Comment by JJGadgets** [comment]
Thanks for looking at the issue, I'm open to be included into the community org if core maintainers is okay with that!

**Comment by hiddeco** [comment]
If you put in a request to have the repository transferred to `fluxcd-community` organization, I would be happy to accept the request and re-add you as a maintainer on the repository.

**Comment by JJGadgets** [comment]
Hey @hiddeco, where would I put such a request in? 

If you meant on the repository’s transfer page, I can’t transfer the repo without already having the relevant permissions to the org assigned to my user, unfortunately.

**Comment by hiddeco** [comment]
Forgot about that limitation for a minute. I think the alternative way to go then is to initiate a transfer to my account, from where I can transfer it to the organization. Tad cumbersome, but should work.

**Comment by JJGadgets** [comment]
Gotcha, going to initiate the transfer to you now.

**Comment by hiddeco** [comment]
https://github.com/fluxcd-community/flux2-schemas is now a thing, thanks for this @JJGadgets :bow:

**Comment by JJGadgets** [comment]
Sorry, forgot to mark as resolved and close the issue, will do so now. Thanks everyone for the work on FluxCD! 🥳
