### ISSUE TITLE
Allow providing custom URL to the Receiver to allow IaC for webhooks

### ISSUE THREAD

**Issue by ar-qun** [fluxcd/flux2#2672]
# Description
Currently, Receiver provides a randomly generated `url` via status. This however can't be picked up by Terraform. See related issue https://github.com/hashicorp/terraform-provider-kubernetes/issues/1699

# Request
Would it be possible to provide a url via a new field? This way the url can be generated in Terraform and know to IaC?

**Comment by hiddeco** [comment]
The URL of the resource is not random, but can be predicted. It equals to `/hook/sha256sum(token+name+namespace)`, where token refers to the secret value retrieved from the `.spec.secretRef` resource.

**Comment by stefanprodan** [comment]
You use the Terraform [sha256](https://www.terraform.io/language/functions/sha256) function to compute the URL as @hiddeco mentioned above.

**Comment by ar-qun** [comment]
@hiddeco @stefanprodan

Thank you very much! Tried it out and it of course worked :)

I went through the entire page and missed the obvious.
