### ISSUE TITLE
Substitution isn't available in remote base/resource/component for kustomization

### ISSUE THREAD

**Issue by davinkevin** [fluxcd/flux2#2675]
### Describe the bug

Hi 👋 , 

To be honest, I open this as a bug just because the variable name and the documentations states the `PostBuild` is executed after the build, but it seems to not be true. And this add a limitation to flux as described in the title. 

If I understand it correctly, the `postBuild` is executed [here](https://github.com/fluxcd/kustomize-controller/blob/ef77093efd9e863dfeee31d98328a2ab09326e5a/controllers/kustomization_controller.go#L685) in the kustomization controller, but the global YAML generation (similar to `kustomize build` command) is executed [here](https://github.com/fluxcd/kustomize-controller/blob/ef77093efd9e863dfeee31d98328a2ab09326e5a/controllers/kustomization_controller.go#L700). 

The problem is the substitution is not possible if the YAML code is located in an external repository (remote base/resource/components) like used [here](https://gitlab.com/davinkevin.fr/home-server/-/blob/main/podcast-server/k8s-server/kustomization.yaml#L11).

### Steps to reproduce

1. Create two repositories
2. Store one set of yaml (manifests + `kustomization.yaml`) in the first one with some values defined to `${replaceMe}`
3. Store another set of yaml (manifests + `kustomization.yaml`), with a remote resource in the kustomization.yaml with a remote resource set to (2)
4. Add to this second set of yaml a usage of `${replaceMe}`
5. Declare everything in `flux` to use the repository declared into (3)

### Expected behavior

I expect `PostBuild` to be executed after full yaml build, including remote resources. So, in the previous example, I expect every value from the `remote resource` to be substituted. 

### Screenshots and recordings

Sorry, I don't have some, but I provided some example before. 

### OS / Distro

linux/k3s but every os/distro is concerned

### Flux version

0.22.x+ (I've checked the current code, this is still present)

### Flux check

N/A

### Git provider

N/A

### Container Registry provider

N/A

### Additional context

N/A

PS: Flux is a wonderful project, so thank you for your hard work ! 👏

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Remote resources are pulled in by Kustomize at build time, and are not visible to the kustomize-controller at any given moment. This means that variable substitution only works for files in Git (or any other source the Kustomization refers to).

I do not expect this to change, as it would require us to deal with fetching remote sources ourself, and most of the magic required for this is not available through public APIs as it is hidden in `internal`. See e.g. https://github.com/kubernetes-sigs/kustomize/blob/9d5491c2e20c23c7a9b3d5a055d2aa24cc14bede/api/internal/git/repospec.go#L85

**Comment by davinkevin** [comment]
Ok, sad to hear that. 

Small question, flux is not able to "build" everything using `kustomize` code and then do the substitution? I though [this](https://github.com/fluxcd/kustomize-controller/blob/ef77093efd9e863dfeee31d98328a2ab09326e5a/controllers/kustomization_controller.go#L700) was the call to kustomize to generate the whole set of YAMLs (following remote resource/base/components).

**Comment by hiddeco** [comment]
You are absolutely right, variable constitution happens _after_, decryption (which I worked on the past weeks) happens _before_. 

Given this, I would expect your example to work. Can you provide the precise line in  the remote base which contains a variable that you expect to be replaced?

**Comment by stefanprodan** [comment]
The build happens at `secureBuildKustomization` not at `asYaml`.

**Comment by davinkevin** [comment]
Thank you @stefanprodan, so I need to check this again 🧐. I keep you updated as soon as possible
