### ISSUE TITLE
Upgrade Flux to the Source v1beta2 API

### ISSUE THREAD

**Issue by punnarpulusu** [fluxcd/flux2#2684]
### Terrafrom upgrade

When using the [Terraform provider for Flux](https://github.com/fluxcd/terraform-provider-flux), you have to manually remove the `v1beta2` GitRepository from the TF state:

```
terraform state rm 'kubectl_manifest.sync["source.toolkit.fluxcd.io/v1beta1/gitrepository/flux-system/flux-system"]'
```

Did you mean to remove `v1beta1` from the terraform state file ??

**Comment by hiddeco** [comment]
You are absolutely right, this is also what the command actually does. I updated the discussion post. Thanks!

**Comment by mewzherder** [comment]
@punnarpulusu Thanks so much for this! We're reaching out to Flux users to hear more about how things are going, gathering feedback, and understanding needs. Would you be willing to have a chat with us? We'd appreciate it. lmk. ❤️
