### ISSUE TITLE
flux-system services fail to reconcile with error "spec.clusterIPs: Required value"

### ISSUE THREAD

**Issue by Alxandr** [fluxcd/flux2#2685]
### Describe the bug

I've been unable to reconcile my cluster for a while. It fails with the error:

```
Kustomization reconciliation failed: Service/flux-system/notification-controller dry-run failed, reason: Invalid, error: Service "notification-controller" is invalid: spec.clusterIPs: Required value
```

I've tried to delete the resources in question (the 3 services in the flux-system namespace) and re-create them using `flux install` anew, but I always end up with the same problem. I also get the same issue just straight up running `flux install` (without first deleting the 3 services).

### Steps to reproduce

I'm not sure. My cluster suddenly stopped reconciling, and I can't get it working again.

### Expected behavior

The flux components should reconcile successfully.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/112334/165617089-06832c32-56c3-452c-be90-e6ee0288c55a.png)

### OS / Distro

OpenSUSE MicroOS

### Flux version

v0.29.4

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.3-k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.20.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.24.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
`spec.clusterIPs` is not a required field, I guess this is a K3s bug. Every Flux release is tested, the e2e tests are performed on Kubernetes Kind, AKS, GKE and EKS.

**Comment by Alxandr** [comment]
After spending a grand old time rebuilding my entire cluster (cause it turned out that upgrading k3s as I was running it was not trivial) things seems to be working again. Seems I was just really unlucky with a series of events. Sorry for the wrong report and thanks for your time :)
