### ISSUE TITLE
Flux build kustomization with a local kustomization file should not need a kubeClient

### ISSUE THREAD

**Issue by souleb** [fluxcd/flux2#2688]
### Describe the bug

When using `flux build` with the flag `--kustomization-file`, we don't fetch the `kustomization` file from the cluster, so no connection is needed. Today we still request a kubeClient in this scenario and we should not.

### Steps to reproduce

flux build kustomization my-app --path ./path/to/local/manifests --kustomization-file ./path/to/local/my-app.yaml

### Expected behavior

we should not need a kubeClient when rendering with a local kustomization file.

### OS / Distro

macOS

### Flux version

v0.29.4

### Flux check

► checking prerequisites
✗ flux 0.29.4 <0.29.5 (new version is available, please upgrade)
✔ Kubernetes 1.22.3+fdba464 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.21.3
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.5
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I don't see how you could run build without having access to the cluster to fetch configMaps/secrets for variable substitutions.

**Comment by souleb** [comment]
> I don't see how you could run build without having access to the cluster to fetch configMaps/secrets for variable substitutions.

True! Going to close this.

**Comment by stevejr** [comment]
@stefanprodan - is there a way to have an offline mode for those that do not use configmaps or secrets for their variable substitutions?

**Comment by mbaeuerle** [comment]
> @stefanprodan - is there a way to have an offline mode for those that do not use configmaps or secrets for their variable substitutions?

I think it's reasonable to ask for a offline mode (e.g. with reduced feature set). We would like to do a `flux build` for PRs that change the customization files. But that would mean that the Github action would need to access the cluster again. That Github doesn`t need access to the cluster is one of the advantages of Flux, after all.

**Comment by souleb** [comment]
We are looking at it.
