### ISSUE TITLE
kustomize build failed: accumulating resources

### ISSUE THREAD

**Issue by hareeshmu** [fluxcd/flux2#2709]
### Describe the bug

Most of the time seeing below error:

`    message: 'kustomize build failed: accumulating resources: accumulation err=''accumulating
      resources from ''cert-manager'': read /tmp/kustomization-2262966/cluster/crds/cert-manager:
      is a directory'': recursed accumulation of path ''/tmp/kustomization-2262966/cluster/crds/cert-manager'':
      accumulating resources: accumulation err=''accumulating resources from ''https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml'':
      Get "https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml":
      net/http: TLS handshake timeout'': evalsymlink failure on ''/tmp/kustomize-1562403375/releases/download/v1.7.1/cert-manager.crds.yaml''
      : lstat /tmp/kustomize-1562403375/releases: no such file or directory'
    reason: BuildFailed
    status: "False"
    type: Ready`

### Steps to reproduce

While reconciling git repo

### Expected behavior

It should be success and proceed with reconciliation 

### OS / Distro

Ubuntu 22.04

### Flux version

flux: v0.30.2

### Flux check

$ flux check
► checking prerequisites
✔ Kubernetes 1.23.6+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jprecuch** [comment]
This normally means that you might have conflicting kustomization.yaml entries rwhere there are 2 references for same path/resources . This is hard to troubleshoot without really seeing your files definitions.
It's best to review all the files that it complains about

**Comment by stefanprodan** [comment]
`net/http: TLS handshake timeout` this means Flux can't reach GitHub, I guess your cluster egress is broken.

**Comment by kingdonb** [comment]
Please let us know if this turns out to be the case or not. Since it seems likely to be an issue with your cluster networking, I'm closing this. (We can reopen if that's not the case.)
