### ISSUE TITLE
CLI command to read status information from a commit

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/flux2#271]
The notification controller supports writing events to git repositories in the form of a commit status. This functionality completes the feedback loop, allowing in theory some sort of pipeline to automate the promotion by creating a PR or making a git commit to another repo/directory. To implement this the pipeline would have to be able to fetch the commit status for a specific commit. It would be nice to have a CLI command that does this instead of having to write custom bash each time.

The new command could look something similar to this. The important thing would be that it returns the same data format for all git providers.
```shell
export GITHUB_TOKEN=<my-token>
gotk status github --owner=<user> --repository=<repo name> --ref <ref>
```

**Comment by kingdonb** [comment]
@phillebaba Do you have an example of one of those custom bash scripts that you sound like you've had to use?

If you've been using this technique anger, (or if there has been any other progress related to this issue that you'd like to share) I'd like to give implementing this a try, and it will be helpful to know I guess what knobs you've needed, or anything else that you can add that might help me get it started!

**Comment by phillebaba** [comment]
I ended up building  a custom tool for this. It is very specific to the way we work at Xenit, but might be helpful to some. The issue right now is that the docs are bad/non-existant.

https://github.com/XenitAB/gitops-promotion
