### ISSUE TITLE
storageClass parameters in values file is ignored

### ISSUE THREAD

**Issue by ahmad-shams** [fluxcd/flux2#2724]
### Describe the bug

When deploying Jenkins to eks using fluxcd, storageClass parameters provided via values.yaml file is ignored and after deployment, the persistent volume is cretaed on the default StorageClass and not the StorageClass provided at values.yaml

when using same values.yaml file and deploying jenkins using helm cli tool, then deployment is behaving ok and the provided StorageClass is used

### Steps to reproduce

commit values file with following section:
persistence:
  enabled: true
  storageClass: efs-sc-staging
  size: 10Gi
  
  when fluxcd reconsile this folder then the acital used StorageClass is gp2

same values file, when using it with helm tool cli the actual Storage class used is the right one

### Expected behavior

Storageclass provided via values file; example 
persistence:
  enabled: true
  storageClass: efs-sc-staging
  size: 10Gi
  
  should be used by fluxcd to deploy the app in same way as it works with helm cli tool

### OS / Distro

eks

### Flux version

v0.30.2

### Flux check

➜  ~ flux check
► checking prerequisites
✔ Kubernetes 1.21.9-eks-0d102a7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please post here the HelmRelease YAML as you have it in Git, please use GH code blocks so we can see the indentation.

**Comment by ahmad-shams** [comment]
`apiVersion: v1
kind: Namespace
metadata:
  name: common
---  
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
  namespace: common
spec:
  url: https://charts.jenkins.io
  interval: 10m
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ci-staging
spec:
  interval: 1m
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: common
      interval: 10m
    valuesFrom:
    - chartFileRef:
        path: values.yaml
        optional: true
`

**Comment by hiddeco** [comment]
Your `.spec.chart` is not valid, as `valuesFrom` is not a valid field. The `.spec.chart` only knows `valuesFiles`, which can be used to rebuild the chart using a (composition of) alternative values files included in the source.

`valuesFrom` should be used on the `.spec` of the `HelmRelease` itself, please read the documentation on values: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources

**Comment by stefanprodan** [comment]
@ahmad-shams you may want to use this script to validate all Flux YAMLs before pushing to Git: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh

**Comment by ahmad-shams** [comment]
Thanks, I will go through the answer
