### ISSUE TITLE
No way to perform flux bootstrap using tags

### ISSUE THREAD

**Issue by gavinclarkeuk** [fluxcd/flux2#2726]
### Describe the bug

The GitRepository api supports `spec.ref.tags` to point flux to a specific tag, however there is no way of providing a tag to the flux cli bootstrap command. If you've modified the GitRepository to use tags then it will be overwritten if you upgrade flux by using the bootstrap command again.

### Steps to reproduce

1. use `flux bootstrap github` command to set up flux with a github repository
2. modify the generated gotk-sync.yaml to update the GitRepository spec.ref to use a tag instead of a branch
3. rerun the flux bootstrap command

You'll see the gotk-sync.yaml has been been reverted to point to a branch

### Expected behavior

Either provide an explicit `--tag` option for the bootstrap command, or have the bootstrap command preserve the existing GitRepository spec if it is run without specifying a branch/tag

### OS / Distro

macOs 10.15

### Flux version

v0.30.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.9-eks-14c7a48 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
To customize Flux manifests, you should use patches instead. Please see this guide [https://fluxcd.io/docs/installation/#customize-flux-manifests](https://fluxcd.io/docs/installation/#customize-flux-manifests) and [https://fluxcd.io/docs/cheatsheets/bootstrap/](https://fluxcd.io/docs/cheatsheets/bootstrap/)
