### ISSUE TITLE
Issue upgrading flux using bootstrap command

### ISSUE THREAD

**Issue by marcincuber** [fluxcd/flux2#2751]
### Describe the bug

I have existing flux system installed and I don't seem to be able to upgrade my existing templates:

I am running following command:
```
> $ flux bootstrap github --owner=org --repository=k8s-gitops-staging --path="environments/aws/" --branch=master --components-extra=image-reflector-controller,image-automation-controller
```

```
Please enter your GitHub personal access token (PAT):
► connecting to github.com
► cloning branch "master" from Git repository "https://github.com/org/k8s-gitops-staging.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
✗ sync path configuration ("./environments/aws") would overwrite path ("./environments/aws/flux-system") of existing Kustomization
```

I can confirm that paths are definitely correct and flux files should simply be upgrade in `./environments/aws/flux-system` directory.

Could I get some advise how I should proceed with the upgrade without breaking anything?

### Steps to reproduce

Peforming below command in the existing repository
1. flux bootstrap github --owner=org --repository=k8s-gitops-staging --path="environments/aws/" --branch=master --components-extra=image-reflector-controller,image-automation-controller

### Expected behavior

I would expect for flux components to be upgraded.

### OS / Distro

MacOS 12.3.1

### Flux version

0.30.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.6-eks-7d68063 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.18.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You can't change the path at upgrade time. If you want to bootstrap on a different path, then you to run `flux uninstall --keep-namespace` then run bootstrap fresh.
