### ISSUE TITLE
garbage collection on removal of Kustomization does not work as documented

### ISSUE THREAD

**Issue by reiSh6phoo9o** [fluxcd/flux2#2752]
### Describe the bug

In flux documentation regarding garbage collection, it says (https://fluxcd.io/docs/components/kustomize/kustomization/#garbage-collection): "Garbage collection is also performed when a Kustomization object is deleted, triggering a removal of all Kubernetes objects previously applied on the cluster."

From that, I assume that if I remove a flux Kustomization manifest from my flux repo, commit and push:
- flux will remove the Kustomization object from my cluster
- flux will remove all resources, which were created when the Kustomization object got created

Only the first applies, though; all other resources stay on my cluster and are not garbage collected.

### Steps to reproduce

1. Deploy podinfo using HelmRelease and Kustomization; flux repo structure is:
- `apps/base/podinfo/helmrelease.yaml`
- `apps/base/podinfo/kustomization.yaml`
- `clusters/dev/podinfo.yaml`

flux watches `clusters/dev`path.

This is inside the files:
`apps/base/podinfo/helmrelease.yaml`
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 60m0s
```
`apps/base/podinfo/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm_release.yaml
namespace: default
```
`clusters/dev/podinfo.yaml`
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/base/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

2. verify that objects are present on the cluster:
```
# Kustomization is present
➜  flux-gitops git:(minikube_bit) ✗ flux get kustomizations podinfo-dev
NAME       	REVISION            	SUSPENDED	READY	MESSAGE
podinfo-dev	minikube_bit/0822b88	False    	True 	Applied revision: minikube_bit/0822b88

# HelmRelease is present
➜  flux-gitops git:(minikube_bit) ✗ kubectl get helmreleases.helm.toolkit.fluxcd.io
NAME      AGE   READY   STATUS
podinfo   73m   True    Release reconciliation succeeded

# objects created by Helm chart are present
➜  flux-gitops git:(minikube_bit) ✗ kubectl get all
NAME                           READY   STATUS    RESTARTS   AGE
pod/podinfo-78ffc8bdcc-l8jcn   1/1     Running   0          73m

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/podinfo      ClusterIP   10.105.234.111   <none>        9898/TCP,9999/TCP   73m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/podinfo   1/1     1            1           73m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/podinfo-78ffc8bdcc   1         1         1       73m
```

3. delete Kustomization file, git commit and push
after reconciliation, verify objects in cluster:
```
# verify Kustomization is removed
➜  flux-gitops git:(minikube_bit) ✗  flux get kustomizations podinfo-dev
✗ no Kustomization objects found in flux-system namespace

# BUT: HelmRelease is still present
➜  flux-gitops git:(minikube_bit) ✗ kubectl get helmreleases.helm.toolkit.fluxcd.io
NAME      AGE   READY   STATUS
podinfo   77m   True    Release reconciliation succeeded

# it's obvious, that then also all other objects governed by helmrelase are still present:
➜  flux-gitops git:(minikube_bit) ✗ kubectl get all -n default
NAME                           READY   STATUS    RESTARTS   AGE
pod/podinfo-78ffc8bdcc-l8jcn   1/1     Running   0          78m

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/podinfo      ClusterIP   10.105.234.111   <none>        9898/TCP,9999/TCP   78m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/podinfo   1/1     1            1           78m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/podinfo-78ffc8bdcc   1         1         1       78m
```

### Expected behavior

From the documentation, I expect:
When Kustomization ( `clusters/dev/podinfo.yaml` ) is removed, HelmRelease is garbage collected

### OS / Distro

N/A

### Flux version

N/A

### Flux check

➜  flux-gitops git:(minikube_bit) ✗ flux check
► checking prerequisites
✔ Kubernetes 1.21.9-eks-0d102a7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
Hey @reiSh6phoo9o ,
The Kustomize controller does garbage collect the objects it created when it is removed.
I am not sure why it isn't working in your case. If the flux is watching the repository, it is possible that the customization you deleted was recreated on the next run. You can remove the file for the Flux kustomization from the repository to ensure this isn't what's happening.

**Comment by reiSh6phoo9o** [comment]
Hi @SomtochiAma ,
I delete the Kustomization exact in the way you sugest, it is: remove the file, push to the repo, let flux delete the Kustomization object.
The Kustomization object is deleted by flux, I can confirm; but the other objects stay

**Comment by kingdonb** [comment]
Is this possibly related to:

* https://github.com/fluxcd/flux2/issues/2660

Short version: is your kustomization still pointing at an existing path or was the entire path removed

**Comment by reiSh6phoo9o** [comment]
Hi @kingdonb,
I do not think this is related, since in my case, there is no "empty folder" involved: I delete the flux Kustomization CR, and the path this Kustomization points to does still exist (with all manifests inside).

When deleting the Kustomization, I get entries in flux logs showing me that flux did do garbage collection; but, as described above, flux garbage collection only removes the Kustomization object, not the objects governed by this Kustomization.

These are parts of flux logs after removing `clusters/dev/podinfo.yaml` from git repo:
```
2022-05-30T11:52:05.477Z info Kustomization/flux-system.flux-system - garbage collection completed: Kustomization/flux-system/podinfo-dev deleted
2022-05-30T11:52:05.563Z info Kustomization/flux-system.flux-system - Reconciliation finished in 3.1621235s, next run in 10m0s
2022-05-30T11:52:05.565Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object
2022-05-30T11:52:39.863Z info GitRepository/flux-system.flux-system - garbage collected old artifacts
```

I can reproduce this behaviour in several clusters, with different flux installations.
I bootstrap flux without any fancy settings:
```
flux bootstrap gitlab --hostname=<my-git> --owner=<my-owner> --repository=flux-gitops --branch=develop --path=clusters/dev --token-auth --token <mytoken>
```

Do I misunderstand the way I should structure my repo? Currently I have a seperate flux Kustomization for every application in my `clusters/dev` path, like:
```
clusters/dev/
  podinfo.yaml
  app2.yaml
  appN.yaml
```

So, I diverge from the example at https://github.com/fluxcd/flux2-kustomize-helm-example/tree/main/clusters, where there is one Kustomization per cluster for all applications:
```
clusters/dev/
  apps.yaml
```

Thanks everyone for looking into this!

**Comment by reiSh6phoo9o** [comment]
Hi @stefanprodan,
thanks for the hint with `apiVersion` , I'll test again (I'm currently using `v1beta1` )
I'll do a quick test.
here is my Kustomization:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/base/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

**Comment by reiSh6phoo9o** [comment]
@stefanprodan,
thanks, updating my `apiVersion` to `v1beta2` solved the issue.

Sorry for the hassle! thanks everyone for your awesome work!
