### ISSUE TITLE
flux bootstrap git timeout -- ssh works fine

### ISSUE THREAD

**Issue by wibed** [fluxcd/flux2#2754]
### Describe the bug

i run the command 
```sh
flux bootstrap git --private-key-file=/Users/wibe/.ssh/flux --url=ssh://git@localhost:9000/home/git/cluster.git
```

the public key already in the `authorized_keys` file works fine, if i issue:
```sh
git clone ssh://git@localhost/home/git/cluster.git
--- RESPONSE---
Cloning into 'cluster'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 117 (delta 23), reused 107 (delta 22), pack-reused 0
Receiving objects: 100% (117/117), 55.11 KiB | 18.37 MiB/s, done.
Resolving deltas: 100% (23/23), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

check
```sh
flux check
----- RESPONSE -----                                                                                     
► checking prerequisites
✔ Kubernetes 1.23.6+k3s1 >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed
```

get sources
```sh
flux get sources git
----- RESPONSE -----                                                                                           
NAME            REVISION        SUSPENDED       READY   MESSAGE                                                                                                                                                          
flux-system                     False           False   failed to checkout and determine revision: unable to clone 'ssh://git@localhost:9000/home/git/cluster.git': dial tcp 127.0.0.1:9000: connect: connection refused
```

### Steps to reproduce

- create a private git server
- provision your keys
- try to bootstrap flux given repo

### Expected behavior

for the ssh to connect

### OS / Distro

Mac os

### Flux version

flux: v0.30.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.6+k3s1 >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

private git server

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
```
git clone ssh://git@localhost/home/git/cluster.git
```

`localhost` on your machine is different from `localhost` in the cluster. Or is the git server deployed on your cluster?

**Comment by wibed** [comment]
@SomtochiAma it is deployed on the cluster. is that an issue?

**Comment by SomtochiAma** [comment]
No, that should be fine.
The `source-controller` deployment is trying to connect to the git server at `localhost:9000`. Only containers in the same pod can communicate using localhost. You could try using the service to connect to it.

**Comment by wibed** [comment]
if i pass the service ip, it does try to clone the repo first and fails doing so.
if i give it the forwarded port it clones and timesout after (as stated above)

**Comment by SomtochiAma** [comment]
So what's happening is that when running the bootstrap command on your machine, the git server is accessible at `localhost`. I am guessing you port-forwarded. But when the source-controller is trying to reconcile the git repository it doesn't work. 
You would need to use a URL that works both within and outside the cluster. Can you use an ingress?

Alternatively, you can [customize](https://fluxcd.io/docs/installation/#customize-flux-manifests) the GitRepository manifest to use the svc URL. You would probably need to update the flux-system secret (the know hosts part since it will have localhost instead)

**Comment by stefanprodan** [comment]
Bootstrap against localhost is not supported, also running a Git server on the same cluster with Flux breaks the whole GitOps idea since the cluster state can’t be restored, if the cluster goes down so does the git server running on it.
