### ISSUE TITLE
Add an --offline or --dry-run flag to flux build kustomization

### ISSUE THREAD

**Issue by fire-ant** [fluxcd/flux2#2765]
### Describe the bug

Today if attempting something like:

`flux build kustomization my-app --path ./path/to/local/manifests --kustomization-file ./path/to/local/my-app.yaml`

Flux requires 2 things:

- a valid apiserver endpoint listed in the current context kubeconfig
- a kustomisation object matching that which is referenced when using the command flux build kustomization 

For environments where these may not be available (for example a developers machine). it would be ideal to forgo interaction with the api server and remove the dependency for these types of situations.

### Steps to reproduce

attempt the command mentioned above in an similar environment/configuration. 

### Expected behavior

ideally you should be able to locally reference a set of manifests in path and a kustomization file and generate/transform/expand the manifests as necessary without any interaction with the cluster.

### OS / Distro

Arch Linux

### Flux version

v0.29.0

### Flux check

N/A

### Git provider

N/A

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Duplicate of: https://github.com/fluxcd/flux2/issues/2688

**Comment by fire-ant** [comment]
@stefanprodan thanks, lets close this and continue there
