### ISSUE TITLE
flux version only displays when connected to an initialised cluster

### ISSUE THREAD

**Issue by steveww** [fluxcd/flux2#2766]
### Describe the bug

Running `flux version` only displays when connected to a cluster. If you're not connected to a valid cluster you can not find out the version of the CLI.

### Steps to reproduce

Have an empty of invalid kube context, run `flux version`

### Expected behavior

I would expect it to show the version of the CLI no matter whether it can connect to a cluster or not. Having to specify `--client` is an extra step that should not be required, `flux version` should be able to work it out. `kubectl version` always reports the client version even if it can not connect to a cluster.

### Screenshots and recordings

Empty kube context

flux version
✗ kubernetes client initialization failed: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused

Valid kube context with empty cluster

flux version
✗ no deployments found in flux-system namespace

### OS / Distro

Mac

### Flux version

v0.30.2

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.21.11-gke.900 >=1.20.6-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darkowlzz** [comment]
Hi, there's `flux -v` flag that prints the CLI version.

```console
$ flux -v
flux version 0.30.2
```

**Comment by stefanprodan** [comment]
There is also:

```console
$ flux version --client
flux: v0.30.2
```
