### ISSUE TITLE
flux build/diff: fs-security-constraint error

### ISSUE THREAD

**Issue by Thaval** [fluxcd/flux2#2785]
### Describe the bug

When running `flux build ...`, an error is shown that indicates security issue. For example:
```
flux build kustomization my-app --path ./corpsol --kustomization-file ./corpsol/kustomization.yaml
```
will display the following error

```
✗ kustomize build failed: fs-security-constraint abs ./corpsol: path './corpsol' is not in or below 'C:\'
```

The kustomization.yaml looks like this

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
- ../../../../.common/helm_templates/flux_manifests/alert.yaml
```

### Steps to reproduce

- Install Flux
- Run `flux build kustomization my-app --path ./corpsol --kustomization-file ./corpsol/kustomization.yaml`
- See the error - fs-security-constraint (no files are built)

### Expected behavior

The kustomization should be built successfully, so that a preview is shown.

### OS / Distro

Windows 10

### Flux version

v0.30.2

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thaval** [comment]
@souleb What do you mean: The files and content or the absolute path of ./corpsol?

**Comment by Thaval** [comment]
What's the current state?

**Comment by souleb** [comment]
Hello There. We discussed this during the last dev meeting. Let's chat online about pairing.

**Comment by Thaval** [comment]
Alright, thanks! :) Could you reproduce this? Let me know if you need more information.

**Comment by 4c74356b41** [comment]
getting the same error for `flux diff`:

```
✗ kustomize build failed: must build at directory: not a valid directory: fs-security-constraint abs C:\_git\flux-fleet\clusters\prd: path 'C:\_git\flux-fleet\clusters\prd' is not in or below 'C:\'
```

**Comment by stefanprodan** [comment]
Fixing this on Windows is not going to be easy as none of the Flux maintainers use MSFT products. I suggest installing the Flux CLI on **Windows Subsystem for Linux** which has no issues.

**Comment by 4c74356b41** [comment]
can you, perhaps, point me to the code that is throwing? I'm willing to try, however I'm not really good with go :(

**Comment by stefanprodan** [comment]
The error comes from our own filesystem implementation https://github.com/fluxcd/pkg/blob/main/kustomize/filesys/fs_secure.go

**Comment by 4c74356b41** [comment]
thanks, i'll try looking at it, but at a glance it doesn't look like something I'll be able to figure out xD

**Comment by Thaval** [comment]
@stefanprodan Ok, understand this. Totally new to golang, but I only use Windows. However, is there a guide on how to kickstart flux development? Would like to know how to run the code and test changes.

**Comment by souleb** [comment]
@Thaval can you try with this pull request: https://github.com/fluxcd/flux2/pull/3317?

**Comment by Thaval** [comment]
> @Thaval can you try with this pull request: https://github.com/fluxcd/flux2/pull/3317?

Sure I can. But I need to figure out how to run the commands or better said, build and use the project.

**Comment by souleb** [comment]
```sh
⋊> ~ make build-dev                                                                                         10:14:28
⋊> ~ ./bin/flux diff kustomization ...
```

**Comment by 4c74356b41** [comment]
this doesnt build a binary for windows? at least for me.

**Comment by 4c74356b41** [comment]
okay, with this build it is actually working! sweeeet.

```
.\flux.exe diff kustomization --path C:\_git\xxx\infrastructure\core\ cluster-base
✓  Kustomization diffing...
► Namespace/yyydrifted

metadata.labels
  + one map entry added:
    test: test

⚠️ identified at least one change, exiting with non-zero exit code
```
