### ISSUE TITLE
Azure Blob Container Fails to Connect Using Valid SPN

### ISSUE THREAD

**Issue by jonathan-innis** [fluxcd/flux2#2791]
### Describe the bug

Attempting to connect to an Azure Blob container as described in [these docs](https://fluxcd.io/docs/components/source/buckets/#azure-service-principal-secret-example) does not succeed. Using a valid SPN that has contributor permission on the container I am getting the following error

```bash
NAMESPACE   NAME           ENDPOINT                                AGE     READY   STATUS
default     azure-public   https://shasama.blob.core.windows.net   7d20h   False   failed to create token credential from 'azure-sp-auth' Secret: invalid tenantID. You can locate your tenantID by following the instructions listed here: https://docs.microsoft.com/partner-center/find-ids-and-domain-names
```

### Steps to reproduce

1. Create an SPN and give it sufficient permission to access the Azure Blob store
2. Create a bucket that references the Azure Blob endpoint in Azure
3. Create an SPN secret as described [here](https://fluxcd.io/docs/components/source/buckets/#azure-service-principal-secret-example)

### Expected behavior

Bucket should succeed to connect to the storage account and begin pulling from the container

### OS / Distro

Ubuntu 20.04

### Flux version

flux: v0.28.5

### Flux check

jonathaninnis@DESKTOP-PMUFP6M:~$ flux check
► checking prerequisites
✗ flux 0.28.5 <0.30.2 (new version is available, please upgrade)
✔ Kubernetes 1.21.9 >=1.20.6-0
► checking controllers
✔ fluxconfig-agent: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-agent:1.2.0
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.2.0
✔ fluxconfig-controller: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-controller:1.2.0
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.2.0
✔ helm-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/helm-controller:v0.20.0
✔ kustomize-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/kustomize-controller:v0.24.0
✔ notification-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/notification-controller:v0.23.3
✔ source-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/source-controller:v0.24.2
✔ all checks passed

### Git provider

Azure Blob Container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Can you please confirm there is not an accidental newline added to your tenant ID or something? Going through our code, the error seems to originate from the Azure SDK which uses the direct values from the Secret: https://github.com/fluxcd/source-controller/blob/8a99fc7fe8b7b0ad59dab1d554cb909cee6fc316/pkg/azure/blob.go#L307

**Comment by summerhasama** [comment]
Tried out the Azure Blob Container as source with Service Principal for auth and looks like it works.
