### ISSUE TITLE
Source controller randomly loses connection to Bitbucket Cloud

### ISSUE THREAD

**Issue by trenslow** [fluxcd/flux2#2828]
### Describe the bug

Sorry guys, this one is a bit difficult to reproduce, but I still wanted to post because I wanted to see if anyone else is having the same issue as me.

The source controller (experiencing on both v0.23.x and v0.24.x) intermittenly loses connection to the Bitbucket Cloud repo with which it was bootstrapped with the following error:

```
flux get image update

MESSAGE
unable to clone 'https://bitbucket.org/<redacted>/<redacted>': transport closed
```

This error will also remain, even if I try restarting the Flux deployments or deleting and recreating the Flux pods. I even checked if I can authenticate with the same user/token combo on my local machine and I can easily clone the repo that Flux was bootstrapped with.

Is anyone else experiencing this behavior? How can I restart the connection?

### Steps to reproduce

Bootstrap Flux with a Bitbucket Cloud repo using a token authentication. Error can occur anytime.

### Expected behavior

I would expect that Flux would first off not lose connection with the repo, but also recover after sometime.

### OS / Distro

GKE cluster

### Flux version

flux: v0.31.1

### Flux check

✔ Kubernetes 1.23.5-gke.1501 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.18.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

Bitbucket Cloud

### Additional context

Logs don't seem to be complaining about the connection to the flux-system repo:

```
2022-06-09T13:21:20.989Z info GitRepository/flux-system.flux-system - artifact up-to-date with remote revision: 'master/8edb70515dee13958a8356a822ed27964e11c940' 
```

(this revision is behind the current one)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@pjbgf I don't think the error posted here has anything to do with source-controller. It shows up at `flux get image` so it's image-automation-controller and libgit2.

**Comment by stefanprodan** [comment]
> Since Flux can't talk to git

Based on your own report, Flux can talk to git just fine, it's the image automation that doesn't work.

**Comment by trenslow** [comment]
Good point. I realized I'm one minor version behind on the current image-automation-controller, so I went ahead and updated it to v0.23.2. It's working initially and will monitor to see if there's similar behavior as with the previous two minor versions.

**Comment by pjbgf** [comment]
@trenslow here's a release candidate version of image automation controller that further improves Git connection management:

`ghcr.io/fluxcd/image-automation-controller:rc-843074dd`

The issue you are experiencing is intermittent, and should be less likely to take place with the version above.

**Comment by trenslow** [comment]
So far since I updated to the latest image-automation-controller, I haven't lost connection to Bitbucket. I will continue to monitor it. If I lose connection I will try out the release candidate to see if there's any improvement/regression.

**Comment by trenslow** [comment]
Just wanted to report that with the latest release of the image automation controller (v0.23.4), I haven't experienced the issues reported above for around two weeks. I would consider this issue resolved. Thanks team!

**Comment by pjbgf** [comment]
That's awesome, thank you @trenslow for reporting back! :bow: :bow: :bow:
