### ISSUE TITLE
Flux is overwriting decrypted secrets on every reconciliation check

### ISSUE THREAD

**Issue by guillem-tldv** [fluxcd/flux2#2831]
### Describe the bug

Hello!

We are using SOPS with Flux to deploy encrypted secrets so we can use them with our ingress-nginx deployment. We started to experiment intermittent issues on the API with the clients receiving 401 errors every now and then.

After carefully reviewing the logs, we found out that the issues are coming from Flux overwriting an already decrypted secret just before starting the automatic reconciliation process. During this period of time (a minute or so, depending on the cluster usage) the secret contains the encrypted values so the applications detect the change and nothing works until it is decrypted by SOPS.

This is happening every `kustomization` interval time, which is causing serious issues in our AP
### Steps to reproduce

1. Start a cluster with flux and the nginx-ingress controller
2. Deploy a dummy application and an ingress with basic-auth authentication. Encrypt the secret containing the basic-auth authentication using sops.
3. Set a short interval on the kustomization so you can see the issue faster
4. Run a curl script loop against your ingress endpoint and see how responses move from 200 to 401 without doing any change on the flux monitored repository

### Expected behavior

* Flux does not put the encrypted values in the Kubernetes secret, only the decrypted ones.
* Flux does not update a resource if it hasn't changed

### OS / Distro

Ubuntu 22.04

### Flux version

v0.28.4

### Flux check

► checking prerequisites
✗ flux 0.28.4 <0.31.1 (new version is available, please upgrade)
✔ Kubernetes 1.23.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Are you sure the secret is not applied by more than one Flux Kustomization? We have many tests around SOPS and Secrets, I don't see how Flux would create the secret with the encrypted values unless it gets applied by a 2nd Kustomization that doesn't have decryption enabled.

**Comment by guillem-tldv** [comment]
Hello @stefanprodan! Thanks for your quick reply!
I have been reviewing the kustomizations, and all of them have the sops decryption enabled. I have also validated that the affected secrets are only deployed in one of them.

**Comment by guillem-tldv** [comment]
@stefanprodan I'm just running the flux upgrade to v0.31.1 to see if this issue was already fixed!

I am using `sops` with `age` encryption

To create the secrets, I'm just creating the plain text version of the secret (always using stringData to define the values) and then encrypting it with the following sops command:
```bash
# the key is defined in .sops.yaml
sops -e raw_secret.yaml > cluster/example/app/ingress-secret.yaml
```

The secrets are quite simple:
```yaml
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-ingress-auth
    namespace: monitoring
type: Opaque
stringData: 
    auth: |
        username:htpasswdhas...
        username2:htpasswdhas...
```

**Comment by stefanprodan** [comment]
We actually have a test to verify that sops secrets are not overwritten if nothing changed https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_decryptor_test.go#L231 I can't explain how this happens. We'll need a test repo to reproduce this with latest flux.

**Comment by j0sh3rs** [comment]
@guillem-tldv Can you elaborate on the fix you needed to do here? I'm in the same boat, where my encrypted secrets reencrypt all the time causing service restarts and outages.

Was it just as simple as moving your flux-system kustomizations somewhere else? Or running bootstrap against a folder with limited kustomizations in it? An example would be very helpful if you can!

**Comment by j0sh3rs** [comment]
Ah, nevermind! I solved it too. I had a directory inside my bootstrap directory (`./cluster`) which contained secrets (`./cluster/secrets`) and related kustomization.yaml files. Moving this out of the broader `./cluster` folder solved the problem, so it wasn't being picked up, as you say, by the flux-system kustomization.
