### ISSUE TITLE
flux bootstrap github error

### ISSUE THREAD

**Issue by haohello** [fluxcd/flux2#2834]
### Describe the bug

Not sure why it always shows this error when I run the `flux bootstrap github` command.

![image](https://user-images.githubusercontent.com/134774/173294129-49792f43-8e10-4c3c-b59c-f46cacc9372b.png)

![image](https://user-images.githubusercontent.com/134774/173294182-ea1be2c6-7f08-4d14-8bf4-d3528bf14a3b.png)

### Steps to reproduce

flux bootstrap github \
  --private=true \
  --owner=haohello \
  --repository=haohello/devtaoismflux \
  --personal \
  --path=bootstrap \
  --branch=main
► connecting to github.com
✗ failed to get Git repository "https://github.com/haohello/": validation error for OrgRepositoryRef.RepositoryName: field is required
-bash: --repository=haohello/devtaoismflux: No such file or directory

### Expected behavior

No errors

### OS / Distro

Ubuntu 22.04

### Flux version

v0.31.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.6+k3s1 >=1.20.6-0
► checking controllers
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raid-rohana-healthy** [comment]
Hi - could you please explain how did you get arround the issue. i'm facing the same issue my self 
Thx

**Comment by kingdonb** [comment]
The repository name `--repository=haohello/devtaoismflux` should have been `--repository=devtaoismflux`

The org name is already included separately as `--owner` 👍 @raid-rohana-healthy hope this helps
