### ISSUE TITLE
'Using Flux on Azure' documentation is out-of-date: Helm OCI registry compatibility

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#2842]
From https://github.com/fluxcd/flux2/discussions/2841:

<div type='discussions-op-text'>

<sup>Originally posted by **stevendick-swissre** June 15, 2022</sup>
The documentation states that Helm OCI registries are not supported, but isn't OCI support now available since Flux 0.31.0?</div>

---

The last sentence in https://fluxcd.io/docs/use-cases/azure/#helm-repositories-on-azure-container-registry needs a change, with a ref to e.g. the OCI HelmRepository example (https://fluxcd.io/docs/components/source/helmrepositories/#helm-oci-repository).

**Comment by kingdonb** [comment]
This seems to be covered by:

* https://github.com/fluxcd/website/pull/992
