### ISSUE TITLE
`flux bootstrap` Image pull failed because unauthorized (ghcr.io)

### ISSUE THREAD

**Issue by karunsiri** [fluxcd/flux2#2860]
### Describe the bug

I was running `flux bootstrap` onto a fresh cluster. Waited a bit and the bootstrap failed with `ImagePullBackOff` error showed up in the log

```
error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

So I try to pull the image locally (outside of cluster) and the same error occurs.

The image I was pulling is `ghcr.io/fluxcd/kustomize-controller:v0.25.0`
Ran via

```
docker pull ghcr.io/fluxcd/kustomize-controller:v0.25.0
```
 

### Steps to reproduce

Run `flux bootstrap git` as described in the doc.

### Expected behavior

The bootstrap command completes and install flux suite into `flux-system` namespace.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/1308495/175027909-91b1f48c-27ca-442e-9da6-70c9b845b118.png)

and
![image](https://user-images.githubusercontent.com/1308495/175027639-a66fac53-a8c1-43e3-b269-555222a12ade.png)

and 
![image](https://user-images.githubusercontent.com/1308495/175027810-85d1c608-6d07-4d16-ba6f-094825cac2d5.png)

### OS / Distro

Kubernetes 1.21 running on AMI Linux

### Flux version

v0.30.2

### Flux check

► checking prerequisites
✗ flux 0.30.2 <0.31.1 (new version is available, please upgrade)
✔ Kubernetes 1.21.12-eks-a64ea69 >=1.20.6-0
► checking controllers   <-- stuck at this step

### Container Registry provider

ghcr.io

### Additional context

I ran `flux bootstrap` successfully before. This just occurred today.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
GitHub is at present degraded, I expect things to work when all is green again. https://githubstatus.com

**Comment by karunsiri** [comment]
Oh I didn't know GH is having a problem. I'm going to close this now.

**Comment by stefanprodan** [comment]
We do push all Flux images to DockerHub as a backup, so you can do `flux bootstrap --registry=docker.io` if GHCR is down.
