### ISSUE TITLE
HelmRelease - non SemVer chart versions cannot be deployed

### ISSUE THREAD

**Issue by Layer8Err** [fluxcd/flux2#2883]
### Describe the bug

When deploying a HelmRelease that references a chart using a version like "1.2345.0067" the chart cannot be deployed and flux throws an error:

chart pull error: chart pull error: failed to get chart version for remote reference: unable to locate any tags in provided repository: oci://xxxxxxxxxxx.azurecr.io/chartnamegoeshere

flux logs show:
2022-06-29T21:00:48.603Z error HelmChart/namespace-chartnamegoeshere.flux-system - Reconciler error chart pull error: chart pull error: failed to get chart version for remote reference: unable to
locate any tags in provided repository: oci://xxxxxxxxxxx.azurecr.io/chartnamegoeshere

### Steps to reproduce

# Create error
1. Connect oci HelmRepository
2. Push a helm chart to the HelmRepository using an "improper" version like "1.2345.0067"
3. Create a fluxcd HelmRelease and specify the chart version to use (e.g. "1.2345.0067")
4. Wait for an error message

# Check error
1. push a helm chart to HelmRepository using a "proper" version like "1.2345.67"
2. Create or update the HelmRelease to specify the proper version "1.2345.56"
3. Wait for flux to find the tag and pull the chart

### Expected behavior

I would expect flux to be less opinionated about what version names can be used for a helm chart. I would expect versions 1.2345.0067 and 1.2345.67 to be handled as two separate versions, and I would expect both versions to be handled by flux.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.31.2

### Flux check

❯ flux check
► checking prerequisites
✗ flux 0.31.2 <0.31.3 (new version is available, please upgrade)
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.9
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Azure DevOps

### Container Registry provider

Azure

### Additional context

ACR manifest json:

[flux-semvar-err.json.txt](https://github.com/fluxcd/flux2/files/9014535/flux-semvar-err.json.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Flux only support semver for Helm charts, semver does not allow `0` prefixed numbers. Strict semver is a Helm requirement: https://helm.sh/docs/topics/charts/#charts-and-versioning we have no plans on diverging from this.

**Comment by Layer8Err** [comment]
Closing. SemVer2 is the way to go

**Comment by drewwells** [comment]
Why isn't this included in the documentation anywhere? https://fluxcd.io/flux/components/source/helmcharts/#version

**Comment by stefanprodan** [comment]
> Why isn't this included in the documentation anywhere? 

We assume that users read the Helm docs: https://helm.sh/docs/topics/charts/#charts-and-versioning

> Every chart must have a version number. A version must follow the [SemVer 2](https://semver.org/spec/v2.0.0.html) standard.
> non-SemVer names are explicitly disallowed by the system.

**Comment by drewwells** [comment]
The error above does not indicate SemVer2 is the source of the issue. There's no logs, no errors about semver2. The best I can tell is the tag does not exist in the oci repository. I can even pull the tag from our OCI repository using helm. I think this issue is vague enough to warrant work on the ticket.

`chart pull error: chart pull error: failed to get chart version for remote reference: unable to locate any tags in provided repository: oci://xxxxxxxxxxx.azurecr.io/chartnamegoeshere`

**Comment by stefanprodan** [comment]
@drewwells use an OCIRepository instead of HelmRepository, we ship this in Flux v2.3 and should improve the UX. See here how to use OCIRepository: https://fluxcd.io/blog/2024/05/flux-v2.3.0/#enhanced-helm-oci-support

**Comment by drewwells** [comment]
@stefanprodan  We're stuck on an older version b/c we're using k8s <1.28. Does OCIRepository support non-semver tags or does it emit error status/logs when a semver2 error is encountered?
