### ISSUE TITLE
Flux Logs Grafana Dashboard does not display any data

### ISSUE THREAD

**Issue by mv548t** [fluxcd/flux2#2904]
### Describe the bug

The Flux Logs Grafana dashboard does not display any data due to logs seemingly not being un-escaped correctly:
![image](https://user-images.githubusercontent.com/104774299/178729573-8b7654f1-9509-4de4-8075-4d5bcb7c2c36.png)

Detected fields include double quotes for are not detected at all (e.g. the "level" field):
![image](https://user-images.githubusercontent.com/104774299/178730000-50381662-3c2a-4c71-9528-6ec667a45215.png)
![image](https://user-images.githubusercontent.com/104774299/178730411-14d97aa9-6cd6-47b6-841d-11f124e6d21e.png)

As a result the configured filters do not work anymore.

### Steps to reproduce

1. Install the monitoring stack from this repository
2. Open the Flux Logs Grafana Dashboard

### Expected behavior

The dashboard displays data correctly.

### OS / Distro

Fedora 36

### Flux version

v0.31.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.10 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.9
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You may want to try the new setup here: https://github.com/fluxcd/flux2-monitoring-example
