### ISSUE TITLE
Helm Release doesn't respect the interval

### ISSUE THREAD

**Issue by jerem0808** [fluxcd/flux2#2936]
### Describe the bug

we have set the interval under spec.interval to be 30m. But the after the helm install is successful the helm upgrade starts after a couple of minutes. 
HelmRelease
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myRelease
spec:
  interval: 30m
  [...]
``` 
```
Normal  info    53m                helm-controller  Helm install has started 
Normal  info    51m                helm-controller  Helm install succeeded   
Normal  info    49m                helm-controller  Helm upgrade has started 
Normal  info    45m                helm-controller  Helm upgrade succeeded   
```

### Steps to reproduce

use the interval in the spec.interval in the helm release resource

### Expected behavior

I expect that the helm upgrade starts 30m after the successful helm installation event

### OS / Distro

N/A

### Flux version

v0.14.2

### Flux check

/ # flux check
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✔ Kubernetes 1.22.4 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr-docker-remote.artifactory.swisscom.com/fluxcd/helm-controller:v0.10.1
✔ kustomize-controller: deployment ready
► ghcr-docker-remote.artifactory.swisscom.com/fluxcd/kustomize-controller:v0.12.2
✔ notification-controller: deployment ready
► ghcr-docker-remote.artifactory.swisscom.com/fluxcd/notification-controller:v0.14.1
✔ source-controller: deployment ready
► ghcr-docker-remote.artifactory.swisscom.com/fluxcd/source-controller:v0.13.2
✔ all checks passed

### Git provider

Bitbucket

### Container Registry provider

Artifactory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Please share your `HelmRelease` resource so we have more context about the chart (source type) being used.

**Comment by jerem0808** [comment]
```---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eric-pc-controller
spec:
  releaseName: eric-pc-controller
  dependsOn:
    - name: eric-pc-kvdb-rd-crd
      namespace: eric-crd-ns
    - name: eric-sec-sip-tls-crd
      namespace: eric-crd-ns
    - name: eric-sec-certm-crd
      namespace: eric-crd-ns
  chart:
    spec:
      chart: eric-pc-controller
      version: '1.50.2-112' # Manually corrected this chart for the deployment eric-pc-mm-controller-supervisor
      sourceRef:
        kind: HelmRepository
        name: sema-5gc-artifactory
        namespace: flux-system
  interval: 30m
  timeout: 15m
  install:
    disableWait: true # prevent waiting, to force post-install hooks to execute
  #  remediation:
  #    retries: 0
      # remediateLastFailure: true
  upgrade:
    timeout: '10m0s'
    disableWait: true

  valuesFrom:
    - kind: ConfigMap
      name: eric-pcc-values
  values:
    global:
      registry:
        url: sema-5gc-docker-local.artifactory.swisscom.com/pcc
        pullSecret: regcred
      pullSecret: regcred
    imageCredentials:
      registry:
        url: sema-5gc-docker-local.artifactory.swisscom.com/pcc
        pullSecret: regcred
      pullSecret: regcred
```

**Comment by hiddeco** [comment]
Can not really explain the behavior you are seeing based on this, but what I do notice in your "flux check" output is that your helm-controller version is extremely old (`v0.10.1`) as `v0.22.2` is latest. Think your best bet would be to update the controller first, before further debugging this. As anything we discover for your current running version likely no longer applies to the current state of the helm-controller's code base.

**Comment by jerem0808** [comment]
Hi 
yes the problem is the Helm charts we are using doesn't comply with Kustomize v.4. That's the reason we stayed on this old release

**Comment by kingdonb** [comment]
In my experience most helm chart authors are very receptive to fixing these issues, as they want their charts to be inclusive of people using GitOps workflows to install them, and Flux is one of the primary well-known ways to accomplish this. Helm itself also acknowledges this issue, and would add it as a feature of `helm lint` if it was more straightforward to catch it.

* https://github.com/helm/helm/issues/4107

Is it a public chart that is maintained, and has anyone raised this issue with the maintainers? It would be much better not to remain on an old Flux version with CVEs and migrate to a maintained version instead, as any bugs you find in v0.14 Flux that persist in the current version, won't be able to be backported.

Fixes will only be able to be fixed in a new release going forward, (and that release is definitely going to be based on the new version of Kustomize v4+ as that's what the Flux team is maintaining Flux itself against today.)

**Comment by jerem0808** [comment]
Hi 
It's not a publicly available chart.
Thanks for the information about helm lint. 
I will then close the issue for the moment.
