### ISSUE TITLE
Enable `RecoverPanic` option on reconcilers

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#2952]
Controller-runtime [has a setting](https://github.com/kubernetes-sigs/controller-runtime/blob/e42a8c17945360813e64bde2c4ff742515b750ba/pkg/controller/controller.go#L58-L59) which can be set on a reconciler to ensure it recovers from panics instead of making the whole controller crash. This should be enabled on all reconcilers to improve continuity, which is especially useful for e.g. source-controller where a restart often means an erase of the cache.

- [x] source-controller
- [x] kustomize-controller
- [x] helm-controller
- [x] notification-controller
- [x] image-reflector-controller
- [x] image-automation-controller

**Comment by Santosh1176** [comment]
Hey @hiddeco can I work on this?
Just to clarify, all the reconcilers in the above listed controllers(repos) need to be enabled with RecoverPanic option?

**Comment by stefanprodan** [comment]
> Just to clarify, all the reconcilers in the above listed controllers(repos) need to be enabled with RecoverPanic option?

Yes

**Comment by Santosh1176** [comment]
Please /assign

**Comment by pjbgf** [comment]
@Santosh1176 thanks for working through all controllers to get this implemented. :bow:

**Comment by Santosh1176** [comment]
> @Santosh1176 thanks for working through all controllers to get this implemented. bow

Thank you!
