### ISSUE TITLE
Processes/Policies to Revisit Post-GA

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#2963]
Once Flux v2 becomes GA there are some processes and policies that may need to be reviewed, and documented, to align with the expectations that comes with the GA status.

Here are a few ideas:
- [x] Release cadence.
- [x] API Backwards compatibility.
- [x] Support Policy (e.g. back-porting of security fixes).

**Comment by stefanprodan** [comment]
Documented in https://fluxcd.io/flux/releases/
