### ISSUE TITLE
flux bootstrap fails to work with sops secrets

### ISSUE THREAD

**Issue by plockaby** [fluxcd/flux2#2980]
### Describe the bug

I went to upgrade my cluster using the normal `flux bootstrap`:

```
flux bootstrap git \                                                                                               
    --silent \
    --token-auth=true \
    --url=https://bitbucket.org/XXXX/XXXX.git \
    --components=source-controller,kustomize-controller,helm-controller,notification-controller \
    --components-extra=image-reflector-controller,image-automation-controller \
    --path=./configurations \
    --username=XXXX \
    --password=XXXX
► cloning branch "main" from Git repository "https://bitbucket.org/XXXX/XXXX.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("86819bc71e8f4aea157c21ab7a6a30db46d3432e")
► pushing component manifests to "https://bitbucket.org/XXXX/XXXX.git"
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✗ Secret/flux-system/flux-repository-api-token validation error: error decoding from json: illegal base64 data at input byte 3
```

The cluster is still upgraded correctly and the secrets work correctly with kustomize. It's just bootstrap that seems to have the problem.

### Steps to reproduce

1. Install flux and set up some sops secrets
2. Try to upgrade with `flux bootstrap`

### Expected behavior

I expect that flux bootstrap will correctly read the secrets and finish the upgrade successfully.

### OS / Distro

macOS 12

### Flux version

v0.32.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.11-eks-18ef993 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.24.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.20.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Why are SOPS secrets inside the `flux-system` overlay? Bootstrap can't work with such a configuration because the Flux CLI is not designed to decrypt secrets. I suggest you move the secrets out if the flux-system base.

**Comment by stefanprodan** [comment]
> Should I pull all of the non-gotk stuff out of there?

Yes, place them on the same level as the `flux-system` dir.

**Comment by plockaby** [comment]
Thanks! That's what I get for trying to be clever. Works now. 👍🏻
