### ISSUE TITLE
flux bootstrap assumes being run from C: drive on windows 

### ISSUE THREAD

**Issue by bravecobra** [fluxcd/flux2#2986]
### Describe the bug

On Windows, when flux is being run on a different drive, it can't create a relative path to the TEMP directory it works in.

### Steps to reproduce

```
cd D:
flux bootstrap github --branch=main --path=clusters/mycluster --owner=myuser --repository=myrepository --personal
Please enter your GitHub personal access token (PAT):
► connecting to github.com
► cloning branch "master" from Git repository "https://github.com/myuser/myrepository.git"
✔ cloned repository
► generating component manifests
✗ component manifest generation failed: Rel: can't make C:\Users\user\AppData\Local\Temp\flux-manifests-1705128869 relative to D:\
```

### Expected behavior

Being able to run in any directory on a windows system.

### OS / Distro

Windows 10

### Flux version

v0.32.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Duplicate of #1153 (I think)

**Comment by bravecobra** [comment]
Closed as duplicate
