### ISSUE TITLE
Gitrepository resource not found after storing the artifact for it

### ISSUE THREAD

**Issue by dbanetto** [fluxcd/flux2#3013]
### Describe the bug

The source controller has pulled the repository, fired an event for it then fails to find it right afterwards.

The logs below are setting the source controller to `debug` level.

```
{"level":"debug","ts":"2022-08-21T01:45:16.524Z","logger":"controller.gitrepository","msg":"git repository checked out","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"github-k8s","namespace":"flux-system","reconcileID":"457909d9-0af8-4c3a-95fd-0d42cc0249c7","url":"ssh://git@github.com/dbanetto/k8s.git","revision":"manifests/4f042144f4e3723f4b24bedb776bc512573ecadc"}
{"level":"info","ts":"2022-08-21T01:45:16.651Z","msg":"stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'","name":"github-k8s","namespace":"flux-system","reconciler kind":"GitRepository","reason":"NewArtifact","annotations":{"source.toolkit.fluxcd.io/checksum":"dafe36cf2f7c4254d088a0018c1081428b4de8472ebbb9d385ddeb21b51d131d","source.toolkit.fluxcd.io/revision":"manifests/4f042144f4e3723f4b24bedb776bc512573ecadc"}}
{"level":"debug","ts":"2022-08-21T01:45:16.652Z","logger":"events","msg":"Normal","object":{"kind":"GitRepository","namespace":"flux-system","name":"github-k8s","uid":"335152a8-6d64-4bf8-9c4a-dfd185d07415","apiVersion":"source.toolkit.fluxcd.io/v1beta2","resourceVersion":"565873"},"reason":"NewArtifact","message":"stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'"}
{"level":"info","ts":"2022-08-21T01:45:16.661Z","logger":"controller.gitrepository","msg":"stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"github-k8s","namespace":"flux-system","reconcileID":"457909d9-0af8-4c3a-95fd-0d42cc0249c7"}
{"level":"error","ts":"2022-08-21T01:45:16.677Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"github-k8s","namespace":"flux-system","error":"gitrepositories.source.toolkit.fluxcd.io \"github-k8s\" not found","errorCauses":[{"error":"gitrepositories.source.toolkit.fluxcd.io \"github-k8s\" not found","errorCauses":[{"error":"gitrepositories.source.toolkit.fluxcd.io \"github-k8s\" not found"},{"error":"gitrepositories.source.toolkit.fluxcd.io \"github-k8s\" not found"}]}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

### Steps to reproduce

1. Running a k3s cluster on version v1.24.3+k3s1 or v1.23.9+k3s1
2. Using the [install.yaml](https://github.com/fluxcd/flux2/releases/download/v0.32.0/install.yaml) for v0.32.0
3. Setup a private Gihub repo using deploy keys (read-write enabled)
4. Stored the keys in `source-credentials`
5. Setup using
```yaml
"apiVersion": "source.toolkit.fluxcd.io/v1beta2"
"kind": "GitRepository"
"metadata":
  "name": "github-k8s"
  "namespace": "flux-system"
"spec":
  "gitImplementation": "go-git"
  "interval": "60s"
  "ref":
    "branch": "manifests"
  "secretRef":
    "name": "source-credentials"
  "url": "ssh://git@github.com/dbanetto/k8s.git" # & without the .git
```

### Expected behavior

That the GitRepository would have successfully stored the artifact and the status of the resource would turn to `Ready`

### OS / Distro

Arch Linux & Debian (stable)

### Flux version

0.32.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.3+k3s1 >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.27.0
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.24.1
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.25.1
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.22.2
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.20.0
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Github

### Additional context

```
Name:         github-k8s
Namespace:    flux-system
Labels:       <none>
Annotations:  <none>
API Version:  source.toolkit.fluxcd.io/v1beta2
Kind:         GitRepository
Metadata:
  Creation Timestamp:  2022-08-21T00:54:15Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  2
  Managed Fields:
    API Version:  source.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:gitImplementation:
        f:interval:
        f:ref:
          .:
          f:branch:
        f:secretRef:
          .:
          f:name:
        f:timeout:
      f:status:
        .:
        f:observedGeneration:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-08-21T00:54:15Z
    API Version:  source.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
    Manager:      source-controller
    Operation:    Update
    Time:         2022-08-21T00:54:25Z
    API Version:  source.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:url:
    Manager:         kubectl-edit
    Operation:       Update
    Time:            2022-08-21T02:08:09Z
  Resource Version:  585626
  UID:               335152a8-6d64-4bf8-9c4a-dfd185d07415
Spec:
  Git Implementation:  go-git
  Interval:            60s
  Ref:
    Branch:  manifests
  Secret Ref:
    Name:   source-credentials
  Timeout:  60s
  URL:      ssh://git@github.com/dbanetto/k8s
Status:
  Observed Generation:  -1
Events:
  Type     Reason              Age                   From               Message
  ----     ------              ----                  ----               -------
  Normal   NewArtifact         61m (x10 over 74m)    source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
  Normal   NewArtifact         37m (x11 over 50m)    source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
  Normal   NewArtifact         24m (x6 over 25m)     source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
  Warning  GitOperationFailed  24m                   source-controller  failed to checkout and determine revision: unable to clone 'ssh://git@github.com/dbanetto/k8s.git': context canceled
  Warning  GitOperationFailed  24m                   source-controller  failed to checkout and determine revision: unable to clone 'ssh://git@github.com/dbanetto/k8s.git': error decoding upload-pack response: context canceled
  Normal   NewArtifact         10m (x11 over 24m)    source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
  Normal   NewArtifact         66s (x10 over 5m10s)  source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
  Normal   NewArtifact         20s (x6 over 59s)     source-controller  stored artifact for commit 'Rendered manifests from 65bf4ee106ca17934bb185b96a...'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darkowlzz** [comment]
Hi, thanks for reporting the issue. I tried reproducing this on the latest k3d (v1.23.8+k3s1) with defaults but it seems to be working fine.
Looking at your logs, it seems like when the source-controller tries to patch the GitRepository object status at the very end to reflect the new artifact on the object, it fails. My guess is that the error `"gitrepositories.source.toolkit.fluxcd.io \"github-k8s\" not found"` is from the kubernetes (controller-runtime) client when it fetches the latest version of the GitRepository object before patching it. But for some reason, it can't find the object and the patching fails, which results in the whole reconciliation to fail. The error results in a retry and it keeps on retrying.

Can you share more details about you cluster? Do you have any RBAC permission restrictions or is there anything running in the cluster that could restrict RBAC of other workloads? Maybe it's not really RBAC related as that would show RBAC related error message. The controller-runtime client usually has a cache of the object it watches. In this case, the client cache should have the GitRepository object in it because it's already fetched once at the beginning of the reconciliation. The behavior seems like the cache is somehow empty by the end of the reconciliation. In the past we had seen issues running flux in k3s due to the network policy and advise users to disable it, refer https://github.com/fluxcd/flux2/issues/294 . But this situation seems a little different.

It'd be very helpful to be able to reproduce this issue. Can you share more about your setup?

**Comment by kingdonb** [comment]
We had a suspicion for this report, that something is broadly wrong with the cluster or the cluster data store.

Is k3d using the normal etcd or is there a backing service? I am aware that k3s can use any backing service such as PostgreSQL or MySQL for the etcd API service that it hosts in the cluster. It is possible that some error back there is preventing writes from being completed on your cluster's control plane.

We judged this from the NewArtifact event which repeats. It would only be a new artifact the second time it was observed, if the event that we see was broadcast without being completely committed. So we looked at the fact you're using k3s and guessed it might be something like this. Is this maybe in the ballpark, or sparks other ideas of what might be the cause?

**Comment by dbanetto** [comment]
(Sorry for the delay, this is my hobby cluster & I do not get much time for it)

I do share your suspicion that this is wider reaching than Flux now & is more k3s/my own networking stack messing things up. 

I have had another attempt to debug this with the k3s `--debug` flag enabled there is also logs about timeouts to the kube api server and looking at other services that use the kstatus-style (e.g. `cert-manager`) have been failing in the same way. 

From your storage layer question: I did have some disks full, however cleaning them out did not help. There are no other errors (or at least that I can find) for the storage layer of kubeapi or k3s.

So given that I'll close off this issue & be off to learn more about k3s to resolve this. Thank you both @darkowlzz & @kingdonb for helping me with this.

**Comment by dbanetto** [comment]
I have finally figured out what happened.

The manifest files were going through Jsonnet at some point which had a `std.prune` on the manifests.

Since `std.prune` is recursive this ends up [removing this very necessary part of the CRDs](https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml#L738-L739) that links the status to the resource. Which then causes it all to fall over.
