### ISSUE TITLE
FluxCD tries to upgrade again on previous dry-run error 

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#3030]
### Describe the bug

I've tried to upgrade helmchart using FluxCD from one version to another. However new chart had issue in .yaml file (passed helm int)
When FluxCD tried to apply it it threw error:
```
helmrelease/prometheus.monitoring
Helm upgrade has started
revision
2022.9.0-DEV12

[08:37]
helmrelease/prometheus.monitoring
reconciliation failed: Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
 line 21: mapping key "[prometheus.io/scrape](http://prometheus.io/scrape)" already defined at line 18
revision
2022.9.0-DEV12
```
This is proper and I was able to find and fix issue. Problem here is that even we specified:
```
  install:
    disableWait: false
    remediation:
      retries: 0
  upgrade:
    disableWait: false
    preserveValues: false
    remediation:
      retries: 0
```
The FluxCD tries to do the same again and again. It works fine if upgrade fails after dry-run. However if it fails on dry-run it tries to upgrade again and again which ends up being spammed with error we already know until we really fix the chart.

Is the a way how to prevent retried upgrades by FluxCD when error happens during --dry-run phase (helm release not being marked as Failed)

### Steps to reproduce

1. Deploy chart properly
2. Prepare chart with error in some template which helm --dry-run would catch
3. Try to deploy this chart using FluxCD
4. FluxCD will fail and report it
5. FluxCD will try to deploy this chart over and over based on configured period

### Expected behavior

If FluxCD dry-run failed it should just stop doing any further upgrades

### OS / Distro

GKE

### Flux version

v0.32.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.2-gke.1900 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This was fixed some years ago, we now have rate limits in place for error alerts.
