### ISSUE TITLE
[New feat] Add dependency on CRD presence

### ISSUE THREAD

**Issue by Boojapho** [fluxcd/flux2#3042]
Use case:

We have around 25 Helm charts we deploy in our cluster with Flux using Helm Resources.  In about 80% of the dependencies we put into place, we are waiting on a CRD from another Helm Chart to be present.  For example, creating a `VirtualService` from Istio or a `ServiceMonitor` from Prometheus.  It can be time consuming to wait for these other applications to become healthy before starting the dependent application.  

Proposed feature:

Add the dependencies for the presence of a CRD.  The deployment would not begin until it detected the presence of the resource(s) that it was dependent on.  This would be in addition to the current dependencies.

Additional options:

- Make it generic to wait for the presence of anything (e.g. a secret/configmap)
- Wait on health if the resource has one (e.g. deployment, daemonset, stateful set)

**Comment by stefanprodan** [comment]
Are you using `dependsOn` in HelmReleases or in Flux Kustomizations?

**Comment by makkes** [comment]
For Kustomizations you can use health checks to wait for the presence of a certain resource: https://fluxcd.io/docs/components/kustomize/kustomization/#health-assessment

**Comment by Boojapho** [comment]
> Are you using `dependsOn` in HelmReleases or in Flux Kustomizations?

We use Helm Releases for everything.
