### ISSUE TITLE
metrics to show the current GitRepository

### ISSUE THREAD

**Issue by qudongfang** [fluxcd/flux2#3106]
### Describe the bug

People may flip `GitRepository::spec.ref.branch` to a `dev` branch to test/verify something and forget to revert back after.

It would be great if flux2 can export metrics to show the current `GitRepository::spec.ref.branch`.
and then we can alert(warn) if `GitRepository::spec.ref.branch` is not on `main/master/prod` branch.

### Steps to reproduce

N/A

### Expected behavior

N/A

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
The `GitRepository` manifest should ratehr itself live in Git and be protected by e.g. PRs or MRs.

**Comment by kingdonb** [comment]
I think we're suggesting that you would use a static analysis to prevent this configuration before it reaches the cluster. I don't know if that means we shouldn't expose this as a metric, there are a lot of different things we could expose as a metric.

This one is very specific to the GitRepository kind. The branch name is not something I think we would usually consider as a metric to export.

**Comment by stefanprodan** [comment]
I'm not for adding the ref to metrics, a ref in spec can be a semver rage or a commit SHA, if we reports the resolved ref then our metrics will suffer from high cardinality, each commit will result in a unique metric breaking our dashboards and all the current alerts people are using. Also having a different set of metrics for Git means we need to drop our generic metric and come up with dedicated ones for each custom resource kind and all their combined fields.

**Comment by dmichel1** [comment]
I was thinking this could be implemented as an additional metric and not added as a label to existing metrics because of all the reasons you listed (and I 100% agree).

kube and istio do this with the `kube_node_info` and `istio_build` metrics which have all the version information.

```
kube_node_info{container_runtime_version="containerd://1.4.13", internal_ip="10.3.67.211", job="kube-state-metrics", kernel_version="5.4.202+", kubelet_version="v1.21.14-gke.2100", kubeproxy_version="v1.21.14-gke.2100", node="gke-kube-1", os_image="Container-Optimized OS from Google", pod_cidr="10.3.73.0/26", provider_id="gce://kube-1", system_uuid="1faaf414-4b03-bc45"}
```


e.g. we could have something like `gotk_gitrepository_info`

**Comment by mtparet** [comment]
Why not adding the current sha1 (not the ref) so it is alway the same kind of value ?

**Comment by kingdonb** [comment]
Please refer to:

* https://github.com/fluxcd/flux2/issues/4128

This has been addressed, now you can create any metrics that you wish if the information is in the CRD spec or status, you can create a metric to report on it.

See also:

https://fluxcd.io/flux/monitoring/custom-metrics/

**Comment by mtparet** [comment]
Wonderful, will try it soon! Thanks !
