### ISSUE TITLE
Create a migration guide for Helm Operator users

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#311]
We should create a migration guide for current Helm Operator users, which clearly instructs them about breaking and semantic changes, and includes how to gradually migrate resources.

**Comment by seaneagan** [comment]
I think the gradual case (subset of HelmReleases at a time) will be a bit tricky, at least if you want zero downtime. You cannot delete a HelmRelease v1 without the Helm Operator deleting the Helm release (downtime) as far as I'm aware, without disabling the Helm Operator altogether. If you just leave Helm Operator and the HelmRelease v1 in place and add HelmRelease v2 and helm-controller, then both will be operating on the same Helm release concurrently, which doesn't seem good. One could re-enable (e.g. scale back up) the Helm Operator after migrating each subset to make this work though.

**Comment by hiddeco** [comment]
> One could re-enable (e.g. scale back up) the Helm Operator after migrating each subset to make this work though.

This was our advice the previous time(s) when we migrated API versions:

> Once the old operator is not running, it is safe to deploy the new operator, and start replacing the old resources with new resources. You can keep the old resources around during this process, since the new operator will ignore them.

https://docs.fluxcd.io/projects/helm-operator/en/stable/how-to/upgrade-to-ga/
