### ISSUE TITLE
--allow-insecure-http forces HTTPS in corresponding GitRepository

### ISSUE THREAD

**Issue by carlosonunez-vmw** [fluxcd/flux2#3116]
### Describe the bug

Given an HTTP-based "dumb" Git server
When I try to bootstrap it with `flux bootstrap git --allow-insecure-http --token-auth --password XXX --url http://git.server --path x/y/z`
Then the URL in the `GitRepository` source created for it starts with HTTPS anyway
  And `Kustomize` fails to reconcile (if HTTPS is not configured on the "dumb" Git server)

### Steps to reproduce

1. Install Flux as normal.
2. Provision a Kind cluster
3. Create a HTTP-based Git server with nginx as documented [here](https://thenewstack.io/how-to-set-up-the-http-git-server-for-private-projects/)
4. Run: `flux bootstrap git --allow-insecure-http=true --url=http://git.server/test/repo --username=git --password=supersecret --path="x/y/z" --token-auth`
5. `kubectl -n flux-system get gitrepository`; inspect the URL

### Expected behavior

The URL should start with `http`

### OS / Distro

N/A

### Flux version

v0.33.0

### Flux check

N/A

### Git provider

Plain `git`

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
I would like to try and verify this as a bug, there is one thing I'd like to check before I spend that time if you can let us know, does your git server silently upgrade the connection to an https URL?

Some HTTP servers will send back a redirect 30x code when you try to access it at an http URL, if yours does this it could explain why Flux is entering the https URL for an endpoint which is expected to be insecure.

(I will try to verify this on my own and come back if I don't hear from you)

**Comment by carlosonunez-vmw** [comment]
Hi! It does not have HSTS enabled. It's strictly HTTP.On Sep 21, 2022, at 07:20, Kingdon Barrett ***@***.***> wrote:﻿
I would like to try and verify this as a bug, there is one thing I'd like to check before I spend that time if you can let us know, does your git server silently upgrade the connection to an https URL?
Some HTTP servers will send back a redirect 30x code when you try to access it at an http URL, if yours does this it could explain why Flux is entering the https URL for an endpoint which is expected to be insecure.
(I will try to verify this on my own and come back if I don't hear from you)
