### ISSUE TITLE
ImageRepository not using serviceAccountName

### ISSUE THREAD

**Issue by pusherman** [fluxcd/flux2#3150]
### Describe the bug

When attempting to use the native AWS ECR auto-login feature, I set up my `ImageRepository` to have a `serviceAccountName` that has access to log in to ECR.  When I describe the ImageRepository after it has been created I get the following `NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors`.

```
% kubectl get imagerepository demo-repo -o yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  creationTimestamp: "2022-09-27T15:09:44Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: demo-repo
  namespace: flux-system
  resourceVersion: "390341123"
  uid: d620c6fb-ae55-455b-b261-81b628d4ddab
spec:
  image: 99999999999.dkr.ecr.us-east-1.amazonaws.com/services/demo-repo
  interval: 1m0s
  serviceAccountName: demo-repo-service-account
status:
  canonicalImageName: 99999999999.dkr.ecr.us-east-1.amazonaws.com/services/demo-repo
  conditions:
  - lastTransitionTime: "2022-09-27T15:09:44Z"
    message: "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor
      verbose messaging see aws.Config.CredentialsChainVerboseErrors"
    reason: ReconciliationFailed
    status: "False"
    type: Ready
  observedGeneration: 1
```

```
% kubectl get serviceaccount demo-repo-service-account -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::99999999999:role/demo-repo-role
  creationTimestamp: "2022-09-27T15:09:44Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: demo-repo-service-account
  namespace: flux-system
  resourceVersion: "390340560"
  uid: ee8e54e2-8a8e-48f6-9c4e-e88a7982e62d
secrets:
- name: demo-repo-service-account-token-6pmn9
```

### Steps to reproduce

1. Bootstrap flux with `image-reflector-controller,image-automation-controller`
2. Create service account to be used by the ImageRepository
3. In the ImageRepository yaml define a `serviceAccountName` using the role from step 2.
4. `kubectl get imagerepository demo-repo`

### Expected behavior

The ImageRepository should be able to access AWS services via the serviceAccount defined in the yaml.

### OS / Distro

N/A

### Flux version

v0.34.0

### Flux check

% flux check
► checking prerequisites
✔ Kubernetes 1.23.7-eks-4721010 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.24.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.25.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.28.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.26.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.29.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Container Registry provider

AWS ECR (Private Repos)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pusherman** [comment]
Thanks @stefanprodan - is there documentation on how to annotate the controller service account?  I did follow the guide the patch the Kustomization with the `--aws-autologin-for-ecr` but that's all I saw in the docs.

**Comment by stefanprodan** [comment]
Here is an example https://fluxcd.io/flux/cheatsheets/bootstrap/#iam-roles-for-service-account Please make sure to delete image-reflector-controller pod after the annotation has been synced on the service account. This is a limitation of EKS IRSA, the new pod will get an AWS token mounted as a volume.

**Comment by stefanprodan** [comment]
Also you’ll have to delete the `serviceAccountName` from spec, Flux will use the pod IAM role only if no static credentials are provided is spec either with `secretRef` or `serviceAccountName`.

**Comment by pusherman** [comment]
Thanks so much!  That seems to have worked.  Would it be helpful to update the docs [here](https://fluxcd.io/flux/guides/image-update/#using-native-aws-ecr-auto-login) to include the patch to add the role to the serviceAccount for the controller?  It looks like it's there for GCP but not AWS.  Is there any case where you would want to use ECR auto-login and not need the role patch?

If it makes sense to do so, I'm happy to put up a PR.

**Comment by stefanprodan** [comment]
> Is there any case where you would want to use ECR auto-login and not need the role patch?

Yes, in most cases you don’t need to annotate the SA because all Kubernetes nodes in EKS have read access to ECR and Flux knows how to fetch the credentials like kubelet.

**Comment by pusherman** [comment]
Got it. Thanks again for all the help!
