### ISSUE TITLE
Error: immutable field detected

### ISSUE THREAD

**Issue by joshuadmatthews** [fluxcd/flux2#3172]
### Describe the bug

I constantly see this error, it seems whenever a manifest is misconfigured in some way flux complains about immutable field detected. 

Even in scenarios where the manifest is valid, changing the manifest may cause the same issue. I have tried deleting the existing resource and still it complains. 

Can someone provide some solid explanation of what this error means and when it gets thrown? I am troubled by the lack of information on this.

### Steps to reproduce

Change a manifest, or check an invalid manifest into source control. One example I am seeing now is a deployment with no container causes this error. 

### Expected behavior

More detailed exception.

### OS / Distro

Linux

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrDayne** [comment]
I have same error.

**Comment by stefanprodan** [comment]
The error messages for invalid YAML have been improved in Flux v2.2, please upgrade
