### ISSUE TITLE
Panels in Grafana dashboards are wrong

### ISSUE THREAD

**Issue by nicklev** [fluxcd/flux2#3183]
### Describe the bug

Hi there!

I used the Grafana dashboards that are available in the repo (https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/monitoring-config/dashboards) and I believe they are wrong.

For example the Cluster Reconciliation Duration in Flux Cluster Stats dashboard is calculated like this:
  sum(rate(gotk_reconcile_duration_seconds_sum{namespace=\~"$operator_namespace",exported_namespace=\~"$namespace",kind=\~"Kustomization|HelmRelease"}[5m])) by (kind, name)
/  sum(rate(gotk_reconcile_duration_seconds_count{namespace=\~"$operator_namespace",exported_namespace=\~"$namespace",kind=\~"Kustomization|HelmRelease"}[5m])) by (kind, name)

I don't think it's necessary to divide by gotk_reconcile_duration_seconds_count because rate(gotk_reconcile_duration_seconds_sum) already calculates the average. Am I wrong?

Also Cluster Reconciliation Duration  is calculated differently in Flux Control Plane & Flux Cluster Stats.
In addition, the Helm Release Duration in Flux Control Plane is calculated differently from Cluster Reconciliation Duration.

All these lead to confusion.
Is there any documentation on how to use the metrics?

Kind regards,
Nick

### Steps to reproduce

Use Grafana dashboards in https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/monitoring-config/dashboards

### Expected behavior

Valid dashboards. I can't trust what I'm seeing. :P

### OS / Distro

Ubuntu 20.04

### Flux version

flux: v0.34.0

### Flux check

► checking prerequisites
✗ flux 0.34.0 <0.35.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.24.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.28.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.26.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.29.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/flux2-monitoring-example
