### ISSUE TITLE
Flux won't update itself during reconciliation

### ISSUE THREAD

**Issue by TheEdgeOfRage** [fluxcd/flux2#3186]
### Describe the bug

I have installed flux using the bootstrap command, from a Github repo with a PAT.
It has generated the flux-system directory with all the default gotk stuff, but I needed
to make some changes to the controller deployments (label selectors, CPU limit, reconciliation interval).

I'm applying the changes using kustomize `patchesStrategicMerge` and have kustomize apply them
on top of the existing flux definitions.
After making any of the changes and committing them to the main branch, the git source controller
finds the change and the kustomize controller allegedly applies that commit, but the changes 
aren't actually applied to the cluster.

If I rerun the bootstrap command it applies the previously unapplied changes to the cluster, but I want
to be able to apply changes by just committing. Is that possible?

```
$ git rev-parse HEAD
9b2cec010de468275d5149997051adbb1f62e6b9

$ flux get kustomization flux-system
NAME       	REVISION      	SUSPENDED	READY	MESSAGE
flux-system	master/9b2cec0	False    	True 	Applied revision: master/9b2cec0

$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ kubectl diff -k .
```
```diff
diff -u -N /tmp/LIVE-1499849567/apps.v1.Deployment.flux-system.image-automation-controller /tmp/MERGED-401395484/apps.v1.Deployment.flux-system.image-automation-controller
--- /tmp/LIVE-1499849567/apps.v1.Deployment.flux-system.image-automation-controller	2022-10-09 15:35:40.737898975 +0200
+++ /tmp/MERGED-401395484/apps.v1.Deployment.flux-system.image-automation-controller	2022-10-09 15:35:40.741232306 +0200
@@ -4,7 +4,7 @@
   annotations:
     deployment.kubernetes.io/revision: "2"
   creationTimestamp: "2022-05-06T10:22:35Z"
-  generation: 2
+  generation: 3
   labels:
     app.kubernetes.io/instance: flux-system
     app.kubernetes.io/part-of: flux
@@ -78,7 +78,7 @@
           timeoutSeconds: 1
         resources:
           limits:
-            cpu: "1"
+            cpu: "2"
             memory: 1Gi
           requests:
             cpu: 100m
diff -u -N /tmp/LIVE-1499849567/kustomize.toolkit.fluxcd.io.v1beta2.Kustomization.flux-system.flux-system /tmp/MERGED-401395484/kustomize.toolkit.fluxcd.io.v1beta2.Kustomization.flux-system.flux-system
--- /tmp/LIVE-1499849567/kustomize.toolkit.fluxcd.io.v1beta2.Kustomization.flux-system.flux-system	2022-10-09 15:35:41.324565371 +0200
+++ /tmp/MERGED-401395484/kustomize.toolkit.fluxcd.io.v1beta2.Kustomization.flux-system.flux-system	2022-10-09 15:35:41.327898702 +0200
@@ -6,14 +6,16 @@
   creationTimestamp: "2022-05-06T10:22:35Z"
   finalizers:
   - finalizers.fluxcd.io
-  generation: 1
+  generation: 2
   name: flux-system
   namespace: flux-system
   resourceVersion: "516128965"
   uid: 39098480-af51-414d-98e1-b5e2156d5c1e
 spec:
+  decryption:
+    provider: sops
   force: false
-  interval: 10m0s
+  interval: 1m0s
   path: ./flux/clusters/dev
   prune: true
   sourceRef:
```

### Steps to reproduce

1. Install flux using the flux CLI bootstrap command and a github token
2. Create a patch to change something in one of the controller deployments (in my case, CPU limit for the image-automation-controller)
3. Add the patch to the flux-system `kustomization.yaml`
4. Commit back to the main branch and push to git
5. The flux source and kustomize controllers show the latest commit in the "applied revision" message, but the changes are not present in the cluster

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml # untouched by me
- gotk-sync.yaml # untouched by me
patchesStrategicMerge:
- ./gotk-components-patch.yaml
- ./gotk-sync-patch.yaml
```

gotk-components-patch.yaml:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 2
            memory: 1Gi
```
gotk-sync-patch.yaml:
```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  decryption:
    provider: sops
```

### Expected behavior

I'd expect flux to apply changes to itself when they are present in the flux manifests.

### OS / Distro

CLI is on Archlinux, but my problem is not with the CLI

### Flux version

v0.35.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.10-eks-15b7512 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.24.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.25.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.28.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.26.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.29.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see the docs here: https://fluxcd.io/flux/installation/configuration/boostrap-customization/
