### ISSUE TITLE
Review use of `accessFrom` across controllers

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3191]
On the run up to GA we need to check whether we want to include the `accessFrom` field, given that its being used in the controllers below and its RFC (https://github.com/fluxcd/flux2/pull/2092) is yet to be made implementable.

- https://github.com/fluxcd/image-reflector-controller/blob/f485eb1fb3c09245deb20f5646ceb946b788f585/api/v1beta1/imagerepository_types.go#L87
- https://github.com/fluxcd/source-controller/blob/70d9f126f9436ec032904ead5bbf79a168562e6d/api/v1beta1/bucket_types.go#L82
- https://github.com/fluxcd/source-controller/blob/70d9f126f9436ec032904ead5bbf79a168562e6d/api/v1beta1/helmrepository_types.go#L74
- https://github.com/fluxcd/source-controller/blob/70d9f126f9436ec032904ead5bbf79a168562e6d/api/v1beta1/gitrepository_types.go#L98

**Comment by stefanprodan** [comment]
The RFC #2092 was dropped and we've removed `accessFrom` from the v1 source APIs. I think we can close this umbrella issue for the same reason mentioned here: https://github.com/fluxcd/flux2/issues/2592#issuecomment-1603071130 We'll review each API before it reaches GA and we'll track it separately.
