### ISSUE TITLE
Implement `flux diff artifact`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3194]
To avoid pushing artifacts with the same content to the registry, we could add a diff command that compares the locally build tarball checksum with the upstream tarball included in the first layer of the OCI artifact.

Example:

```sh
flux diff artifact oci://ghcr.io/stefanprodan/manifests:podinfo:6.2.0 --path=./kustomize
``` 

The above command will return exit code 0 if no diff was detected or exit code 1 if the contents differs.

**Comment by developer-guy** [comment]
I'm willing to do this, and it looks yummy!
