### ISSUE TITLE
Not parsing URL ("ssh://git@git.sr.ht:~sseneca/sserver") correctly

### ISSUE THREAD

**Issue by sseneca** [fluxcd/flux2#3245]
### Describe the bug

I'm trying to switch from using GitHub to host my manifests to https://git.sr.ht.

https://git.sr.ht has its usernames like "~sseneca", so the URL is `ssh://git@git.sr.ht:~sseneca/sserver`

But trying to run this gives me `✗ parse "ssh://git@git.sr.ht:~sseneca/sserver": invalid port ":~sseneca" after host`

### Steps to reproduce

1. Try to bootstrap Flux to point it to new Git URL: `flux bootstrap git --url="ssh://git@git.sr.ht:~sseneca/sserver" --branch=main --path=clusters/sserver --ssh-key-algorithm ed25519`

### Expected behavior

It should parse the URL correctly and update the remote successfully.

### OS / Distro

Linux

### Flux version

flux: v0.35.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.6+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.30.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Sourcehut

### Container Registry provider

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
This is not due to the `~` in the URL, but rather due to you attempting to use the SCP-like format which is supported by Flux. See [this note](https://fluxcd.io/flux/components/source/gitrepositories/#url) in our documentation.

I would expect `ssh://git@git.sr.ht/~sseneca/sserver` to work without issues.
