### ISSUE TITLE
Flux diff RBAC permissions

### ISSUE THREAD

**Issue by ericjohansson89** [fluxcd/flux2#3250]
### Describe the bug

We are in the process of writing a pipeline job that intends to utilize the `diff kustomization` part of the CLI.

The intended flow for this pipeline job is that we have a monorepo that acts as source for multiple clusters containing a multitude of application infrastructure such as routing, metrics collection and more. When we make a merge request towards a branch that clusters pull source from we want to run a pipeline job in each cluster through gitlabs kubernetes runners. Meaning we would spawn a job in each cluster that then would run a diff inside its cluster and report back to the merge request. 

The runners in the clusters are shared in the organisations so the RBAC permissions for these should be least privileged. The idea was that give these runners enough privilege to run diffs but when trying this out we saw that they actually runs patch command on all the resources (with dry-run command). This puts a big problem that the shared runners would have patch privileges which is far from optimal.

The alternative solution is to setup a kubernetes token with higher privileges and feed that into the kubernetes job. The issue with this approach is that since we want to run it on non-protected branches a developer with malicious intent could create a job to run on their specific branch that utilizes this token.

It would be much easier if there was only a "view" requirement on the diff tool, meaning something like rbac permissions of get/list/watch.

### Steps to reproduce

1. Install Flux
2. Setup GitRepository + Kustomization part deploying some resource, namespace as an example
3. Make a local edit to the namespace parameters
4. Setup a ServiceAccount with get/list/watch capabilities
6. Use ServiceAccount token when running flux diff kustomization command
7. See issues in output about patching (with dry-run flag)

### Expected behavior

I would like to run diffs without needing patch permissions inside the clusters

### Screenshots and recordings

![Screenshot 2022-10-25 at 14 03 33](https://user-images.githubusercontent.com/25033858/197769145-85296caf-851c-47c3-b3e6-fb3bc7af5057.png)

### OS / Distro

Linux

### Flux version

0.33.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.14-eks-6d3986b >=1.20.6-0
► checking controllers
► checking crds
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> I would like to run diffs without needing patch permissions inside the clusters

Kubernetes does not support this, the same permissions are needed for a dry-run as for the actual apply.

**Comment by ericjohansson89** [comment]
@stefanprodan So what do your recommend way of doing in this scenario? How are developers intended to use the diff tool? You would like to run it on a merge request so that you understand what is to be changed when merging into the main branch?

**Comment by stefanprodan** [comment]
The diff tool is meant for local envs, where you run Kubernetes Kind or you have some remote dev cluster. Given that Kubernetes doesn't have dedicated RBAC for dry-runs, the diff tool must be used with care, running it from CI onto production comes with major security risks.

**Comment by ericjohansson89** [comment]
That is unfortunate, we would really like it to be as a part in our pipeline chain giving feedback to the developers on what the outcome of the changes would be if it was to be merged.

**Comment by ericjohansson89** [comment]
I would also argue that it then goes a bit against what you describe the cli to be on your documentation

https://fluxcd.io/flux/cmd/flux/#flux
```
Command line utility for assembling Kubernetes CD pipelines
```
