### ISSUE TITLE
missing year / author information in license

### ISSUE THREAD

**Issue by dmccaffery** [fluxcd/flux2#3275]
https://github.com/fluxcd/flux2/blob/7ee90a34e57e741b2c658b983f9e76ee490db4ee/LICENSE#L189

**Comment by stefanprodan** [comment]
Same with https://github.com/kubernetes/kubernetes/blob/master/LICENSE#L190

**Comment by dmccaffery** [comment]
... interesting. :-D

**Comment by dmccaffery** [comment]
... seems you are supposed to: https://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by dmccaffery** [comment]
Maybe I'm wrong -- I'm not a legal expert, but got the same response from:

https://github.com/google/go-containerregistry/issues/1484#issuecomment-1299138966

**Comment by stefanprodan** [comment]
We specify the year and copyright owner on each code file https://github.com/fluxcd/flux2/blob/main/cmd/flux/main.go#L1-L15 so I don’t think we need to change the main license file.
