### ISSUE TITLE
✗ no deployments found in flux-system namespace,fluxcd was installed by kubevela

### ISSUE THREAD

**Issue by 13567436138** [fluxcd/flux2#3291]
### Describe the bug

✗ no deployments found in flux-system namespace

### Steps to reproduce

```
[root@node01 ~]# flux version
✗ no deployments found in flux-system namespace
[root@node01 ~]# kubectl get deploy -n flux-system 
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
fluxcd-helm-controller               1/1     1            1           13d
fluxcd-image-automation-controller   1/1     1            1           13d
fluxcd-image-reflector-controller    1/1     1            1           13d
fluxcd-kustomize-controller          1/1     1            1           13d
fluxcd-source-controller             1/1     1            1           13d
```

### Expected behavior

has deployment

### OS / Distro

centos 8

### Flux version

v0.22.0

### Flux check

[root@node01 ~]# flux check
► checking prerequisites
✔ Kubernetes 1.21.0 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Looks like Kubevela doesn't uses the official manifests to deploy Flux. For the Flux CLI to work properly we expect vendors to use the upstream manifests.
