### ISSUE TITLE
Flux monitoring stack stack failing to reconcile since v41.x chart upgrade

### ISSUE THREAD

**Issue by jonwilliams84** [fluxcd/flux2#3304]
### Describe the bug

Flux monitoring stack stack failing to reconcile

### Steps to reproduce

Installed flux monitoring stack based on v35.x of chart. This has been updated today to 41.x of the chart.

Reconciliation is now failing:

### Expected behavior

Release should reconcile.

### OS / Distro

Ubuntu 20.05

### Flux version

V0.36.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.11+k3s2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.26.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.22.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Gitlab

### Container Registry provider

DockerHub

### Additional context

`$ flux reconcile helmrelease kube-prometheus-stack -n monitoring
► annotating HelmRelease kube-prometheus-stack in monitoring namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✗ HelmRelease reconciliation failed: upgrade retries exhausted

$ flux suspend helmrelease kube-prometheus-stack -n monitoring
► suspending helmrelease kube-prometheus-stack in monitoring namespace
✔ helmrelease suspended

$ flux resume helmrelease kube-prometheus-stack -n monitoring
► resuming helmrelease kube-prometheus-stack in monitoring namespace
✔ helmrelease resumed
◎ waiting for HelmRelease reconciliation
✗ Helm upgrade failed: cannot patch "kube-prometheus-stack-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "kube-prometheus-stack-prometheus-node-exporter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kube-prometheus-stack", "app.kubernetes.io/name":"prometheus-node-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
It's a major version bump, so the Helm chart comes with breaking changes. I guess you need to delete that statefulset.

**Comment by jonwilliams84** [comment]
Deleting the daemonset for node exporter has allowed reconciliation.
