### ISSUE TITLE
flux diff kustomization - failed to decode Kubernetes YAML from /etc/netplan/50-cloud-init.yaml: missing Resource metadata <nil>  <nil>

### ISSUE THREAD

**Issue by joshuadmatthews** [fluxcd/flux2#3311]
### Describe the bug

I am attempting to figure out why flux is reconciling nonstop on my cluster

I am executing the command 

` flux diff kustomization mykustomization --path . /home/mymanifests`

and the result is 

`✗ failed to generate kustomization.yaml: failed to decode Kubernetes YAML from /etc/netplan/50-cloud-init.yaml: missing Resource metadata <nil> <nil>
`

Not sure where to go from here. Flux check returns all good. 

### Steps to reproduce

clone manifests locally
do flux diff
get error

### Expected behavior

no error

### OS / Distro

Ubuntu

### Flux version

flux: v0.36.0

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.24.6 >=1.20.6-0
► checking controllers
✔ fluxconfig-agent: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-agent:1.6.1
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.6.1
✔ fluxconfig-controller: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-controller:1.6.1
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.6.1
✔ helm-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/helm-controller:v0.25.0
✔ image-automation-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/image-automation-controller:v0.26.0
✔ image-reflector-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/image-reflector-controller:v0.22.0
✔ kustomize-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/kustomize-controller:v0.29.0
✔ notification-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/notification-controller:v0.27.0
✔ source-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/source-controller:v0.30.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ fluxconfigs.clusterconfig.azure.com/v1alpha1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Github enterprise

### Container Registry provider

ACR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This has a type `--path . /home/mymanifests` should be `--path ./home/mymanifests`

**Comment by joshuadmatthews** [comment]
Thanks! Fixed the typo and found my path was wrong. Fixed and got a result.
