### ISSUE TITLE
Changing Kustomization name will deleted all objects

### ISSUE THREAD

**Issue by siwyroot** [fluxcd/flux2#3316]
### Describe the bug

When user changes name of already created Kustomization flux will delete object and recreate it, it some conditions it will also delete all objects related to that Kustomization which can sometimes 'lock' reconciliation because of finalizers.

### Steps to reproduce

1. Create Kustomization and wait for it to create all objects
2. Change name of Kustomization and push new change
3. Watch as your world burns for a second or two

### Expected behavior

Changing name of Kustomization should not be disruptive operation

### OS / Distro

N/A

### Flux version

0.36.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This is the expected behaviour, it's like renaming any other Kubernetes object, the API deletes and recreates it. Before renaming set `prune: false` do disable the GC.

**Comment by stefanprodan** [comment]
@siwyroot maybe in here https://fluxcd.io/flux/faq/#how-can-i-safely-move-resources-from-one-dir-to-another "How can I safely rename Flux Kustomizations?"
