### ISSUE TITLE
flux bootstrap behind a proxy fails with "failed to fetch image reference"

### ISSUE THREAD

**Issue by florath** [fluxcd/flux2#3327]
### Describe the bug

flux bootstrap fails behind a proxy.

Error log:

```
► connecting to https://example.com
► cloning branch "main" from Git repository "https://example.com/my_owner/my_repo.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✗ Deployment/flux-system/helm-controller dry-run failed, error: admission webhook "mutate.kyverno.svc-fail" denied the request: 

policy Deployment/flux-system/helm-controller for resource error: 

verify-flux-images:
  autogen-verify-cosign-signature: 'failed to update digest: failed to fetch image
    reference: ghcr.io/fluxcd/helm-controller:v0.26.0, error: Get "https://ghcr.io/v2/":
    dial tcp: lookup ghcr.io on 169.169.169.169:53: server misbehaving'

```

### Steps to reproduce

1. Install flux on a server behind a proxy
2. run
    `flux bootstrap gitlab --hostname example.com --owner my_owner --repository my_repo --cluster-domain my.domain --context="kubernetes-admin@my.domain" --branch=main --path=clusters/staging --token-auth`

### Expected behavior

Ready to use flux installation.

### Screenshots and recordings

http(s)_proxy and no_proxy set: upper and lower case.

For me it looks that the repo can be reached using the proxy (which is the only way) - but the 'verify-flux-images' is not using the proxy.

### OS / Distro

Ubuntu 22.04

### Flux version

0.36.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.3 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✗ check failed

### Git provider

GitHub Enterprise

### Additional context

I'm using https://github.com/fluxcd/flux2-multi-tenancy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patinocode** [comment]
Hi @florath,
I suspect your issue is related to proxy misconfiguration, not FluxCD.

Breaking down the error you're seeing `dial tcp: lookup ghcr.io on 169.169.169.169:53: server misbehaving`

`lookup ghcr.io` - attempting a DNS lookup for `ghcr.io`
`on 169.169.169.169:53` - DNS server `169.169.169.169` DNS port `53`
`server misbehaving` - Probably from an unexpected response from server `169.169.169.169`

You can probably use the `nslookup` command to confirm the issue.
[This](https://stackoverflow.com/questions/53475168/docker-for-windows-server-misbehaving-when-trying-to-pull) SO post reports a similar config & error.

**Comment by florath** [comment]
I'm pretty sure that this is not a configuration problem with the proxy (at least not with the ways as described in the documentation :wink: ).

Please see the logs:

```
► connecting to https://example.com
► cloning branch "main" from Git repository "https://example.com/my_owner/my_repo.git"

<== At this point flux successfully uses the the proxy. There is no other way of reaching the repository

✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✗ Deployment/flux-system/helm-controller dry-run failed, error: admission webhook "mutate.kyverno.svc-fail" denied the request: 

<== At this point flux does *not* use the proxy.

```

Therefore I'd exclude a general problem with the proxy configuration. I'm using this kubernetes cluster for some time now and downloaded already many images either from the Internet or a private docker registry using the proxy.

My idea is that the module which is responsible for the "verify-flux-images" step does not pick up the current proxy configuration or uses a different which is not documented.

**Comment by stefanprodan** [comment]
This is not related to Flux, please remove Kyverno or reach out to the Kyverno team on how to configure proxies.
