### ISSUE TITLE
Internal error occurred: failed calling webhook "validate.kyverno.svc-fail"

### ISSUE THREAD

**Issue by florath** [fluxcd/flux2#3335]
### Describe the bug

Calling `flux bootstrap` leads to the following error:

```
► connecting to https://example.com
► cloning branch "main" from Git repository "https://example.com/my_owner/my_repo.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✗ GitRepository/flux-system/flux-system dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "validate.kyverno.svc-fail": failed to call webhook: Post "https://kyverno-svc.kyverno.svc:443/validate/fail?timeout=10s": service "kyverno-svc" not found
```

### Steps to reproduce

Install and uninstall flux a couple of times.

Then run:

`flux bootstrap gitlab --hostname example.com --owner my_owner --repository my_repo --cluster-domain my.domain --context="kubernetes-admin@my.domain" --branch=main --path=clusters/staging --token-auth
`

### Expected behavior

flux is bootstraped and ready to run.

### OS / Distro

Ubuntu 22.04

### Flux version

0.36.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.3 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✗ check failed

### Git provider

gitlab enterprise

### Additional context

I run some 'flux bootstrap' and 'flux uninstall' to find some problems in the config.

Now I ended up in a state which I passed already a couple of times.

Any hint what causes this `Internal error` and how to handle it are highly welcome.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The error has nothing to do with Flux, Kyverno is broken on your cluster as the log says `service "kyverno-svc" not found`, you may want to exclude the `flux-system` namespace from Kyverno policies.
