### ISSUE TITLE
Update GH Actions Helm promotion example

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#3338]
On the Flux website, there is a use-case example on doing Helm chart promotions using GitHub actions. [This example](https://fluxcd.io/flux/use-cases/gh-actions-helm-promotion/#define-the-promotion-github-workflow) depends on the assumption that the `Revision` contains a 1:1 copy of the version as reported by the chart metadata.

For (verified) Helm charts originating from an OCI registry, this is expected to change based on [RFC-0005](https://github.com/fluxcd/flux2/tree/main/rfcs/0005-artifact-revision-and-digest). Before this is released, we should update the example to only look at the left side of the `VERSION=${{ github.event.client_payload.metadata.revision }}` string, after splitting it by `@`.

**Comment by stefanprodan** [comment]
The `metadata.revision` reported by helm-controller comes from the Helm chart metadata which is strict semver and does't contain the digest appended with `@`.
