### ISSUE TITLE
Improve Flux Fuzz tests reliability

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3346]
Recently a [change upstream](https://github.com/google/oss-fuzz/pull/8937/files) have broken all builds across fluxcd. 
This is broken both at upstream build time (for our project) as well as locally within our projects. Here's the output error:
```
+ cd /tmp/oss_fuzz-9iS27e/go-118-fuzz-build
+ go build -o /root/go/bin/go-118-fuzz-build
+ cd addimport
/root/go/src/github.com/fluxcd/image-reflector-controller/tests/fuzz/oss_fuzz_build.sh: line 37: cd: addimport: No such file or directory
+ cleanup
+ rm -rf /tmp/oss_fuzz-9iS27e
ERROR:root:Building fuzzers failed.
```
This is due to [changes](https://github.com/AdamKorcz/go-118-fuzz-build/pull/9) on https://github.com/AdamKorcz/go-118-fuzz-build/ which were not backwards compatible. This package is the basis of all Go support on oss-fuzz, and therefore any changes to it will affect us.

For improved reliability we shall remove any unsupported features upstream and trying to rely solely on their setup to run smoke tests. 
We will still suffer from issues when upstream changes are introduced, but this should decrease their impact.

We may also have to change the way we approach fuzz testing. Once of the key changes being to avoid sharing code amongst fuzz and non-fuzz tests. Although this is supported by Go fuzz, this isn't working well with oss-fuzz, and attempts to improve upstream support are [currently stuck](https://github.com/google/oss-fuzz/pull/8285).

#### Outstanding Tasks 

- [x] Upstream changes
  - [x] Add support for linking [additional libs](https://github.com/fluxcd/image-automation-controller/blob/43b99c65b6716dcb760ba8e0baede8b2bdc492f2/tests/fuzz/compile_native_go_fuzzer#L72) whilst compiling. (https://github.com/google/oss-fuzz/pull/9063)
  - [x] Create auto discovery script within fluxcd project, so that `oss_fuzz_build.sh` does not need to be duplicated across all flux projects. (https://github.com/google/oss-fuzz/pull/9064)
- [ ] CI
  - [ ] Update `make fuzz-smoketest` to be based on Upstream base image
  - [ ] Use `google/oss-fuzz/infra/cifuzz/actions/build_fuzzers` and `google/oss-fuzz/infra/cifuzz/actions/run_fuzzers` on cifuzz
- [x] pkg
  - [x] https://github.com/fluxcd/pkg/pull/415
  - [x] https://github.com/fluxcd/pkg/pull/416
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/pkg/pull/436)
- [x] helm-controller
  - [x] https://github.com/fluxcd/helm-controller/pull/565
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/helm-controller/pull/578)
- [x] kustomize-controller
  - [x] https://github.com/fluxcd/kustomize-controller/pull/771
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/kustomize-controller/pull/777)
- [x] source-controller
  - [x] https://github.com/fluxcd/source-controller/pull/965
  - [x] https://github.com/fluxcd/source-controller/pull/968
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/source-controller/pull/977/commits/3a6d2a1f16e83e53e1a1f64ef086689a991d0370)
- [x] notification-controller
  - [x] https://github.com/fluxcd/notification-controller/pull/446
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/notification-controller/pull/454)
- [x] image-automation-controller
  - [x] https://github.com/fluxcd/image-automation-controller/pull/462
  - [x] https://github.com/fluxcd/image-automation-controller/pull/464
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/image-automation-controller/pull/468/commits/a18b51b479a768e0df25520d764dc64dcd839fd5)
- [x] image-reflector-controller
  - [x] https://github.com/fluxcd/image-reflector-controller/pull/329
  - [x] Rely on upstream discovery/build scripts (https://github.com/fluxcd/image-reflector-controller/pull/330)

**Comment by AdamKorcz** [comment]
Sorry for missing this. I checked all Go projects in OSS-Fuzz for breakages but must have missed Flux since the build was broken since September: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#fluxcd, or is the OSS-Fuzz build status reporting incorrect build status?

If there is anything I can help with, please let me know.

**Comment by pjbgf** [comment]
@AdamKorcz Don't worry about it. Due to things like libgit2, Flux had a lot of custom code to run its fuzzers and at times it got out of sync with upstream. For example, our CI checks are based on local Dockerfiles. With the changes on this issue we should make our use of oss-fuzz more streamlined and completely aligned with oss-fuzz.

I have been working through some of the upstream build failures, but most recently our internal CI builds also broke. Once we are done aligning the fuzz implementation all of them should be fixed.

**Comment by stefanprodan** [comment]
@pjbgf can this be closed?

**Comment by pjbgf** [comment]
Yes, closing it now.
