### ISSUE TITLE
reconciler kind "Bucket": panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bingws** [fluxcd/flux2#3373]
### Describe the bug

after i upgrade the config : setting spec.<action>.disableWait.
the pod  flux-source-controller-xxx  restart. then get the following error:
![image](https://user-images.githubusercontent.com/10806595/205565429-8475eecb-39f5-4ddc-bff3-bf58247dc54d.png)

### Steps to reproduce

after  setting spec.<action>.disableWait.  to true

then get the error

### Expected behavior

get invalid memory address or nil pointer dereference

### OS / Distro

linux

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
There is no `flux-source-controller` in the official distribution of Flux. Please see the docs on how to install Flux https://fluxcd.io/flux/installation/
