### ISSUE TITLE
Kustomization .spec.dependsOn not respected when controller restarts

### ISSUE THREAD

**Issue by vinkiel** [fluxcd/flux2#3390]
### Describe the bug

When using Kustomization `.spec.dependsOn` and kustomization controller is restarted , flux ignores dependency and run all of them parallel instead of predefined order.

### Steps to reproduce

You can use tutorial https://fluxcd.io/flux/use-cases/running-jobs/ 
Then restart kustomization controller ex using 
`kubectl rollout restart deployment kustomize-controller  -n flux-system`
All artifacts are applied the same time regardless of dependsOn order.

### Expected behavior

Kustomization `.spec.dependsOn` should be respected also during controller startup.

### OS / Distro

Mac OS 12.1 (21C52)

### Flux version

0.37.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> Kustomization .spec.dependsOn should be respected also during controller startup.

It does respects it, but since all dependants are ready it runs them in parallel.
