### ISSUE TITLE
`flux diff` does not work with `.yml` extension.

### ISSUE THREAD

**Issue by reitermarkus** [fluxcd/flux2#3391]
### Describe the bug

`flux diff` does not look for a `kustomization.yml`, only for a `kustomization.yaml`.

### Steps to reproduce

1. Run 
   ```
   flux diff kustomization flux-system --kustomization-file ./cluster/flux-system/gotk-sync.yaml --path ./cluster/traefik-system
   ```
   with an existing `./cluster/traefik-system/kustomization.yml`.
2. Command fails with:
   ```
   ✗ failed to generate kustomization.yaml: open cluster/traefik-system/kustomization.yaml: no such file or directory %!s(<nil>) <nil>
   ```

### Expected behavior

`flux diff` should also look for `cluster/traefik-system/kustomization.yml`.

### OS / Distro

macOS 12.6

### Flux version

v0.37.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.4 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
@reitermarkus this will be in the next release. Or you can test it by building the cli yourself.

**Comment by souleb** [comment]
This has been release in v0.38.0. Closing this, please re-open if needed.
