### ISSUE TITLE
Install specific version of flux

### ISSUE THREAD

**Issue by nisanthreddy** [fluxcd/flux2#3395]
I've a mac and need to install Flux V2 on it. I tried using the command "brew install fluxcd/tap/flux" from installation page of Flux, it installs the latest version of flux which is 0.37.0.

 How can I install a specific version of flux using homebrew? To be more specific I require version 0.16.1 to troubleshoot some of the issues.

And also can someone help me in installing flux on Azure Cloud Shell (bash)?

**Comment by hiddeco** [comment]
On that same page: https://github.com/fluxcd/flux2/discussions/489#discussioncomment-3858081
