### ISSUE TITLE
Unable to specify CA for Helm OCI repository

### ISSUE THREAD

**Issue by mnaser** [fluxcd/flux2#3417]
### Describe the bug

At the moment, there is no possibility of using a custom certificate authority against a HelmRepository of type `oci`.  While authentication makes sense to implement later down the line, the ability of trusting a CA should be something that is needed.

### Steps to reproduce

1. Create HelmRepository against internal CA OCI repository
2. Use `secretRef` with `caFile` set
3. HelmChart build will fail:

```
openstack-ceph-provisioners           ceph-provisioners           0.1.8     HelmRepository   atmosphere             7m46s   False   chart pull error: failed to download chart for remote reference: failed to do request: Head "https://atmosphere.openstack:5000/v2/charts/ceph-provisioners/manifests/0.1.8": x509: certificate signed by unknown authority
```

### Expected behavior

I expect that it will accept it since I provided a CA file.

### Screenshots and recordings

N/A

### OS / Distro

N/A

### Flux version

v0.37.0

### Flux check

root@ctl1:~# flux check
► checking prerequisites
✔ Kubernetes 1.22.17 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

N/A

### Container Registry provider

Distribution (formerly Docker Registry)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
This is blocked upstream. We are working with the helm maintainer to fix it.

In the meantime, what you can do is patch the `source-controller` deployment to add your certificate in the pod's trusted root certificate store.

**Comment by kingdonb** [comment]
Link:

* https://github.com/fluxcd/source-controller/issues/723

**Comment by joelcomp1** [comment]
any updates on this? Trying to migrate my local instances to use OCI in Harbor but having the same issue as mentioned here.

**Comment by hiddeco** [comment]
As mentioned:

> This is blocked upstream. We are working with the helm maintainer to fix it.

See https://github.com/helm/helm/pull/11711

**Comment by souleb** [comment]
This will be resolved by https://github.com/fluxcd/source-controller/issues/723

**Comment by mfilotto** [comment]
A satisfaying workaround is to mount CA in source controller using this [tip](https://paraspatidar.medium.com/add-self-signed-or-ca-root-certificate-in-kubernetes-pod-ca-root-certificate-store-cb7863cb3f87)

```apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# Mount custom certificat in source controller
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: ca-pemstore
          configMap:
            name: ca-pemstore
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: ca-pemstore
          mountPath: /etc/ssl/certs/my-cert.pem
          subPath: my-cert.pem
          readOnly: true
    target:
      kind: Deployment
      name: source-controller
```

**Comment by makkes** [comment]
Great you found that. Paulo also suggested this in https://github.com/fluxcd/flux2/discussions/2921#discussioncomment-3196724. I suppose we should add it as an item to the [FAQ page](https://fluxcd.io/flux/faq/).

**Comment by souleb** [comment]
fixed in https://github.com/fluxcd/source-controller/pull/1097
