### ISSUE TITLE
`flux create secret git` command fails when the git repository is inaccessible from the client running `flux`, even with `--export`

### ISSUE THREAD

**Issue by SohumB** [fluxcd/flux2#3430]
### Describe the bug

To create a test/dev setup for my team, I'm building them a flux environment in minikube where the flux repository is mounted within the cluster, so they can just commit locally and see the change reflected in their local minikube.

To make this happen, I'm trying to run a command that looks like `flux --context=minikube create secret git minikube-auth --url ssh://git@git-server.flux-system.svc.cluster.local/git-server/repos/crops.git --private-key-file ~/.minikube/machines/minikube/id_rsa`, and when that didn't work, the same command with `--export`. Both commands fail with 

```
✗ SSH key scan for host git-server.flux-system.svc.cluster.local:22 failed, error: dial tcp: lookup git-server.flux-system.svc.cluster.local on 127.0.0.1:53: no such host
```

### Steps to reproduce

```
flux create secret git minikube-auth --url ssh://git@git-server.flux-system.svc.cluster.local/git-server/repos/crops.git --export
```

or any other address that isn't visible from the machine running the `flux` cli.

I suspect this issue also occurs with `flux create source git`.

### Expected behavior

I can understand if you wanted guardrails on the `create` command, but I would like a way to skip them. At the least, I'd like a way to skip them when using `--export`, so you'd have to opt into it.

### OS / Distro

Debian GNU/Linux bookworm/sid

### Flux version

v0.36.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aryan9600** [comment]
the flux cli scans the ssh host provided for its preferred public keys. from what i can understand, you're running the a git server inside your minikube cluster. the cli can't reach the host provided by you as it can't be resolved from outside the cluster. i think port forwarding the git server service and using localhost to run flux cli commands might work.

**Comment by SohumB** [comment]
Yes, you've understood correctly... but you'd need to both run a port-forward and edit your dns resolver to get the dns resolution of the ssh host to work, and I'd rather not add that kind of complexity to a setup script all my devs are going to run. 

The solution I'm going to run with for now is just investigating the format of the secret flux creates and manually creating it with `kubectl create secret`. It's minikube, so I have all of the public key data flux would otherwise scrape available. This issue is more that it just seems strange to me that the flux cli wouldn't be able to support this usecase, at least in `--export` mode.

**Comment by aryan9600** [comment]
how can the cli running on a machine (and it's network namespace) resolve a host which is internal to the the kubernetes cluster?

**Comment by SohumB** [comment]
I don't want it to. I want the `source-controller` running inside the cluster to use a url and ssh credentials I provide it, to connect to a host that is internal to the cluster. I want the cli running within a distinct network namespace to simply give me the ability to provide that url and ssh credentials, without trying to reach out to that host.

**Comment by stefanprodan** [comment]
@SohumB please see here how to generate the secret: https://fluxcd.io/flux/components/source/gitrepositories/#ssh-authentication

**Comment by kingdonb** [comment]
Please note that the SSH public key of the host is part of the credential, when it comes to SSH authentication. If the CLI cannot retrieve that public key, then it cannot pass the key along to source-controller. From a security perspective, the public key is pinned in the secret, so creating the secret necessarily retrieves that public key, to include it pinned there.

The example in the docs linked above shows the structure and format of the secret; if your developers are connecting git repos to clusters when they cannot access them directly, how else can they verify the public key?

You should get similar behavior (no connection) when running `flux create secret git` if you passed a public key, maybe it is an issue that there is no flag to pass a public key from a file directly to `flux create secret git`?
