### ISSUE TITLE
Multiple controllers using high load, going unresponsive, and crashing the node they live on

### ISSUE THREAD

**Issue by annaken** [fluxcd/flux2#3502]
### Describe the bug

I'm having issues with some flux controllers suddenly having very high load and hanging totally unresponsive, and usually kill the node (EC2 m5.2xlarge instances).

I opened a bug report for the kustomize controller here https://github.com/fluxcd/kustomize-controller/issues/779
but now I also see the image-automation controller also displaying the same behaviour.

We've now managed to identify that this is only happening on the clusters which are running 5.15-flatcar and containerd://1.6.6. It's not happening on clusters running 5.10-flatcar  and containerd://1.5.4.

Additionally, when I look at the pod allocations I see
```
  Namespace                   Name                                                         CPU Requests  CPU Limits   Memory Requests     Memory Limits        Age
  flux-system                 helm-controller-cb74b8c59-4z77j                              100m (1%)     1 (14%)      64Mi (0%)            1Gi (3%)             23h
  flux-system                 image-reflector-controller-7b7dd8b7b7-d6z7c                  800m (11%)    1200m (17%)  858993459200m (2%)   1288490188800m (4%)  23h
  flux-system                 notification-controller-595d477fd7-vpljp                     100m (1%)     1 (14%)      200Mi (0%)           1Gi (3%)             23h
  flux-system                 source-controller-7c78dd47f-8cc96                            1800m (25%)   2400m (34%)  1932735283200m (6%)  2576980377600m (8%)  23h
  flux-system                 image-automation-controller-6ffb56c4d4-gtrzn                 800m (11%)    1200m (17%)  858993459200m (2%)  1288490188800m (4%)  23h
  flux-system                 kustomize-controller-78fc8ffd6b-kt7cr                        1800m (25%)   2400m (34%)  858993459200m (2%)  1288490188800m (4%)  23h
```

That strange memory allocation looks exactly like another issue we had with containerd 1.6.6 and our java apps, https://github.com/flatcar/Flatcar/issues/698 (which we fixed by explicitly setting JAVA_TOOL_OPTIONS value: "-XX:ActiveProcessorCount=1 -Xmx384m").

Is there something weird going on with cgroups and memory allocation?

Right now our only mitigation is to roll back to an older AMI.

### Steps to reproduce

Bring up flux components on 5.15-flatcar and containerd://1.6.6, wait an hour or two.
At some point at least one of the kustomize or image-automation controller will get sky-high load, become unresponsive, and kill the node it is on.

### Expected behavior

For the flux components to neither crash nor crash nodes.

### Screenshots and recordings

<img width="822" alt="Screen Shot 2023-01-20 at 15 16 50" src="https://user-images.githubusercontent.com/4245581/213882481-db7cd4f1-5ff3-43b7-9aed-2ad623231677.png">

### OS / Distro

 5.10.52-flatcar (containerd 1.5.4)

### Flux version

flux: v0.32.0

### Flux check

$ flux check
► checking prerequisites
✗ flux 0.32.0 <0.38.3 (new version is available, please upgrade)
✔ Kubernetes 1.20.10 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.30.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@makkes I see you've tagged this a Flux bug, have you tested Flux with flatcar? Is it really a Flux issue?

**Comment by makkes** [comment]
Definitely not confirmed as a Flux bug, yet. Just labelled it as it was reported as one.

**Comment by annaken** [comment]
Whilst we do see this behaviour with flux, we also discovered it in some other components, and it seems like a bad combination of older k8s (1.20, 1.21) and newer flatcar, with containerd v1.6.6 and too-new cgroup settings.
