### ISSUE TITLE
The "install Flux" GitHub Action is failing

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux2#3509]
Fixed by #3508 

This is failing since #3474 was merged today. I tested the script locally, and I apologize that I apparently never tested what happens when you don't pass a token, so probably for everyone today at once, the Install Flux GitHub Action is failing.

**Comment by kingdonb** [comment]
In the future when #3508 is closed, or today,
people who arrive at this issue the solution is the same:

You can resolve this for yourself by adding the `GITHUB_TOKEN` to your install flux action. Here is the reference from:

https://github.com/fluxcd/flux2/tree/main/action#flux-github-action

> For more information, please [read about the GitHub token secret](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret).
> 
```yaml
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
> 
> This is useful if you are seeing failures on shared runners, those failures are usually API limits being hit.

It can be that once the current issue is closed, people will still find this issue report in the future, and they are searching because they are occasionally rate limited and they haven't read this section of the doc yet. If the failure is intermittent and you can find no explanation, then the answer is probably rate limiting. That's what this PR was initially created to solve.

Everyone that sees a new persistent red light on their Actions dashboard today, can add the token to resolve it yourself now.

Or, just wait until #3508 is merged and then you'll go back to seeing the same intermittent failure at the low failure rate that has been ongoing since #3455 was opened, until you add a token. If you want to permanently resolve it, read the doc above.

Hopefully we can use this minor failure of scripting review to get the word out better about a needed fix for this rate limiting.

**Comment by joelnotified** [comment]
I'm getting `Error: Process completed with exit code 22.` when trying to install FluxCLI via the GitHub Action. Not sure if it's related or not. I've tried the `GITHUB_TOKEN` but still getting the same error.

```
        uses: fluxcd/flux2/action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

```
Run fluxcd/flux[2](...)/action@main
  with:
    version: 0.[3](...)8.3
    token: ***
    arch: amd6[4](...)
  env:
    PARAMETERS_FILE: bicep/parameters/parameters.test.json
    pythonLocation: /opt/hostedtoolcache/Python/3.10.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.9/x64/lib
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Run ARCH=amd64
  ARCH=amd64
  VERSION=0.38.3
  TOKEN=***
  
  if [ -z "${VERSION}" ]; then
    if [ -n "${TOKEN}" ]; then
      VERSION_SLUG=$(curl https://api.github.com/repos/fluxcd/flux2/releases/latest --silent --location --header "Authorization: token ${TOKEN}" | grep tag_name)
    else
      # With no GITHUB_TOKEN you will experience occasional failures due to rate limiting
      # Ref: https://github.com/fluxcd/flux2/issues/3[5](...)09#issuecomment-1400820992
      VERSION_SLUG=$(curl https://api.github.com/repos/fluxcd/flux2/releases/latest --silent --location | grep tag_name)
    fi
  fi
  
  VERSION=$(echo "${VERSION_SLUG}" | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
  
  BIN_URL="https://github.com/fluxcd/flux2/releases/download/v${VERSION}/flux_${VERSION}_linux_${ARCH}.tar.gz"
  curl --silent --fail --location "${BIN_URL}" --output /tmp/flux.tar.gz
  mkdir -p /tmp/flux
  tar -C /tmp/flux/ -zxvf /tmp/flux.tar.gz
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PARAMETERS_FILE: bicep/parameters/parameters.test.json
    pythonLocation: /opt/hostedtoolcache/Python/3.10.9/x[6](....#step:9:6)4
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.[9](...#step:9:9)/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.[10](...#step:9:10).9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.9/x64/lib
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Error: Process completed with exit code [22](...#step:9:23).
```

**Comment by joelnotified** [comment]
Looks like reverting to an older version (`536f4c31ce580a5bc64fb27e4c199050248a6067`) helped me at least. Maybe there is a bug in the latest commit?

**Comment by kingdonb** [comment]
Thank you @joelnotified for resolving this 🏆
