### ISSUE TITLE
no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1alpha1"

### ISSUE THREAD

**Issue by samarth96** [fluxcd/flux2#3521]
### Describe the bug

I have installed v0.38.3 flux
The extra components are enabled during flux bootstrap
--components-extra=image-reflector-controller,image-automation-controller

Helm install failed: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "xyz-image-policy" namespace: "test78" from "": no matches for kind "ImagePolicy" in version "image.toolkit.fluxcd.io/v1alpha1"...

This setup was working with flux v0.18.3. After upgrading to latest version, this error is coming

Some useful info

> bash-4.2$ flux --version
> flux version 0.38.3

> bash-4.2$ kubectl get crds | grep fluxcd
> alerts.notification.toolkit.fluxcd.io            2023-01-20T05:40:50Z
> buckets.source.toolkit.fluxcd.io                 2023-01-20T05:40:50Z
> gitrepositories.source.toolkit.fluxcd.io         2023-01-20T05:40:50Z
> helmcharts.source.toolkit.fluxcd.io              2023-01-20T05:40:50Z
> helmreleases.helm.toolkit.fluxcd.io              2023-01-20T05:40:50Z
> helmrepositories.source.toolkit.fluxcd.io        2023-01-20T05:40:50Z
> imagepolicies.image.toolkit.fluxcd.io            2023-01-20T05:40:50Z
> imagerepositories.image.toolkit.fluxcd.io        2023-01-20T05:40:50Z
> imageupdateautomations.image.toolkit.fluxcd.io   2023-01-20T05:40:50Z
> kustomizations.kustomize.toolkit.fluxcd.io       2023-01-20T05:40:51Z
> ocirepositories.source.toolkit.fluxcd.io         2023-01-26T16:50:16Z
> providers.notification.toolkit.fluxcd.io         2023-01-20T05:40:51Z
> receivers.notification.toolkit.fluxcd.io         2023-01-20T05:40:51Z

> bash-4.2$ kubectl get crd imagerepositories.image.toolkit.fluxcd.io -oyaml
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
>   annotations:
>     controller-gen.kubebuilder.io/version: v0.8.0
>   creationTimestamp: "2023-01-20T05:40:50Z"
>   generation: 2
>   labels:
>     app.kubernetes.io/component: image-reflector-controller
>     app.kubernetes.io/instance: test78
>     app.kubernetes.io/part-of: flux
>     app.kubernetes.io/version: v0.38.3
>     kustomize.toolkit.fluxcd.io/name: test78
>     kustomize.toolkit.fluxcd.io/namespace: test78
>   name: imagerepositories.image.toolkit.fluxcd.io
>   resourceVersion: "50626880"
>   uid: d539a578-9e85-4694-90db-2579e75f9090
> spec:
>   conversion:
>     strategy: None
>   group: image.toolkit.fluxcd.io
>   names:
>     kind: ImageRepository
>     listKind: ImageRepositoryList
>     plural: imagerepositories
>     singular: imagerepository
>   scope: Namespaced
>   versions:
>   - additionalPrinterColumns:
>     - jsonPath: .status.lastScanResult.scanTime
>       name: Last scan
>       type: string
>     - jsonPath: .status.lastScanResult.tagCount
>       name: Tags
>       type: string
>     name: v1beta1
>     schema:
>       openAPIV3Schema:
>         description: ImageRepository is the Schema for the imagerepositories API
>         properties:
>           apiVersion:
>             description: 'APIVersion defines the versioned schema of this representation
>               of an object. Servers should convert recognized schemas to the latest
>               internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
>             type: string
>           kind:
>             description: 'Kind is a string value representing the REST resource this
>               object represents. Servers may infer this from the endpoint the client
>               submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
>             type: string
>           metadata:
>             type: object
>           spec:
>             description: ImageRepositorySpec defines the parameters for scanning an
>               image repository, e.g., `fluxcd/flux`.
>             properties:
>               accessFrom:
>                 description: AccessFrom defines an ACL for allowing cross-namespace
>                   references to the ImageRepository object based on the caller's namespace
>                   labels.
>                 properties:
>                   namespaceSelectors:
>                     description: NamespaceSelectors is the list of namespace selectors
>                       to which this ACL applies. Items in this list are evaluated
>                       using a logical OR operation.
>                     items:
>                       description: NamespaceSelector selects the namespaces to which
>                         this ACL applies. An empty map of MatchLabels matches all
>                         namespaces in a cluster.
>                       properties:
>                         matchLabels:
>                           additionalProperties:
>                             type: string
>                           description: MatchLabels is a map of {key,value} pairs.
>                             A single {key,value} in the matchLabels map is equivalent
>                             to an element of matchExpressions, whose key field is
>                             "key", the operator is "In", and the values array contains
>                             only "value". The requirements are ANDed.
>                           type: object
>                       type: object
>                     type: array
>                 required:
>                 - namespaceSelectors
>                 type: object
>               certSecretRef:
>                 description: "CertSecretRef can be given the name of a secret containing
>                   either or both of \n - a PEM-encoded client certificate (`certFile`)
>                   and private key (`keyFile`); - a PEM-encoded CA certificate (`caFile`)
>                   \n and whichever are supplied, will be used for connecting to the
>                   registry. The client cert and key are useful if you are authenticating
>                   with a certificate; the CA cert is useful if you are using a self-signed
>                   server certificate."
>                 properties:
>                   name:
>                     description: Name of the referent.
>                     type: string
>                 required:
>                 - name
>                 type: object
>               exclusionList:
>                 description: ExclusionList is a list of regex strings used to exclude
>                   certain tags from being stored in the database.
>                 items:
>                   type: string
>                 type: array
>               image:
>                 description: Image is the name of the image repository
>                 type: string
>               interval:
>                 description: Interval is the length of time to wait between scans
>                   of the image repository.
>                 pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
>                 type: string
>               secretRef:
>                 description: SecretRef can be given the name of a secret containing
>                   credentials to use for the image registry. The secret should be
>                   created with `kubectl create secret docker-registry`, or the equivalent.
>                 properties:
>                   name:
>                     description: Name of the referent.
>                     type: string
>                 required:
>                 - name
>                 type: object
>               serviceAccountName:
>                 description: ServiceAccountName is the name of the Kubernetes ServiceAccount
>                   used to authenticate the image pull if the service account has attached
>                   pull secrets.
>                 maxLength: 253
>                 type: string
>               suspend:
>                 description: This flag tells the controller to suspend subsequent
>                   image scans. It does not apply to already started scans. Defaults
>                   to false.
>                 type: boolean
>               timeout:
>                 description: Timeout for image scanning. Defaults to 'Interval' duration.
>                 pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m))+$
>                 type: string
>             type: object
>           status:
>             default:
>               observedGeneration: -1
>             description: ImageRepositoryStatus defines the observed state of ImageRepository
>             properties:
>               canonicalImageName:
>                 description: CanonicalName is the name of the image repository with
>                   all the implied bits made explicit; e.g., `docker.io/library/alpine`
>                   rather than `alpine`.
>                 type: string
>               conditions:
>                 items:
>                   description: "Condition contains details for one aspect of the current
>                     state of this API Resource. --- This struct is intended for direct
>                     use as an array at the field path .status.conditions.  For example,
>                     \n type FooStatus struct{ // Represents the observations of a
>                     foo's current state. // Known .status.conditions.type are: \"Available\",
>                     \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
>                     // +listType=map // +listMapKey=type Conditions []metav1.Condition
>                     `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
>                     protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
>                   properties:
>                     lastTransitionTime:
>                       description: lastTransitionTime is the last time the condition
>                         transitioned from one status to another. This should be when
>                         the underlying condition changed.  If that is not known, then
>                         using the time when the API field changed is acceptable.
>                       format: date-time
>                       type: string
>                     message:
>                       description: message is a human readable message indicating
>                         details about the transition. This may be an empty string.
>                       maxLength: 32768
>                       type: string
>                     observedGeneration:
>                       description: observedGeneration represents the .metadata.generation
>                         that the condition was set based upon. For instance, if .metadata.generation
>                         is currently 12, but the .status.conditions[x].observedGeneration
>                         is 9, the condition is out of date with respect to the current
>                         state of the instance.
>                       format: int64
>                       minimum: 0
>                       type: integer
>                     reason:
>                       description: reason contains a programmatic identifier indicating
>                         the reason for the condition's last transition. Producers
>                         of specific condition types may define expected values and
>                         meanings for this field, and whether the values are considered
>                         a guaranteed API. The value should be a CamelCase string.
>                         This field may not be empty.
>                       maxLength: 1024
>                       minLength: 1
>                       pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
>                       type: string
>                     status:
>                       description: status of the condition, one of True, False, Unknown.
>                       enum:
>                       - "True"
>                       - "False"
>                       - Unknown
>                       type: string
>                     type:
>                       description: type of condition in CamelCase or in foo.example.com/CamelCase.
>                         --- Many .condition.type values are consistent across resources
>                         like Available, but because arbitrary conditions can be useful
>                         (see .node.status.conditions), the ability to deconflict is
>                         important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
>                       maxLength: 316
>                       pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
>                       type: string
>                   required:
>                   - lastTransitionTime
>                   - message
>                   - reason
>                   - status
>                   - type
>                   type: object
>                 type: array
>               lastHandledReconcileAt:
>                 description: LastHandledReconcileAt holds the value of the most recent
>                   reconcile request value, so a change of the annotation value can
>                   be detected.
>                 type: string
>               lastScanResult:
>                 description: LastScanResult contains the number of fetched tags.
>                 properties:
>                   scanTime:
>                     format: date-time
>                     type: string
>                   tagCount:
>                     type: integer
>                 required:
>                 - tagCount
>                 type: object
>               observedGeneration:
>                 description: ObservedGeneration is the last reconciled generation.
>                 format: int64
>                 type: integer
>             type: object
>         type: object
>     served: true
>     storage: true
>     subresources:
>       status: {}
> status:
>   acceptedNames:
>     kind: ImageRepository
>     listKind: ImageRepositoryList
>     plural: imagerepositories
>     singular: imagerepository
>   conditions:
>   - lastTransitionTime: "2023-01-20T05:40:50Z"
>     message: no conflicts found
>     reason: NoConflicts
>     status: "True"
>     type: NamesAccepted
>   - lastTransitionTime: "2023-01-20T05:40:50Z"
>     message: the initial names have been accepted
>     reason: InitialNamesAccepted
>     status: "True"
>     type: Established
>   storedVersions:
>   - v1beta1
> 
> 
> 
> 

### Steps to reproduce

Installed flux using curl -s https://fluxcd.io/install.sh | sudo bash

### Expected behavior

kind ImageRepository should be present 

### OS / Distro

Linux 7.9

### Flux version

v0.38.3

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
All alpha APIs have been removed from Flux, you need to upgrade to beta all your manifests.
