### ISSUE TITLE
flux diff and build not stripping sops: key or metadata

### ISSUE THREAD

**Issue by farflungfish** [fluxcd/flux2#3538]
### Describe the bug
**updated to 0.39**
The `sops:` key or metadata is not being stripped when running a flux diff or flux build.

For flux diff, this results in an error:

```
HelmRelease/namespace/app1 dry-run failed, error: failed to create typed patch object (namespace/app1; helm.toolkit.fluxcd.io/v2beta1, Kind=HelmRelease): .sops: field not declared in schema
```

### Steps to reproduce

Create a file and use sops to encrypt a value. Essentially any file with the `sops:` key contained.

Run `flux diff kustomization app --path=./path`

### Expected behavior

The cli, as I understand, should strip the `sops:` key and metadata on a build or diff.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.38.3

### Flux check
► checking prerequisites
✔ Kubernetes 1.24.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.29.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.29.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.24.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.33.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.31.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.34.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farflungfish** [comment]
I can do a flux build as expected. Upon stripping the .sops **manually** (which apparently I shouldn't have to do) I still get unexpected behaviour.

The unexpected behaviour is that the cli compares the secret values. The expected behaviour is that it only compares the keys!

https://github.com/fluxcd/flux2/issues/2387#issuecomment-1030113742 @stefanprodan

example output:

```
spec.values.secret
  ± value change
    - somevalue
    + ENC[AES256_GCM,data:abc123,type:str]
```

**Comment by souleb** [comment]
can you provide an example yaml for us to reproduce this?

**Comment by farflungfish** [comment]
Hey @souleb I was in the middle of making and testing an end to end example and I discovered it was working as expected. My colleague and I are drilling down further into what is specifically going wrong with our setup. Will raise another issue should we discover the problem is relevant and not just our setup :) Thanks for your attention!
