### ISSUE TITLE
Failed to configure git repo for in-cluster secrets decryption

### ISSUE THREAD

**Issue by crazyelectron-io** [fluxcd/flux2#3543]
### Describe the bug

When following the [Mozilla SOPS guide](https://fluxcd.io/flux/guides/mozilla-sops/), I stumble upon the following error when executing the command `flex create source git flux-secrets --url=ssh://git@github.com/crazyelectron-io/flux-secrets`:
```
✚ generating GitRepository source
✔ collected public key from SSH server:
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHA<<<SNIP>>>/++Tpockg=
✚ deploy key: ecdsa-sha2-nistp384 AAAAE2VjZH<<<SNIP>>>mtRJ5/A==

Have you added the deploy key to your repository: y
► applying secret with repository credentials
✔ authentication configured
► applying GitRepository source
✔ GitRepository source updated
◎ waiting for GitRepository source reconciliation
✗ failed to checkout and determine revision: unable to clone: repository not found: git repository: 'ssh://git@github.com/crazyelectron-io/flux-secrets'
```
When cloning with `git clone ssh://git@github.com/crazyelectron-io/flux-secrets` it works just fine:
```
Cloning into 'flux-secrets'...
warning: You appear to have cloned an empty repository.
```

### Steps to reproduce

1. Install Flux in the K3s cluster
2. Perform the steps in the Mozilla SOPS guide

### Expected behavior

Flux secrets repo configured.

### OS / Distro

MacOS Ventura 13.1 (M1 Pro SoC)

### Flux version

v0.38.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.3+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.30.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crazyelectron-io** [comment]
Thanks for your quick response.
I added a file to the repo and ran the command `flux reconcile source git flux-secrets` which resulted in:
```shell
► annotating GitRepository flux-secrets in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/dae22bd37432ec6eaae20737fcd9fe4f99f82b14
```
Next, I ran the following command:
```shell
flux create kustomization flux-secrets \
--source=flux-secrets \
--path=./cluster/home \
--prune=true \
--interval=10m \
--decryption-provider=sops \
--decryption-secret=sops-gpg
```
Which resulted in:
```shell
✚ generating Kustomization
► applying Kustomization
✔ Kustomization created
◎ waiting for Kustomization reconciliation
```
and it hangs there. I'm not sure about the `--path` parameter: it now points to the root of my own manifests. Should it point to the `./cluster/home/flux-system` directory? I have a simple monorepo setup with `cluster` as the root directory and `./cluster/home` as the base for `flux-system` and my own manifest folders.

In Kubernetes `flux-secrets` contains:
  *identity* - holding the private key
  *identity.pub* - with the public key
  *known_hosts* - with `github.com` as host entry

How can I troubleshoot this? Are there logfiles to check?

**Comment by kingdonb** [comment]
The detailed information for each resource is in the Events, you can `kubectl describe` or `flux get` the resource and it should show you (after the timeout) what reason it has failed to progress.

It should be in the `flux get kustomization` output which pulls from `flux-system` by default.
