### ISSUE TITLE
Kubernetes client initialization failed: kubernetes configuration load failed:

### ISSUE THREAD

**Issue by avasile8709** [fluxcd/flux2#3548]
I encounter the below error "no kind ClusterConfig" when I'm trying to setup flux.

root@andvas-VirtualBox:~/.kube# flux --kubeconfig /root/.kube/config check --pre
► checking prerequisites
✗ Kubernetes client initialization failed: kubernetes configuration load failed: error loading config file "/root/.kube/config": no kind "ClusterConfig" is registered for version "k0s.k0sproject.io/v1beta1" in scheme "pkg/runtime/scheme.go:100"

root@andvas-VirtualBox:~/.kube# cat /root/.kube/config
# generated-by-k0sctl 2023-01-31T15:00:25+02:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
namespace: kube-system
spec:
  api:
    address: 192.168.100.21
    port: 8080
    sans:
    - 192.168.100.21
    - 127.0.0.1
  network:
    provider: calico
  storage:
    etcd:
      peerAddress: 192.168.100.21

root@andvas-VirtualBox:~/.kube# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:8080
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

I'm using OS Ubuntu 22.10

**Comment by makkes** [comment]
Your file `/root/.kube/config` is not a kubeconfig file. You will see that running the following command will also fail:

```
kubectl --kubeconfig /root/.kube/config
```

**Comment by avasile8709** [comment]
thank you, 
Solved, I've updated the 'config' file with the output for 'k0s kubeconfig admin' command
