### ISSUE TITLE
"flux bootstrap git" with github repository fails

### ISSUE THREAD

**Issue by bdew** [fluxcd/flux2#3554]
### Describe the bug

Trying to run

    flux bootstrap git --url=ssh://git@github.com/bdew/flux.git --branch=master --path=clusters/o1

Without ssh-agent this fails with

```
► cloning branch "master" from Git repository "ssh://git@github.com/bdew/flux.git"
⚠️  clone failure: unable to construct auth method with options: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
⚠️  clone failure: unable to construct auth method with options: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
✗ failed to clone repository: unable to construct auth method with options: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

With ssh-agent instead it fails with

```
► cloning branch "master" from Git repository "ssh://git@github.com/bdew/flux.git"
⚠️  clone failure: unable to clone 'ssh://git@github.com/bdew/flux.git': ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
⚠️  clone failure: unable to clone 'ssh://git@github.com/bdew/flux.git': repository already exists
✗ failed to clone repository: unable to clone 'ssh://git@github.com/bdew/flux.git': repository already exists
```

The documentation says that it will generate an ssh key and prompt me to register it but that never happens.

### Steps to reproduce

flux bootstrap git --url=ssh://git@github.com/bdew/flux.git --branch=master --path=clusters/o1

### Expected behavior

Bootstrap to generate a key then clone the repo

### OS / Distro

Ubuntu 22.04.1 LTS

### Flux version

v0.39.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.6+k3s1 >=1.20.6-0
► checking controllers
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.31.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.33.0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.29.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aryan9600** [comment]
The ssh key that's generated and supposed to be registered is for flux controllers. Its stored in a Kubernetes secret and then fetched by a controller during reconciliation to clone or push to the repo. For the cli to be able to clone or push as a part of the bootstrap process, you need to provide an existing private key using the `--private-key-file` flag.

**Comment by bdew** [comment]
With --private-key-file i got

```
► cloning branch "main" from Git repository "ssh://git@github.com/bdew/flux.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("0fae21685b1e8069ba064b0836a0f7385ea4e7f9")
► pushing component manifests to "ssh://git@github.com/bdew/flux.git"
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ssh-ed25519 <redacted>
? Please give the key access to your repository?
```

But the public key it gave me was for the key i passed in with the option, it did not generate a new key.

Also why does it need a key explicitly passed in and doesn't try to use the normal ssh keys from ~/.ssh? 
I was able to just clone the repository with git clone without passing keys.

**Comment by aryan9600** [comment]
`clone failure: unable to clone 'ssh://git@github.com/bdew/flux.git': ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain` is also a transient error that happens due to network issues. does retrying the initial command with ssh-agent enabled work?

**Comment by bdew** [comment]
I messed with it a bit more... It only works if i manually pass the key with `--private-key-file` or by loading it in ssh-agent.

With `--private-key-file` flux does not generate a new key and instead asks me to add the key i gave it to the repository (which is already there).

With me manually loading the key in ssh-agent - it does generate a new key and asks me to add it.

Either way it doesn't seem to use keys from ~/.ssh (which both ssh and git use successfully)

**Comment by stefanprodan** [comment]
Flux does not uses `~/.ssh`, in the docs we say that we either use the SSH agent or the passed private key. I don't know where you've read that Flux reads `~/.ssh`.

**Comment by catsem** [comment]
I just ran into the same issue. It just does not work as expected when reading the documentation here: 
https://fluxcd.io/flux/installation/#generic-git-server

> The above command will generate an SSH key (defaults to RSA 2048 but can be changed with --ssh-key-algorithm), and it will prompt you to add the SSH public key as a deploy key to your repository.

No it won't. It expects that you have already created a keypair and added the public one into your repo config.

**Comment by makkes** [comment]
> I just ran into the same issue. It just does not work as expected when reading the documentation here: https://fluxcd.io/flux/installation/#generic-git-server
> 
> > The above command will generate an SSH key (defaults to RSA 2048 but can be changed with --ssh-key-algorithm), and it will prompt you to add the SSH public key as a deploy key to your repository.
> 
> No it won't. It expects that you have already created a keypair and added the public one into your repo config.

There's a misunderstanding here: during the bootstrapping process Flux clones the given repository using your **local** credentials. It **also** generates an SSH keypair, stores it in a Kubernetes Secret and asks you to add the public part to the repository. The latter is used from then on by Flux running in your cluster.

**Comment by bdew** [comment]
> during the bootstrapping process Flux clones the given repository on your local machine using your **local** credentials

The problem for me was that it wasn't using the local credentials from ~/.ssh

It would only work if i passed the key in manually with  --private-key-file or by loading it in ssh-agent.

It was confusing for me because that's different from how pretty much every other software that uses ssh/git works.
