### ISSUE TITLE
listing kustomizations requires cluster admin privileges 

### ISSUE THREAD

**Issue by thenu97** [fluxcd/flux2#3572]
### Describe the bug

`kubectl get kustomizations -n flux-system` & `flux get kustomization` requires Cluster Admin Role for Azure Kubernetes Service, AKS

### Steps to reproduce

1. Give yourself Cluster Write Access to AKS
2. Attempt to get Kustomization via `kubectl` or `flux` 

### Expected behavior

You should be able to view Kustomization resources with Cluster Read Role
You should be able to view and reconcile Kustomization resources with Cluster Write Role

### OS / Distro

macOS Ventura 13.2

### Flux version

v0.39.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.5 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.29.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.29.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.24.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.33.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.31.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.34.0
► checking crds
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This will be fixed by https://github.com/fluxcd/flux2/pull/3566
