### ISSUE TITLE
flux pods crash on uninstallation of flux on other namespace

### ISSUE THREAD

**Issue by suvajit-sarkar** [fluxcd/flux2#3576]
### Describe the bug

In case of two or more flux installations on different namespace of Kubernetes cluster, uninstall of any one results in crashing of other namespace flux pods.

### Steps to reproduce

For example
1. Bootstrap flux in namespace-A
2. Bootstrap flux in namespace-B
3. Uninstall flux in namespace-B
4. See the flux pods going into crash on namespace-A

### Expected behavior

The flux should be uninstalled from namespace-B without effecting flux on namespace-A.
The issue seems to be with flux removing the CRDs with uninstallations, causing other flux in the cluster to crash

### OS / Distro

N/A

### Flux version

v2

### Flux check

N/A

### Additional context

Is there a way to uninstall flux with out removing the flux CRDs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
There is no support in the CLI for installing multiple Flux instances. Running more than one instance of Flux is not recommended, if you're doing this for isolating tenants please see https://github.com/fluxcd/flux2-multi-tenancy

**Comment by jagpreetsinghsasan** [comment]
@stefanprodan can we not have the CRD's also in the same namespace where the flux is actually deployed? I totally agree that having multiple flux instances isn't a best practice scenario, but for development phases (like, visualisation of multi-cluster deployment over a single cluster by simply grouping resources under namespaces and then each namespace having its own flux), this feature can be very helpful.

**Comment by hiddeco** [comment]
Custom Resource Definitions are cluster-scoped by (Kubernetes) design, so no, this is not an option.

**Comment by stefanprodan** [comment]
Closing this with the resolution: we don't support install multiple Flux instances on a cluster.
