### ISSUE TITLE
Container images of release v0.39.0 are not longer docker-ce 20.10.11 compatible

### ISSUE THREAD

**Issue by networkhell** [fluxcd/flux2#3577]
### Describe the bug

All component container images of release v0.39.0 are not longer compatible to docker-ce 20.10.11. I guess this is an issue mostly for kubespray users that have to stick to docker-engine on kubernetes because this is the latest supported version of the docker engine.

I will update this issue as soon as I am able to test with the latest bugfix release of docker-ce 20.10. 

### Steps to reproduce

~ # docker pull fluxcd/kustomize-controller:v0.33.0
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
~ # docker --version
Docker version 20.10.11, build dea9396

### Expected behavior

I don't know if this change was necessary and/or intended. If not it would be great if you could provide images compatible with older docker engines for users that have to stick with it for now.

### OS / Distro

CentOS 7.9 

### Flux version

v0.39.0

### Flux check

downgraded to 0.37.0 - because flux pod images could not be pulled

► checking prerequisites
✗ flux 0.37.0 <0.39.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.8 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► harbor.senacor-lbb.noris.de/hub.docker.com-proxy/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Closing this because if inactivity and being unable to reproduce on latest `20.10.x`. Feel free to comment if you continue to have this issue with latest version.
