### ISSUE TITLE
`--export` results at times in double newline at EOF

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#3593]
While looking into #3592, I noticed some of our tests around `--export` functionalities have files which end with a double newline.

The culprit of this seems to be the usage of `rootCmd.Println` to print the rendered YAML, which by itself adds a newline (even if the thing it prints already has this at the end).

To provide a better UX, we should ensure we only print a single one at the end of the file which also makes

```console
$ flux ... --export >> file.yaml
$ flux ... --export >> file.yaml
```

produce prettier files.

**Comment by Santosh1176** [comment]
Hey @hiddeco Can I take this up?

As using the `-update` flag for test is not working for me, I updated the goldenfiles manually by removing the additional newline.

```
santosh@flux2:main$ make test TEST_PKG_PATH="./cmd/flux" TEST_ARGS="-run TestExport -update" 
go mod tidy -compat=1.20
cd tests/azure && go mod tidy -compat=1.20
go fmt ./...
go vet ./...
mkdir -p /media/coding/coding/contrib/flux/flux2/testbin
/media/coding/coding/contrib/flux/flux2/bin/setup-envtest use latest --arch=amd64 --bin-dir=/media/coding/coding/contrib/flux/flux2/testbin
Version: 1.26.1
OS/Arch: linux/amd64
md5: q6yUrWDnTJP88foqTLkatA==
Path: /media/coding/coding/contrib/flux/flux2/testbin/k8s/1.26.1-linux-amd64
KUBEBUILDER_ASSETS=""/media/coding/coding/contrib/flux/flux2/testbin/k8s/1.26.1-linux-amd64"" go test ./cmd/flux -coverprofile cover.out --tags=unit -run TestExport -update
NOTE: -update flag passed but golden template files can't be updated, please update it manually
NOTE: -update flag passed but golden template files can't be updated, please update it manually
NOTE: -update flag passed but golden template files can't be updated, please update it manually
.
.
.
``` 

The tests for the same are now passing with only a single newline at the end of the file.
Is it the desired behaviour?
Thanks.

**Comment by makkes** [comment]
@yiannistri is working on it. Not sure if there's opportunity to pair on it. Up to you guys.

**Comment by Santosh1176** [comment]
@makkes Sorry, I didn’t notice the assignment.
