### ISSUE TITLE
Helmrelease didn't pick up values when using postbuild to patch a configmap

### ISSUE THREAD

**Issue by ju187** [fluxcd/flux2#3599]
### Describe the bug

Have a helmrelease that takes value from a configmap.  The comfig has variables defined so the same component could be deployed to multiple environment using postbuild substitution.  The helmrelease is like this---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: argo
spec:
  targetNamespace: argo
  releaseName: argo-rollouts
  chart:
    spec:
      chart: argo-rollouts
      version: "2.14.0"
      sourceRef:
        kind: HelmRepository
        name: argo-rollouts
        namespace: argo
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 60m0s
  valuesFrom:
    - kind: ConfigMap
      name: rollouts-values
      valuesKey: rollouts-values.yaml

The configmap is like this---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollouts-values
  namespace: argo
data:
  rollouts-values.yaml: |
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${argoRolloutARN}
    controller:
      resources: 
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 512Mi
      metrics:
        enabled: true
    podAnnotations: 
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8090"
    serviceAnnotations: 
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8090"
In the same folder has a kustomization file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - rollouts-values.yaml

in the flux-syetem folder, the kustomization is like this
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:  
  name: my-repo
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./clusters/test
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-metadata
      optional: false
    - kind: ConfigMap
      name: my-repo
      optional: false
  prune: false
  sourceRef:
    kind: GitRepository
    name: my-repo

FluxCD correctly did the substitution in the rollouts-values.yaml, but the new value is not picked up by the helmrelease.  What is the sequence of the different kustomization files, is there a race condition?  Thanks

### Steps to reproduce

Create the above mentioned file in the structure and check deployed artifacts

### Expected behavior

The installed argo rollout controller should have a value of the variable substituted

### OS / Distro

macOS 12.6.2

### Flux version

0.19

### Flux check

checking prerequisites
✗ flux 0.19.0 <0.39.0 (new version is available, please upgrade)
✔ Kubernetes 1.24.8-eks-ffeb93d >=1.19.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Changes to a `ConfigMap` are noticed on the next `interval`, given yours has a high value this may mean you need to trigger a manual reconciliation.
