### ISSUE TITLE
HelmRelease semver versions for pre-releases

### ISSUE THREAD

**Issue by pefeigl** [fluxcd/flux2#3600]
Hello!

For development, I'd like to install the latest *prerelease* version (changes often, format is like `0.1.2-15+2023-02-17-deadbeef`, metadata after `+` must be ignored).

However, in HelmReleases neither `version: ~0.1.0` nor `version: *` seem to convince flux to even consider that version which includes a prerelease.

I've verified that that version exists in the repository. The SemVer2 spec specifies the ordering, so to my understanding that pre-release version should definitely match it. How can I write a version expression that *will* take that pre-release version into account?

Thanks for any help with this!

**Comment by hiddeco** [comment]
To include pre-releases, you need to include `-0` in your version selector: https://github.com/Masterminds/semver#working-with-prerelease-versions

**Comment by pefeigl** [comment]
but that will only allow 0.1.2-*, not 0.1.*-*, right? is there any way to stay at a fixed minor version, but update to the newest patch+release available?

**Comment by hiddeco** [comment]
You are welcome, closing this as it has been solved :tada:
