### ISSUE TITLE
Duplicate Mattermost info notifications being fired multiple times in only one tenant and fleet

### ISSUE THREAD

**Issue by JayasreeReddy20** [fluxcd/flux2#3613]
We have observed the **info** notifications of the latest commit id being fired multiple times. This notifications keeps on occurring till the new commit id comes up and it again repeats with the latest commit id. This is happening only to one tenant and fleet. 

Checked similar issue fixed in your list https://github.com/fluxcd/flux2/issues/3072 which have the exact same configurations as mine but this didn't help me. 
Could you help me here if you have any idea on this?

**Comment by JayasreeReddy20** [comment]
Hi Team,
Could you please provide me an update if you have any idea on this issue?

**Comment by stefanprodan** [comment]
I guess you have defined multiple alerts that subscribe to the same event sources. You can find out using `flux get alerts -A` and then `flux export alert` for each one to inspect the sources.

**Comment by JayasreeReddy20** [comment]
Yes, we have checked on this and it helped. Now, we aren't receiving any duplicate alerts. You can proceed to close this issue. Many thanks for your input.
