### ISSUE TITLE
"gotk install" fails on Windows

### ISSUE THREAD

**Issue by robertsmieja** [fluxcd/flux2#362]
I'm not sure what other information would be useful. `--verbose` didn't seem to add anything.

Terminal output:
```
~ ❯ gotk --version
gotk version 0.1.8


~\..\gotk-system ❯ gotk install  --verbose --dry-run
✚ generating manifests
✗ install failed: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\...\AppData\Local\Temp\kustomize-264520769\repo'


~\..\gotk-system  ❯ ls
        Directory: C:\Users\..\gotk-system

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----        10/15/2020   7:38 PM                  patches
-a---        10/15/2020   8:00 PM            280   applications.yaml
-a---        10/15/2020   4:18 AM           6115   gotk-system.yaml
-a---        10/15/2020   7:51 PM            270   kustomization.yaml
-a---        10/15/2020   8:00 PM            268   system.yaml
-a---        10/15/2020   2:34 AM          87053   toolkit-components.yaml
-a---        10/15/2020   7:48 PM            279   toolkit-kustomization.yaml
-a---        10/18/2020   8:20 PM            299   toolkit-source.yaml
```

This is the directory I previously bootstrapped using `v0.1.8` using WSL on Windows 10.

Let me know if there's any other information I can provide.

EDIT:
The same command (`gotk install  --verbose --dry-run`) works under WSL.

**Comment by Sleepy-GH** [comment]
Just ran into the same issue. Tried both under WSL and also with the Windows executable in Powershell.

**Comment by stealthybox** [comment]
gotk is working fine under the WSL2 Linux kernel.
( I dev on WSL2 )

I will try the Windows build in Powershell and see if I can isolate the issue affecting the more Windows native environments.

**Comment by Sleepy-GH** [comment]
Yeah, WSL2 actually uses a Linux VM in the background where WSL1 just translated Linux commands to windows commands so there might be a difference there.
Thanks for looking into it.

**Comment by haraldatbmw** [comment]
Run into the same issue. I'm using Windows 10 and have no option to install WSL2.
It seams that the temp path creation fails under Windows. The directory `C:\Users\xxx\AppData\Local\Temp\kustomize-030280576\repo` was not created.

```
C:\Users\xxx>gotk bootstrap github --owner=%GITHUB_USER% --repository=xxx-infra --branch=main --path=xxx-dev --personal
► connecting to github.com
✔ repository cloned
✚ generating manifests
✗ generating install manifests failed: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\xxx\AppData\Local\Temp\kustomize-030280576\repo'
```

**Comment by haraldatbmw** [comment]
I debugged the code on my windows machine and found the code-line that breaks. But don't know why those paths are getting compared via `d.HasPrefix`.

https://github.com/kubernetes-sigs/kustomize/blob/76a8f034cb906baf1ca0a4f7b62cef785960a0a8/api/loader/loadrestrictions.go#L24

<img width="1154" alt="gotk-debugging-windows" src="https://user-images.githubusercontent.com/49680586/97159574-618d5280-177b-11eb-8e75-3bbcf550f886.png">

**Comment by haraldatbmw** [comment]
I just verified that the existing pullrequest which is referenced in this issue https://github.com/kubernetes-sigs/kustomize/issues/2789 will fix this gotk issue.

**Comment by stefanprodan** [comment]
Thanks @haraldatbmw for digging into this. What if we drop the root-only restriction, would that solve the issue?

**Comment by haraldatbmw** [comment]
@stefanprodan The fix is inside the go-getter project (detect.go) https://github.com/hashicorp/go-getter/pull/284/files
Is there a place inside the toolkit code where the root-only restriction can be dropped?

**Comment by stefanprodan** [comment]
@haraldatbmw can you please try my PR on Windows? Thanks

**Comment by haraldatbmw** [comment]
@stefanprodan I tested your PR on Windows without success. The same error occurs. The Detect function is called too and results in the same error. I think it's best to force the fix in go-getter and kustomize.

`install failed: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\xxx\AppData\Local\Temp\kustomize-400166277\repo'`

**Comment by stefanprodan** [comment]
Ok so there is nothing we can do but wait on a fix in kustomize and by the looks of it, it will take some time. Meanwhile Windows users should download  kustomize v3.4.0 and install the toolkit with:

```sh
kustomize build https://github.com/fluxcd/toolkit/manifests/install?ref=main | kubectl apply -f-
```
