### ISSUE TITLE
Misleading error "immutable field detected, failed to delete object" due to syntax errors on the manifest when using force: true

### ISSUE THREAD

**Issue by TheEdgeOfRage** [fluxcd/flux2#3627]
### Describe the bug

We've seen this error a couple of times now and it's an annoying one for new users of Flux. When there's a syntax error on the manifest, but it's still merged to main, we get this error on the kustomization:

```
✗ Kustomization reconciliation failed: Deployment/default/test immutable field detected, failed to delete object, error: deployments.apps "test" not found
```

Even though the root cause has nothing to do with immutable fields and the resource not existing, but rather, there being an error on the manifest definition itself. It has led us down wrong rabbit holes a couple of times now and I don't quite understand why this is happening.

### Steps to reproduce

Full example repo here: https://gitea.theedgeofrage.com/TheEdgeOfRage/flux-test

Given a basic default flux setup, I have modified the default flux Kustomization to set `force: true` and `prune: false`. This also works with not editing the kustomization, but instead defining a new one. The I define a simple deployment resource with an erroneous manifest:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: alpine
          envFrom:
            - secretRef:
              name: example

```

Note the missing indentation on the `name` field in the `secretRef`. The secret doesn't even have to exist for this error to trigger.

After adding it to my kustomization file, pushing, and triggering a reconciliation. I get the aforementioned error:

```
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/c5f55aa879fdd321fdf78ceabefaace2cb0fd10a
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: Deployment/default/test immutable field detected, failed to delete object, error: deployments.apps "test" not found
```

### Expected behavior

I'd expect flux to tell me that there was something wrong with the manifest syntax, and not that there is an immutable field and that it cannot delete a resource which hasn't even been created yet

### OS / Distro

N/A

### Flux version

v0.40.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.34.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.32.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.35.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

selfhosted Gitea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please consider using [validate.sh](https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh) in your CI and locally, this will detect invalid definitions before they get synced on the cluster.

**Comment by TheEdgeOfRage** [comment]
Alright, I managed to adjust the validate script to work with sops secrets (or rather just ignore them). I guess this is a decent solution, but it'd still be nice to have proper error reporting by flux :)

**Comment by stefanprodan** [comment]
@somtochiama can you please look into a way to improve the error message on force apply? Thanks

**Comment by stefanprodan** [comment]
@TheEdgeOfRage can you please open an issue on https://github.com/fluxcd/flux2-kustomize-helm-example and describe how you're dealing with SOPS validation? I think it would be valuable for all Flux users. Thanks.

**Comment by somtochiama** [comment]
Reopening since the fix from `fluxcd/pkg`  hasn't been released and kustomize-controller hasn't been updated
