### ISSUE TITLE
FluxCD source: authentication required - github Personal access tokens

### ISSUE THREAD

**Issue by DevOpsJazz** [fluxcd/flux2#3668]
### Describe the bug

Hi there

I have problem setting up a secret for a source to access github.

I am using Bear token with github personal access token

Lokking at the documentation: https://fluxcd.io/flux/components/source/gitrepositories/#bearer-token-authentication

I am getting the following error: authentication required

We have installed/bootstraped FluxCD using the operator in namespace flux-system

### Steps to reproduce

1. Create a new token in Github

`https://github.<domain>.com/settings/tokens`

2. Ceate and kubectl apply a secret
Secret
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-repo-cred
data:
  my-token: <token>
```

3. Create a FluxCD Source/GitRepository
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxdemo
  namespace: fluxdemo
spec:
  secretRef:
    name: github-repo-cred
  interval: 30s
  ref:
    semver: '>=0.0.1 <9.9.9'
  url: https://github.<domain>.com/org-zero/fluxdemo.git
```

```bash
get gitrepository
NAME       URL                                                   AGE   READY   STATUS
fluxdemo   https://github.<domain>.com/org-zero/fluxdemo.git   18s   False   failed to checkout and determine revision: unable to clone 'https://github.<domain>.com/org-zero/fluxdemo.git': authentication required
````

### Expected behavior

FluxCD ready for source / GitRepository

### OS / Distro

Windows 11

### Flux version

flux version flux: v0.38.3 helm-controller: v0.26.0 image-automation-controller: v0.26.1 image-reflector-controller: v0.22.1 kustomize-controller: v0.30.0 notification-controller: v0.28.0 source-controller: v0.31.0

### Flux check

flux check
► checking prerequisites
✗ flux 0.38.3 <0.40.2 (new version is available, please upgrade)
✔ Kubernetes 1.23.14+rke2r1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr-remote.artifactory.domain.com/fluxcd/helm-controller:v0.26.0
✔ image-automation-controller: deployment ready
► ghcr-remote.artifactory.<domain>.com/fluxcd/image-automation-controller:v0.26.1
✔ image-reflector-controller: deployment ready
► ghcr-remote.artifactory.<domain>.com/fluxcd/image-reflector-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr-remote.artifactory.<domain>.com/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr-remote.artifactory.<domain>.com/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr-remote.artifactory.<domain>.com/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

github enterprise

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Your example Secret states `.data.my-token`, while the documentation you are referring to explicitly mentions `.data.bearerToken`. Is this an error in your comment, or the actual state of the Secret you are working with?

In case of the latter, changing it to `bearerToken` should make it work as expected.

**Comment by hiddeco** [comment]
In addition, your source-controller version is too outdated to make this work at all. Support for bearer tokens was introduced recently, in [source-controller `v0.34.0`](https://github.com/fluxcd/source-controller/blob/main/CHANGELOG.md#0340).

**Comment by hiddeco** [comment]
Closing this as I suspect this has been answered. If you still find issues after updating to the mentioned version, do not hesitate to get back to us.

**Comment by DevOpsJazz** [comment]
Thanks for info

**Comment by asitha99x** [comment]
at the same problem. any pointed would be appreciated !
ghcr.io/fluxcd/source-controller:v0.36.1

`failed to checkout and determine revision: unable to clone 'https://gitlab.com/s...cd.git': authentication required`

```
apiVersion: v1
kind: Secret
metadata:
  name: bearer-token-auth
  namespace: flux-system
type: Opaque
data:
  bearerToken: ===base64text====
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxcd-repo-green
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://gitlab.com/sample/ab/cd.git
  ref:
    branch: master
  secretRef:
    name: bearer-token-auth
```

the token value is just the token correct, and it has to be base64 ? 
on the repo definition dose it have to end with .git is it significant ?
its a maintainer token from https://gitlab.com/....settings/access_tokens

@DevOpsJazz any idea how you overcome. was it just the Flux version
Many thanks !

**Comment by hiddeco** [comment]
Have you confirmed the token does not accidentally end with a newline?

**Comment by asitha99x** [comment]
i did that mistake.
but then corrected, this is how i generate the base64, 
`echo -n 'glpat-XXXXXX' | base64 `
hope this is correct
i was wondering do we have to have the add anything extra like 
`Bearer<space>token  `

thank you

**Comment by asitha99x** [comment]
update, for anyone else reading.
we had to fall back to https://fluxcd.io/flux/components/source/gitrepositories/#ssh-authentication. in our specific scenario we need to bootstrap multiple git reports. 
1. we are doing to the primary fluxcd boot strapping using terraform module  https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github

2. for the secondary git repo boot strapping we are using a cut-down version of the same terraform module  just get the ssh authentication in-place with the secondary gitrepo. ( this is convenient as we dont have to manually mange any secrets, and the tf state obviously ) 

3. finally  we are syncing the secondary GitRepository definitions using the primary flux repo.
 
we are still verymuch interested to know how a proper  Bearer token authentication works.
thank you.

**Comment by bornav** [comment]
same issue happens on v1.0.0-rc.1
specifying the bearer token in the url and using it as normal authentification seems to work, but as a secret returns back "authentification required", everything else set up as @asitha99x  specified

**Comment by ajhall** [comment]
I was fighting with this for quite a while to make it work with GitHub app tokens. I came across this comment in the go-git source:
https://github.com/fluxcd/go-git/blob/2e5c9d01cfc45de34975e567cf7cf5bf13fee082/plumbing/transport/http/common.go#L222-L225

Which led me here:
https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#using-basic-authentication
> Some REST API endpoints for GitHub Apps and OAuth Apps require you to use basic authentication to access the endpoint. You will use the app's client ID as the username and the app's client secret as the password.

It seems GitHub doesn't accept a bearer token in the Authorization header when cloning Git repos, but it does accept them via basic auth.

**Comment by 589290** [comment]
> I was fighting with this for quite a while to make it work with GitHub app tokens. I came across this comment in the go-git source: https://github.com/fluxcd/go-git/blob/2e5c9d01cfc45de34975e567cf7cf5bf13fee082/plumbing/transport/http/common.go#L222-L225
> 
> ```
> // IMPORTANT: If you are looking to use OAuth tokens with popular servers (e.g.
> // GitHub, Bitbucket, GitLab) you should use BasicAuth instead. These servers
> // use basic HTTP authentication, with the OAuth token as user or password.
> // Check the documentation of your git server for details.
> ```
> 
> Which led me here: https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#using-basic-authentication
> 
> > Some REST API endpoints for GitHub Apps and OAuth Apps require you to use basic authentication to access the endpoint. You will use the app's client ID as the username and the app's client secret as the password.
> 
> It seems GitHub doesn't accept a bearer token in the Authorization header when cloning Git repos, but it does accept them via basic auth.
> 
> I was able to get this working by creating a [basic auth secret](https://fluxcd.io/flux/components/source/gitrepositories/#basic-access-authentication) with the `username` field set to the app's client ID from the GitHub App settings page and the `password` field set to the bearer token.

Did you have to base64 encode the values you used for `username` and `password` in the secret? Also, if the GitRepository flux is using is in a particular namespace does the secret have to be in the same namespace or does it have to be in `flux-system`? I'm failing to see how an arbitrary secret is tied to one of many git repo's declared in flux.

**Comment by ajhall** [comment]
@589290, the values in the Kubernetes Secret object are base64-encoded like any other Kubernetes secret, but the actual values contained in the secret are just the plaintext values for the client ID and bearer token.

The secret does have to be in the same namespace as the GitRepository, and the GitRepository references the secret by name in its `.spec.secretRef.name` field (see the [GitRepository docs](https://fluxcd.io/flux/components/source/gitrepositories/#secret-reference) and the [`secretRef` field in the API spec](https://fluxcd.io/flux/components/source/api/v1/#source.toolkit.fluxcd.io/v1.GitRepositorySpec))

**Comment by 589290** [comment]
Thanks for the help @ajhall ... got me unstuck and pulling auth'd git repos w/ flux!

**Comment by jcabrerizo** [comment]
Thank you @ajhall you saved my day.
Just adding some extra trick: you can pass as user name `pat` (case sensitive), and then your token to authenticate using your handle.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: flux-ns
type: Opaque
data:
  password: $BASE64_TOKEN
  username: cGF0 # pat
```

**Comment by JamesMcMahon** [comment]
@ajhall 

> I was able to get this working by creating a [basic auth secret](https://fluxcd.io/flux/components/source/gitrepositories/#basic-access-authentication) with the username field set to the app's client ID from the GitHub App settings page and the password field set to the bearer token.

What is the "app" you are referring to? Does the basic access auth approach require creating a [GitHub App](https://github.com/settings/apps)?

> you can pass as user name pat

Didn't work for me personally - but I also don't have an GitHub App setup, was trying to get this work using a personal account token.

**Comment by ajhall** [comment]
@JamesMcMahon, yeah, I used a GitHub App for my setup. I think a personal access token would work similarly, but I haven't tried it personally.
