### ISSUE TITLE
namespace "flux-system" not found

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/flux2#3678]
### Describe the bug

When running bootstrap if any CRD still exists it will not create the `--namespace` specified.

So you get error like:
```
✗ namespaces "flux-system" not found
```

### Steps to reproduce

1. Create cluster and bootstrap
2. Deploy some HelmRepository/HelmChart/HelmRelease/Kustomizations
3. flux uninstall (Delete's everything but CRDs can't be removed due to resources still exist)
4. flux bootstrap

### Expected behavior

flux bootstrap by default creates flux-system (namespace specified) only if CRDs (maybe ClusterRoles) don't already exist.
Flux should ignore if those resources exist (as they would in this scenario) and create namespace if missing as it normally would.

### OS / Distro

macOS 13.2.1

### Flux version

0.40.2

### Flux check

❯ flux check
► checking prerequisites
✗ flux 0.40.2 <0.41.0 (new version is available, please upgrade)
✔ Kubernetes 1.25.6-eks-48e63af >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cdenneen** [comment]
```
| CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io status: 'Terminating',
│ CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io status: 'Terminating',
│ CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io status: 'Terminating',
│ CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io status: 'Terminating'
```

**Comment by stefanprodan** [comment]
The namespace is probably there stuck in finalizers. To properly uninstall Flux please use `flux uninstall`.

**Comment by cdenneen** [comment]
I did do a flux uninstall, confirmed namespace was gone.
It was the CRDs that were the issue. I removed all my resources of those
CRDs and then the CRDs and then bootstrap will work.

It needs to be adjusted to still bootstrap when CRDs exist. Or allow the
resources to exist (not going to uninstall and helm release)

Think the CRDs were all stuck in Terminating not the namespace. That was
confirmed gone.

**Comment by stefanprodan** [comment]
> It needs to be adjusted to still bootstrap when CRDs exist. 

The CRDs were stuck in Terminating, that’s why it didn’t work and I suspect the namespace was the same. The bootstrap command doesn’t care if there are any CRDs, it will just do an upgrade.

**Comment by cdenneen** [comment]
The uninstall removes the finalizers (or tries to) so not sure how to
cleanly get them to remove so you can reinstall
