### ISSUE TITLE
flux build and flux diff don't honor .sourceignore files

### ISSUE THREAD

**Issue by tun0** [fluxcd/flux2#3695]
### Describe the bug

If you have one or more `.sourceignore` files in your (local) checkout, these are being ignored when running `flux build ks` and `flux diff ks`. This can lead to confusing output of these commands.

### Steps to reproduce

1. Have a bunch of manifests in a directory
2. List one or more of the manifests in a `.sourceignore` file
3. Run `flux build ks` and/or `flux diff ks`
4. The manifests listed in `.sourceignore` are present in the output of the respective `flux` commands

### Expected behavior

The manifests listed in `.sourceignore` shouldn't be present in the output of the respective commands.

### OS / Distro

Manjaro

### Flux version

v0.41.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.9-gke.3200 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.31.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:rc-b89a023e@sha256:377a7bc1cf45b4245a82c21be149d8784c8cd74c5c1bc65188e68c28fcbd5dc0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:rc-1303c254@sha256:0b9ea0503f76faf9c4e827c3d1dff72f4c10d8aa9a3be6cfd67e7c467423ee86
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
thanks @tun0 for reporting this. I will submit a patch that will take into account `.sourceignore`.

**Comment by tun0** [comment]
Not sure if this would warrant a separate ticket or not: in order to mimic `.spec.ignore` of `GitRepository`, those commands could benefit from an extra command line argument to provide an (additional) explicit ignore list.

**Comment by souleb** [comment]
Yes, that will be part of the patch.

**Comment by stefanprodan** [comment]
> Not sure if this would warrant a separate ticket or not: in order to mimic .spec.ignore of GitRepository, those commands could benefit from an extra command line argument to provide an (additional) explicit ignore list.

Please create a separate issue for the flags.

**Comment by stefanprodan** [comment]
The `.sourceignore` issue was fixed in #3758
