### ISSUE TITLE
unable to run ImageRepository on azure... failed to configure authentication option...

### ISSUE THREAD

**Issue by girishgouda** [fluxcd/flux2#3700]
### Discussed in https://github.com/fluxcd/flux2/discussions/3698

<div type='discussions-op-text'>

<sup>Originally posted by **girishgouda** March 18, 2023</sup>
This is the yamlfile which i am using for ImageRepository in fluxv2 

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontendapprepo
  namespace: flux-system
spec:
  secretRef:
    name: regcred
  image: docker.io/girishgoudar/voteapp
  interval: 1m0s

and this being the image policy 

 apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontendapppolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontendapprepo
  policy:
    semver:
      range: 1.0.x                

![image](https://user-images.githubusercontent.com/9015874/226115210-0f783b2a-dbf0-4b25-863f-e5090ad4aa1a.png)

i have verified that i was able to pull the docker image from the secret created</div>

**Comment by makkes** [comment]
Your Secret type is wrong, just as the error message says. It must be `kubernetes.io/dockerconfig`, not `kubernetes.io/dockercfg`.
