### ISSUE TITLE
gotk bootstrap gitlab and semver tag

### ISSUE THREAD

**Issue by SpectralHiss** [fluxcd/flux2#371]
Hello,

I am trying to create a new prod release pipeline using the semver tag feature of gotk.

I am not sure this 100% a bug or me not fully grasping the docs. when i run the bootstrap command with --semver-tag:
```
gotk bootstrap gitlab --owner acresoftware/terraform --repository k8s-config --tag-semver=">=0.0.1" --path gitops/configs/prod-cluster --components=source-controller,kustomize-controller,helm-controller,notification-controller --version v0.1.
```
 I get:
```
✗ unknown flag: --tag-semver
```
How to proceed to fix this? is there a way to do it in deployment if CLI doesn't provide the feature?

Also i am a bit confused whether or not i can use it in the manner i did >=0.0.1 I don't want to be too specific yet about it and i just want it to deploy on any new tag.. it would be nice if i knew what algorithm it uses to decide also (in case by mistake somebody retags 0.0.1 when 0.0.2 is out what does it deploy?)
Thanks in advance!

**Comment by hiddeco** [comment]
The `gotk bootstrap` command has at present no such option, and neither does `gotk install`.

`gotk create source git` does have a `--tag-semver` flag, and what it creates can technically be applied to the manifests `gotk install` produce too by changing the `ref` in the generated `GitRepository` to:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
...
spec:
...
  ref:
    semver: '>=0.0.1'
```

**Comment by SpectralHiss** [comment]
Yes I ended up editing the deployment manually, would be nice to have that but I guess not critical so i regard it as solved.

Thanks a lot @hiddeco for your answer!
