### ISSUE TITLE
Gitlab registry does not support Flux OCI media types

### ISSUE THREAD

**Issue by tmmorin** [fluxcd/flux2#3724]
### Describe the bug

I get this error when doing a `flux push artifact` to a gitlab registry (with recent flux 0.41.1):

```
flux push artifact oci://registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:test --path=. --source=git@gitlab.com:sylva-projects/sylva-core.git --revision=kustomize-units-oci-artifact/0574980c2e57149cb5879c27c61cba2551040e59                 
► pushing artifact to registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:tmorin-test
✗ pushing artifact failed: pushing artifact failed: PUT https://registry.gitlab.com/v2/sylva-projects/sylva-core/kustomize-units/manifests/tmorin-test: MANIFEST_INVALID: manifest invalid; unknown media type: application/vnd.cncf.flux.config.v1+json
```

With flux 0.38.3 and 0.39.0 I don't get this error:
```
$ /tmp/flux-0.38.3/flux push artifact oci://registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:tmorin-test --path=. --source=git@gitlab.com:sylva-projects/sylva-core.git --revision=kustomize-units-oci-artifact/0574980c2e57149cb5879c27c61cba2551040e59                 
► pushing artifact to registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:test
✔ artifact successfully pushed to registry.gitlab.com/sylva-projects/sylva-core/kustomize-units@sha256:6f1465fdc0c6b0909569974a2a00a84a71a392ca2c4243c6fae03a418e558b66
$ /tmp/flux-0.39.0/flux push artifact oci://registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:tmorin-test --path=. --source=git@gitlab.com:sylva-projects/sylva-core.git --revision=kustomize-units-oci-artifact/0574980c2e57149cb5879c27c61cba2551040e59                 
► pushing artifact to registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:test
✔ artifact successfully pushed to registry.gitlab.com/sylva-projects/sylva-core/kustomize-units@sha256:0fefc24130d7e6e615179d4e1339f22fb29445df730c2ba51aeeb68289ca67b6
```

The first release that I tested that triggers this error is `0.40.0`.

### Steps to reproduce

Run the following command with flux >= 0.40.0 (adapt it to use a gitlab project in which you have suitable credentials, of course):
```
flux push artifact oci://registry.gitlab.com/sylva-projects/sylva-core/kustomize-units:test --path=. --source=git@gitlab.com:sylva-projects/sylva-core.git --revision=kustomize-units-oci-artifact/0574980c2e57149cb5879c27c61cba2551040e59     
```

### Expected behavior

I would expect the command to work in flux >= 0.40.0 just like it does with 0.39.0.

### OS / Distro

Linux

### Flux version

0.40.0 and after

### Flux check

not relevant

### Additional context

I get this error when pushing to registry.gitlab.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Until GitLab allows Flux artifacts, you have to stick to the old CLI for push operations, but make sure not to use that CLI version for anything else, just push.

**Comment by tmmorin** [comment]
I opened this gitlab.com issue to follow up: https://gitlab.com/gitlab-org/gitlab/-/issues/399923

**Comment by tmmorin** [comment]
> Until GitLab allows Flux artifacts, you have to stick to the old CLI for push operations, but make sure not to use that CLI version for anything else, just push.

Yes, this is exactly why I'm doing right now :+1:

**Comment by arukiidou** [comment]
It has been completed upstream

https://gitlab.com/gitlab-org/container-registry/-/issues/951
