### ISSUE TITLE
 Is there no token auth for source git ? unknown flag: --token-auth

### ISSUE THREAD

**Issue by vyom-soft** [fluxcd/flux2#3741]
### Describe the bug

    On GitLab, I used the following command to bootstrap..
    `$flux bootstrap gitlab --owner=vyomsoft/deployment --repository=vyom-repo --path=clusters/vyom/ --token-auth --hostname=vyom.devopslab.tech`
    How can I do token auth for source GitRepository?

`
$flux create source git dev-monitoring --url=https://vyom.devopslab.tech/vyomsoft/deployment/vyom-repo.git --branch=main --namespace=dev-monitoring --token-auth
`
Is there  no token auth for source git ? unknown flag: --token-auth

Here I do not see entry for token-auth ? With the cmd you proposed. [authentication-required](https://github.com/fluxcd/flux2/issues/529) Please suggest.

### Steps to reproduce

$flux create source git dev-monitoring --url=https://vyom.devopslab.tech/vyomsoft/deployment/vyom-repo.git --branch=main --namespace=dev-monitoring --token-auth

### Expected behavior

With  $flux create source git... the repo should be cloned. 

### OS / Distro

RHEL 8

### Flux version

flux: v0.41.2

### Flux check

$ flux check
► checking prerequisites
✔ Kubernetes 1.26.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The Git protocol has no token concept, that’s something SaaS provides do. Git supports SSH or basic-auth over HTTP/S. For basic auth there are flags such as username and password, please read the docs https://fluxcd.io/flux/installation/#generic-git-server or add `—help` to the command

**Comment by vyom-soft** [comment]
> The Git protocol has no token concept, that’s something SaaS provides do. Git supports SSH or basic-auth over HTTP/S. For basic auth there are flags such as username and password, please read the docs https://fluxcd.io/flux/installation/#generic-git-server or add `--help` to the command

Thank you. 
I am behind private N/W. The bootstrap was performed by using --token-auth.

**Comment by stefanprodan** [comment]
For a GitLab, you can use `flux bootstrap git` and pass the token as the `--password`.
