### ISSUE TITLE
Reconciliation fails when PodDisruptionBudget has no namespace set

### ISSUE THREAD

**Issue by herbertgoto** [fluxcd/flux2#3742]
### Describe the bug

Flux reconciliation fails when a PodDisruptionBudget has not a namespace defined. This is the error:
`PodDisruptionBudget/foobar namespace not specified, error: the server could not find the requested resource`

Namespace is not required according to the [object documentation](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget). 

### Steps to reproduce

1. Create a PodDisruptionBudget without a defined namespace
2. Push it to Git
3. Wait for the reconciliation failure

This is my manifest:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: critical-workloads 
spec:
  minAvailable: 2
  selector:
    matchLabels:
      workload-kind: critical
```

### Expected behavior

A PodDisruptionBudget is created in the Kubernetes cluster and reconciliation does not fail. 

### OS / Distro

macOS m1

### Flux version

flux: v0.41.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.10-eks-48e63af >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/notification-controller:v0.30.2
✔ source-controller: deployment ready
► 044846299318.dkr.ecr.us-east-1.amazonaws.com/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

ECR

### Additional context

flux: v0.41.2
helm-controller: v0.28.1
image-automation-controller: v0.28.0
image-reflector-controller: v0.23.1
kustomize-controller: v0.32.0
notification-controller: v0.30.2
source-controller: v0.33.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
PodDisruptionBudget is a namepaced object and Flux requires all such objects to include `metadata.namespace`. Unlike kubectl, Flux does not assume the `default` namespace, so you must set in the YAML.
