### ISSUE TITLE
Deploy Key with same name everywhere in gitlab

### ISSUE THREAD

**Issue by genofire** [fluxcd/flux2#3749]
### Describe the bug

the function `deployKeyName` generates the same name, even the kubectl context is different.

### Steps to reproduce

1. `export KUBE_CONFIG=a.yaml`
2. `flux bootstrap gitlab --owner=me --repository=clusters/a.git --path . --ssh-hostname=gitlab.com:22 --read-write-key`
3. `export KUBE_CONFIG=b.yaml`
4. `flux bootstrap gitlab --owner=me --repository=clusters/b.git --path . --ssh-hostname=gitlab.com:22 --read-write-key`

### Expected behavior

- name is not set everywhere: `flux-system-main-flux-system-./ `
- or give an cli option to set deployKeyName

### OS / Distro

ubuntu

### Flux version

v0.41.0

### Flux check

...

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

---

This Code does not have any lookup after a repository-name:

https://github.com/fluxcd/flux2/blob/0625bf8185aad97609bef573b936c4a786a80c03/pkg/bootstrap/bootstrap_provider.go#L283

**Comment by makkes** [comment]
Thanks for your report, @genofire. May I ask a question for clarification, please: You provide two steps to reproduce which would result in bootstrapping the SAME cluster with two different repositories? This is not how Flux bootstrapping is supposed to work. You bootstrap a cluster only from a single repository.

However, it looks like your steps to reproduce don't match what the title of this issue says about the same deploy key being generated for two different bootstrap runs (supposedly on two different clusters). If you are using a Git repository for bootstrapping different clusters (which is a 100% supported use case for Flux) you should always use different paths within the repository for each cluster.

Please take a look at [the example repository](https://github.com/fluxcd/flux2-multi-tenancy) for setting up Flux with multiple tenants/clusters.

**Comment by genofire** [comment]
No, that all are different cluster (i edit the description and expose KUBE_CONFIG).

**Comment by stefanprodan** [comment]
@genofire to use the same repo for different clusters you need to pass the cluster name to `--path clusters/my-cluster`, the generated key will contain the cluster name thus no conflicts. Please see https://github.com/fluxcd/flux2-kustomize-helm-example on how to structure your repo.

**Comment by genofire** [comment]
nope, different cluster (in description a and b) with his own repo (also a and b).

i do not need any example, we run already 20 fluxcd instances ...

i just dislike the SSH-Deploy-Key inside of gitlab, because they are all equal (and fluxcd-bootstrap has no option to set this key).

**Comment by makkes** [comment]
> i just dislike the SSH-Deploy-Key inside of gitlab, because they are all equal (and fluxcd-bootstrap has no option to set this key):

With "they are all equal" do you mean their name? Is your request to provide a flag to the Flux CLI to provide a deploy key name that's used when creating it on your GitLab instance?

**Comment by makkes** [comment]
The list from your screenshots shows a bunch of deploy keys that all have the same name which can only happen when you run `flux bootstrap` against different clusters with the same path. As I said above this is discouraged.

**Comment by genofire** [comment]
Exactly, their name on gitlab (or other githosting) i mean - my opinion is the best way would be a cli flag or to use the context name eighter on creation.

different clusters with same path **on different repos** ... yes.

---

sorry, that i was not able to descripe it better (then with a screenshot).

**Comment by hiddeco** [comment]
Given this, one could also argue that the GitLab UI could be more precise by showing to what project a key name is assigned (as apparently: names themselves aren't unique).

**Comment by genofire** [comment]
@hiddeco gitlab shows in which project this ssh-keys uses -> that is helpful.

(after setup an ssh-key for a cluster-repo we allow that key also access the base-repo and use in kubernetes the flux-system secret to access base-GitRepository)

but in the end the UI (which could be just a little bit better) does not help much, if the name is "everywhere" the same.

**Comment by makkes** [comment]
> after setup an ssh-key for a cluster-repo we allow that key also access the base-repo and use in kubernetes the flux-system secret to access base-GitRepository

I wanted to understand your issue in more detail so I reproduced your situation, enabling a key from repository "group/project" in another repository and the UI shows all the information I would need, including the repository where the key is originating at:

![2023-04-05_09-01](https://user-images.githubusercontent.com/387444/230005481-f57b2a51-85c5-4f1c-86b3-bcd6de7fb7dd.png)

So even if the name is the same for all keys you are using, the GitLab UI clearly makes each key distinguishable from the "Project usage" column.
