### ISSUE TITLE
ssh: handshake failed: knownhosts: key mismatch when running flux bootstrap in a new cluster

### ISSUE THREAD

**Issue by brpaz** [fluxcd/flux2#3774]
### Describe the bug

When I run the following bootstrap script:

```sh
flux bootstrap github \
    --components-extra=image-reflector-controller,image-automation-controller \
    --owner=${GITHUB_OWNER} \
    --repository=infrastructure \
    --branch=main \
    --read-write-key \
    --path=./k8s/clusters/dev
```

The flux components are installed successfully, but the cloning of the repository fails in source controller with error: 

```
failed to checkout and determine revision: 
unable to clone 'ssh://git@github.com/myrepo': ssh: 
handshake failed: knownhosts: key mismatch
```

I noticed that in the flux-system secret, the `identify.pub` starts with `ecdsa-sha2-nistp384 ` but on the known hosts, it contains `ecdsa-sha2-nistp256`. Not sure it can be related to that.

I didn´t do anything else besides running `flux bootstrap` in a completely new cluster.

### Steps to reproduce

Simple run flux bootstrap in a new Kind cluster:

``` 
flux bootstrap github \
    --components-extra=image-reflector-controller,image-automation-controller \
    --owner=${GITHUB_OWNER} \
    --repository=infrastructure \
    --branch=main \
    --read-write-key \
    --path=./k8s/clusters/dev
```

### Expected behavior

The manifests should be cloned successfully.

### OS / Distro

Fedora 37

### Flux version

flux: v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.26.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.32.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
The `.known_hosts` field should match GitHub's [official list of host keys](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints) like this:

```
$ kubectl -n flux-system get secret flux-system -o jsonpath={.data.known_hosts}|base64 -d
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
```

**Comment by brpaz** [comment]
That is the value I have in the secret. Still I got the error

`github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=`

**Comment by hiddeco** [comment]
What you can try to do is to update the Secret with all the values GitHub advertises here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

**Comment by brpaz** [comment]
I found the issue. The error message was completely misleading. It was a dns issue, rather than a specific git issue.  The Docker daemon where I am running my Kind cluster was using a wrong dns server. changing to  "8.8.8.8" fixed the problem.
