### ISSUE TITLE
Github Actions installing release candidates

### ISSUE THREAD

**Issue by danquack** [fluxcd/flux2#3782]
### Describe the bug

The [GitHub action](https://github.com/fluxcd/flux2/blob/main/action/action.yml), by default, grabs the latest version. Using the docs for https://github.com/fluxcd/flux2/blob/main/action/README.md#automate-flux-updates, this subscribes users to release candidate (2.0.0 rc-1) vs. previous patterns of only stable versions. Should major pinning be considered, or should new practices be implemented for releasing candidates over stable versions?

Relates to #3735

### Steps to reproduce

Use fluxcd action in GitHub pipelines

### Expected behavior

Only stable versions be published

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
v0 is not a stable version, upgrading from v0.x to v2.0.0-rc.1 is expected as both versions are not stable in semver terms.
