### ISSUE TITLE
flux build creates empty YAML documents

### ISSUE THREAD

**Issue by tun0** [fluxcd/flux2#3784]
### Describe the bug

As of Flux v2.0.0-rc.1 the output of `flux build` changed slightly. It now ends with an empty YAML document.

### Steps to reproduce

1. Install flux v2.0.0-rc.1
2. Create a Kustomization
3. Run `flux build`
4. Output: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
<snip>
---
```

### Expected behavior

Expected output:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
<snip>
```

### OS / Distro

N/A

### Flux version

v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.9-gke.3200 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.32.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
I'm assuming you mean `flux build kustomization` since there are two sub-commands in `flux build`, (the other outputs a `.tgz` file so must not be the same thing.)

We found this:

```
		builder.WriteString("---\n")
```
in some related code, at the end of this function here:

https://github.com/fluxcd/pkg/blob/main/ssa/utils.go#L234

This could certainly cause the issue you're finding, but it looks like this line has been here for quite some time.

**Comment by tun0** [comment]
Something did change though:

```
❯ /tmp/flux/flux-0.41.1 version | head -1
flux: v0.41.1
❯ /tmp/flux/flux-2.0.0-rc.1 version | head -1
flux: v2.0.0-rc.1
❯ /tmp/flux/flux-0.41.1 build ks tests --path flux/apps/staging/tests > out-0.41.1
❯ /tmp/flux/flux-2.0.0-rc.1 build ks tests --path flux/apps/staging/tests > out-2.0.0-rc.1
❯ diff -u out-0.41.1 out-2.0.0-rc.1
--- out-0.41.1  2023-04-13 22:06:59.922617612 +0200
+++ out-2.0.0-rc.1      2023-04-13 22:06:47.625715759 +0200
@@ -231,3 +231,4 @@
           requests:
             cpu: 10m
             memory: 20Mi
+---
❯
```

**Comment by kingdonb** [comment]
I think we found the PR that caused the issue, and @darkowlzz has given me some pointers to follow up!

**Comment by souleb** [comment]
In this pr:
https://github.com/fluxcd/flux2/commit/cecffc058894832979be6c765d59c0a0d2e3fe96

We now use `manifests, err := ssa.ObjectsToYAML(objects)` to get the yaml representation.

**Comment by tun0** [comment]
> We found this:
> 
> ```
> 		builder.WriteString("---\n")
> ```
> 
> in some related code, at the end of this function here:
> 
> https://github.com/fluxcd/pkg/blob/main/ssa/utils.go#L234

I am rather curious what the rationale would (have) be(en) to order it like that (appending`---\n` instead of prepending). Same for its sibling, `ObjectToYAML()`, obviously.

**Comment by stefanprodan** [comment]
@tun0 why does it matter if the file ends with `---`, both kubectl and flux use an YAML parser that skips empty docs.

**Comment by stefanprodan** [comment]
We do this to allow the injection of an ending doc that has no delimiters.

**Comment by tun0** [comment]
Ah, right. Instead of having to do something like `(echo  --- ; k get gitrepo something -oyaml) >> flux-generated.yaml`. Then again, "blindly" appending data to a generated file and assume it'd just work could be debatable as well :wink: Also, "directly" appending would only work once. Additional appends would need the `---` anyway.

But, at least the reasoning is clear now :+1:

**Comment by kingdonb** [comment]
OK, I won't submit a PR that reverts this 👍 thanks for the clarification!
