### ISSUE TITLE
Flux fails to complete installation with a GitLab repo on DOKS

### ISSUE THREAD

**Issue by BobyMCbobs** [fluxcd/flux2#3785]
### Describe the bug

`flux bootstrap` hangs on
```
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ client rate limiter Wait returned an error: context deadline exceeded
```
on initialisation and fails to complete installation

### Steps to reproduce

1. create a cluster with DigitalOcean `doctl k8s cluster create gl-do-flux1 --region syd1 --size s-4vcpu-8gb --count=3`
2. create a GitLab repo in an organisation
3. create personal access token for user account in the organisation
4. `export GITLAB_TOKEN=TOKEN_HERE`
5. `flux bootstrap gitlab --owner=islive.xyz --repository=sites --path=clusters/syd1 --token-auth`

### Expected behavior

Flux should complete installation.

### OS / Distro

macOS 13.3.1

### Flux version

v2.0.0-rc.1 and v0.41.2

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.26.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

GitLab

### Additional context

Kubernetes provider is DigitalOcean.

```
🐚 flux bootstrap gitlab --owner=islive.xyz --repository=infra --path=clusters/syd1 --token-auth
► connecting to https://gitlab.com
► cloning branch "main" from Git repository "https://gitlab.com/islive.xyz/infra.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("d8ee019929943e53529fd58e26c16f1b7b86c3a9")
► pushing component manifests to "https://gitlab.com/islive.xyz/infra.git"
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ committed sync manifests to "main" ("2f34ce23b12731198775486d570b3270d46aafda")
► pushing sync manifests to "https://gitlab.com/islive.xyz/infra.git"
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ client rate limiter Wait returned an error: context deadline exceeded
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 1 health check failure(s)
```

```
🐚 kubectl -n flux-system get pods
NAME                                       READY   STATUS    RESTARTS   AGE
helm-controller-ddb4b564-jpwjz             1/1     Running   0          5m33s
kustomize-controller-787d5575fc-2r246      1/1     Running   0          5m33s
notification-controller-66ff5df674-xbdf4   1/1     Running   0          5m33s
source-controller-68c754f876-hv529         1/1     Running   0          5m33s
```

```
🐚 kubectl -n flux-system logs kustomize-controller-787d5575fc-2r246
...
{"level":"error","ts":"2023-04-11T08:50:22.668Z","msg":"Reconciliation failed after 4.150415486s, next try in 10m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"flux-system","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system","reconcileID":"5c9db79d-84d8-4017-95c9-3e02d85660a5","revision":"main@sha1:2f34ce23b12731198775486d570b3270d46aafda","error":"ServiceAccount/metrics-server namespace not specified, error: the server could not find the requested resource\nCustomResourceDefinition/alerts.notification.toolkit.fluxcd.io configured\nCustomResourceDefinition/buckets.source.toolkit.fluxcd.io configured\nCustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io configured\nCustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io configured\nCustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io configured\nCustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io configured\nCustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io configured\nCustomResourceDefinition/ocirepositories.source.toolkit.fluxcd.io configured\nCustomResourceDefinition/providers.notification.toolkit.fluxcd.io configured\nCustomResourceDefinition/receivers.notification.toolkit.fluxcd.io configured\nNamespace/flux-system configured\n"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BobyMCbobs** [comment]
> ```
> ServiceAccount/metrics-server namespace not specified, error: the server could not find the requested resource
> ```
> 
> Where is this SA defined?

@makkes, thank you for your reply.
I've got it set in https://gitlab.com/islive.xyz/infra/-/blob/ccdffd5e171e2a00f5f6178d906b2ed6f63d6985/clusters/syd1/kube-system/metrics-server.yaml#L6

Is it more typical to start with a blank repo when getting started with Flux?

**Comment by makkes** [comment]
>  I've got it set in https://gitlab.com/islive.xyz/infra/-/blob/ccdffd5e171e2a00f5f6178d906b2ed6f63d6985/clusters/syd1/kube-system/metrics-server.yaml#L6

Well, the manifest doesn't have a namespace specified, that's why the flux-system kustomization fails. You need to either create a `kustomization.yaml` file that prescribes a namespace or set the namespace in each manifest.

> Is it more typical to start with a blank repo when getting started with Flux?

It is totally valid to bootstrap with a pre-loaded repo but the repo needs to be prepared to be reconciled by Flux.

**Comment by BobyMCbobs** [comment]
> > I've got it set in https://gitlab.com/islive.xyz/infra/-/blob/ccdffd5e171e2a00f5f6178d906b2ed6f63d6985/clusters/syd1/kube-system/metrics-server.yaml#L6
> 
> Well, the manifest doesn't have a namespace specified, that's why the flux-system kustomization fails. You need to either create a `kustomization.yaml` file that prescribes a namespace or set the namespace in each manifest.

@makkes, thank you. This issue was surely simpler than I thought.
Flux is in a happy state now. I appreciate your help.

> > Is it more typical to start with a blank repo when getting started with Flux?
> 
> It is totally valid to bootstrap with a pre-loaded repo but the repo needs to be prepared to be reconciled by Flux.

That's good to know!
