### ISSUE TITLE
After upgrading to v2.0.0-rc.1 and updating from v1beta2 to v1, the manifests are still created with v1beta2

### ISSUE THREAD

**Issue by ghost** [fluxcd/flux2#3788]
### Describe the bug

I've just upgraded to v2.0.0-rc.1, which went well, and then I changed the `apiVersion` in my manifests as described in the Upgrade Procedure of the release. For some reason, the manifests are still created in-cluster with `v1beta2` rather than `v1`.

### Steps to reproduce

1. Upgrade to v2.0.0-rc.1
2. Follow the Upgrade Procedure for v2.0.0-rc.1 changing the `apiVersion` from `v1beta2` to `v1` in the manifests
3. Observe that after a reconciliation (or even deleting the Flux objects and letting them be reconciled again), they are still being created in-cluster with `v1beta2` rather than `v1`

### Expected behavior

I was expecting to see the `apiVersion` updated to `v1`.

### OS / Distro

GKE Linux

### Flux version

v2.0.0-rc.1

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.25.7-gke.1000 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.32.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
How did you determined that the resources are created with the old version? Given the CRDs posted here it clearly shows v1.

**Comment by aristapimenta** [comment]
> This is due to kubectl CRD cache, you can explicitly ask for a version:
> 
> ```
> k get kustomizations.v1.kustomize.toolkit.fluxcd.io 
> ```

wow! awesome, thanks!! is there a way to clear the CRD cache?

**Comment by stefanprodan** [comment]
@aristapimenta you can delete `$HOME/.kube/cache` and kubectl will recreate it
