### ISSUE TITLE
Variable substitution not working in spec.commonMetadata

### ISSUE THREAD

**Issue by gavinclarkeuk** [fluxcd/flux2#3789]
### Describe the bug

We substitute numerous variables from a config map, however we're getting errors when we use the variables in spec.commonMetadata.

The error we are seeing is:
```
✗ Kustomization reconciliation failed: Kustomization/flux-system/custom-resources dry-run failed, reason: Invalid, error: Kustomization.kustomize.toolkit.fluxcd.io "custom-resources" is invalid: [metadata.labels: Invalid value: "${cluster_env}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata.labels: Invalid value: "${cluster_name}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

The custom-resources kustomization mentioned in the error doesn't have any labels specified directly, but is created by another kustomization with the below attributes in it's spec:

```yaml
  commonMetadata:
    labels:
      system-code: cluster-services
      environment: ${cluster_env}
      cluster-name: ${cluster_name}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
```

My guess is that the commonMetadata is being applied to the resources after the variable substitution, when it should be applied before.

### Steps to reproduce

- Install flux v2.0.0-rc1
- Create a config map with one or more varibles defiend in
- Create a kustomization which uses variable substitution from the config map to set spec.commonMetadata.labels
- Have the first kustomization deploy a second kustomization

### Expected behavior

The variable substitution should be applied correctly to the second kustomization.

### OS / Distro

N/A

### Flux version

v2.0.0-rc1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.10-eks-48e63af >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gavinclarkeuk** [comment]
We have multiple levels and this was causing issues all the way down, however we did have variables in the top level kustomization. Hardcoding those fixed the issue.

Prior to this upgrade (from 0.41.2)  we applied common labels to child objects via patches and there wasn't an issue with the substitution. That makes me thing the ordering these steps in are applied is subtly different. I'd guess that it goes patches, variables, common metadata. If variable substitution was always done last then it would give a bit more flexibility in where variables can be used.

**Comment by stefanprodan** [comment]
The common metadata is not done via Kustomize because those affect more things like selectors. The labels and annotations are added right before the server-side apply.

**Comment by gavinclarkeuk** [comment]
But you can patch labels and then use them in selectors.

I don't really mind if you just close this, as I've got my project working now, but it seems to me that the docs need clarifying to explain this. The description for the post build substitution talks about "variables to be substituted in the final YAML manifest". I'd expect the "final YAML manifest" to include the common metadata.

**Comment by stefanprodan** [comment]
> But you can patch labels and then use them in selectors.

The metadata is not patched, but set directly on the Kubernetes Go structs before apply. I will note this in the docs.
