### ISSUE TITLE
Flux cli 0.40 breaks "get image policy / image repository"

### ISSUE THREAD

**Issue by annaken** [fluxcd/flux2#3798]
### Describe the bug

In versions of the flux cli <= 0.39, I can do `flux get image policy` and `flux get image repository`, but in version >=0.40, this no longer works.

### Steps to reproduce

Version 0.40:
```
$ ./flux get image policy
✗ no matches for kind "ImagePolicy" in version "image.toolkit.fluxcd.io/v1beta2"
annaken-dub.dev.wgtwo.com[demos] ~/Downloads
$ ./flux get image repository
✗ no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1beta2"
```

### Expected behavior

Version 0.39:
```
$ ./flux get image policy
NAME                     	LATEST IMAGE                                                                           	READY	MESSAGE
my-app     	registry.com/my-app:dev-1234      	True 	Latest image tag for 'registry.com/my-app' resolved to: dev-1234

$ ./flux get image repository
NAME                     	LAST SCAN                	SUSPENDED	READY	MESSAGE
my-app     	2023-04-13T13:18:51+02:00	False    	True 	successful scan, found 19 tags
```

### OS / Distro

macOS 12.6

### Flux version

flux: v0.40.0

### Flux check

$ ./flux check
► checking prerequisites
✗ flux 0.40.0 <2.0.0-rc.1 (new version is available, please upgrade)
✔ Kubernetes 1.21.13 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.30.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
The API version has been bumped: https://github.com/fluxcd/flux2/releases/tag/v0.40.0

**Comment by annaken** [comment]
Oh! I totally missed the API change. Thanks!
