### ISSUE TITLE
Multiple flux instances installation issue

### ISSUE THREAD

**Issue by adityajoshi12** [fluxcd/flux2#3811]
I am trying to install multiple flux instances in a single cluster and installation is always getting failed. I am getting below error.
I am using flux version 0.36.0

```
Bootstrap failed at flux step with error - “◎ waiting for Kustomization \“flux-abc/flux-bval\” to be reconciled”,
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io dry-run failed, reason: Forbidden, error: http://customresourcedefinitions.apiextensions.k8s.io \“http://alerts.notification.toolkit.fluxcd.io\” is forbidden: User \“system:serviceaccount:flux-abc:kustomize-controller\” cannot patch resource \“customresourcedefinitions\” in API group \“http://apiextensions.k8s.io\” at the cluster scope”,
```
```
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io dry-run failed, reason: Forbidden, error: http://customresourcedefinitions.apiextensions.k8s.io \“http://alerts.notification.toolkit.fluxcd.io\” is forbidden: User \“system:serviceaccount:flux-besjwv:kustomize-controller\” cannot patch resource \“customresourcedefinitions\” in API group \“http://apiextensions.k8s.io\” at the cluster scope”
```
```
► cloning branch "b23" from Git repository "ssh://git@github.com/example/test.git"
✔ cloned repositor
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "bescylsdsv6123" ("1a3b2c76536170058841dfc22f60f131fa4bd9ea")
► pushing component manifests to "ssh://git@github.com/example/test.git"
► installing components in "flux-abc" namespace
✗ CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io dry-run failed, reason: Invalid, error: CustomResourceDefinition.apiextensions.k8s.io "alerts.notification.toolkit.fluxcd.io" is invalid: status.storedVersions[1]: Invalid value: "v1beta2": must appear in spec.versions
```

**Comment by makkes** [comment]
Bootstrapping different Flux instances on the same cluster is not a supported operation. Please take a look at our [guide on best practices for shared clusters](https://fluxcd.io/flux/security/best-practices/#additional-best-practices-for-shared-cluster-multi-tenancy).

**Comment by adityajoshi12** [comment]
> Bootstrapping different Flux instances on the same cluster is not a supported operation. Please take a look at our [guide on best practices for shared clusters](https://fluxcd.io/flux/security/best-practices/#additional-best-practices-for-shared-cluster-multi-tenancy).

is there a way, to skip the CRD installation at the time of flux setup and just only bootstrap. My usecase needs to have multiple flux instances in a single cluster.

**Comment by makkes** [comment]
> is there a way, to skip the CRD installation at the time of flux setup and just only bootstrap. My usecase needs to have multiple flux instances in a single cluster.

Not out of the box, no. What you can do is to remove the CRD manifests from `gotk-components.yaml` but keep in mind that subsequent runs of `flux bootstrap` will add them again so by doing this you're basically breaking out of the supported installation process and are on your own. 😉

**Comment by stefanprodan** [comment]
Please see https://fluxcd.io/flux/cheatsheets/sharding/
