### ISSUE TITLE
Liveness probes causing lots of restarts

### ISSUE THREAD

**Issue by aristapimenta** [fluxcd/flux2#3813]
### Describe the bug

Hi,

I have Flux in a few GKE clusters and the liveness probe is failing like this:

```
Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Normal   Created    13m (x8 over 47h)   kubelet  Created container manager
  Normal   Pulled     13m (x7 over 24h)   kubelet  Container image "ghcr.io/fluxcd/source-controller:v1.0.0-rc.1" already present on machine
  Normal   Killing    13m (x5 over 24h)   kubelet  Container manager failed liveness probe, will be restarted
  Normal   Started    13m (x8 over 47h)   kubelet  Started container manager
  Warning  Unhealthy  13m (x44 over 24h)  kubelet  Readiness probe failed: Get "http://240.160.3.25:9090/": dial tcp 240.160.3.25:9090: connect: connection refused
  Warning  Unhealthy  13m (x19 over 24h)  kubelet  Liveness probe failed: Get "http://240.160.3.25:9440/healthz": dial tcp 240.160.3.25:9440: connect: connection refused
```

And causing lots of restarts across many clusters:

```
cloud-dev
NAME                                           READY   STATUS    RESTARTS      AGE
helm-controller-65fc454c55-4xv6t               1/1     Running   6 (22h ago)   7d3h
image-automation-controller-6499959f59-v25hk   1/1     Running   6 (22h ago)   7d3h
image-reflector-controller-8446dc766b-nmmrj    1/1     Running   6 (22h ago)   7d3h
kustomize-controller-6f8f78f589-v5rrs          1/1     Running   6 (22h ago)   7d3h
notification-controller-6cc8544455-d5nsg       1/1     Running   6 (22h ago)   6d
source-controller-c54dc854f-vl2kd              1/1     Running   6 (22h ago)   29h
tf-controller-7fcd95c847-vx2q9                 1/1     Running   6 (22h ago)   29h
cv-dev
NAME                                           READY   STATUS    RESTARTS        AGE
helm-controller-65fc454c55-lgjc6               1/1     Running   6 (3h41m ago)   26h
image-automation-controller-6499959f59-dqvz4   1/1     Running   6 (3h41m ago)   26h
image-reflector-controller-8446dc766b-srfxj    1/1     Running   5 (3h41m ago)   26h
kustomize-controller-6f8f78f589-49blz          1/1     Running   5 (3h41m ago)   26h
notification-controller-6cc8544455-wjtpl       1/1     Running   5 (3h41m ago)   25h
source-controller-c54dc854f-c2xmp              1/1     Running   6 (3h41m ago)   27h
cv-dev-2
NAME                                           READY   STATUS    RESTARTS        AGE
helm-controller-65fc454c55-h8h2t               1/1     Running   6 (157m ago)    3h51m
image-automation-controller-6499959f59-9rz6q   1/1     Running   5 (158m ago)    3h51m
image-reflector-controller-8446dc766b-nwlkg    1/1     Running   28 (158m ago)   4d14h
kustomize-controller-6f8f78f589-tlc22          1/1     Running   24 (157m ago)   3d12h
notification-controller-6cc8544455-4x4w2       1/1     Running   30 (157m ago)   4d19h
source-controller-c54dc854f-htjfk              1/1     Running   23 (157m ago)   3d12h
cv-infra
NAME                                           READY   STATUS    RESTARTS   AGE
helm-controller-65fc454c55-hzbpd               1/1     Running   0          7d3h
image-automation-controller-6499959f59-t64zx   1/1     Running   0          7d3h
image-reflector-controller-8446dc766b-cvtp9    1/1     Running   0          7d3h
kustomize-controller-6f8f78f589-8kllx          1/1     Running   0          7d3h
notification-controller-6cc8544455-qdxg9       1/1     Running   0          7d3h
source-controller-c54dc854f-x5f6z              1/1     Running   0          7d3h
tf-controller-7fcd95c847-7vv7j                 1/1     Running   0          11d
cv-play
NAME                                           READY   STATUS    RESTARTS       AGE
helm-controller-65fc454c55-blmsl               1/1     Running   22 (24h ago)   5d8h
image-automation-controller-6499959f59-bmr5t   1/1     Running   11 (24h ago)   3d22h
image-reflector-controller-8446dc766b-ft568    1/1     Running   0              22h
kustomize-controller-6f8f78f589-nwcq2          1/1     Running   0              21h
notification-controller-6cc8544455-g5mth       1/1     Running   0              16h
source-controller-c54dc854f-brfqd              1/1     Running   11 (24h ago)   3d22h
cv-play-aeris
NAME                                           READY   STATUS    RESTARTS       AGE
helm-controller-746889d448-zn9f8               1/1     Running   10 (13m ago)   47h
image-automation-controller-654b75df84-rv7qb   1/1     Running   10 (13m ago)   25h
image-reflector-controller-588c4676b7-j86ts    1/1     Running   11 (12m ago)   25h
kustomize-controller-99c4d84bd-wgbbn           1/1     Running   5 (13m ago)    14h
notification-controller-66d964799d-9w7zx       1/1     Running   5 (13m ago)    14h
source-controller-7ccc5d646-rm46c              1/1     Running   10 (13m ago)   47h
cv-staging
NAME                                           READY   STATUS    RESTARTS      AGE
helm-controller-65fc454c55-t97xk               1/1     Running   6 (23h ago)   7d3h
image-automation-controller-6499959f59-vsnmv   1/1     Running   6 (23h ago)   7d3h
image-reflector-controller-8446dc766b-dkvvv    1/1     Running   6 (23h ago)   7d3h
kustomize-controller-6f8f78f589-6456t          1/1     Running   6 (23h ago)   7d3h
notification-controller-6cc8544455-xpvq9       1/1     Running   6 (23h ago)   7d3h
source-controller-c54dc854f-48h8r              1/1     Running   6 (23h ago)   7d3h
```

This is the liveness and readiness configuration:

```
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
```

What could be reason for the healthchecks to fail with `connection refused`? Could this configuration be too tight? Should I try to increase the failure count toleration?

### Steps to reproduce

Not sure how to reproduce.

### Expected behavior

Liveness probe wouldn't fail this easily.

### OS / Distro

GKE Linux

### Flux version

v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.7-gke.1000 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.32.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aristapimenta** [comment]
Additionally, when I try to see logs from previous execution with `k logs -p` there are no logs. :thinking:

**Comment by aristapimenta** [comment]
Thanks for the advice @hiddeco!

What is exactly the impact associated with the errors above? Does Flux become unavailable while having this issue, i.e. stops reconciling? How bad really are these restarts? I'm wondering if making it harder for the liveness probe to restart the pod can actually make Flux unavailable for longer rather than improving the situation. If Flux handles those shutdowns gracefully then I think the restarts may actually be a good thing :thinking: Does that make sense?

**Comment by hiddeco** [comment]
> What is exactly the impact associated with the errors above? Does Flux become unavailable while having this issue, i.e. stops reconciling?

Given almost everything Flux does (including starting a reconciliation attempt which retrieves the latest generation of the object) relies on the API server being available, most of what any of the components do will stop working for as long as the server is unavailable. Not limited to the in-process reconciliations failing at some point, as they either can't issue a patch to the API server about any Status updates of the object being reconciled, or can't do what they're designed to do (e.g. (dry-run) applies, Helm upgrades, etc.).

> How bad really are these restarts?

They should generally be harmless as the design of Kubernetes and our controllers is to reach eventual consistency. However, your mileage may vary here as the scheduling of Pods can take an additional amount of time, and/or a restart may have an impact on components like the source-controller when not backed by a Persistent Volume, as it would need to reconcile all Source objects to reproduce the Artifact before they can be consumed again.

**Comment by aristapimenta** [comment]
Given this analysis I think adding a Persistent Volume to my source-controller is a more important thing to do right now rather than making k8s take more time to restart the pods when they would probably benefit from that. Thanks for the explanation!!!
