### ISSUE TITLE
Cannot apply kustomization from GitHub

### ISSUE THREAD

**Issue by darviche** [fluxcd/flux2#3845]
### Describe the bug

When I try to install awx-operator with the Kustomize [method](https://github.com/ansible/awx-operator#basic-install), I get the following error : 
```shell
✗ Kustomization reconciliation failed: kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'https://github.com/ansible/awx-operator/config/default?ref=2.0.1': URL is a git repository': git cmd = '/usr/bin/git fetch --depth=1 origin 2.0.1': exit status 128
```
However, there is no issue with ```kustomize build```

I did see the proposed solution in https://github.com/fluxcd/flux2/issues/3127#issuecomment-1256034594

### Steps to reproduce

1-Include the following **kustomization.yaml** file
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/ansible/awx-operator/config/default?ref=2.0.1

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.0.1

namespace: awx
```
2. Apply the reconciliation

### Expected behavior

Manifests would be fetched from GitHub.

### OS / Distro

Arch Linux

### Flux version

v0.41.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► docker-proxy-asis-ghcr.repos.tech.orange/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► docker-proxy-asis-ghcr.repos.tech.orange/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► docker-proxy-asis-ghcr.repos.tech.orange/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► docker-proxy-asis-ghcr.repos.tech.orange/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Additional context

```shell
root@vm:~# flux version
flux: v0.41.2
helm-controller: v0.31.2
kustomize-controller: v0.35.1
notification-controller: v0.33.0
source-controller: v0.36.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
Tried to reproduce, to not avail. Everything worked perfectly fine in my environment.

**Comment by stefanprodan** [comment]
Looks like a network issue, please use https://github.com/fluxcd/flux2/issues/3127#issuecomment-1255376483
