### ISSUE TITLE
Fluxcd refuses to bootstrap after flux uninstall

### ISSUE THREAD

**Issue by fabszabo** [fluxcd/flux2#3859]
### Describe the bug

Bootstrapping flux works great on a fresh cluster. But flux got stuck, but that's a topic for another bug report. So I tried to uninstall and bootstrap flux again, but it just refuses to work.

The error is similar to this: https://github.com/fluxcd/flux2/discussions/2362

But why does it work fine on the first install? I provide my personal access token and flux creates a deploy key just like on the first install. But it refuses to connect with it.
Message:               failed to checkout and determine revision: unable to clone 'ssh://git@github.com/.../infrastructure': dial tcp ...:22: connect: connection timed out

### Steps to reproduce

Bootstrap flux:
flux bootstrap github \
--owner=... \
--repository=infrastructure \
--branch=master \
--path=clusters/staging \

Provide Personal Access Token.

Uninstall flux:
flux uninstall

Bootstrap flux again: ❌ Doesn't work.

### Expected behavior

It should bootstrap normally.

### OS / Distro

macOS 13.3.1

### Flux version

flux: v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.10-gke.2300 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

GCR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> dial tcp ...:22: connect: connection timed out

This looks like DNS is broken on your cluster, make sure CNI, CoreDNS and external DNS resolutions for github.com are working.

**Comment by fabszabo** [comment]
Thanks for the quick reply. I wonder if the current GitHub issues are causing this? (https://www.githubstatus.com/)

**Comment by fabszabo** [comment]
Thank you! It was a DNS issue.
