### ISSUE TITLE
flux bootstrap gitlab ignores --owner when creating the repo

### ISSUE THREAD

**Issue by abderrahim** [fluxcd/flux2#3867]
### Describe the bug

Following the installation guide for gitlab to create my first flux repo, the repo is created in the wrong location (under my username) rather than the group specified with `--owner`.

### Steps to reproduce

I ran the following command: 
`flux bootstrap gitlab --hostname gitlab.codethink.co.uk --owner software-factory/playground/abderrahim --repository flux-test1 --token-auth --personal`

I got the following output
```
► connecting to https://gitlab.codethink.co.uk
✔ repository "https://gitlab.codethink.co.uk/software-factory/playground/abderrahim/flux-test1" created
► cloning branch "main" from Git repository "https://gitlab.codethink.co.uk/software-factory/playground/abderrahim/flux-test1.git"
⚠️  clone failure: unable to clone: repository not found: git repository: 'https://gitlab.codethink.co.uk/software-factory/playground/abderrahim/flux-test1.git'
⚠️  clone failure: unable to clone 'https://gitlab.codethink.co.uk/software-factory/playground/abderrahim/flux-test1.git': repository already exists
✗ failed to clone repository: unable to clone 'https://gitlab.codethink.co.uk/software-factory/playground/abderrahim/flux-test1.git': repository already exists
```

### Expected behavior

It should work, creating the repository and setting it up.

Instead, the repository was created under my username (rather than the group I specified), and subsequently cloning it failed. 

This might be due to the fact I was using a personal token rather than a project/group token, but it should either figure it out or explicitly throw an error.

### OS / Distro

Debian testing

### Flux version

2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.26.3 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

### Git provider

gitlab entreprise

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Can you please using `flux bootstrap git --url`? You'll need to set the deploy key by hand but it should unblock you until we figure out a fix.

**Comment by abderrahim** [comment]
I forgot to update this. I got it working by using `--deploy-token-auth` as recommended in the [gitlab documentation](https://docs.gitlab.com/ee/user/clusters/agent/gitops/flux_tutorial.html#create-the-flux-repository) instead of `--token-auth --personal` as recommended in the [flux documentation](https://fluxcd.io/flux/installation/#gitlab-and-gitlab-enterprise).

Not sure what to make of this, but at least I'm not blocked.

**Comment by stefanprodan** [comment]
@abderrahim we also have `--deploy-token-auth` in docs, it's right there in the link you posted.

**Comment by somtochiama** [comment]
@abderrahim The `--personal` flag tells flux to create the repository on your personal account. It should work if you only `--token-auth`. The documentation says:

> Run the bootstrap for a repository on your personal GitLab account: 
>
> flux bootstrap gitlab \
  --owner=my-gitlab-username \

However, I think the UX in the CLI should be improved to either return a better error or use the personal repository url when a group is specified instead of a username (and maybe the docs should be updated too, to tell the user to look further down the page for the cli command if the repository is under a group)
