### ISSUE TITLE
Kustomization Resource Dry-Run Fails for Kind ClusterClass

### ISSUE THREAD

**Issue by kdnash82** [fluxcd/flux2#3874]
### Describe the bug

When attempting to apply a ClusterClass resource using Flux v2 Kustomization, the dry-run validation fails with the error message: "no matches for kind 'ClusterClass' in version 'cluster.x-k8s.io/v1beta1'". The ClusterClass kind is available in the management cluster, and the API version is listed as installed.

### Steps to reproduce

Cluster API Version=1.2.8
- Create directory with `kustomization.yaml` file
- Create ClusterClass resource file (apiVersion: cluster.x-k8s.io/v1beta1) and add to directory.
- Create Kustomization resource file that applies ClusterClass resource file
- Apply Kustomization resource file
- `kubectl get kustomization -A`
```
dry-run failed, error: no matches for kind "ClusterClass" in version "cluster.x-k8s.io/v1beta1
```
- `kubectl api-resources`
```
NAME              SHORTNAMES          APIVERSION                       NAMESPACE       KIND
clusterclasses          cc              cluster.x-k8s.io/v1beta1        true            ClusterClass
clusters                cl              cluster.x-k8s.io/v1beta1        true            Cluster
```

- `kubectl kustomize <directory> | kubectl apply  -f -`
-  ClusterClass resource file applied successfully

### Expected behavior

- Apply Kustomization resource
- `kubectl get kustomization -A`
```
Ready=True
Status= Applied revision: name@sha1:UID
```

### OS / Distro

Ubuntu 20.04

### Flux version

flux: v2.0.0-rc.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.10+vmware.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Hmm this may be an issue with the Kubernetes OpenAPI cache as I can't reproduce this on Kind and GKE. Can you please try killing the kustomize-controller pod and see if it recovers after that?

**Comment by somtochiama** [comment]
> The ClusterClass kind is available in the management cluster

Is the Flux Kustomization applying it to a different cluster? If it is, Is the ClusterClass kind available on that cluster?
