### ISSUE TITLE
Flux unable to clone

### ISSUE THREAD

**Issue by nisanthreddy** [fluxcd/flux2#3889]
### Describe the bug

Flux is unable to clone to a bitbucket repository saying error: certificate 

### Steps to reproduce

Installed flux using "brew install flux"

Bootstrapped flux using the following command
flux bootstrap git \
- --git-url=ssh://git@bitbucket.org \
- --branch
- --private-key=ssh/id_rsa \
- --path=/

### Expected behavior

Flux should clone into the repository 

### OS / Distro

Linux

### Flux version

v0.16.1

### Flux check

► checking prerequisites
✗ flux 0.37.0 <2.0.0-rc.3 (new version is available, please upgrade)
✔ Kubernetes 1.25.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
`--git-url` is not an existing flag, it should be `--url`.
