### ISSUE TITLE
Unable to clone Azure DevOps repo: status code: 400

### ISSUE THREAD

**Issue by somtochiama** [fluxcd/flux2#3936]
### Describe the bug

Bootstrapping Flux or creating a GitRepository with an Azure DevOps repository fails with `400` status code error:

```
 flux bootstrap git --url=https://somtochi0669@dev.azure.com/somtochi0669/e2e/_git/fleet-infra-e2e-growing-grub --password=$AZURE_DEVOPS_PAT --path=clusters/my-cluster
► cloning branch "main" from Git repository "https://somtochi0669@dev.azure.com/somtochi0669/e2e/_git/fleet-infra-e2e-growing-grub"
⚠️  clone failure: unable to clone 'https://somtochi0669@dev.azure.com/somtochi0669/e2e/_git/fleet-infra-e2e-growing-grub': unexpected client error: unexpected requesting "https://somtochi0669@dev.azure.com/somtochi0669/e2e/_git/fleet-infra-e2e-growing-grub/git-upload-pack" status code: 400
```

### Steps to reproduce

1. Bootstrap Flux with an Azure DevOps Repo

### Expected behavior

Flux bootstraps successfully

### OS / Distro

N/A

### Flux version

flux: v2.0.0-rc.4

### Flux check

► checking prerequisites
✔ Kubernetes 1.26.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.4
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Azure DevOps

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Fixed via #3943
