### ISSUE TITLE
substituteFrom does not handle periods in the key of a configmap

### ISSUE THREAD

**Issue by warroyo** [fluxcd/flux2#3959]
### Describe the bug

when using substituteFrom in a kustomziation to refer to a configMap, it will error out if there is a key that has a `.` in it. for example:
```
data:
  cluster_name: example-flux
  tls.crt: <cert value here>
```

the error from the Kustomziation is:

``` 
 Kustomization reconciliation failed: var substitution failed for 'cluster-gitops': YAMLToJSON: 'tls.crt' var name is invalid, must match '^[_[:alpha:]][_[:alpha:][:digit:]]*$'
 ```

### Steps to reproduce

1. create a configmap with a key that has a `.` in it. 
2. create a kustomization that refers to that configmap and uses substituteFrom

### Expected behavior

it doesn't break

### OS / Distro

mac

### Flux version

N/A

### Flux check

N/A

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
This is by design, and also noted in the documentation.

> Note: The name of a variable can contain only alphanumeric and underscore characters. The controller validates the variable names using this regular expression:` ^[_[:alpha:]][_[:alpha:][:digit:]]*$`.

https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution
