### ISSUE TITLE
Deploy without a CNI

### ISSUE THREAD

**Issue by maxpain** [fluxcd/flux2#3960]
Hello. What about this? In our cases, it will be extremely useful.
https://github.com/fluxcd/flux2/discussions/3070

Please provide manifests with hostNetwork

**Comment by stefanprodan** [comment]
Please see https://github.com/stefanprodan/flux-aio

**Comment by maxpain** [comment]
@stefanprodan Is it possible to install `flux-aio` without using `timoni`? I just need kustomize manifests.

**Comment by stefanprodan** [comment]
Sure, there is a build command that gives you the YAMLs
