### ISSUE TITLE
Cannot push OCI artifacts to ghcr by following the official documentation

### ISSUE THREAD

**Issue by ameyp** [fluxcd/flux2#3969]
### Describe the bug

I followed https://github.com/fluxcd/flux2/tree/main/action#push-kubernetes-manifests-to-container-registries and created an action with nearly identical contents. However, the `flux push artifact ...` step fails with:

```
pushing artifact failed: pushing artifact failed: HEAD https://ghcr.io/v2/ameyp/manifests/k3s-cluster/blobs/sha256:994b1a57917cbabb64fc705a801940f38b5a55d3104150bacc079affb5da5ee3: unexpected status code 403 Forbidden (HEAD responses have no body, use GET for details)
```

If I run the same command locally after logging in to ghcr.io with `docker login` and a GH PAT, the `push artifact` command succeeds. It also works with quay.io and a user password, which leads me to believe that this is specifically a problem with ghcr.io and `GITHUB_TOKEN`.

In my repository's Settings -> Actions -> General -> Workflow permissions, I have enabled "Read and Write permissions".

### Steps to reproduce

https://github.com/ameyp/k3s-cluster/blob/3edb63ce394643a0a4d662bdd5e6797bae452f17/.github/workflows/build-cdk8s.yaml

### Expected behavior

The push is successful

### OS / Distro

ubuntu-latest on GH Actions

### Flux version

2.0.0-rc.5

### Flux check

N/A

### Git provider

GitHub (Individual)

### Container Registry provider

GitHub Packages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ameyp** [comment]
Worked after:
- Going to my profile package, Packages tab, finding the package that was created, and associating it with the above repository
- Adding the repository to the package's permissions under Actions, and giving it the Write role
- Changing the package's visibility to Public

This got me a new error:

```
pushing artifact failed: pushing artifact failed: POST https://ghcr.io/v2/ameyp/manifests/k3s-cluster/blobs/uploads/: DENIED: installation not allowed to Write organization package
```

I then realized that I had set a top-level `packages: write` permission for the workflow, and then accidentally overridden it for the job while copy-pasting a snippet. Removing that job-level permission fixed the problem, and the push succeeded.

**Comment by makkes** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-in-a-github-actions-workflow has the documentation for how to setup workflows that push to GHCR.
