### ISSUE TITLE
Fluxcd is not able to pick the changes

### ISSUE THREAD

**Issue by Subhasish5** [fluxcd/flux2#3987]
Fluxcd is not able to pick the changes whenever we are making the commits to master branch.

flux logs is telling the below error :

2023-06-20T07:00:35.576Z error Kustomization/flux-system.flux-system - Reconciliation failed after 385.615547ms, next try in 10m0s failed to decode Kubernetes YAML from /tmp/kustomization-228772640/fluxcd/devm/exstream/helmRelease-exstream.yml: MalformedYAMLError: yaml: line 22: mapping values are not allowed in this context <nil>

And when we manually checked the yaml there was no error as such in it.

We tried to suspend it and resume it and again made a commit to the master branch but no results.

Please help further.

Thanks and Regards,
Subhasish

**Comment by somtochiama** [comment]
Can you try running `kustomize build` in that directory locally?
and what does the yaml look like?

**Comment by Subhasish5** [comment]
now we have been able to solve that issue...and again we are facing a different issue now...

The issue is : "client rate limiter Wait returned an error: context deadline exceeded"

Even after making a few changes to the github repository in the master branch, fluxcd is not able to pick the changes...

Also when we are trying to reconcile flux manually also, it's showing this error.

![image](https://github.com/fluxcd/flux2/assets/46413003/1a3c692f-fadd-4992-9cb0-9f13df6aee6d)

How to fix this issue.

Thanks and Regards,
Subhasish

**Comment by Subhasish5** [comment]
> Can you try running `kustomize build` in that directory locally? and what does the yaml look like?

Please help as this is blocking us

**Comment by makkes** [comment]
> > Can you try running `kustomize build` in that directory locally? and what does the yaml look like?
> 
> Please help as this is blocking us

We are trying to help but you're not answering the questions.

**Comment by Subhasish5** [comment]
I tried running kustomize build from my local in the same directory where the kustomization.yml file resides...no changes happened... and below is how our kustomization.yaml looks like : 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
Please help as this is blocking our production

**Comment by Subhasish5** [comment]
@makkes @somtochiama  could you please look into it

**Comment by Subhasish5** [comment]
everything looks fine including helm reconciliation, flux logs, flux events, but still the changes which we are committing are not getting deployed on the cluster...please help

**Comment by makkes** [comment]
This issue has taken some turns so please let's structure this a little. Please bear in mind that the only person that has all the context is you, @Subhasish5. We don't know anything about your system, that's why we've been asking you for information on it. Since you've been posting different errors now, let's please start from scratch:

- What is the thing that does not work? What is happening and what do you expect to happen? Please provide exact steps here so that we can understand your issue better.
- What is the output of `flux get all`?

**Comment by Subhasish5** [comment]
@makkes we have fluxcd configured for each environments in our local git repository. Hence ideally whenever we are making some changes to the helmrelease.yml files in the master branch, the changes should be picked up and should be deployed on to the aks cluster where our application is hosted.

We see that there is no issue with fluxcd reconciliation of those helmreleases, in flux events , flux logs and flux kustomizations, no where we are finding any issue...but still the changes are not getting picked up by fluxcd and deployed on to the aks cluster.

The flux get all output seems to be all fine : 

helmrepository/bitnami          4280c045        False           True    stored artifact for revision '4280c045'
helmrepository/jetstack         04d8e68c        False           True    stored artifact for revision '04d8e68c'
helmrepository/pgadmin4                         False           True    Helm repository is ready
helmrepository/prometheus       baeeac09        False           True    stored artifact for revision 'baeeac09'
helmrepository/vmware-tanzu     3b5c52c3        False           True    stored artifact for revision '3b5c52c3'

And apart from this everything seems to be fine.

Please help.

Thanks and Regards,
Subhasish

**Comment by makkes** [comment]
Judging by the output you gave you don't have a single source defined on your cluster from where Flux could pull your changes. How would you expect it to know where you're maintaining your manifests? Please take a look at https://fluxcd.io/flux/installation/#bootstrap to see how to properly bootstrap Flux.

**Comment by Subhasish5** [comment]
@makkes that's half of the output I gave...please find the complete output...

please let me know if you find anything :

[flux-get-all.txt](https://github.com/fluxcd/flux2/files/11848052/flux-get-all.txt)

**Comment by somtochiama** [comment]
> everything looks fine including helm reconciliation, flux logs, flux events, but still the changes which we are committing are not getting deployed on the cluster...please help

From your `flux get all` everything does look fine.
I see you have only one kustomization. Which changes aren't being deployed on the cluster?
i.e which folders are you adding the yaml files to?

**Comment by Subhasish5** [comment]
@somtochiama we have a fluxcd folder in our GitHub repository within the folders for environments are there. And within which we have application folders and a dedicated helm folder for each application charts and also a separate folder for flux-system.so whenever we make any changes to the helm charts for any application or any version over there,the changes get picked by fluxcd and get deployed on aks cluster.Thoigh every thing looks fine,still I am not sure why the changes are not getting triggered.

**Comment by Subhasish5** [comment]
Can we align over a call to have a more understanding on this please

**Comment by makkes** [comment]
@Subhasish5 there is only so much we can do as maintainers. If you need premium support I would suggest looking into commercial options such as those offered by Weaveworks (my employer). Otherwise there's lots of documentation at https://fluxcd.io, including tutorials, webinars etc.

**Comment by Subhasish5** [comment]
@makkes at least what could be the potential reason that fluxcd is not able to pick the changes even when everything is fine

**Comment by kingdonb** [comment]
@Subhasish5 I would like to refer you to our Support page for options to obtain Flux training and support:

https://fluxcd.io/support/

In it, we have another section where we list guidelines about where it is appropriate to seek out individualized support that is not formulated as a bug report, and I'm afraid the issues queue isn't such a place.

https://fluxcd.io/support/#getting-help-from-the-flux-community

> As we have been overwhelmed with general questions, troubleshooting requests, feature requests, etc. in the past months, we would like to ask you to:

> Read the [documentation](https://fluxcd.io/flux/get-started/) carefully, check the individual troubleshooting sections for advice on how to interpret logs, use relevant tools, etc.
> For Flux questions, see if there are answers on the [GH Discussions page](https://github.com/fluxcd/flux2/discussions)
> Please don’t direct-message project maintainers or relevant others with specific support questions.

Thank you for using Flux!

> Support for Flux users and community is mostly provided by volunteers, who are all on equal footing as peers in the Flux community. This implies that (free) support is provided on a best-effort basis, with no SLA or quality-of-service guarantee.

There are more appropriate forums than the Flux bug queue for your support inquiry, including those that are supported by community. You may be able to find someone who can help you debug interactively in the Flux/CNCF slack, as a suggestion. If there are non-bugs or issues that are specific to your deployment of Flux, those would be above and beyond what is to be expected from the community to support. Please do not misuse the issue queue in this manner.
