### ISSUE TITLE
helm chart updates are not being picked up by flux

### ISSUE THREAD

**Issue by Subhasish5** [fluxcd/flux2#3992]
We have helm charts in master branch where fluxcd has been configured.

But because of some reason, even if we are changing the chart version we can see flux is not able to pick the changes.

Can you please help.

Thanks and Regards,
Subhasish

**Comment by makkes** [comment]
You're not providing any information anyone could use to help you with your issue. If you want to file a bug, please go to https://github.com/fluxcd/flux2/issues/new/choose and fill out the appropriate form, providing the information that's asked for.
