### ISSUE TITLE
Absolute domain name ( cluster.local. with ending dot) is unfriendly to common no_proxy configs

### ISSUE THREAD

**Issue by gberche-orange** [fluxcd/flux2#4009]
### Describe the bug

In https://github.com/fluxcd/flux2/commit/139bbbb87c0130ab4f5e0b4a69b617a59b17cfa9 the url used for contacting source controller becomes `http://notification-controller.flux-system.svc.cluster.local./` with the trailing dot.

While apparently a legal FQDN, urls with leading dots are very unusual. Therefore flux installations which use http proxy, would generally exclude with a no_proxy variable `.svc.cluster.local` but not `.svc.cluster.local.` (with a trailing dot). As a result, some flux installations may fails unexpectedly route internal traffic to the http proxy. Such proxy would then reject requests for unknown internal fqdn `notification-controller.flux-system.svc.cluster.local`

See https://webmasters.stackexchange.com/a/106527/136666 for more background on RFC history explaining that this is a grey area in specs, but definitively unusual practice.

Also flux container images don't contain curl binary, so testing the url requires to reproduce into another container and reproduce the exact same http_proxy and no_proxy variable to reproduce and diagnose mis routing to http proxy.

### Steps to reproduce

Install flux with http_proxy variable set and no_proxy set to `.cluster.local`

### Expected behavior

don't use FQDN with trailing dot

### Screenshots and recordings

helm controller logs:
```
failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./helmchart/flux-system/flux-system-nginx/nginx-ingress-controller-9.7.2.tgz giving up after 10 attempt(s)
```

source controller logs
```
#logs from source-controller: 
{"level":"error","ts":"2023-06-08T12:50:43.184Z","msg":"unable to record event","name":"flux-system-nginx","namespace":"flux-system","reconciler kind":"HelmChart","error":"POST http://notification-controller.flux-system.svc.cluster.local./ giving up after 5 attempt(s): unexpected HTTP status 503 Service Unavailable"} {"level":"info","ts":"2023-06-08T12:50:43.184Z","msg":"pulled 'nginx-ingress-controller' chart with version '9.7.2'","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":\{"name":"flux-system-nginx","namespace":"flux-system"}

,"namespace":"flux-system","name":"flux-system-nginx","reconcileID":"a9d0379a-9a21-4a1b-9cbb-a79d18a56c2e"}
```

### OS / Distro

N/A

### Flux version

0.41.2

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
We've documented here how to setup HTTP/S proxies https://fluxcd.io/flux/cheatsheets/bootstrap/#using-https-proxy-for-egress-traffic.

The ending dot is to reduce the CoreDNS lookups, reverting this and degrading Flux is not something that I would consider.

**Comment by gberche-orange** [comment]
Thanks for the explanation, makes sense, and sorry for the noise. Cross referencing related threads that I overlooked
* https://github.com/fluxcd/website/pull/848
* https://github.com/fluxcd/kustomize-controller/issues/569
* https://github.com/fluxcd/helm-controller/issues/415

and more related background
* http://www.dns-sd.org/trailingdotsindomainnames.html Trailing Dots in Domain Names
* https://www.suse.com/support/kb/doc/?id=000020020 How to improve DNS resolution performance inside a kubernetes cluster?
