### ISSUE TITLE
flux diff command does not return exit code 1 for deleted resources

### ISSUE THREAD

**Issue by BlackDark** [fluxcd/flux2#4066]
### Describe the bug

For me the diff works the outputs contains the deleted resources but the exit code is not as expected 1 instead it is just 0.

```bash
flux diff kustomization permissions --namespace mynamespace --path flux/releases/permissions/overlays/dev
✓  Kustomization diffing...
► RoleBinding/mynamespace/myrole-admin-test deleted

echo $?
0 # imho should be 1 here
```

### Steps to reproduce

1. apply a kustomization with a resource
2. delete resource
3. check diff
4. `echo $?`

### Expected behavior

Exit code should be 1

### OS / Distro

Linux

### Flux version

2.0.0

### Flux check

► checking prerequisites
✗ Kubernetes version v1.23.17+16bcd69 does not match >=1.24.0-0
► checking controllers
► checking crds
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
I @BlackDark this is solved in this pr: https://github.com/fluxcd/flux2/pull/4062
