### ISSUE TITLE
"$ flux check --pre" not working with multiple config files in $KUBECONFIG

### ISSUE THREAD

**Issue by ilkimo** [fluxcd/flux2#4079]
### Describe the bug

When trying to initialize FluxCD following the Get Started (https://fluxcd.io/flux/get-started/), the command "$ flux check --pre" gives an error (shown below) if the env variable $KUBECONFIG contains multiple configuration files chained with ':'.

► checking prerequisites
✔ kubectl 1.27.3 >=1.18.0
✗ Kubernetes client initialization failed: stat /home/<user>/.kube/config:/home/<user>/.kube/other_config.yaml: no such file or directory

I wouldn't expect this to be an issue, but it could also not be a good practice to have different kubernets context files pointed by $KUBECONFIG. If that's the case (or if this is not the right place to point this out), just let me know and close this issue :)

### Steps to reproduce

1. $ export KUBECONFIG=~/.kube/config:~/.kube/other_config.yaml
2. $ flux check --pre

### Expected behavior

Output something like:
► checking prerequisites
✔ kubectl 1.27.3 >=1.18.0
✔ Kubernetes 1.26.3 >=1.16.0
✔ prerequisites checks passed

With possibly some minor version differences

### OS / Distro

Manjaro Linux

### Flux version

N/A

### Flux check

► checking prerequisites
✔ kubectl 1.27.3 >=1.18.0
✗ Kubernetes client initialization failed: stat /home/user/.kube/config:/home/user/.kube/other_config.yaml: no such file or directory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
Please specify the Flux CLI version as requested in the issue template above. Flux follows the same loading semantics as `kubectl` so if the latter works, Flux CLI also will.

What happens if you run the following command?

```
KUBECONFIG=/.kube/config:/.kube/other_config.yaml kubectl cluster-info
```

**Comment by kingdonb** [comment]
If you find this issue recurs on a current release, we can reopen it.

Closing for now.
