### ISSUE TITLE
Add `bootstrap gitea` command

### ISSUE THREAD

**Issue by makkes** [fluxcd/flux2#4080]
As a Flux user I want to use the `bootstrap gitea` command to bootstrap Flux against a repository hosted by a [Gitea](https://about.gitea.com/) instance. The command shoould follow the same semantics as the other provider-specific bootstrap commands.

**Comment by makkes** [comment]
@sbdtu5498, I have assigned you this issue. Feel free to reach out on Slack in case you have any questions.

**Comment by takirala** [comment]
/assign

i can take a stab at this :)

**Comment by takirala** [comment]
/unassign 

Ah @Azhovan beat me to it, i ll let him proceed with #4270

**Comment by Azhovan** [comment]
@makkes I think we should close this since PR was merged.
