### ISSUE TITLE
Label `app.kubernetes.io/part-of: flux` is missing

### ISSUE THREAD

**Issue by mrmartan** [fluxcd/flux2#4081]
### Describe the bug

Flux pods miss the label `app.kubernetes.io/part-of: flux`. I suspect this is since updating to kustomize v5. The label is present on deployments but is missing from `.spec.template.metadata.lables` and `.spec.selector.matchLabels`.

### Steps to reproduce

1. install flux using bootstrap
1. run the following commands

```
$ flux check
► checking prerequisites
✔ Kubernetes 1.24.13 >=1.24.0-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✗ check failed

$ flux logs
✗ no Flux pods found in namespace "flux-system"

$ kubectl get pods -n flux-system
NAME                                       READY   STATUS    RESTARTS   AGE
helm-controller-6bf8874487-wr65w           1/1     Running   0          27m
kustomize-controller-7f6cc5b5df-k6qn9      1/1     Running   0          27m
notification-controller-65f87f44fd-jmsbn   1/1     Running   0          27m
source-controller-68d4c8ffdb-rkvl2         1/1     Running   0          27m
ww-gitops-weave-gitops-58548c9845-9fnvj    1/1     Running   0          22m
```

### Expected behavior

The label is present so that flux commands that rely on it to select flux resources work properly.

### Screenshots and recordings

<img width="493" alt="image" src="https://github.com/fluxcd/flux2/assets/2376580/814cb1e1-e312-4d7e-b7e5-ba5d77cded06">

### OS / Distro

macOS 13

### Flux version

v.2.0.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.13 >=1.24.0-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrmartan** [comment]
Sorry for putting my speculation on it.

If it was never on the pods, how does fluc-cli select them?

Does the notification-controller I posted look right to you?

**Comment by mrmartan** [comment]
I see. What do you think the problem could be?

Flux itself work, just flux CLI, the `check` and `logs` commands don't. `uninstall` works. I have not tried many others.

**Comment by mrmartan** [comment]
So, we have done a clean install of Flux and the issue is resolved. The previous one was na upgrade from 2.0.0-rc.3

**Comment by stefanprodan** [comment]
It may be related to Kustomize 5.0 deprecations that weren’t fully addressed in RC.3. Glad to see GA works fine.
