### ISSUE TITLE
GitRepository seems to freeze when changing to `ref.tag` from `ref.branch` and is unable to revert

### ISSUE THREAD

**Issue by geolney** [fluxcd/flux2#4085]
### Describe the bug

I have a GitRepository referencing one of my repos which at the moment is set as `ref.branch = master` which works fine. When I then set this to `ref.tag = v1` it also works fine and updates to refer this in the Kustomization as intended. 
However when I try to change this back to the same or different branch reference, the GitRepo does not update and seems to be stuck without any errors. 

I can update the `ref.tag` to something else and this updates fine, e.g. v1 -> v2.4, but if I set it to any sort of branch nothing happens. Even doing a `flux reconcile source git <gitrepo>` does not solve issue. 

Rather strangely the ref when I describe it shows:
```
  ref:
    branch: master
    tag: v3.0.73
```
and even though I have removed/commented out the branch (and also tried the same for tag) this does not update the ref and these two references seem to just stay there even when one is referenced. This requires a manual `kubectl edit...` which is not ideal. 

### Steps to reproduce

1. Install flux with the additional image automation controllers - helm v0.22.2, kustomize v0.27.0, notification v0.25.1, source v0.26.1.
2. Define a GitRepository manifest and initially reference a branch that exists:
```
piVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dsp-core
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: <your repo url>
```
3. Apply this and wait for it to exist
4. Update ref to use a tag that now exists
```
ref:
    tag: v1
```
5. Apply and wait to complete.
NOTE - This is the part where despite removing branch reference, the output of describing the gitrepo shows:
```
ref:
  branch: master
  tag: v1
```
6. Comment out/delete the tag and switch back to any branch.
```
ref:
  branch: master
```
9. Apply and observe - it should stay stuck referencing the old tag and not update to the branch and requires manual kubectl edit, and flux reconcile source git does not fix.

### Expected behavior

Expect the GitRepo should be able to switch between branch reference and tag reference with ease and without manual edit required. 

### OS / Distro

Ubunto 20.04

### Flux version

flux: v0.29.3

### Flux check

flux check
► checking prerequisites
✗ flux 0.29.3 <2.0.1 (new version is available, please upgrade)
✔ Kubernetes 1.22.17-eks-a5565ad >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► our-registry/fluxcd/helm-controller:v0.22.2
✔ kustomize-controller: deployment ready
► our-registry/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► our-registry/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► our-registry/fluxcd/source-controller:v0.26.1
✔ all checks passed

using our own registry to proxy-cache normal images from docker hub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This should've been solved in Flux 2.0 GA. Please upgrade and redo the test to confirm. Thanks
