### ISSUE TITLE
Recommended debugging process for distributed Kustomization yamls

### ISSUE THREAD

**Issue by guiguan** [fluxcd/flux2#409]
Hi, Flux 2 is fantastic!

What’s the recommended debugging process for yamls? Is it possible to do a dry-run and print out the final yaml of a Kustomization before committing to repo and applying to cluster?

**Comment by stefanprodan** [comment]
You can run `kustomize create --autodetect` inside the dir you'll be using in `Kustomization.spec.path` and commit that to the repo. In CI you would run `kustomize build ./path > /tmp/output.yaml` then use kubeval/conftest on the output to validate the YAMLs.

**Comment by guiguan** [comment]
@stefanprodan oh, cool. Thank you!
