### ISSUE TITLE
Deploy on container image changed

### ISSUE THREAD

**Issue by RomanBurdiuzha** [fluxcd/flux2#410]
Hello, 
I am looking for a way to update kubernetes deployment when new version of container images published.
In flux1 there was such option to monitor changes in container registry and write back image versions to the deployment files.
Is there any option in flux2 to do this? 
I can't find anything about this in existing documentation.

**Comment by hiddeco** [comment]
This is still under active development, see the [image feature parity section](https://toolkit.fluxcd.io/roadmap/#flux-image-update-feature-parity) on the roadmap.

**Comment by RomanBurdiuzha** [comment]
Thank @hiddeco
