### ISSUE TITLE
 Prepare for Flux v2.0.2

### ISSUE THREAD

**Issue by makkes** [fluxcd/flux2#4110]
Release checklist:

- [ ] image-reflector-controller
- [ ] image-automation-controller
- [ ] kustomize-controller
- [ ] helm-controller
- [ ] notification-controller
- [ ] flux2 v2.0.2
- [ ] update `ctrl_version` workaround in https://github.com/fluxcd/website/pull/1577 and merge

**Comment by stefanprodan** [comment]
I would wait for the SC TLS PRs to be finalized and do v2.1.0.
