### ISSUE TITLE
Jitter requeue interval

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#4120]
To better distribute load when many resources have been configured with the same `.spec.interval`, we want to add +/-% jitter to the defined `.spec.interval` while requeuing the object after a successful reconciliation.

This behavior will be enabled by default with a value of `10` (between 4.5 and 5.5 minutes for an interval of `5m`), but can be disabled or tweaked using the `--interval-jitter-percentage` flag on a controller.

- [x] https://github.com/fluxcd/pkg/pull/613
- [x] https://github.com/fluxcd/source-controller/pull/1184
- [x] kustomize-controller
- [x] helm-controller

**Comment by hiddeco** [comment]
After more investigation, I do not think notification-controller, image-automation-controller and image-reflector-controller are good candidates for this. Because they really lightweight during their reconciliation attempts, or have other means in place to regulate the pace at which things are reconciled (e.g. container registry scanning from the image-reflector-controller).

**Comment by stefanprodan** [comment]
+1

Let's remove those controllers from the list and close this issue as completed.

**Comment by hiddeco** [comment]
https://github.com/fluxcd/website/pull/1619 for finalizing the documentation.
