### ISSUE TITLE
error in deploying secret 

### ISSUE THREAD

**Issue by masihasask** [fluxcd/flux2#4122]
### Describe the bug

When I wanted to deploy secret via kustomization, I've got this error: "error: data values must be of type string"
The secret is on Base64 and there is no problem with argo cd.

### Steps to reproduce

deploy this
 `apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
immutable: false
kind: Secret
metadata:
  name: secret
  namespace: test
type: Opaque`

### Expected behavior

deploy it without any error.

### OS / Distro

openshift 4.10.37

### Flux version

flux: v2.0.1

### Flux check

► checking prerequisites
✗ Kubernetes version v1.23.5+8471591 does not match >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.35.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.29.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by somtochiama** [comment]
I just tested this on flux and it applies the secret successfully.
Is your yaml properly formatted? Can you post the formatted yaml?

**Comment by izabelacg** [comment]
I'm having the same issue... my secret looks like:

---
apiVersion: v1
kind: Secret
metadata:
  name: app-values
stringData:
  values.yml: |
    ---
    workload_name: myapp

**Comment by izabelacg** [comment]
> I'm having the same issue... my secret looks like:
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: app-values
> stringData:
>   values.yml: |
>     ---
>     workload_name: myapp
> ```

My issue was that the service account didn't have the patch permission. So, I update the role to have:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
# redacted some fields from here
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
```

**Comment by somtochiama** [comment]
@izabelacg you had the same error? or a different error message?

**Comment by izabelacg** [comment]
> @izabelacg you had the same error? or a different error message?

I've got the same error message:  "error: data values must be of type string". And after I made some changes to the permissions for the service account that I specified in my Kustomization resource, things worked properly. I believe the last change I made was to add the patch verb. However, it was a little surprising to me because I did miss the patch verb for other resources but the error message was more clear about not being able to patch the resource. I will try to make some tests to confirm if there wasn't additional changes I made, but I believe this was the only thing I changed before it started working.

**Comment by ksbalas** [comment]
I have faced the same issue while creating secret

**Comment by stefanprodan** [comment]
We can't log the actual error because would contain the secret data, if it's says `forbidden` what follows next doesn't matter, it's an RBAC issue.

**Comment by ishuar** [comment]
Had the same issue while secret creation. The error message is quite misleading because in our case the root  kustomization was missing the namespace definition where it should create all its resources.
