### ISSUE TITLE
source git commands fail with failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1: the server could not find the requested resource

### ISSUE THREAD

**Issue by MrBasset** [fluxcd/flux2#4130]
### Describe the bug

We are in the process of replacing a traditionally deployed flux with Azure's GitOps Extension. During which we have updated our Flux CLI version to 2.0.1. Now if we try to execute any commands involving the git source, e.g `flux get source git` we get the error above.

I suspect that this is possibly because we upgraded a cluster running an earlier version of flux; perhaps the extension did not replace the flux CRDs, however I quickly created a brand new cluster in Azure and installed the GitOps Extension on it and got the same error.

I have tried to execute the command with the verbose instruction but no additional output is provided:
```
flux --verbose -n flux-system get source git
✗ failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1: the server could not find the requested resource
```

### Steps to reproduce

1. Spin up a Dev/Test AKS cluster within Azure
2. Add the GitOps extension, pointing it at a Git repository with a flux project in it. Set up the relevant Kustomize path for flux.
3. Wait for the main configuration to be marked compliant indicating Azure has created the GitRepository manifest has been deployed
4. Execute the command `flux get source git` and observe the error

### Expected behavior

The main git repository should be listed

### OS / Distro

Ubuntu 22.04LTS

### Flux version

v2.0.1

### Flux check

flux check                                                                                                                                                                   ─╯
► checking prerequisites
✔ Kubernetes 1.26.3 >=1.24.0-0
► checking controllers
✔ fluxconfig-agent: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-agent:1.7.4
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.7.4
✔ fluxconfig-controller: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-controller:1.7.4
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.7.4
✔ helm-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ fluxconfigs.clusterconfig.azure.com/v1alpha1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

Azure DevOps

### Additional context

Other flux source commands such as `flux get source helm` work fine, also the GitRepository object exists and flux will perform a successful deployment. The most annoying thing is that we can't execute commands like `flux reconcile source git <name>`.

```
kubectl get GitRepository -n flux-system
NAME             URL                                                            AGE     READY   STATUS
cluster-config   ssh://git@ssh.dev.azure.com/v3/my/project/here   8m47s   True    stored artifact for revision 'MNBM-436-update-flux-new@sha1:7bb2ed5e679b046bc027deae32e6515710a418aa'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The Azure Flux distribution is months behind the latest release. You need to download a CLI version that works with `gitrepositories.source.toolkit.fluxcd.io/v1beta2`, try this one https://github.com/fluxcd/flux2/releases/tag/v0.41.2

**Comment by MrBasset** [comment]
Urgh that was totally the issue, seems obvious in retrospect. Thanks.

For future reference is there a way to track the MS deployed version of Flux against a compatible CLI version?

**Comment by stefanprodan** [comment]
> For future reference is there a way to track the MS deployed version of Flux against a compatible CLI version?

This is something that MSFT should do, as in inform their users which Flux CLI is compatible with their distribution.
