### ISSUE TITLE
Flux cli build kustomization ignores remote resources

### ISSUE THREAD

**Issue by adusumillipraveen** [fluxcd/flux2#4146]
### Describe the bug

We load CRDs to the repo like from a [kustomization](https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/traefik-crds/kustomization.yaml) pointed in a [flux kustomize](https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/base/kustomize.yaml#L20) .
Below command works fine when i try on 0.41.2 , but doesn't return anything on 2.0.1.  I couldn't see any flags like load-restrictor in docs/code for cli commands.  Couldn't trace what change would have caused this too, not sure if i have missed any docs

`flux build kustomization traefik-crd --path ./apps/admin/traefik-crds --kustomization-file apps/admin/base/kustomize.yam`

### Steps to reproduce

1. Install flux latest version
2. Create a kustomization with remote files like [kustomization](https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/traefik-crds/kustomization.yaml) pointed in a [flux kustomize](https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/base/kustomize.yaml#L20) . 
3. Create a flux kustomization pointing to the directory like  [flux kustomize](https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/base/kustomize.yaml#L20) 
4. Run `flux build kustomization traefik-crd --path ./apps/admin/traefik-crds --kustomization-file apps/admin/base/kustomize.yam`
5. Output will be empty

### Expected behavior

1. Output is expected to have output for kustomization with CRDs 
2. It works as expected in 0.41.x, but not in latest 2.x

### OS / Distro

Arch Linux

### Flux version

v2.0.1

### Flux check

flux check
► checking prerequisites
✗ flux 0.41.2 <2.0.1 (new version is available, please upgrade)
✔ Kubernetes 1.25.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by allenporter** [comment]
I think this may have broken with https://github.com/fluxcd/flux2/commit/f0c498ff54b3fb5acb6b510216207a2edc5baf9c as calling `NewGeneratorWithIgnore` 

The problem is in `fluxcd/pkg` which ends up filtering out the resources in [filterSlice](https://github.com/fluxcd/pkg/blob/e4b557edc0373ca36a9d5747dc9b3df8fa62f5a3/kustomize/filters.go#L84) which removes all urls from the `resources`.
