### ISSUE TITLE
Flux bootstrap  client rate limiter Wait returned an error: context deadline exceeded

### ISSUE THREAD

**Issue by jouros** [fluxcd/flux2#4191]
### Describe the bug

   ► cloning branch "main" from Git repository "https://***/_git/karbon1"
    ✔ cloned repository
    ► generating component manifests
    ✔ generated component manifests
    ✔ component manifests are up to date
    ► installing components in "flux-system" namespace
    ✔ installed components
    ✔ reconciled components
    ► determining if source secret "flux-system/flux-system" exists
    ► generating source secret
    ► applying source secret "flux-system/flux-system"
    ✔ reconciled source secret
    ► generating sync manifests
    ✔ generated sync manifests
    ✔ sync manifests are up to date
    ► applying sync manifests
    ✔ reconciled sync configuration
    ◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
    ✗ client rate limiter Wait returned an error: context deadline exceeded
    ► confirming components are healthy
    ✔ helm-controller: deployment ready
    ✔ kustomize-controller: deployment ready
    ✔ notification-controller: deployment ready
    ✔ source-controller: deployment ready
    ✔ all components are healthy
    ✗ bootstrap failed with 1 health check failure(s)

### Steps to reproduce

flux bootstrap git --registry=***/karbon/fluxcd --image-pull-secret=fluxregcred --url=https://***/_git/karbon1 --branch=main --password=*** --token-auth --path=clusters/kube2prod --verbose

### Expected behavior

Normal bootstrap

### OS / Distro

Ubuntu 22.04.2 LTS

### Flux version

flux: v2.0.1

### Flux check

flux check --pre
► checking prerequisites
✗ flux 2.0.1 <2.1.0 (new version is available, please upgrade)
✔ Kubernetes 1.27.2 >=1.24.0-0
✔ prerequisites checks passed

### Git provider

Azure DevOps

### Container Registry provider

Private Registry

### Additional context

flux get source git flux-system
NAME            REVISION                SUSPENDED       READY   MESSAGE
flux-system     main@sha1:b2439fa1      False           True    stored artifact for revision 'main@sha1:b2439fa1'

kubectl get pods -n flux-system
NAME                                       READY   STATUS    RESTARTS   AGE
helm-controller-6c87b9c9ff-8mlbm           1/1     Running   0          60s
kustomize-controller-7d69d8787-59b9j       1/1     Running   0          60s
notification-controller-56f8f99c68-x7rd7   1/1     Running   0          60s
source-controller-64457886d9-nlv2s         1/1     Running   0          60s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You're Kubernetes API is having a hard time, if rerun bootstrap does it still timeout?

**Comment by jouros** [comment]
Yes:  ✗ client rate limiter Wait returned an error: context deadline exceeded
I have:
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 5m
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/kube2prod
  prune: true
  validation: client
  
but ./tenants/kube2prod folder is still empty, not configured yet, could this missing config be a problem here?

**Comment by stefanprodan** [comment]
`validation: client` does not exists in `kustomize.toolkit.fluxcd.io/v1`, this field is from v1beta1 and no longer works. You may want to comment out all Flux Kustomizations in Git and see if plain bootstrap works.

**Comment by jouros** [comment]
Yes, that was it: ✔ all components are healthy
