### ISSUE TITLE
Flux not detecting changes pushed up to GitRepository, not un-doiing them when manually applied either

### ISSUE THREAD

**Issue by sseneca** [fluxcd/flux2#4211]
### Describe the bug

Not sure exactly when this started happening, I would assume since I upgraded Flux to v2, but changes I push up to the GitRepository aren't getting applied to the cluster.

Flux *does* pull the latest changes from Git and shows it having the correct SHA value associated with a latest commit, but it doesn't detect the applied manifests are out of sync with the manifests in Git. I have to `kubectl apply -f` the manifests and that applies them fine, Flux doesn't then undo the changes or anything.

I *think* I've un-suspended anything that was suspended but this is happening between simple k8s `Deployments` and `HelmRelease`s as well. The GIt source isn't suspended either :thinking: 

I'm probably missing something really small, but I can't figure out what, so... :)

### Steps to reproduce

1. Latest Flux running on k3s cluster
2. Make change to manifest and push it up to Git repo
3. Nothing happens
4. Apply change manually with `kubectl apply -f`

### Expected behavior

It should apply that change

### OS / Distro

arch linux

### Flux version

flux: v2.1.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.4+k3s1 >=1.25.0-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

sourcehut (git.sr.ht)

### Container Registry provider

n/a

### Additional context

e.g. with the following patchset to a bare deployment:

```
commit fb5a2c3e08b440205d925d8661beb43f0fdc853a
Author: sseneca <redacted>
Date:   Thu Aug 31 12:07:33 2023 +0100

    binwiederhier/ntfy:v2.7.0

diff --git a/clusters/sserver/ntfy/deployment.yaml b/clusters/sserver/ntfy/deployment.yaml
index 9cee3d6..e3e4cad 100644
--- a/clusters/sserver/ntfy/deployment.yaml
+++ b/clusters/sserver/ntfy/deployment.yaml
@@ -18,7 +18,7 @@ spec:
         app: ntfy
     spec:
       containers:
-        - image: binwiederhier/ntfy:v2.4.0
+        - image: binwiederhier/ntfy:v2.7.0
           name: ntfy
           args:
             - serve
```

Flux doesn't want to do anything about it:

```json
{
  "level": "info",
  "ts": "2023-08-31T11:08:00.857Z",
  "msg": "stored artifact for commit 'binwiederhier/ntfy:v2.7.0'",
  "controller": "gitrepository",
  "controllerGroup": "source.toolkit.fluxcd.io",
  "controllerKind": "GitRepository",
  "GitRepository": {
    "name": "flux-system",
    "namespace": "flux-system"
  },
  "namespace": "flux-system",
  "name": "flux-system",
  "reconcileID": "dea29a1f-2906-4627-8226-103af097b5e0"
}
```

So it's seen it should be running the tag with 2.7.0, but checking the `Deployment` shows it's still running `image: binwiederhier/ntfy:v2.4.0`.

Then with a helm release, similar thing:

```
commit 4fdc7f5d0c405932c79b3767dfe398907f3207b9
Author: sseneca <redacted>
Date:   Thu Aug 31 12:03:33 2023 +0100

    ingress-nginx/controller:v1.8.1

diff --git a/clusters/sserver/ingress-nginx/release.yaml b/clusters/sserver/ingress-nginx/release.yaml
index 8d09398..f384b47 100644
--- a/clusters/sserver/ingress-nginx/release.yaml
+++ b/clusters/sserver/ingress-nginx/release.yaml
@@ -9,7 +9,7 @@ spec:
   chart:
     spec:
       chart: ingress-nginx
-      version: 4.6.0
+      version: 4.7.1
       sourceRef:
         name: ingress-nginx
         kind: HelmRepository
@@ -18,6 +18,6 @@ spec:
       image:
         registry: registry.k8s.io
         image: ingress-nginx/controller
-        tag: "v1.7.0"
-        digest: sha256:7612338342a1e7b8090bef78f2a04fffcadd548ccaabe8a47bf7758ff549a5f7
-        digestChroot: sha256:e84ef3b44c8efeefd8b0aa08770a886bfea1f04c53b61b4ba9a7204e9f1a7edc
+        tag: "v1.8.1"
+        digest: sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd
+        digestChroot: sha256:e0d4121e3c5e39de9122e55e331a32d5ebf8d4d257227cb93ab54a1b912a7627
```

But again:

```json
{
  "level": "info",
  "ts": "2023-08-31T11:58:46.503Z",
  "msg": "artifact up-to-date with remote revision: '4.6.0'",
  "controller": "helmchart",
  "controllerGroup": "source.toolkit.fluxcd.io",
  "controllerKind": "HelmChart",
  "HelmChart": {
    "name": "kube-system-ingress-nginx",
    "namespace": "kube-system"
  },
  "namespace": "kube-system",
  "name": "kube-system-ingress-nginx",
  "reconcileID": "eed0f202-0476-4a8f-811c-adda2564157e"
}
```

then from the helm controller:

```json
{
  "level": "info",
  "ts": "2023-08-31T12:00:09.286Z",
  "msg": "reconciliation finished in 89.880362ms, next run in 5m10.635617745s",
  "controller": "helmrelease",
  "controllerGroup": "helm.toolkit.fluxcd.io",
  "controllerKind": "HelmRelease",
  "HelmRelease": {
    "name": "ingress-nginx",
    "namespace": "kube-system"
  },
  "namespace": "kube-system",
  "name": "ingress-nginx",
  "reconcileID": "44f1901c-9bf2-4230-834b-a0d3f1e89650"
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please post here `flux trace -n your-ns Deployment/your-deployment` and the same thing for the HelmRelease.
