### ISSUE TITLE
flux upgrade runs into infinite loop

### ISSUE THREAD

**Issue by mrwormhole** [fluxcd/flux2#4259]
### Describe the bug

I have had flux 2.0 RC1 installed cluster with extra components like image reflector and image update automation, essentially I have run the first upgrade example

```sh
git clone https://<git-host>/<org>/<bootstrap-repo>
cd <bootstrap-repo>
flux install --export > ./clusters/my-cluster/flux-system/gotk-components.yaml
git add -A && git commit -m "Update $(flux -v) on my-cluster"
git push
```

and then run 

```sh
flux reconcile ks flux-system --with-source
```

this did end up deleting extra components and infinite reconcile loop, only solution was to delete the flux completely and do the bootstrap process I have done

timeout waiting for: [CustomResourceDefinition/imagepolicies.image.toolkit.fluxcd.io status: 'Terminating', CustomResourceDefinition/imagerepositories.image.toolkit.fluxcd.io status: 'Terminating', CustomResourceDefinition/imageupdateautomations.image.toolkit.fluxcd.io status: 'Terminating']

```
► connecting to github.com
► cloning branch "main" from Git repository "https://github.com/mrwormhole/flux-gitops.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✗ timeout waiting for: [CustomResourceDefinition/imageupdateautomations.image.toolkit.fluxcd.io status: 'Terminating', CustomResourceDefinition/imagerepositories.image.toolkit.fluxcd.io status: 'Terminating', CustomResourceDefinition/imagepolicies.image.toolkit.fluxcd.io status: 'Terminating']
```

### Steps to reproduce

1- bootstrap the flux with extra image components
2- upgrade it from 2.0 RC1 to 2.1 latest cli and run
```
git clone https://<git-host>/<org>/<bootstrap-repo>
cd <bootstrap-repo>
flux install --export > ./clusters/my-cluster/flux-system/gotk-components.yaml
git add -A && git commit -m "Update $(flux -v) on my-cluster"
git push
```
3- 
![image](https://github.com/fluxcd/flux2/assets/22800416/2f348949-4c3d-4ff7-8094-7a36cd958389)

![image](https://github.com/fluxcd/flux2/assets/22800416/2a8d6414-dd3b-4faa-9f39-44dd311c61ce)

### Expected behavior

I believe flux install should be forgiving for extra components and not delete it because even when I went back for to bootstrap update process, I was getting the same error, so it got in that stuck reconcile state until I uninstall flux completely

### Screenshots and recordings

this is after I got stuck in timeout of `flux install --export >./clusters/my-cluster/flux-system/gotk-components.yaml`

it halted even the normal bootstrap process, because the git commit deleted extra components from `gotk-components.yaml`, I have squashed everything but it didn't fix.

![image](https://github.com/fluxcd/flux2/assets/22800416/22289682-347e-4099-88e1-9703cad41806)

I had to uninstall flux again and bootstrap with the above as classic setup process. Now infinite reconcile loop is gone, I believe there should be a note saying bootstrap one is our preferred way of updating

### OS / Distro

Arch Linux

### Flux version

flux version 2.1.0

### Flux check

N/A

### Git provider

github

### Container Registry provider

github

### Additional context

this could be a biiig issue for people who have to go through the uninstall phase, I would love a note in the first upgrade notes saying, you ``MUST`` specify extra components for safety OR you should use the normal bootstrap update procedure to avoid reconcile loop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> can a note be added there?

I guess you're referring to https://fluxcd.io/flux/installation/upgrade/ ?

**Comment by stefanprodan** [comment]
@mrwormhole can you check my PR and tell me if having that note in docs would've helped you avoid this issue.
