### ISSUE TITLE
Re-running Flux Bootstrap Not Upgrading

### ISSUE THREAD

**Issue by pusherman** [fluxcd/flux2#4267]
### Describe the bug

Currently at v0.41.2 and trying to update to version 2 but re-running the bootstrap command does not upgrade any components.

### Steps to reproduce

```
% flux version
flux: v0.41.2
helm-controller: v0.31.2
kustomize-controller: v0.35.1
notification-controller: v0.33.0
source-controller: v0.36.1
```

```
% flux check
► checking prerequisites
✗ flux 0.41.2 <2.1.1 (new version is available, please upgrade)
✔ Kubernetes 1.27.4-eks-2d98532 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed
```
```
% flux bootstrap git \
  --url=ssh://git@bitbucket.org/<myrepo>/eks.git \
  --branch=main \
  --private-key-file=/path/to/flux/key/flux_id_rsa \
  --path=clusters/my-cluster
► cloning branch "main" from Git repository "ssh://git@bitbucket.org/<myrepo>/eks.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ssh-rsa AAAAB3NzaC1yc2...5p6QuT5sF6ZFJ/9rjd8WPdkw==
Please give the key access to your repository: y
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✔ Kustomization reconciled successfully
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
```

### Expected behavior

Flux to be upgraded to the latest version.

### OS / Distro

macOS 13.5.2

### Flux version

v0.41.2

### Flux check

► checking prerequisites
✗ flux 0.41.2 <2.1.1 (new version is available, please upgrade)
✔ Kubernetes 1.27.4-eks-2d98532 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
See https://fluxcd.io/flux/installation/upgrade/#flux-cli-upgrade

**Comment by pusherman** [comment]
Right.  I am using the https://fluxcd.io/flux/installation/upgrade/#upgrade-with-flux-cli method.  It is just not updating anything this time.  I've used this same method many times before and previously it has worked to update.

As shown in my steps to reproduce
```
flux bootstrap git \
  --url=ssh://git@bitbucket.org/<myrepo>/eks.git \
  --branch=main \
  --private-key-file=/path/to/flux/key/flux_id_rsa \
  --path=clusters/my-cluster
  ```

Are you saying this method no longer works and I should use the "Upgrade with git" section of the document you linked to?
