### ISSUE TITLE
cosign signature validation fails with valid image

### ISSUE THREAD

**Issue by nagyv** [fluxcd/flux2#4273]
### Describe the bug

The error I receive is: `failed to verify the signature using provider ‘cosign’: no matching signatures were found for ‘registry.gitlab.com/gitlab-org/ci-cd/deploy-stage/demos/podtato-head-delivery/dev/podtato-head-arms:latest`

I used the keys generated with `cosign generate-key-pair k8s://podtato-head-dev/cosign-key` for signing, and the same key is provided in the `OCIRepository:spec.verify.secretRef.name` 

The signatures are available beside the image at https://gitlab.com/gitlab-org/ci-cd/deploy-stage/demos/podtato-head-delivery/container_registry/4561427

Running `cosign verify --key k8s://podtato-head-dev/cosign-key registry.gitlab.com/gitlab-org/ci-cd/deploy-stage/demos/podtato-head-delivery/entrypoint-dev:latest validates the image. 

Could it be version incompatibility with `cosign`? (Running `generate-key-pair` and `sign` with different versions sometimes does not work.)

### Steps to reproduce

1. Install Flux
2. Run `cosign generate-key-pair k8s://default/cosign-key` to set up the cosign password, private and public keys in the cluster
3. Sign an image with `cosign generate-key-pair k8s://default/cosign-key ...`
4. Create an OCIRepository with `metadata.namespace: default`, `spec.verify.provider: cosign`, `spec.verify.provider: secretRef.name: cosign-key`.

### Expected behavior

The OCIRepository should deploy and validation should pass

### OS / Distro

N/A

### Flux version

N/A

### Flux check

► checking prerequisites
✗ flux 2.1.0 <2.1.1 (new version is available, please upgrade)
✔ Kubernetes 1.27.3-gke.100 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Container Registry provider

GitLab

### Additional context

cosign version used for signing:

```
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.
GitVersion:    v2.0.2
GitCommit:     unknown
GitTreeState:  clean
BuildDate:     unknown
GoVersion:     go1.20.8
Compiler:      gc
Platform:      linux/amd64
```

and key generation:

```
GitVersion:    v2.0.2
GitCommit:     unknown
GitTreeState:  clean
BuildDate:     unknown
GoVersion:     go1.20.8
Compiler:      gc
Platform:      darwin/arm64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I guess the secret structure doesn't match what Flux expects https://fluxcd.io/flux/components/source/ocirepositories/#public-keys-verification

**Comment by nagyv** [comment]
@stefanprodan I think the structure is fine. If I'm not mistaken, it just requires a key with `.pub` extension.

```
$ kubectl describe secret -n podtato-head-dev cosign-key
Name:         cosign-key
Namespace:    podtato-head-dev
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
cosign.key:       653 bytes
cosign.password:  20 bytes
cosign.pub:       178 bytes
```

**Comment by stefanprodan** [comment]
Are you using Cosign 2.1? This is what Flux uses https://github.com/fluxcd/source-controller/blob/801fb52e352286e22a11c8bf8490b44d968003a5/go.mod#L59

**Comment by nagyv** [comment]
@stefanprodan I tried already all the combinations. It fails even when both the `generate-key-pair` and the `sign` uses 

```
$ cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.
GitVersion:    v2.1.1
GitCommit:     unknown
GitTreeState:  clean
BuildDate:     unknown
GoVersion:     go1.20.6
Compiler:      gc
Platform:      linux/amd64
```

**Comment by nagyv** [comment]
I am happy to schedule working on this during the next GitLab milestone (starting in mid-October). I'd like to ask for help in:

- try to reproduce it (I use nix [to build an image](https://gitlab.com/gitlab-org/ci-cd/deploy-stage/demos/podtato-head-delivery/-/blob/main/.gitlab-ci.yml#L15) that includes cosign, and the [image is publicly available](https://gitlab.com/gitlab-org/ci-cd/deploy-stage/demos/podtato-head-delivery/container_registry/5600012))
- give hints on the possible error, further troubleshooting and possible fix

**Comment by stefanprodan** [comment]
Can you please try with `flux push artifact` then `cosign sign` of the OCI digest returned by the Flux CLI?

**Comment by stefanprodan** [comment]
I tried to replicate this but it works for me with Cosign v2.2.0. I followed the exact steps as you, but with Docker Hub.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  creationTimestamp: "2023-09-21T17:01:22Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: test
  namespace: default
  resourceVersion: "400411"
  uid: 082a7003-3b18-4006-af54-49b28dab2bde
spec:
  interval: 5m
  provider: generic
  ref:
    tag: test
  timeout: 60s
  url: oci://docker.io/stefanprodan/ocitest
  verify:
    provider: cosign
    secretRef:
      name: cosign-key
status:
  artifact:
    digest: sha256:4f74d61c31c3b6904316c6498274304879b66abd34f53ab834aa6492684d7646
    lastUpdateTime: "2023-09-21T17:01:28Z"
    metadata:
      org.opencontainers.image.created: "2023-09-21T16:56:52Z"
      org.opencontainers.image.revision: test
      org.opencontainers.image.source: test
    path: ocirepository/default/test/sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789.tar.gz
    revision: test@sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789
    size: 355116
    url: http://source-controller.flux-system.svc.cluster.local./ocirepository/default/test/sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789.tar.gz
  conditions:
  - lastTransitionTime: "2023-09-21T17:01:28Z"
    message: stored artifact for digest 'test@sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-21T17:01:28Z"
    message: stored artifact for digest 'test@sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  - lastTransitionTime: "2023-09-21T17:01:26Z"
    message: verified signature of revision test@sha256:bae8ea96aa57c211c925e85f2aea5b76d218dbc875f78454a04847b6f196a789
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: SourceVerified
  observedGeneration: 1
  url: http://source-controller.flux-system.svc.cluster.local./ocirepository/default/test/latest.tar.gz
```

**Comment by nagyv** [comment]
Thank you @stefanprodan for spending time with me here. I found the bug in my setup. I was checking the signature on a different image that I was actually signing. 🤦‍♂️ I'm sorry for wasting your time.
