### ISSUE TITLE
Feature Request: Flux bootstrap to support GitRepository proxySecretRef feature flag

### ISSUE THREAD

**Issue by anzlay** [fluxcd/flux2#4277]
During the FluxCD bootstrap process we need a mechanism that can configure the initial GitRepository (flux-system) we need to have a method that allows us to use the `proxySecretRef` field and set it to the appropriate name. This is to enable us to automatically ingest the new Proxy secret reference as defined here https://fluxcd.io/flux/components/source/gitrepositories/#proxy-secret-reference
cc @xUnholy

**Comment by xUnholy** [comment]
This has been recommended to be done via patches to the GitRepository resource to avoid needing to add additional flags. This will yield the same result without needing to add additional code which is awesome.

**Comment by anzlay** [comment]
This issue has been resolved and closing issue.
