### ISSUE TITLE
Platform agnostic bootstrapper

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#43]
A simple and straight forward way to make the toolkit work with any platform is to provide a bootstrapper that just assumes it should connect to some Git server while making use of the local SSH agent.

Command:

```
tk bootstrap git \
--repository=<GitHub repository name> \
--version=<toolkit version> \
--components=<toolkit controllers> \
```

Workflow:

- clone the repository
- generate install manifests
- commit and push the install manifests to git using the local SSH agent (override the files if they exist)
- apply the manifests on the target cluster (on install)
- wait for controllers rollout
- generate SSH keys and hosts (on install)
- print generated public key (on install)
- create a source manifest for the specified Git repository (on install)
- create a kustomization manifest for reconciling the manifests (on install)
- commit and push the source/ks manifests to git (on install)
- apply the manifests on the target cluster (on install)
- wait for the kustomization rollout

Bonus points:

Some Git servers allow new repositories to be created on push, we could provide an additional flag (e.g. `--init`) which creates a new Git repository locally, with the remote set to the provided `--repository` URL, instead of cloning it. Cloning should however always be attempted first to make the command idempotent.

**Comment by stealthybox** [comment]
Related #1165

**Comment by stefanprodan** [comment]
I would close this and open a new issue for implementing a bootstrap that shells out to the Git CLI (if we still want to do that, IMO this is very low prio).
