### ISSUE TITLE
Storage leak: Flux consumes all 20Gi node storage

### ISSUE THREAD

**Issue by preston-willis** [fluxcd/flux2#4305]
### Describe the bug

It seems flux has used all of the space on my cluster node (20Gi provisioned). It's not cleaning up tmp directories maybe?

All of my source controllers error with: `no space left on device`

I've been having a source-controller OOM issue recently as well after increasing to 2Gi. Could these possibly be related?

Helm controller error:
`failed to fetch Helm repository index: failed to create temp file to cache index to: open /tmp/chart-index-1686487677.yaml: no space left on device`

Flux logs:
`
2023-10-06T12:23:57.956Z error GitRepository/cert-src.flux-system - failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-cert-src-1028436833/.git/objects/pack/tmp_pack_1574212311: no space left on device failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-cert-src-1028436833/.git/objects/pack/tmp_pack_1574212311: no space left on device
2023-10-06T12:23:57.996Z error GitRepository/cert-src.flux-system - Reconciler error failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-cert-src-1028436833/.git/objects/pack/tmp_pack_1574212311: no space left on device
2023-10-06T12:23:58.085Z error GitRepository/flux-system.flux-system - failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-flux-system-2156429295/.git/objects/pack/tmp_pack_1941696581: no space left on device failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-flux-system-2156429295/.git/objects/pack/tmp_pack_1941696581: no space left on device
2023-10-06T12:23:58.108Z error GitRepository/flux-system.flux-system - Reconciler error failed to checkout and determine revision: unable to clone 'https://bitbucket.org/blueline-rms/blueline-fleet/': write /tmp/gitrepository-flux-system-flux-system-2156429295/.git/objects/pack/tmp_pack_1941696581: no space left on device
2023-10-06T12:23:58.751Z error GitRepository/cert-src.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-3153013629: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-3153013629: no space left on device
2023-10-06T12:23:58.823Z error GitRepository/cert-src.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-3153013629: no space left on device
2023-10-06T12:23:58.863Z error GitRepository/flux-system.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-1741503687: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-1741503687: no space left on device
2023-10-06T12:23:58.895Z error GitRepository/flux-system.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-1741503687: no space left on device
2023-10-06T12:24:00.327Z error GitRepository/cert-src.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-1485184750: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-1485184750: no space left on device
2023-10-06T12:24:00.347Z error GitRepository/cert-src.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-1485184750: no space left on device
2023-10-06T12:24:00.396Z error GitRepository/flux-system.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-997426327: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-997426327: no space left on device
2023-10-06T12:24:00.422Z error GitRepository/flux-system.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-997426327: no space left on device
2023-10-06T12:24:03.349Z error GitRepository/cert-src.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-4075851183: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-4075851183: no space left on device
2023-10-06T12:24:03.366Z error GitRepository/cert-src.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-4075851183: no space left on device
2023-10-06T12:24:03.423Z error GitRepository/flux-system.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-120919579: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-120919579: no space left on device
2023-10-06T12:24:03.469Z error GitRepository/flux-system.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-120919579: no space left on device
2023-10-06T12:24:09.370Z error GitRepository/cert-src.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-543919790: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-543919790: no space left on device
2023-10-06T12:24:09.392Z error GitRepository/cert-src.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-543919790: no space left on device
2023-10-06T12:24:09.470Z error GitRepository/flux-system.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-382034221: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-382034221: no space left on device
2023-10-06T12:24:09.497Z error GitRepository/flux-system.flux-system - Reconciler error failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-flux-system-382034221: no space left on device
2023-10-06T12:24:21.396Z error GitRepository/cert-src.flux-system - failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-3956427777: no space left on device failed to create temporary working directory: mkdir /tmp/gitrepository-flux-system-cert-src-3956427777: no space left on device
`
### kubectl get pods -n flux-system

helm-controller-7c8b698656-dlfzc               1/1     Running                  1 (16h ago)      17h
image-automation-controller-5c9fdb555f-2xkjt   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-4n8wf   0/1     CrashLoopBackOff         124 (119s ago)   11h
image-automation-controller-5c9fdb555f-4znhm   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-582c8   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-6kzz5   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-6p2vw   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-7mbqd   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-8sbp8   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-925tf   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-9m5p6   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-9v8kl   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-bms94   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-bww9v   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-ckl58   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-cw924   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-d4jh7   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-gkndw   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-h5jp9   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-h69xx   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-jwp9q   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-k566q   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-m6xxz   0/1     ContainerStatusUnknown   51 (11h ago)     17h
image-automation-controller-5c9fdb555f-mnlnr   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-n987q   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-p25x2   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-ptpvs   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-q4qd5   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-qpwwt   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-qxdtr   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-rk66w   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-t6zf8   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-tm6sr   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-tzgvq   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-v4rpn   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-vfbfd   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-w86mh   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-wmd4s   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-wrqgt   0/1     Evicted                  0                11h
image-automation-controller-5c9fdb555f-z6bdg   0/1     Evicted                  0                11h
image-reflector-controller-86d47b689f-25tv8    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-2bv69    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-45s7v    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-4945l    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-4f57r    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-4h8xm    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-4jnxg    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-5jqq4    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-5ks8l    1/1     Running                  0                7h43m
image-reflector-controller-86d47b689f-5nmkg    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-5tzxt    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-5z8bl    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-5zcqd    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-68dhn    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-6zzkq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-7dpmq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-7g7mm    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-7kzxq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-8nl68    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-9c7cv    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-b5tl8    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-bcldq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-c945c    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-d6q5m    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-d9r4w    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-dkrxp    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-f9nxk    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-hj8tq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-hx5m4    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-jd8xn    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-jfbqb    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-jjcqh    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-k9hdw    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-kxhj7    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-l2swn    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-l6srp    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-lcxjp    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-lfsf6    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-lqq28    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-m7zqx    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-mbmjg    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-mc8dw    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-mjns5    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-n2phb    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-nktm8    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-p5lxt    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-p98ng    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-pkq9m    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-pqmn8    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-qhn77    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-rrfv9    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-slmzq    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-t7b2l    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-vdbkg    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-w2ggk    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-wjblw    0/1     OOMKilled                1 (16h ago)      17h
image-reflector-controller-86d47b689f-x22nw    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-xgwvk    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-xhxq6    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-xkk86    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-zglvr    0/1     Evicted                  0                7h43m
image-reflector-controller-86d47b689f-zwdc5    0/1     Evicted                  0                7h43m
kustomize-controller-858996fc8d-fw5v5          1/1     Running                  1 (16h ago)      17h
notification-controller-ddf44665d-ls9wz        1/1     Running                  0                17h
source-controller-594c848975-x8lmk             1/1     Running                  105 (6h4m ago)   16h

### kubectl describe nodes:
Capacity:
  cpu:                2
  ephemeral-storage:  20959212Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3943376Ki
  pods:               17
Allocatable:
  cpu:                1930m
  ephemeral-storage:  18242267924
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3388368Ki
  pods:               17
System Info:
  Machine ID:                 ec2edbf38e929c499f39fc704107f67e
  System UUID:                ec2edbf3-8e92-9c49-9f39-fc704107f67e
  Boot ID:                    1a526694-d9cb-426c-baa0-80a7530c1777
  Kernel Version:             5.10.184-175.731.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.19
  Kubelet Version:            v1.27.1-eks-2f008fe
  Kube-Proxy Version:         v1.27.1-eks-2f008fe
ProviderID:                   aws:///us-east-2a/i-04031487985adc8ee
Non-terminated Pods:          (8 in total)
  Namespace                   Name                                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  flux-system                 helm-controller-7c8b698656-dlfzc         100m (5%)     1 (51%)     64Mi (1%)        1Gi (30%)      17h
  flux-system                 kustomize-controller-858996fc8d-fw5v5    100m (5%)     1 (51%)     64Mi (1%)        1Gi (30%)      17h
  flux-system                 source-controller-594c848975-x8lmk       50m (2%)      1 (51%)     64Mi (1%)        1Gi (30%)      16h
  kube-system                 aws-node-ldgn2                           25m (1%)      0 (0%)      0 (0%)           0 (0%)         24d
  kube-system                 coredns-647484dc8b-5tv54                 100m (5%)     0 (0%)      70Mi (2%)        170Mi (5%)     24d
  kube-system                 coredns-647484dc8b-hfztz                 100m (5%)     0 (0%)      70Mi (2%)        170Mi (5%)     24d
  kube-system                 ebs-csi-node-f7hsb                       30m (1%)      300m (15%)  120Mi (3%)       768Mi (23%)    4d11h
  kube-system                 kube-proxy-lxmwt                         100m (5%)     0 (0%)      0 (0%)           0 (0%)         24d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  cpu                605m (31%)   3300m (170%)
  memory             452Mi (13%)  4180Mi (126%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:
  Type     Reason                Age                     From     Message
  Warning  FreeDiskSpaceFailed   19m (x18 over 5h54m)    kubelet  Failed to garbage collect required amount of images. Attempted to free 4292426137 bytes, but only found 0 bytes eligible to free.
  Warning  EvictionThresholdMet  9m14s (x2614 over 12h)  kubelet  Attempting to reclaim ephemeral-storage
  Warning  FreeDiskSpaceFailed   4m14s (x74 over 7h44m)  kubelet  (combined from similar events): Failed to garbage collect required amount of images. Attempted to free 4292417945 bytes, but only found 0 bytes eligible to free.

### Steps to reproduce

I ran flux for about a month on my cluster, re-bootstrapping a few times

### Expected behavior

 I expected flux to use at most 5Gi

### OS / Distro

AWS EKS t3.medium Amazon Linux 2 amd64

### Flux version

v2.1.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.4-eks-2d98532 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Bitbucket

### Container Registry provider

dockerhub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
On my clusters `/tmp` is empty and if Flux had such a leak we would've had tones of people reporting this. I guess the disk got filled with container images and OS packages or maybe the Git repos you're using are very large. You can exec in the Flux containers and run `du` to see how much space is used, you could also run `flux stats -A` to see size of the Git repos pulled by source-controller.

**Comment by preston-willis** [comment]
> On my clusters `/tmp` is empty and if Flux had such a leak we would've had tones of people reporting this. I guess the disk got filled with container images and OS packages or maybe the Git repos you're using are very large. You can exec in the Flux containers and run `du` to see how much space is used, you could also run `flux stats -A` to see the size of the Git repos pulled by source-controller.

Cant exec due to the storage being completely full, will run flux stats and get back to you

I recently reorganized my git repo to include another Flux GitRepository pointing to the same repo to a folder outside of where flux is bootstrapped (For shared cluster resources). Could this be related?

**Comment by stefanprodan** [comment]
Flux bootstrap is meant to be run on an empty repo that Flux manages, have you run this on some repo with large files inside?

**Comment by preston-willis** [comment]
Now that I think about it, that repo has my terraform provider files in it. 
Also, should I be using flux-multi-tenant to manage multiple clusters on a single repo?

**Comment by stefanprodan** [comment]
Yes both [flux-multi-tenant](https://github.com/fluxcd/flux2-multi-tenancy) and [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example) are Ok to use for multiple clusters. But there is no need to create more than one GitRepository if you have single one, just refer it you Kustomizations and set diffrent paths in there.

**Comment by preston-willis** [comment]
Ah, I see. I didnt know Kustomizations could reference files outside of the flux directory. Removed terraform files and trying bootstrap again

**Comment by stefanprodan** [comment]
Terraform file don't take much space, so that's not the issue. 20Gi total space means you are left with just a couple of Gi for images which I suspect fill your disk.

**Comment by stefanprodan** [comment]
To see how much space the repo takes, checkout it locally and run `du -h` from the repo root.

**Comment by preston-willis** [comment]
My terraform directory is 500M ... oops

**Comment by stefanprodan** [comment]
Well that explains it, but never the less, you should have at least 100Gi disk for your nodes, the moment you'll start deploying apps, the container images will fill the disk and you'll be stuck again.

**Comment by preston-willis** [comment]
Appreciate the help, should I nuke my repo or is removing the files enough?

**Comment by stefanprodan** [comment]
I suggest you start fresh with an empty Git repo dedicated for Flux, where you have only YAML. Those 500M files will still be in Git history in `.git` after deletion.

**Comment by preston-willis** [comment]
Ok, I'll use that with the kustomize example you provided to manage my clusters, although I think I'd rather store my shared yaml in a separate repo so and pull from different branches for staging/prod, and then apply prod changes by merging a PR. Is there any reason this is not recommended in the example?

**Comment by stefanprodan** [comment]
There are many way to structure your repos, using branches can work if staging and prod don't diverge over time. See https://fluxcd.io/flux/guides/repository-structure/

**Comment by preston-willis** [comment]
Got it. Thanks for all the help!
