### ISSUE TITLE
Memory Leak: Flux source-controller OOM on bootstrap

### ISSUE THREAD

**Issue by preston-willis** [fluxcd/flux2#4306]
### Describe the bug

Flux bootstrap fails to reconcile with the source controller exiting with code 137 (OOM)

### kubectl describe pod <source-controller-pod> -n flux-system
Args:
      --events-addr=http://notification-controller.flux-system.svc.cluster.local./
      --watch-all-namespaces=true
      --log-level=info
      --log-encoding=json
      --enable-leader-election
      --storage-path=/data
      --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
    State:          Running
      Started:      Fri, 06 Oct 2023 18:51:09 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 06 Oct 2023 18:50:53 +0000
      Finished:     Fri, 06 Oct 2023 18:51:08 +0000
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      50m
      memory:   64Mi
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RUNTIME_NAMESPACE:  flux-system (v1:metadata.namespace)
      TUF_ROOT:           /tmp/.sigstore
    Mounts:
      /data from data (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zllsx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-zllsx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  47s                default-scheduler  Successfully assigned flux-system/source-controller-594c848975-vcsdt to ip-172-31-38-206.us-east-2.compute.internal
  Normal   Pulling    46s                kubelet            Pulling image "ghcr.io/fluxcd/source-controller:v1.1.1"
  Normal   Pulled     43s                kubelet            Successfully pulled image "ghcr.io/fluxcd/source-controller:v1.1.1" in 2.801715447s (2.801733226s including waiting)
  Normal   Created    26s (x2 over 43s)  kubelet            Created container manager
  Normal   Started    26s (x2 over 42s)  kubelet            Started container manager
  Normal   Pulled     26s                kubelet            Container image "ghcr.io/fluxcd/source-controller:v1.1.1" already present on machine
  Warning  Unhealthy  6s (x4 over 25s)   kubelet            Readiness probe failed: Get "http://172.31.35.26:9090/": dial tcp 172.31.35.26:9090: connect: connection refused

### flux logs
`2023-10-06T18:50:51.721Z info Kustomization/flux-system.flux-system - Source is not ready, artifact not found
`
I've tried increasing the source-controller deployment memory limit to 2Gi and 3Gi

### Steps to reproduce

Bootstrap with flux

### Expected behavior

I expected flux to bootstrap correctly

### OS / Distro

AWS EKS t3.medium Amazon Linux 2 amd64

### Flux version

v2.1.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.4-eks-2d98532 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Bitbucket

### Container Registry provider

dockerhub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Let's discuss this in #4305 no need for a 2nd issue

**Comment by khusseini** [comment]
@stefanprodan these two issues are not the same. one is memory one is disk space. I am having a problem with memory leaks too because my repository is big (1.5Gi)
When bootstrapping flux the source controller simply doesn't have enouh resource limits and doesn't start, this in turn leads to the git repository not being pulled and the artifact not built which in turn doesn't apply the kustomizations to apply higher resource limits. 
We need a way to control the resource requests and limits upon bootstrap. 
Currently the bootstrap is useless for us and we have to go the manual route of creating secrets and keys.
