### ISSUE TITLE
cli: gotk -> flux

### ISSUE THREAD

**Issue by clstb** [fluxcd/flux2#432]
Hi there!

I noticed that in docs the cli naming changed from gotk to flux. Furthermore it seems like the namespace for the controllers got changed and possibly the main config folder of the repository `gotk-system`, though I have not verified that.

Could a page to the docs be added describing what changed and needed migration steps if there are any?

**Comment by stefanprodan** [comment]
Please see https://github.com/fluxcd/flux2/discussions/413

**Comment by clstb** [comment]
Great, thank you!
