### ISSUE TITLE
Syntactic typo in docs for Bucket CRD

### ISSUE THREAD

**Issue by tvi** [fluxcd/flux2#436]
Hello,
On page https://toolkit.fluxcd.io/components/source/buckets/ in section `AWS IAM authentication` there is wrong `apiVersion: source.toolkit.fluccd.io/v1beta1`. It should be `apiVersion: source.toolkit.fluxcd.io/v1beta1`
I wanted to fix it, but I cannot find source of truth for the docs and when I grep this repo its not there.
Thanks.

**Comment by hiddeco** [comment]
@tvi this gets pulled in from https://github.com/fluxcd/source-controller/blob/c74fca7a2bc0a1543f403dcee25c2f70d08a108c/docs/spec/v1beta1/buckets.md

**Comment by tvi** [comment]
Thanks @hiddeco !
Attaching PR https://github.com/fluxcd/source-controller/pull/198
