### ISSUE TITLE
error message on bootstrap lacking accuracy

### ISSUE THREAD

**Issue by wibed** [fluxcd/flux2#4373]
### Describe the bug

bootstrap only times out, if there are any mistakes within the repo.

atm i work around it by bootstrapping onto an empty repo, cloning the directory into the existing codebase
and force pushing the current codebase back into the repo.

then i reconcile and get a proper error message

### Steps to reproduce

include following `HelmRelease`

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      releaseName: cluster0
      version: ">=1.0.0"
``` 

bootstrap output:
```shell
✗ client rate limiter Wait returned an error: context deadline exceeded
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 1 health check failure(s)
```

above method output:
```shell
✗ Kustomization reconciliation failed: HelmRelease/csi-driver-nfs/csi-driver-nfs dry-run failed: failed to create typed patch object (csi-driver-nfs/csi-driver-nfs; helm.toolkit.fluxcd.io/v2beta1, Kind=HelmRelease): .spec.chart.spec.releaseName: field not declared in schema
```

### Expected behavior

to receive the actual error it failed from the bootstrap command

### OS / Distro

macos 

### Flux version

2.1.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.3 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Bootstrap should only deploy Flux, all other things must be managed by dedicated Flux Kustomizations, please see the example on how to organise your repo:  https://github.com/fluxcd/flux2-kustomize-helm-example

Think of bootstrap as your boot sequence, you wouldn't add there apps.

**Comment by wibed** [comment]
in the case youd like to expand. forwarding the error message from the first reconciliation might be an option.

thank you for your time!
