### ISSUE TITLE
flux completion bash windows for linux  (WSL)issue

### ISSUE THREAD

**Issue by cforce** [fluxcd/flux2#4383]
### Describe the bug

Followed the guide at https://fluxcd.io/flux/cmd/flux_completion_bash/
Wsl Ubuntu shell throws error.

### Steps to reproduce

➜ . <(flux completion bash)
/proc/self/fd/11:type:12106: bad option: -t

~
➜ command -v flux >/dev/null && . <(flux completion bash)
Options
/proc/self/fd/11:type:12106: bad option: -t
zsh: command not found: Options

### Expected behavior

no error

### OS / Distro

Windows 10

### Flux version

2.1.2

### Flux check

➜ flux check
► checking prerequisites
✔ Kubernetes 1.26.6 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
Are you sure you're running bash? Confirm with `echo $BASH_VERSION`.

**Comment by cforce** [comment]
Oh yes, youz are so right
. <(flux completion zsh) is much better   :-)
