### ISSUE TITLE
flux uninstall leaves some artifacts

### ISSUE THREAD

**Issue by fenio** [fluxcd/flux2#4398]
### Describe the bug

After running `flux uninstall` I'm trying to again bootstrap it and it fails due to references to some stuff which should no longer be part of the cluster.

I'd like to start from scratch wit Flux cause I messed up my current setup as part of experiments.

So I ran `flux uninstall`, then I renamed repo in github and I'm trying to bootstrap flux again and it stucks on:

```
[☸ lab:default] [⏱ 2s]
❯ ~ flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=homelab \
  --branch=main \
  --path=./cluster \
  --personal --private=false
► connecting to github.com
► cloning branch "main" from Git repository "https://github.com/fenio/homelab.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBIYwDSQs7j2L4JXVZ/BMjY8bjbJHJIUDWT3cxer76RwDlqzyDXH1zILxA1MSDaaNOrqmtZY8/DKO5BJ4jMxPswoP2iIzwW1/ZB9CQlZjNFEpGDkW2EWGPNjwGlzrhdFNbw==
✔ configured deploy key "flux-system-main-flux-system-./cluster" for "https://github.com/fenio/homelab"
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
```

This is what `flux get all -A shows`

```
[☸ lab:default]
❯ ~/SECRETS flux get all -A
NAMESPACE  	NAME                     	REVISION          	SUSPENDED	READY	MESSAGE
flux-system	gitrepository/flux-system	main@sha1:78b2fc6e	False    	True 	stored artifact for revision 'main@sha1:78b2fc6e'

NAMESPACE  	NAME                     	REVISION	SUSPENDED	READY	MESSAGE
flux-system	kustomization/flux-system	        	False    	False	kustomize build failed: accumulating resources: accumulation err='accumulating resources from './apps/network': read /tmp/kustomization-258694489/cluster/apps/network: is a directory': recursed accumulation of path '/tmp/kustomization-258694489/cluster/apps/network': accumulating resources: accumulation err='accumulating resources from './metallb/ks.yaml': open /tmp/kustomization-258694489/cluster/apps/network/metallb/ks.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/tmp/kustomization-258694489/cluster/apps/network/metallb/ks.yaml' : lstat /tmp/kustomization-258694489/cluster/apps/network/metallb/ks.yaml: no such file or directory
```

And yeah... metallb/ks.yaml was part of the previously bootstrapped flux but somehow after uninstall and fresh bootstrap it still "remembers" that previous stuff.

I tried uninstall / bootstrap several times and same effect. I also tried to uninstall and then find anything related to Flux in clean cluster but I couldn't. To be honest I'm not sure where to look for it.

### Steps to reproduce

Well I'm pretty sure it's going to be hard to reproduce. But I still have my cluster in this weird state so I'm happy to share more details.

### Expected behavior

I'd expect that `flux uninstall` gets rid of anything related to previous flux install.

### OS / Distro

k0s on Debian 12

### Flux version

v2.1.2

### Flux check

[☸ lab:default] [⏱ 5m]
❯ ~ flux check
► checking prerequisites
✔ Kubernetes 1.28.3+k0s >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

But reconciliation fails.

### Git provider

github

### Container Registry provider

various

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fenio** [comment]
Ok seems that flux bootstrap didn't really create new repository so somehow even after rename of old one it still tries to use it. Pretty weird.

**Comment by fenio** [comment]
Now I deleted old repo instead of just renaming it and it went fine.

[☸ lab:default]
❯ ~ flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=homelab \
  --branch=main \
  --path=./cluster \
  --personal --private=false
► connecting to github.com
✔ repository "https://github.com/fenio/homelab" created
► cloning branch "main" from Git repository "https://github.com/fenio/homelab.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("66de2a3c1ffea7efef9a1ba4b6d80d785827483c")
► pushing component manifests to "https://github.com/fenio/homelab.git"
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBCqKKlw5qItdIznrFdsrDlLLZQwh4qw/yaWaqFjhLKB2misbRal0dnkQjnQ/pYVgeTc/cNjDE815Cp4GxbxYsgr85afvgbSomyOFVzkgqbnwDDeO97yV3aDnKOcoFr+/yA==
✔ configured deploy key "flux-system-main-flux-system-./cluster" for "https://github.com/fenio/homelab"
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ committed sync manifests to "main" ("c483a4dfce8401693439b1fd2561bac0839200f1")
► pushing sync manifests to "https://github.com/fenio/homelab.git"
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✔ Kustomization reconciled successfully
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy

So maybe just a hint that renaming repo on github side doesn't really mean that Flux won't be able to access it. 
It does ;)

**Comment by stefanprodan** [comment]
Renaming a repo doesn't do anything, GitHub sets up redirects in a such a way that both URLs old and new point to the same Git repo.

**Comment by fenio** [comment]
Yep. I learnt that the hard way. Feel free to close the ticket ;)
