### ISSUE TITLE
Flux adding releasename as prefix causes problems with NGINX ingress controller admission webhooks.

### ISSUE THREAD

**Issue by cloud-az** [fluxcd/flux2#4406]
### Describe the bug

Flux in Gitlab version 2.1.1 adding prefix to all resources for helmreleases causes error when configuering new ingress resources:

`ingress/sk-kubecost/xxx-ingress dry-run failed, reason: InternalError: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "[https://ingress-nginx-controller-admission.ingress.svc:443/networking/v1/ingresses?timeout=10s":](https://ingress-nginx-controller-admission.ingress.svc/networking/v1/ingresses?timeout=10s%22:) service "ingress-nginx-controller-admission" not found.`

Kubectl get svc -n ingress shows services with "ingress" as prefix,

### Steps to reproduce

Flux version: 2.1.1
AKS version: 1.26.3 - Linux
NGINX controller version: 1.7.1, Helm chart version 4.6.1

### Expected behavior

Being able to force not creating prefixes.

### Screenshots and recordings

![image](https://github.com/fluxcd/flux2/assets/130577660/9180f48e-2cb0-4f53-9c06-3c49576e3dfb)

### OS / Distro

ubuntu 20.4

### Flux version

2.1.1

### Flux check

✔ all checks passed

### Git provider

GitLab

### Container Registry provider

ACR - private

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
It's not Flux, but the chart who adds the prefix. Delete the HelmRelease and recreate it with `spec.releaseName` set to `ingress-nginx`.

**Comment by cloud-az** [comment]
Thank you! It is working now. 
But can not find any explanations on why it does not set any prefixes now?!

**Comment by stefanprodan** [comment]
> But can not find any explanations on why it does not set any prefixes now?!

Because the chart template skips the prefix if the release name matches the chart name. It's standard behaviour of most Helm chats. See https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/_helpers.tpl#L17
