### ISSUE TITLE
Kustomization sync failed: missing metadata.name in object

### ISSUE THREAD

**Issue by emily-zall** [fluxcd/flux2#4407]
### Describe the bug

I accidentally named a file Kustomization.yaml instead of kustomization.yaml and got this confusing error. It went away when I changed the file name to lowercase.

' Warning  BuildFailed              77s (x42 over 44m)      kustomize-controller  (combined from similar events): failed to decode Kubernetes YAML from /tmp/kustomization-2971422069/transaction-service/Kustomization.yaml: missing metadata.name in object {{kustomize.config.k8s.io/v1beta1 Kustomization} {{ } map[] map[]}} <nil>'

### Steps to reproduce

setup flux with a file called Kustomization.yaml with contents such as the following:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
```

See the sync error on the Kustomization.

### Expected behavior

I would expect that Kustomization.yaml works the same as the lowercase version. I don't expect flux to change the functionality of Kustomize based on the file name.

### OS / Distro

Mac OS 13.4.1

### Flux version

flux: v0.41.2

### Flux check

➜ flux check
► checking prerequisites
✗ flux 0.41.2 <2.1.2 (new version is available, please upgrade)
✔ Kubernetes 1.26.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Kustomize SDK is case sensitive, we can't change this in Flux https://github.com/kubernetes-sigs/kustomize/blob/82ee768212df792aec76636c07c487b40500ce46/api/konfig/general.go#L10-L16

**Comment by Jackbennett** [comment]
```
failed to decode Kubernetes YAML from /tmp/kustomization-613842398/myrepopath/capacitor/kusomization.yaml: missing metadata.name in object {{kustomize.config.k8s.io/v1beta1 Kustomization} {{ } map[] map[]}} <nil>
```

Any chance a better error message can give you a clue? kustomize has a message we just don't get it from flux https://github.com/kubernetes-sigs/kustomize/blob/16a7ce2b8b4ca73f2647e75a7def39cccf17157f/kustomize/commands/internal/kustfile/kustomizationfile.go#L149
