### ISSUE TITLE
Feature Request: mustache + downward api

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/flux2#4418]
Allow CRDs to utilize Kubernetes Downward API.

Allowing the Flux CRs to reference downward API via mustache syntax. 

`{{metadata.labels.environment}}`
`{{metadata.annotations.cert-manager_namespace}}`

would allow for `commonMetadata` supplied from `Kustomization` to be referenced in deployed manifests (resources, HelmRelease, ConfigMap, etc).

Currently the way to do this with DownwardAPI in Kustomize is a bit clunky but it's doable however it would be cleaner if that could be leveraged via templating like `mustache` where you could pull those values right into the field you need them.

**Comment by kingdonb** [comment]
I don't know how likely this is to be implemented, but I think it represents a pretty substantial change to Flux.

Generally I think we ask for major changes to go through an RFC, but in this case I'd actually be more comfortable if I saw it implemented in a fork first, so we can see how useful it is and if there are any pitfalls that come from the use.

Flux is not dogmatic about things like "single source of truth" but it is cautious of levers and features which may dramatically change the experience or the reproducibility of the deployments. This definitely sounds like one of those little changes that has a big impact. Where would you add the mustache, in the manifests? How are you doing this with Kustomize and the downward API now, can you share a bit about your implementation?

This might make more sense to convert into a discussion.
