### ISSUE TITLE
Kustomize controller not telling where the issue is

### ISSUE THREAD

**Issue by samip5** [fluxcd/flux2#4426]
### Describe the bug

I believe the kustomize controller should tell me exactly where the issue is when I get an `error decrypting env sources: no kustomization file found` for a kustomization.

### Steps to reproduce

Sorry, but not sure how.

### Expected behavior

I would expect it to print out somewhere where it doesn't find a kustomization file.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Git provider

Github

### Additional context

My public GitOps repo is at: https://github.com/samip5/k8s-cluster

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Can you please upgrade to Flux 2.2.3 and see if this is fixed, also please fill in the details in the issue, what flux version are you and the output of flux check

**Comment by samip5** [comment]
I'm closing this as I cannot remember which version was used.
