### ISSUE TITLE
image-reflector-controller listen DockerHub Webhooks

### ISSUE THREAD

**Issue by zs-dima** [fluxcd/flux2#4429]
It might be nice to listen to DockerHub webhooks to reduce or replace polling.
Polling mechanisms are not effective, while webhooks are perfect for this task.
Also, webhooks contain image and tag information to re-deploy only specific items.

**Comment by hiddeco** [comment]
This is already supported using https://fluxcd.io/flux/components/notification/receivers/#dockerhub

**Comment by zs-dima** [comment]
@hiddeco thanks for the answer, but Receivers have no option to re-deploy based on image and tag passed as Webhook payload.

**Comment by makkes** [comment]
@zs-dima Flux is built on the premise of reconciliation. The desired state needs to be declared in the form of a Kubernetes resource, in your case an ImagePolicy. I would like to understand in what way the [current functionality of ImagePolicies](https://fluxcd.io/flux/components/image/imagepolicies/#policy) doesn't satisfy the use case you have in mind.

**Comment by zs-dima** [comment]
@makkes thanks a lot for looking into. Current ImagePolicy require to specify separate declaration for each image, which can be quite many and they can change frequently during development. At the same time, the webhook payload contains all the information needed to redeploy the associated resources.

**Comment by makkes** [comment]
I understand. You would like to update image references, e.g. Deployments, from a webhook event. However, this is not the way we built Flux because it's edge-triggered while Flux is level-triggered (or [pull-based](https://fluxcd.io/flux/guides/webhook-receivers/)), meaning that Flux reconciles desired state and doesn't act solely upon events received from third-party systems. What if the event gets lost (the network is not reliable, after all)?

That's why you will need to declare an ImagePolicy for each image (you only need to create a resource per namespace, though).

**Comment by makkes** [comment]
> how ImagePolicy (filter image tag) and ImageRepository (filter image name) can find out image name:tag from webhook?

They don't need to because all the information they need to find the latest image is given in the ImageRepository and ImpagePolicy specs, respectively. As I said above the webhook is nothing more than a ping.

**Comment by zs-dima** [comment]
@makkes for example we set this webhook for 100 different images in DockerHub. How Flux will find out certain ImageRepository+ImagePolicy to update without reading webhook payload? It is not effective way to try to update all Flux images in this case.

**Comment by zs-dima** [comment]
@makkes thanks, so on webhook Flux will pull information from 100 DockerHub repositories instead of reading specific repository+tag from payload? Even if pull is not needed or related to 1 specific repository?
Looks like a good point for improvement.

**Comment by hiddeco** [comment]
> Looks like a good point for improvement.

This is just an oversimplified thought, and would IMHO not be an improvement at all. Given Flux would not be able to do many things it is capable of doing at the moment. Like using [policies](https://fluxcd.io/flux/components/image/imagepolicies/#policy) for image update automations, while simultaneously being able to change this policy to a different selector at any point in time.

In addition, it would have to rely on the webhook being available at all times to be able to detect new versions. Which in case of downtime of the endpoint, or environments on the edge with limited connectivity, would mean it would not make an update happen at all. With the current design, none of this is a problem.

Given this, we do not have an interest for the image-reflector-controller to directly be able to consume DockerHub webhook events beyond the current available notification-controller feature.
