### ISSUE TITLE
Support for Helm/Kustomization Uninstall Alerts

### ISSUE THREAD

**Issue by salamkar** [fluxcd/flux2#4432]
when setting up alerts for helmreleases install and upgrade alerts are forwarded to the alert provider. However Uninstall alerts are missing. The same issue applies for Kustomization deletion. The alert for kustomization deletion are also missing.

`flux: v2.0.0-rc.4
helm-controller: v0.34.0
kustomize-controller: v1.0.0-rc.4
notification-controller: v1.0.0-rc.4
source-controller: v1.0.0-rc.4`

### Discussed in https://github.com/fluxcd/flux2/discussions/3979

<div type='discussions-op-text'>

<sup>Originally posted by **NiklasSoderstrom** June 16, 2023</sup>
It is possible to get Flux to uninstall a helm deployment by reconciling to an empty directory with prune set to true. When the helm uninstall is ordered, I  would like to know when the resources has been deleted (similar to helm uninstall --wait).

There is a metric available that show the status of the HelmRelease. This can show as "Deleted", but it is set to true when the helm uninstall is ordered rather than when it has concluded.

There is no notification event for Helm uninstall.

Would it be possible to either create a notification when a helm uninstall has been concluded or change the behavior of the state metric so that it is set to true when the helm uninstall has finished.

 Or maybe both?</div>

**Comment by hiddeco** [comment]
For `HelmRelease` resources an event will be emitted at all times when an uninstall happens from next release on.

**Comment by stefanprodan** [comment]
Tested this with helm-controller prerelease
<img width="866" alt="Screenshot 2023-11-30 at 12 19 12" src="https://github.com/fluxcd/flux2/assets/3797675/b0deb912-ffda-49d7-af6c-d4eb92982c97">

Closing this issue as it's solved. The event will be available once we release Flux v2.2.2
