### ISSUE TITLE
imagerepositories.image.toolkit.fluxcd.io missing

### ISSUE THREAD

**Issue by bogdancosmin** [fluxcd/flux2#4451]
### Describe the bug

Trying to create an imagerepository the kustomize throws this error:
```
ImageRepository/kafka/strimzi-operator dry-run failed: failed to get API group resources: unable to retrieve the complete list of se │
│ rver APIs: image.toolkit.fluxcd.io/v1beta2: the server could not find the requested resource
```

### Steps to reproduce

1. brew install flux
2. create an ImageRepository
3. update flux to the latest version
4. imagerepositories.image.toolkit.fluxcd.io still missing

### Expected behavior

ImageRepository should be created 

### OS / Distro

macOS 14.1.2

### Flux version

v2.1.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.2 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Image automation is an opt-in feature, please here how to enable it: https://fluxcd.io/flux/installation/configuration/optional-components/
