### ISSUE TITLE
FluxCD installation setup in private AKS cluster is getting failed.

### ISSUE THREAD

**Issue by vivuu1989** [fluxcd/flux2#4462]
### Describe the bug

We were trying to integrate our existing Azuredevops based based pipeline and Helm based releases to AKS cluster using the GitOps approach by FluxCd extension. All our AKS instances are created using terraform and we were using the serviceprincipal with ACR access and privatedns zone record creation and all other required permissions (also owner of the subscription).  These Aks clusters are created long before and which are in continuous usage. But when we tried to install the FluxCD by following the MS document , getting below error.

az k8s-extension create --resource-group my-rg --cluster-name my --cluster-type managedClusters -n flux --extension-type microsoft.flux --auto-upgrade-minor-version
(ExtensionOperationFailed) The extension operation failed with the following error:  Extensions are only supported on clusters using Managed Service Identity. See https://aka.ms/aks-extensions-service-principal-not-supported, For general troubleshooting visit: https://aka.ms/k8s-extensions-TSG.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Extensions are only supported on clusters using Managed Service Identity. See https://aka.ms/aks-extensions-service-principal-not-supported, For general troubleshooting visit: https://aka.ms/k8s-extensions-TSG.

I read in the site that, we have to enable the managed Identity for this clusters. As we have a lot of dependent services with this cluster, how to make the Flux cd installed without making any disruption. Changing the SPN enabled cluster to managed identity based Aks will have any impact ?

### Steps to reproduce

Message: The extension operation failed with the following error:  Extensions are only supported on clusters using Managed Service Identity. See https://aka.ms/aks-extensions-service-principal-not-supported, For general troubleshooting visit: https://aka.ms/k8s-extensions-TSG.

### Expected behavior

Fluxcd installed and working in SPN based AKS cluster and integrated with Azuredevops

### OS / Distro

Linux

### Flux version

NA

### Flux check

V1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Raise this with Microsoft support please. If you want to use upstream Flux, see here the docs: https://fluxcd.io/flux/installation/bootstrap/azure-devops/
