### ISSUE TITLE
Flux v2.2.0 HelmRepository of type OCI not reconciling

### ISSUE THREAD

**Issue by buroa** [fluxcd/flux2#4469]
### Describe the bug

All of my HelmRepositories of type: oci are not reconciling or providing a status.

### Steps to reproduce

Upgrade to v2.2.0 and have a HelmRepository of type: oci
It won't ever go "Ready"

### Expected behavior

Goes Ready, just like the previous versions

### Screenshots and recordings

<img width="1619" alt="Screenshot 2023-12-12 at 10 51 40 AM" src="https://github.com/fluxcd/flux2/assets/36205263/51a61f93-1b93-4525-940c-b238995f5832">

### OS / Distro

Linux

### Flux version

v2.2.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
I can confirm I'm seeing the same issue.

**Comment by stefanprodan** [comment]
Yeap, HelmRepository of type OCI is now static. See the changelog https://github.com/fluxcd/flux2/releases/tag/v2.2.0

**Comment by onedr0p** [comment]
Thanks! Missed that in the release notes.
