### ISSUE TITLE
Provide integration with Keptn

### ISSUE THREAD

**Issue by jetzlstorfer** [fluxcd/flux2#447]
I would like to see an integration with [Keptn](https://keptn.sh) (a control-plane for continuous delivery and automated operations) and be able to trigger Flux deployments with Keptn. 

There has already been an issue created in the Keptn repo: https://github.com/keptn/keptn/issues/2669
For better transparency, I'm also creating the issue on this organization.

The idea is that if you have both Keptn and Flux, it should be possible to trigger a new deployment via Keptn, and once the deployment is finished, Keptn is notified to trigger additional tests, evaluation, and even promotion to a subsequent environment/stage.

**Comment by squaremo** [comment]
Thanks for telling us about this :tada: If you want to solicit people's ideas on the intended integration, please consider [starting a discussion](https://github.com/fluxcd/flux2/discussions).

**Comment by stefanprodan** [comment]
Closing this as there is nothing to act on. Please open a [discussion](https://github.com/fluxcd/flux2/discussions) if there is something needed from the Flux side.
