### ISSUE TITLE
helm-controller sharding not working in 2.2.1

### ISSUE THREAD

**Issue by MaxRink** [fluxcd/flux2#4500]
### Describe the bug

We have two instances of the helm operator in each cluster, one for platform components, another one for everything else.
With the latest release both controllers try to reconcile all HRs, which leads to 'interesting' behaviour 
e.g.
```
  Normal   UpgradeSucceeded     26m                helm-controller  Helm upgrade succeeded for release schiff-system/schiff-network.v2 with chart schiff-network@0.1.0
  Warning  UpgradeFailed        26m                helm-controller  Helm upgrade failed for release schiff-system/schiff-network with chart schiff-network@0.1.0: release: already exists
```

### Steps to reproduce

Flux 1 has:
`      --watch-label-selector=sharding.fluxcd.io/key=platform`
Flux 2 has:
`      --watch-label-selector=sharding.fluxcd.io/key notin (platform)`
i also tried 
`      --watch-label-selector=!sharding.fluxcd.io/key`
just to make sure (which is in the current docs)
Both worked in the past and there was no change in any of the changelogs

The HRs either have 
```
  labels:
    sharding.fluxcd.io/key: platform
```

or no label at all

### Expected behavior

The sharding works as expected.

### OS / Distro

N/A

### Flux version

v2.2.1

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Sorry you had to run into this Max. We addressed this in the above issue, and CI is currently building `v0.37.2` which should be available in a couple minutes. As soon as that's available, I will do an emergency release of the CLI as well.

But in the meantime, updating just the controller should be sufficient.

**Comment by hiddeco** [comment]
Now available as https://github.com/fluxcd/flux2/releases/tag/v2.2.2
