### ISSUE TITLE
SkipDryRunOnMissingResource-like option

### ISSUE THREAD

**Issue by zs-dima** [fluxcd/flux2#4515]
Might be nice to add an option similar to SkipDryRunOnMissingResource in ArgoCD.
Currently deployment hangs without manual dependsOn specification to deploy configurations after HelmRelease.
It would be nice if Flux would not pass the orchestration to the user to do manually.
ArgoCD does not require manual orchestration by specifying the SkipDryRunOnMissingResource attribute for configurations.

### Steps to reproduce

Deploy HelmRelease and related configuration without manual dependsOn specification.

### Expected behavior

It would be nice if Flux would not pass the orchestration to the user to do manually.

**Comment by stefanprodan** [comment]
Flux is not Argo, skipping dryrun would do nothing, Flux doesn't unpack Helm charts into plain YAMLs, so even if you skip dry run it will fail to apply, since a HelmRelease is reconciled by a different controller.
