### ISSUE TITLE
 Flux Workflow command for commit/push 

### ISSUE THREAD

**Issue by 0x53fa29jhezc** [fluxcd/flux2#454]
Would be nice to have a command for upgrading the cluster 

For example with a check of the files like in the example https://github.com/stefanprodan/flux2-kustomize-helm-example 
-> scripts/validate.sh 
This script is really helpful and gives specially beginners good feedback to avoid submitting invalid configs

after validating it just pushes with

git add -A && git commit -m "message" && git push

there could also be a automatic increase of a semver Version for commit message + maybe tagging the commit

The command could look like: 

flux upgrade --major -> increase x.0.0
flux upgrade --minor -> increase 0.x.0
flux upgrade --patch -> increase 0.0.x

**Comment by stefanprodan** [comment]
Please add your suggestion here: https://github.com/fluxcd/flux2/discussions/478
