### ISSUE TITLE
cli should error on unrecognized parameters

### ISSUE THREAD

**Issue by avila-m-6** [fluxcd/flux2#4551]
### Describe the bug

flux cli ignored my resource argument on `flux uninstall`, fully uninstalling flux instead of my specific intended resource.

### Steps to reproduce

```
$ kubectl get helmrelease.helm.toolkit.fluxcd.io -n flux-ca-system my-resource
NAME             AGE   READY   STATUS
my-resource      23m   False   HelmChart 'flux-ca-system/flux-ca-system-my-resource' is not ready
$ flux --version
flux version 2.1.0
$ flux uninstall helmrelease.helm.toolkit.fluxcd.io -n flux-ca-system my-resource
Are you sure you want to delete Flux and its custom resource definitions: y
► deleting components in flux-ca-system namespace
✔ ServiceAccount/flux-ca-system/helm-controller deleted
✔ ServiceAccount/flux-ca-system/image-automation-controller deleted
[...] (59 other resources)
✔ Namespace/flux-ca-system deleted
✔ uninstall finished
$ 
```
### Expected behavior

An error should be thrown like "my resource is not a recognized argument for flux uninstall".

### OS / Distro

Ubuntu 22.04 (wsl)

### Flux version

v2.1.0

### Flux check

N/A

### Additional context

I now know to remove the helmrelease with flux uninstall is a mistake, this caused an unintended removal. But that may've been caught by the cli exception.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Feel free to open a PR similar to https://github.com/fluxcd/flux2/pull/4404

**Comment by twinguy** [comment]
Hi everyone, first time contributor but regular user of Flux.  Happy to help with this effort.  For the uninstall command, I did some testing and it looks like adding `Args: cobra.OnlyValidArgs` and `ValidArgs: []string{"keep-namespace", "dry-run", "silent"}` gives the expected behavior.

**Comment by stefanprodan** [comment]
Hey @twinguy the uninstall has no args but only flags, same as bootstrap, please see the PR I linked above.
