### ISSUE TITLE
SOPS requires some write access when using AWS KMS

### ISSUE THREAD

**Issue by dulltz** [fluxcd/flux2#457]
This is the feedback about [the guide about SOPS](https://github.com/fluxcd/flux2/blob/16fa167931481e48845c63f088ddff2291ea1cc9/docs/guides/mozilla-sops.md).
The SOPS guide says that using AWS KMS requires read access to KMS.
However, in fact, it requires write access called `KMS:Decrypt`.
This is a little misleading, so we should update the document.

> When using AWS/GCP KMS, you'll have to bind an IAM Role with read access to the KMS keys to the default service account of the flux-system namespace for kustomize-controller to be able to fetch keys from KMS. 

https://github.com/fluxcd/flux2/blob/16fa167931481e48845c63f088ddff2291ea1cc9/docs/guides/mozilla-sops.md#configure-secrets-decryption

**Comment by dulltz** [comment]
By the way, is it preferable to report documentation feedback to a GitHub Issue or to a Discussion?

**Comment by stefanprodan** [comment]
This kind of feedback is fine here as an issue, thank you.

I think we should add a phrase for AWS with an example of IAM and the eksctl command to bind the SA. Can you make a PR for this?

**Comment by dulltz** [comment]
OK, I will send a PR.

**Comment by gertux** [comment]
An example policy would be great. I'm using the policy below which works with the sops cli in a container running with the same service account (flux-system:default):
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kms:eu-west-1:XXXXX209540:key/4f581f5b-7f78-45e9-a543-83a7022e8105"
        }
    ]
}
```
It fails with:
```
{"level":"error","ts":"2020-11-18T08:18:35.764Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"kustomize.toolkit.fluxcd.io","reconcilerKind":"Kustomization","controller":"kustomization","name":"flux-system","namespace":"flux-system","error":"decryption failed for 'demoapp': GetDataKey: Error getting data key: 0 successful groups required, got 0"}
```
Turning on debug logging did not reveal anything extra.

**Comment by stefanprodan** [comment]
@gertux you need to restart the kustomize-controller pod I think for the IAM binding to apply.

**Comment by dulltz** [comment]
@gertux 
Did you set `fsGroup: 1337` ?
The kustomize-controller container is running as a non-root user, so you need to set 
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

**Comment by gertux** [comment]
@stefanprodan the controller was restarted, so the service account was linked to the AWS role and policy.

@dulltz is right, the fsGroup was missing, thanks for that !

**Comment by stefanprodan** [comment]
This should work now in v0.3.0, the kustomize-controller uses fsGroup and I've added the IAM example to the docs.
