### ISSUE TITLE
HelmRepository is in Not Ready state after upgrading to v2.2.2

### ISSUE THREAD

**Issue by DanielAntos90** [fluxcd/flux2#4593]
### Describe the bug

HelmRepository stucks in Not Ready state after upgrading flux to v.2.2.2. I have tried patch the flux to 2.2.3, but HelmRepository is still in Not Ready State. I have also tried to upgrade HelmRelease to helm.toolkit.fluxcd.io/v2beta2 but it didn't help.

### Steps to reproduce

HelmRepositry configuration for weave

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts

### Expected behavior

It should be in Ready state

### OS / Distro

macOS 14.2.0

### Flux version

v2.2.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.26.10 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.3
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.4
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by debdutdeb** [comment]
With https://github.com/fluxcd/flux2-kustomize-helm-example/pull/106 we can close this right?
