### ISSUE TITLE
Collect all errors for bulk `kubectl` actions before returning

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#46]
At present when we are for example checking the rollout status of multiple installed components, it will stop and only return the first error if some component's rollout failed.

To provide a user with a better overview of what happened, we should complete the bulk run before bailing so that we can return a full overview of what did and did not succeed.

For bonus points: we would like to minimize the number of shell-outs we make to `kubectl`, and use the Golang Kubernetes client where possible. An example of this for rollout checks can be found [here](https://github.com/weaveworks/flagger/blob/master/pkg/canary/deployment_ready.go).

**Comment by adrian** [comment]
@hiddeco looks like you've already addressed this issue with https://github.com/fluxcd/flux2/pull/922
