### ISSUE TITLE
Support setting timezone in controller images

### ISSUE THREAD

**Issue by onedr0p** [fluxcd/flux2#460]
It would be nice for users of Flux2 if we could set the timezone in the controller containers. Being in the USA it's often annoying to look at the logs and determine the correct time, since we follow DST. Having the timezone correct in the containers would help quickly and easily determine the time. 

For adding support (I think) all that is needed it setting a `TZ` environment variable and adding the `tzdata` package to the controllers. People can configurable in the `flux` cli by passing a `--timezone` flag which sets the environment variable in the manifests. E.g. `flux bootstrap github --timezone="America/New_York" ...`

E.g. in helm-controller

```
FROM alpine:3.12

ENV TZ

# link repo to the GitHub Container Registry image
LABEL org.opencontainers.image.source="https://github.com/fluxcd/helm-controller"

RUN apk add --no-cache ca-certificates tini tzdata

COPY --from=builder /workspace/helm-controller /usr/local/bin/

RUN addgroup -S controller && adduser -S -g controller controller

USER controller

ENTRYPOINT [ "/sbin/tini", "--", "helm-controller" ]
```

Thanks for considering.

**Comment by onedr0p** [comment]
Please let me know if this is something you're willing to support, I can work on a PR.

**Comment by hiddeco** [comment]
This idea is disastrous for servers in multiple regions, and likely even more for containers that can literally be spawned on any continent. So, no.

**Comment by onedr0p** [comment]
Sorry I am not following. It is my understanding that the containers do not use the hosts timezone settings. Since all the containers use UTC by default how is it any different from switching from one timezone to another? In the method I explained above the default would be UTC but could be user-configurable.

**Comment by hiddeco** [comment]
> What kind of disasters are we expecting?

The `tzdata` package will get out of date, as a new timezone database is published every now and then. This is for example also the reason the `CronJob` kind does not offer support for time zones, which I solved by writing [cronjobber](https://github.com/hiddeco/cronjobber) that offers a sidecar utility to keep it up-to-date.

Logging (or storing timestamps in general) in UTC is just a very good (and common) practice, that is hard to argue against.

**Comment by onedr0p** [comment]
Thanks for explaining that more, I understand. While hesitant I digress.

Also, Cronjobber seems like a tool I never knew I needed. :)
