### ISSUE TITLE
Unable to update flux binary via flux install: Invalid: CustomResourceDefinition.apiextensions.k8s.io "alerts.notification.toolkit.fluxcd.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta3": must appear in spec.versions

### ISSUE THREAD

**Issue by schmidi** [fluxcd/flux2#4628]
### Describe the bug

When trying to update the flux binary from 2.1.2 to 2.2.3 in the command line results in an error.

The flux installation on the cluster has already been updated to 2.2.3 via renovate pull request.

```
$ flux install
✚ generating manifests
✔ manifests build completed
► installing components in flux-system namespace
✗ install failed: CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io dry-run failed, reason: Invalid: CustomResourceDefinition.apiextensions.k8s.io "alerts.notification.toolkit.fluxcd.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta3": must appear in spec.versions
```

### Steps to reproduce

1. Run `flux check` everything looks ok
2. Run  `flux install` the error message occurs

### Expected behavior

`flux install` should succeed

### OS / Distro

Ubuntu Server 20.04

### Flux version

v2.1.2

### Flux check

flux check
► checking prerequisites
✗ flux 2.1.2 <2.2.3 (new version is available, please upgrade)
✔ Kubernetes 1.29.1+k3s2 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.4
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The check command tells you what's the issue:
```
✗ flux 2.1.2 <2.2.3 (new version is available, please upgrade)
```

You need to download the latest flux CLI binary and use in on your computer.
