### ISSUE TITLE
API definitions contain invalid tag `genclient:Namespaced`

### ISSUE THREAD

**Issue by gmolau** [fluxcd/flux2#4634]
Many API definitions of the Flux project contain a tag `genclient:Namespaced`. This tag isn't actually used by controller-tools, only `nonNamespaced`.

Having this tag does not create immediate problems, but can trip up other tools that validate the tags, e.g. applyconfiguration-gen [here](https://github.com/kubernetes/code-generator/blob/a8c17f9aa5fa2645fe279eaf74d362f85fddca00/cmd/client-gen/generators/util/tags.go#L27).

Originally discussed in the CNCF Slack [here](https://cloud-native.slack.com/archives/CLAJ40HV3/p1708794732147909).

PRs to remove this tag everywhere:
* https://github.com/fluxcd/helm-controller/pull/901
* https://github.com/fluxcd/kustomize-controller/pull/1092
* https://github.com/fluxcd/source-controller/pull/1386
* https://github.com/fluxcd/notification-controller/pull/749
* https://github.com/fluxcd/pkg/pull/740

**Comment by gmolau** [comment]
The image controllers don't use it, see https://github.com/search?q=%2Fgenclient%3ANamespaced%2F+org%3Afluxcd&type=code

I had missed one in pkg though, added this now.

**Comment by gmolau** [comment]
@stefanprodan Can you trigger a release for these updates? I know I could depend on the commits directly, but I would like to keep the version of my Docker images in sync with the lib.

**Comment by stefanprodan** [comment]
@gmolau these changes will be included in the next minor scheduled for mid April.
