### ISSUE TITLE
Is it necessary for FluxCD to have access to Kubernetes nodes root directories? 

### ISSUE THREAD

**Issue by rajagopalrao** [fluxcd/flux2#4691]
Is it necessary for FluxCD to have access to Kubernetes nodes root directories? If so, then how does FluxCD tackle the Security policies that are applied to Kubernetes Clusters?

**Comment by stefanprodan** [comment]
> Is it necessary for FluxCD to have access to Kubernetes nodes root directories?

No, please see the security docs: https://fluxcd.io/flux/security/#pod-security-standard

Also use GH discussions for questions instead of issues.  https://github.com/fluxcd/flux2/discussions

**Comment by rajagopalrao** [comment]
Do we need to grant Cluster Admin role to FluxCD for during the installation and also to perform it's regular operations post installation? As we have setup FluxCD on a Kubernetes CLuster, Cluster Admin team is not happy to grant Cluster Admin role to FluxCD. Kindly share the list of permissions FluxCD needs for it's installation & it's operations.

**Comment by stefanprodan** [comment]
@rajagopalrao the Admin team has to install Flux, then limit its access, they need to follow these docs:
- https://fluxcd.io/flux/installation/configuration/multitenancy/
- https://github.com/fluxcd/flux2-multi-tenancy
