### ISSUE TITLE
KUBECONFIG with multiple config files error

### ISSUE THREAD

**Issue by tibberg** [fluxcd/flux2#472]
If I run `flux check --pre` it will give me the following error: 
<pre>► checking prerequisites
✔ kubectl 1.19.3 &gt;=1.18.0
✗ Kubernetes client initialization failed: stat /home/tib/.kube/config:/home/tib/.kube/config-cluster-X:/home/tib/.kube/config-cluster-Y: no such file or directory
</pre>

**Comment by tibberg** [comment]
of course if I run it with `flux check --pre --kubeconfig ~/.kube/config` it works.

**Comment by jbalonso** [comment]
Notably, the specific kubeconfig file addressed must be the one with the configuration defined:
```
$ flux check --pre --kubeconfig /home/jalonso/.kube/config
► checking prerequisites
✔ kubectl 1.19.4 >=1.18.0
✗ Kubernetes client initialization failed: invalid configuration: [context was not found for specified context: home, cluster has no server defined]
```

Notice: the active context is set in `~/.kube/config`, but that context is defined in a different file.

**Comment by anthr76** [comment]
Facing this issue as well.
