### ISSUE TITLE
Patches are not being applied running the OLM operator

### ISSUE THREAD

**Issue by kritag** [fluxcd/flux2#4725]
### Describe the bug

I manage several clusters, and in our organization I want to employ the OLM operator for our OCP clusters. Flux works as expected in our clusters, but I would like to use the OLM operator that is in the Operator Marketplace.

We have an existing repository containing manifests, but we are reliant on proxying the traffic towards github (ssh), so we have set up a proxy. Again, this works for our other clusters and has for years.

We apply a host alias in this way in our `kustomization.yaml` file in our repo:

```yaml
- patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: all
        spec:
          template:
            spec:
              hostAliases:
                - hostnames:
                  - github.com
                  ip: 10.201.201.201
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
```

We have a simple `socat` proxy deployed and set up that does the proxying for us. The issue is that the patch above is not applied to any of our deployments that are labeled as such. The actual Kustomization object present in our cluster contain these patches, and flux is stuck in what seems like a catch 22, that it can't connect to github to do the gitops it's supposed to.

The error in OCP is
```
2024-04-16T08:03:45.763Z error GitRepository/flux-system.flux-system - Reconciler error failed to checkout and determine revision: unable to clone 'ssh://git@github.com/<redacted>': dial tcp 140.82.121.4:22: connect: connection timed out
```

This IP should be the aforementioned IP that is supposed to be applied as a patch to all flux objects, but it is not applied.

Here is a snippet of the kustomization object present in the cluster, by running ` oc edit kustomizations.kustomize.toolkit.fluxcd.io -n flux-system flux-system` :
```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2024-04-11T12:45:28.67117861+02:00"
  creationTimestamp: "2024-04-04T12:17:23Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 5
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
  resourceVersion: "70522988"
  uid: 7ac6cbb1-636f-476d-9a09-6ccf7d2aca5c
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  force: false
  interval: 10m0s
  patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                securityContext:
                  runAsUser: 65534
                  seccompProfile:
                    $patch: delete
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |-
      - op: remove
        path: /metadata/labels/pod-security.kubernetes.io~1warn
      - op: remove
        path: /metadata/labels/pod-security.kubernetes.io~1warn-version
    target:
      kind: Namespace
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            hostAliases:
              - hostnames:
                - github.com
                ip: 10.201.201.201
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
``` 

### Steps to reproduce

1. Bootstrap flux through the CLI
2. Install the flux OLM operator from the OpenShift marketplace

### Expected behavior

Patches from our kustomization is applied.

### OS / Distro

CoreOS

### Flux version

2.2.2

### Flux check

► checking prerequisites
✗ flux 2.2.2 <2.2.3 (new CLI version is available, please upgrade)
✔ Kubernetes 1.27.11+749fe1d >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.2
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.37.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.31.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The OLM operator does not support customisations nor can you run it on a cluster where you've run `flux bootstrap`. The OLM operator is not supported by the Flux team, we recommend using `flux bootstrap` by applying the customisations as documented here: https://fluxcd.io/flux/installation/configuration/boostrap-customization/

There are many things wrong with your setup, the root Flux Kustomization should't contain any patches, nor decryption. Please see here how to structure your repo: https://github.com/fluxcd/flux2-kustomize-helm-example
