### ISSUE TITLE
flux report skipping unknown hook: "post-install, pre-uninstall"

### ISSUE THREAD

**Issue by JingangLi** [fluxcd/flux2#4756]
### Describe the bug

Hi, 

I use flux v2.2.3 to manamge my helm chart deployment.

I have a helm hook as this :

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-helm.fullname" . }}-ljg
  labels:
    {{- include "demo-helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-install, pre-uninstall"
    helm.sh/hook-delete-policy: "hook-failed"
    helm.sh/hook-weight: "-204"

But the flux helm controller report this log:
2024/05/03 20:41:50 info: skipping unknown hook: "post-install, pre-uninstall"

And my KRM resource with this helm hook isn't created.

Could you give me some support on it?

Many thanks.

### Steps to reproduce

Build helm chart with the deployment has above hook deifnition.

### Expected behavior

The KRM resource should be deployed

### OS / Distro

Linux

### Flux version

v2.2.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.28.7-gke.1026000 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.3
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.4
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
`pre-uninstall` is not a valid Helm hook, see: https://helm.sh/docs/topics/charts_hooks/#the-available-hooks

**Comment by JingangLi** [comment]
Hi @hiddeco ,

Many thanks. I refer to wrong definition before.

Rgds,
Jingang Li
