### ISSUE TITLE
HelmRelease does not install missing resources on Upgrade

### ISSUE THREAD

**Issue by rrileyca** [fluxcd/flux2#4765]
### Describe the bug

To my knowledge there is no way to reconcile ALL resources in FluxCD. My example scenario is installing helm chart that creates a CRD like a `ServiceMonitor` from Prometheus. If you delete that ServiceMonitor, I don't know of a way to have FluxCD reconcile it back. I have to resort to `helm template` to create the ServiceMonitor and apply it manually.

### Steps to reproduce

1. Install a chart like [Bitnami's RabbitMQ chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq). Enable the values:
```yaml
metrics:  
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: prometheus
```
2. Delete the `ServiceMonitor` that this chart creates
3. Run `flux reconcile helmrelease ${rabbitmq_release_name}`

### Expected behavior

The `ServiceMonitor` should come back, but it does not.

### OS / Distro

Ubuntu 22.04

### Flux version

2.0.1

### Flux check

flux check                                                                                                                                               (hbsi-dev-aks/kube-state-metrics)
► checking prerequisites
✗ flux 2.0.1 <2.2.3 (new version is available, please upgrade)
✔ Kubernetes 1.28.5 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► my-local-nexus.com/fluxcd/helm-controller:v0.37.4
✔ image-automation-controller: deployment ready
► my-local-nexus.com/fluxcd/image-automation-controller:v0.37.1
✔ image-reflector-controller: deployment ready
► my-local-nexus.com/fluxcd/image-reflector-controller:v0.31.2
✔ kustomize-controller: deployment ready
► my-local-nexus.com/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► my-local-nexus.com/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► my-local-nexus.com/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

Nexus (proxy to dockerhub)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You need to enable drift detection and correction, docs here: https://fluxcd.io/flux/components/helm/helmreleases/#drift-detection

**Comment by rrileyca** [comment]
@stefanprodan Thank you. Apologies I did not see that portion of the docs. This is exactly what I needed.
