### ISSUE TITLE
[document bug] v2.2.3 release notes 

### ISSUE THREAD

**Issue by topikachu** [fluxcd/flux2#4786]
### Describe the bug

The link "the procedure documented in 2.2.0" points to the wrong 2.0.0 URL.

### Steps to reproduce

As above

### Expected behavior

To the correct 2.2.0 URL

### OS / Distro

N/A

### Flux version

v2.2.3

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Fixed! Thanks for reporting
