### ISSUE TITLE
HelmRepository with oci type - Harbor registry

### ISSUE THREAD

**Issue by giladk1221** [fluxcd/flux2#4814]
### Describe the bug

we configured Helm Repository with oci type to our private harbor(Version v2.7.2-a051373e) with the url: oci://harbor.office.com/devops
its created successfully and the status for the object is ready=true and status helm repository is ready.

when we create HelmRelease Object with this configuration:
fluxd version : flux2-2.11.1

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: go-oci-test/go-test-new
      version: "1.5"
      sourceRef:
        kind: HelmRepository
        name: harbor-helm-charts-devops
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    file: values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: test-values
  targetNamespace: lala
  interval: 1m
  timeout: 3m

its return an error:

    message: 'chart pull error: failed to get chart version for remote reference:
      could not get tags for "go-oci-test/go-test-new": unable to locate any tags
      in provided repository: oci://harbor.office.com/devops/go-oci-test/go-test-new'
    observedGeneration: 1

and its very strange because if we run manually with helm command this one:
helm pull oci://harbor.office.com/devops/go-oci-test/go-test-new --version 1.5

its working successfully without any issue.

waiting for your advice please

### Steps to reproduce

we configured Helm Repository with oci type to our private harbor(Version v2.7.2-a051373e) with the url: oci://harbor.office.com/devops
its created successfully and the status for the object is ready=true and status helm repository is ready.

when we create HelmRelease Object with this configuration:
fluxd version : flux2-2.11.1

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: go-oci-test/go-test-new
      version: "1.5"
      sourceRef:
        kind: HelmRepository
        name: harbor-helm-charts-devops
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    file: values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: test-values
  targetNamespace: lala
  interval: 1m
  timeout: 3m

its return an error:

    message: 'chart pull error: failed to get chart version for remote reference:
      could not get tags for "go-oci-test/go-test-new": unable to locate any tags
      in provided repository: oci://harbor.office.com/devops/go-oci-test/go-test-new'
    observedGeneration: 1

and its very strange because if we run manually with helm command this one:
helm pull oci://harbor.office.com/devops/go-oci-test/go-test-new --version 1.5

its working successfully without any issue.

waiting for your advice please

### Expected behavior

find relevant tags for chart that configured in helmrelease

### OS / Distro

N/A

### Flux version

v2.1.2

### Flux check

► checking prerequisites
✗ flux 2.1.2 <2.3.0 (new version is available, please upgrade)
✔ Kubernetes 1.25.10+vmware.1 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► harbor.office.com/devops/fluxcd/helm-controller:v0.36.2
✔ image-automation-controller: deployment ready
► harbor.office.com/devops/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► harbor.office.com/devops/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► harbor.office.com/devops/fluxcd/kustomize-controller:v1.1.1-ca
✔ notification-controller: deployment ready
► harbor.office.com/devops/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► harbor.office.com/devops/fluxcd/source-controller:v1.1.2-ca
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab

### Container Registry provider

Harbor Repository

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by giladk1221** [comment]
> Are you sure to have a tag that matches the strict constraint `v2.7.2-a051373e`?

this is the version for our harbor repositry:
![image](https://github.com/fluxcd/flux2/assets/29776916/cfe36746-fe74-4790-a435-b0f04b89e53a)

we are using tag version "1.5" in the chart itself.
and this need to be ok and working.
can you see this here:
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: test
namespace: flux-system
spec:
interval: 30m
chart:
spec:
chart: go-oci-test/go-test-new
version: "1.5"

**Comment by giladk1221** [comment]
tags : 1.4, 1.5

![image](https://github.com/fluxcd/flux2/assets/29776916/75917077-4785-4f73-93d3-2f1d370f39c5)

**Comment by souleb** [comment]
can you provide your helm version? The same client is used so you should have same behavior. Also are you using https?

**Comment by giladk1221** [comment]
> can you provide your helm version? The same client is used so you should have same behavior. Also are you using https?

helm version -
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}

using https for? if its for harbor connection, yes its via https.

**Comment by giladk1221** [comment]
I found Bug in fluxcd code:
Under HelmRelease manifest, you must specify the version for the chart like that : x.x.x (its means 3 digits)
If you specify 2 digits like in the example I uploaded here its return the error: "failed to fetch tags...."


chart: go-oci-test/go-test-new
version: "1.5"

Important to notice that helm pull working successfully with 2 digits, so it's look like a bug under Flux code

Please update the relevant code

**Comment by souleb** [comment]
We assume valid `version 2` semantic versions. While `helm` attempts to coerce a version into a semantic, e.g. a version listed without all 3 parts (e.g. 1.2) it will attempt to coerce it into a valid semantic version (e.g., 1.2.0).

The difference is in the [parsing function](https://pkg.go.dev/github.com/Masterminds/semver/v3#hdr-Parsing_Semantic_Versions) we use.

We won't change the function that we use, but we could return any `ErrInvalidSemVer` error.
