### ISSUE TITLE
HelmChart display all error message: open /data/helmrepository/flux-system/xxx.yaml:       no such file or directory

### ISSUE THREAD

**Issue by dirien** [fluxcd/flux2#482]
Hi,

my HelmCharts show all following error message:

![image](https://user-images.githubusercontent.com/38325136/99762532-05f38200-2af9-11eb-8296-60ee8da90a57.png)

The message in detail
![image](https://user-images.githubusercontent.com/38325136/99762544-1277da80-2af9-11eb-94f5-ffafacd16a57.png)

Is there something i miss during install of the flux controller?

**Comment by hiddeco** [comment]
This is due to a bug that has been fixed in `v0.3.0` of the source-controller (https://github.com/fluxcd/source-controller/pull/208). We are expecting to make a `flux` release today that includes this bugfix.

**Comment by dirien** [comment]
Thanks @hiddeco for the swift reponse. Looking forward for the release.

**Comment by hiddeco** [comment]
`v0.3.0` was released one hour ago: https://github.com/fluxcd/flux2/releases/v0.3.0

**Comment by dirien** [comment]
so to update i just need to call flux bootstrap again? I just browsed the docs and can't see a section on how to update...

**Comment by hiddeco** [comment]
Correct.
