### ISSUE TITLE
bootstrap fails on private gitlab/cluster

### ISSUE THREAD

**Issue by davidberglund** [fluxcd/flux2#483]
Trying to bootstrap flux in private environment. The Gitlab subdomain is not visible from public internet.

Command and arguments used:
flux bootstrap gitlab --hostname=gitlab.domain.com --token-auth --owner=mygroup --repository=fleet-infra --branch=master --path=staging

► connecting to gitlab.domain.com
✔ repository created
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system created
networkpolicy.networking.k8s.io/allow-scraping created
networkpolicy.networking.k8s.io/allow-webhooks created
networkpolicy.networking.k8s.io/deny-ingress created
role.rbac.authorization.k8s.io/crd-controller-flux-system created
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
service/source-controller created
deployment.apps/source-controller created
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
deployment.apps/kustomize-controller created
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
deployment.apps/helm-controller created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
service/notification-controller created
service/webhook-receiver created
deployment.apps/notification-controller created
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "source-controller" successfully rolled out
Waiting for deployment "kustomize-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✗ unable to clone 'https://gitlab.domain.com/mygroup/fleet-infra', error: Get "https://gitlab.domain.com/mygroup/flux-infra/info/refs?service=git-upload-pack": dial tcp: lookup gitlab.domain.com on XX.XXX.XXX.XX:53: no such host

The IP it resolves is incorrect and unknown to me. Evidently it does resolve the Gitlab instance when creating repo and commiting the manifests. No sure how to proceed with this. 

Thanks in advance
David

**Comment by stefanprodan** [comment]
That error comes from the controllers running in your cluster while the bootstrap happens on your local machine. You need to fix your Kubernetes cluster DNS.

**Comment by davidberglund** [comment]
You mean that the cluster and my local machine resolves using different DNS servers?

**Comment by stefanprodan** [comment]
Create an alpine pod in your cluster and you should see the same lookup error,I think you'll need to add your GitLab domain to CoreDNS.

**Comment by davidberglund** [comment]
Great, that put me on the right path. Having issues configuring DNS with Microk8s now but I think we can close this as it's not a flux issue.
