### ISSUE TITLE
Controller global decryption for AWS KMS no effect

### ISSUE THREAD

**Issue by rfernandezadl** [fluxcd/flux2#4853]
### Summary:
While following instructions to set FluxCD to decrypt secrets using AWS KMS at https://fluxcd.io/flux/components/kustomize/kustomizations/#decryption I keep getting fluxCD showing in my test kustomization `Secret/somenamespace/test-sops-secret is SOPS encrypted, configuring decryption is required for this secret to be reconciled` even though the kustomize-controller is properly configured with a enough OIDC/IRSA setup to work with the key.

My understanding is that according to documentation https://fluxcd.io/flux/guides/mozilla-sops/#encrypting-secrets-using-various-cloud-providers

> When using AWS/GCP KMS, you don’t have to include the gpg secretRef under spec.provider (you can skip the --decryption-secret flag when running flux create kustomization), instead you’ll have to bind an IAM Role with access to the KMS keys to the kustomize-controller service account of the flux-system namespace for kustomize-controller to be able to fetch keys from KMS.

There is no need to use the `secretRef` under `spec.provider` which is also mentioned here: When using AWS/GCP KMS, you don’t have to include the gpg secretRef under spec.provider (you can skip the --decryption-secret flag when running flux create kustomization), instead you’ll have to bind an IAM Role with access to the KMS keys to the kustomize-controller service account of the flux-system namespace for kustomize-controller to be able to fetch keys from KMS.

> it is possible to specify global decryption settings on the kustomize-controller Pod. When the controller fails to find credentials on the Kustomization object itself, it will fall back to these defaults.

So far, FluxCD kustomize-controller logs keep stating that no decryption has been configured.

### Steps to reproduce

1 . FluxCD deployed at bootstrap, Kustomize-Controller Service account patch with annotation according to:
https://fluxcd.io/flux/installation/configuration/workload-identity/#aws-iam-roles-for-service-accounts

2. Secrets manually created using KMS key locally ( to be committed to upstream gitops repo) and pushed through application's kustomization

3. Review SA `kustomize-controller` is properly annotated

4. Review output of `flux get kustomizations` to find error: `Secret/namespace/secret-name` is SOPS encrypted, configuring decryption is required for this secret to be reconciled`

### Expected behavior

I expect to see my secret being decrypted in cluster, with the key I am passing for configuration

### OS / Distro

N/A

### Flux version

v2.2.3

### Flux check

► checking prerequisites
✗ flux 2.2.3 <2.3.0 (new CLI version is available, please upgrade)
✔ Kubernetes 1.26.15-eks-3af4770 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.3
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.4
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The Flux Kustomization that applies the secret must have:
```yaml
spec:
  decryption:
    provider: sops
```

Can you post here the Flux Kustomization that errors out with `kubectl -n <ns> get ks <name> -o yaml` .

**Comment by rfernandezadl** [comment]
This is right, It is required that the Flux Kustomization responsible for applying the secret contains `spec.decryption.provider` set to sops (only provider available right now). 
I made the assumption it would default to decrypt due to the fact this is setup to work in AWS. Instead, to "trigger" defaulting the decryption to the annotated SA controller. Not including a secret triggers this mechanism, but a provider needs to be specified. I am good to go!
