### ISSUE TITLE
gitrepository failed to checkout and determine revision: unable to clone object not found

### ISSUE THREAD

**Issue by lloiacono-fuji** [fluxcd/flux2#4875]
### Describe the bug

Hello guys,
after running these command:
```
 git reset --hard commit_sha256
 git push origin ocloud --force 
```
gitrepository goes to READY FALSE with these error:

failed to checkout and determine revision: unable to clone 'https://xxx.xxx.xxx/xxx-xxx-xxx.git': object not found

024-07-05T21:07:10.792Z error GitRepository/flux-system.flux-system - failed to checkout and determine revision: unable to clone 'https://xxx.xxx.xxx/xxx-xxx-xxx.git': object not found failed to checkout and determine revision: unable to clone 'https://xxx.xxx.xxx/xxx-xxx-xxx.git': object not found
2024-07-05T21:07:10.809Z error GitRepository/flux-system.flux-system - Reconciler error failed to checkout and determine revision: unable to clone 'https://xxx.xxx.xxx/xxx-xxx-xxx.git': object not found

I tried running flux uninstall and re-running bootstrap but the problem persists. Gitrepository remains in ready False

I solve the problem if I recreate a branch from scratch and report the Kubernetes configurations
However, recreating the branch causes problems for our workflow.
How can I solve this problem on this particular branch that is not working?

Thanks in advance to anyone who can help us!

### Steps to reproduce

```
 git reset --hard commit_sha256
 git push origin branch_name --force 
```

### Expected behavior

gitrepository READY TRUE

### OS / Distro

Ubuntu 22.04

### Flux version

flux: v2.0.0

### Flux check

► checking prerequisites
✗ flux 2.0.0 <2.3.0 (new version is available, please upgrade)
✔ Kubernetes 1.27.10 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Gitlab CE

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luca-loiacono** [comment]
I ran git reset in a lab repository. 
I understand that by rewriting the git history, fluxcd desynchronizes.

However, I thought that recreating it from scratch with a new installation would be successful. 

with git revert instead of git reset everything obviously works correctly.

**Comment by lucaloiacono-fujifilm** [comment]
These tests were performed in a laboratory repository
I understand that by rewriting the git history, fluxcd desynchronizes.

However, I thought that recreating it from scratch with a new installation would be successful.
With git revert instead of git reset everything obviously works correctly.
