### ISSUE TITLE
lastAppliedRevision value does not exist for Kind: HelmRelease

### ISSUE THREAD

**Issue by 1ms-ms** [fluxcd/flux2#4895]
### Describe the bug

When going through [custom metrics guide ](https://fluxcd.io/flux/monitoring/custom-metrics/#adding-custom-metrics), there is a metric definition for HelmRelease kind:
```
- groupVersionKind:
    group: helm.toolkit.fluxcd.io
    version: "v2"
    kind: HelmRelease
  metricNamePrefix: gotk
  metrics:
    [...]
    - name: "helmrelease_version_info"
      help: "The version information of helm release resource."
      each:
        type: Info
        info:
          labelsFromPath:
            version: [status, lastAppliedRevision]
```
which includes this `labelsFromPath` fragment, that will build a label from `status.lastAppliedRevision`. 
The problem is, it seems there is no `lastAppliedRevision` key for HelmRelease kind, thus this metric will never be created, as this label does not exist. 

As I'm going through the [CRD manifest for HelmRelease](https://github.com/fluxcd/helm-controller/releases/download/v1.0.1/helm-controller.crds.yaml), I see 
```
[...]
history:
  [...]
  lastAppliedRevision:
    description: LastAppliedRevision is the revision of the last successfully
      applied source.
    type: string
```
and 
```
[...]
status:
  [...]
  lastAppliedRevision:
    description: |-
      LastAppliedRevision is the revision of the last successfully applied
      source.
      Deprecated: the revision can now be found in the History.
    type: string
```
, which confirms that `status.lastAppliedRevision` has been moved and the documentation is not updated accordingly.

### Steps to reproduce

none

### Expected behavior

I would expect to have two labels added instead, e.g.:
```
currentVersion: [spec, history, chartVersion]
lastAttemptedVersion: [status, lastAttemptedRevision]
```
or at least correction of the current label to use newest CRD key.

### OS / Distro

N/A

### Flux version

v2.3.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.30.2-eks-db838b0 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.38.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.32.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I've changed it in the config repo here https://github.com/fluxcd/flux2-monitoring-example/blob/5bf921a7b553df4dde59a186549f450b6c306be8/monitoring/controllers/kube-prometheus-stack/kube-state-metrics-config.yaml#L72 docs are behind, thanks for the report.
