### ISSUE TITLE
Kustomize .spec.components EOL

### ISSUE THREAD

**Issue by alexandrtru** [fluxcd/flux2#4903]
Hi, team! 

As i describe in discussion https://github.com/fluxcd/flux2/discussions/4896 we plan use `.spec.components` as part of core-concept in our use case.

Did you plan delete this feature or move it from alpha state further?

Thanks!

**Comment by stefanprodan** [comment]
We have no plans to remove this feature, it will stay in alpha until Kustomize moves it to beta, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1802-kustomize-components#graduation-criteria
