### ISSUE TITLE
Flux v2.3.0 - `HelmRelease`, `failed to convert merged object to last applied version: ... field not declared in schema`

### ISSUE THREAD

**Issue by daniel-ciaglia** [fluxcd/flux2#4906]
### Describe the bug

After successfully updating FluxCD to v2.3.0, all my `HelmRelease`s were just fine.

[some days later]

After bumping their api version to `helm.toolkit.fluxcd.io/v2` I get the mentioned error **in their parent Kustomization**

```
failed to convert merged object to last applied version: .spec.chart.spec.ignoreMissingValuesFiles: field not declared in schema
```

This feels like a regression on this bug: https://github.com/fluxcd/flux2/issues/4479

## Fix
To fix the error, I have to
- edit the `HelmRelease`
- add the field in question
- do `flux reconcile helmrelease sample-app`
- do `flux reconcile kustomization sample-app`

### Steps to reproduce

N/A

### Expected behavior

no interruption of service

### OS / Distro

EKS 1.29 on AWS Linux

### Flux version

2.3.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daniel-ciaglia** [comment]
Addition: so far this happened **sporadically** and **not systematically**

**Comment by daniel-ciaglia** [comment]
Hopefully this was a one-off. It did not happen again on 10 environments over night :crossed_fingers:

**Comment by stefanprodan** [comment]
This may be due to stale cache of the OpenAPI definitions loaded into Kubernetes API.

**Comment by stealthybox** [comment]
I am able to reproduce a similar error message by applying the `old_config` and `new_config` in https://github.com/stealthybox/crd-deprecate.
