### ISSUE TITLE
GitRepository https authorization failed under self-host GitHub Enterprise

### ISSUE THREAD

**Issue by chimisu** [fluxcd/flux2#494]
My GitRepository as below content:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 30s
  url: https://git.xxxx.com/xxxx/xxxx.git
  ref:
    branch: master
  secretRef:
    name: https-credentials

---
apiVersion: v1
kind: Secret
metadata:
  name: https-credentials
  namespace: flux-system
type: Opaque
data:
  username: xxxx
  password: xxxx
```

describe gitrepository
```
$ flux get sources git
$ NAME            REVISION                                        READY   MESSAGE
flux-system     master/084cd3a8a225cb349b362664ceb7f4e5400f22f8 True    Fetched revision: master/084cd3a8a225cb349b362664ceb7f4e5400f22f8
test                                                            False   unable to clone 'https://git.xxxx.com/xxxx/xxxx.git', error: authorization failed
```
I configured the personal access token as password and I can clone the code with the token in git command.
Does flux2 gitrepository support self-host github enterprise?

**Comment by stefanprodan** [comment]
Make sure your credentials are correctly encoded in the secret, if the last characters of the base64 value are `Cg==` then you've added `/n` and the end.

**Comment by chimisu** [comment]
@stefanprodan I'm sure my credential is correct,I can clone the code by git commmand success.The last characters of the base64 value are't include `Cg==`

**Comment by stefanprodan** [comment]
Can you please decode the secret data and check if it's working:
```
kubectl -n flux-system get secrets/https-credentials --template={{.data.password}} | base64 -D
```

PS. We have users on GitHub Enterprise and no one complied about https or ssh auth, so I think it must be something related to the credentials or maybe there is an allowlist of trusted IPs or some firewall between the cluster and Git that is blocking the auth request.

**Comment by chimisu** [comment]
I decoded the token,it's correct,I don't know what the issue is.

**Comment by chimisu** [comment]
@stefanprodan I generated a wrong base64 string,the correct command is `echo -n "token" | base64`,close the issue.
