### ISSUE TITLE
Improvement of OpenSSF Scorecard Score

### ISSUE THREAD

**Issue by harshitasao** [fluxcd/flux2#4943]
Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.

As this project already has scorecard action, I'm here to increase the final score by going over each check. I've listed all of the checks where work needs to be done, in order of its criticality. I plan to submit each PR for each fix. Please let me know what you think and for which ones a PR is welcome that I will submit it ASAP.

**Current Score:** 8.6
**Improved Score:** 8.8

**Scorecard report:** https://scorecard.dev/viewer/?uri=github.com/fluxcd/flux2

Here's a few checks we can work on to improve the project's security posture:

- [ ] [Dangerous-Workflow](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow): Score = 0
     - untrusted code checkout '${{ github.event.pull_request.head.sha }}': .github/workflows/backport.yaml:15
     - Does not affect: see [comment.](https://github.com/fluxcd/flux2/issues/4943#issuecomment-2303933870)

- [X] [Token-Permissions](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions): Score = 9
    - The issue here is that many workflows doesn’t have a top-level read-only permissions block like present in the other workflows. Scorecard is quite severe in this check: a single workflow without top-level permissions gets a 0/10 for the check.
    - PR: https://github.com/fluxcd/flux2/pull/4948

- [X] [Pinned-Dependencies](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies): Score = 6
    - Github actions and container images in dockerfile are not pinned by hash, which results in a low score. But pinning container images would introduce the risk of running outdated images.
    - PR: https://github.com/fluxcd/flux2/pull/4948
  
 

/cc @joycebrum @diogoteles08 @pnacht @nate-double-u

**Comment by stefanprodan** [comment]
The backport workflow can only be trigger by a label add by maintainers on PRs, this workflow does not run by default, so a malicious PR would not be able to read any GHA secrets. Can we exclude this workflow from the scorecard scanner?

**Comment by harshitasao** [comment]
> The backport workflow can only be triggered with a custom label add by maintainers on PRs, this workflow does not run by default, so a malicious PR would not be able to read any GHA secrets. Can we exclude this workflow from the scorecard scanner?

I don't think we can exclude a workflow from the scorecard scanner.

**Comment by harshitasao** [comment]
Closing this issue as all the task are done!
