### ISSUE TITLE
repository not found on bootstrap

### ISSUE THREAD

**Issue by cdonahue55** [fluxcd/flux2#4954]
### Describe the bug

I'm attempting a flux bootstrap  and am receiving a "repository not found" error

### Steps to reproduce

flux bootstrap github   --owner=$GITHUB_USER   --repository=fleet-infra   --branch=main   --path=./clusters/my-cluster
Please enter your GitHub personal access token (PAT): 
► connecting to github.com
✔ repository "https://github.com/MyOrg/fleet-infra" created
► cloning branch "main" from Git repository "https://github.com/MyOrg/fleet-infra.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed component manifests to "main" ("fe5c023b9cce38fe420ba7c01d29fbd47f8699fd")
► pushing component manifests to "https://github.com/MyOrg/fleet-infra.git"
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
► generating sync manifests
✔ generated sync manifests
✔ committed sync manifests to "main" ("7bd53c357b64515c5c26c42b7e61258610d0528c")
► pushing sync manifests to "https://github.com/MyOrg/fleet-infra.git"
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for GitRepository "flux-system/flux-system" to be reconciled
✗ failed to checkout and determine revision: unable to list remote for 'ssh://git@github.com/MyOrg/fleet-infra': repository not found
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ Source is not ready, artifact not found, retrying in 30s
► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 2 health check failure(s): [error while waiting for GitRepository to be ready: 'failed to checkout and determine revision: unable to list remote for 'ssh://git@github.com/MyOrg/fleet-infra': repository not found', error while waiting for Kustomization to be ready: 'Source is not ready, artifact not found, retrying in 30s']

### Expected behavior

The bootstrap creates the repository at the path listed. However the  checkout fails to find the repository it just created.

### OS / Distro

Ubuntu 22.04

### Flux version

v2.3.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.28.10 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> determining if source secret "flux-system/flux-system" exists
> source secret up to date

I guess the PAT has changed, and the one in the cluster does not have access to the repo. You need to rotate the secret, to do this run `kubectl -n flux-system delete secret flux-system` and rerun bootstrap.

**Comment by cdonahue55** [comment]
closing
