### ISSUE TITLE
Helm controller runs upgrade on Helm release every 1 minute 

### ISSUE THREAD

**Issue by comminutus** [fluxcd/flux2#4981]
### Describe the bug

Every minute or so, it seems the Helm controller is trying to upgrade one of my Helm releases.  If I watch the Helm releases with `flux get hr -n default -w` I see this every minute:
```
my-chart	0.2.0	False	True	Helm upgrade succeeded for release default/my-chart.v15 with chart my-chart@0.2.0
```

In the Flux Helm controller pod log, I see this about every minute:
```
2024-09-13T13:44:49.422Z info HelmRelease/mike-chart.default - release in-sync with desired state
```

This HelmRelease references a HelmChart defined like:
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: mike-chart
  namespace: flux-system
spec:
  chart: ./helm-charts/my-chart
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m0s
```
It's using the same Git repository as the Flux resources are committed to via `sourceRef` instead of using `url` from an external repository.

The HelmChart's interval is set to 1 min, as is the HelmRelease.

Why does the Helm controller keep trying to upgrade the Helm release?

### Steps to reproduce

1. Create a HelmRepository with an interval of 1min that references the same Git repository as where other Flux resources are committed to via `sourceRef`.
2. Create a HelmRelease with an interval of 1min which references this HelmRepository.
3. Deploy both the HelmRepository and HelmRelease
4. Watch the Helm controller's logs for perpetual messages like _release in-sync with desired state_

### Expected behavior

The Helm controller should only upgrade the Helm release if it detects a new version or new revision, depending on the chart's `reconcileStrategy` (defaults to _ChartVersion_).

### OS / Distro

Fedora Silverblue 40

### Flux version

v2.3.0

### Flux check

```
flux check
► checking prerequisites
✔ Kubernetes 1.30.0+k3s1 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

Self-Hosted Gitea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The `release in-sync with desired state` does not say it has performed an upgrade, it's no-op.

**Comment by comminutus** [comment]
@stefanprodan My apologies, I mistook this and the output of `flux get hr -n default -w` every one minute from that chart to mean that it was running an upgrade every minute.  It looks like the output happens when the interval timer is up, and since this is the only helm release I have with 1 min intervals (since it's my own repository) I see them in the output all the time.
