### ISSUE TITLE
flux cli does not warn or show an error if kubectl does not exist

### ISSUE THREAD

**Issue by chanwit** [fluxcd/flux2#499]
**Context:**
When using Flux on a fresh installed box.

**What I found:**
At the step of running `kubectl apply` it shows the manifest applying error, but it's actually kubectl binary does not exist, for example.

**Expected:**
The CLI should give a warning, or show an error if we don't have the `kubectl` binary installed.

**Comment by stefanprodan** [comment]
The CLI does check kubectl and the Kubernetes version with `flux check --pre`.

**Comment by chanwit** [comment]
maybe the cli gives users a specific error message when doing so?

**Comment by stefanprodan** [comment]
```console
$ flux check --pre
► checking prerequisites
✗ kubectl version can't be determined
```
