### ISSUE TITLE
[Docs] No example for custom credentials (from secret)

### ISSUE THREAD

**Issue by MarkusTeufelberger** [fluxcd/flux2#502]
According to https://toolkit.fluxcd.io/cmd/flux_create_source_git/#options there's an option called `--secret-ref string             the name of an existing secret containing SSH or basic credentials`

I can't find any example (other than letting flux auto-generate something, looking at the result and then re-implementing this) for how this secret should actually look like, the guides also usually let flux create this secret on the fly. It would be nice to see examples for both cases (SSH/basic credentials) in the documentation on the website.

**Comment by stefanprodan** [comment]
Docs are here: https://toolkit.fluxcd.io/components/source/gitrepositories/#https-authentication

**Comment by MarkusTeufelberger** [comment]
Oh, thanks! Totally missed that one, I'll just close this issue. My only suggestion would then be to link to https://toolkit.fluxcd.io/components/source/gitrepositories/ from https://toolkit.fluxcd.io/cmd/flux_create_source_git/
