### ISSUE TITLE
image-automation-controller cannot push when using cross-namespace GitRepository

### ISSUE THREAD

**Issue by norman-zon** [fluxcd/flux2#5095]
### Describe the bug

When using an `ImageUpdateAutomation` that refers (as SourceRef) a `GitRepository` in another namespace, the image-automation-controller can't push to the gitRepo:

```
failed to update source: failed to push to remote: unknown error: ERROR: The key you are authenticating with has been marked as read only
```

### Steps to reproduce

1. Install Flux with `image-reflector-controller`, `image-automation-controller` and `--no-cross-namespace-refs=false`
2. Create a Gitrepo in namespace A
2. Create an ImageAutomation in namespace B, that uses the Gitrepo in namespace A as SourceRef
3. See error in image-automation-controller log

### Expected behavior

I expect the controller to be able to push the ImageAutomation commit the same as when using only one namespace

### OS / Distro

N/A

### Flux version

N/A

### Flux check

❯ flux check
► checking prerequisites
✔ Kubernetes 1.30.5-gke.1443001 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.4.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.1.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.39.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.33.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.4.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.4.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.4.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
This happens when e.g. you use `flux bootstrap` and don't provide `--read-write-key`. Then the deploy key will be created read-only (least privilege). You can delete the deploy key and run `flux bootstrap --read-write-key ...` or manually generate a deploy key and put it in the `flux-system` Secret.

**Comment by norman-zon** [comment]
My bad. It was indeed the deploy key.
Many thanks @makkes for helping me to debug in the CNCF slack!

And many apologies for the unnecessary issue.
