### ISSUE TITLE
Updating flux2

### ISSUE THREAD

**Issue by jacek-jablonski** [fluxcd/flux2#517]
Hi,
I couldn't find any information about upgrading flux to newer versions.
Should I just use:
```
 flux install --version=latest --namespace=flux-system
```
or is there other way?
Thanks.

**Comment by stefanprodan** [comment]
@jacek-jablonski first you download the latest CLI then run `flux install`, more info here https://toolkit.fluxcd.io/guides/installation/#upgrade
