### ISSUE TITLE
Automate AUR releases

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#530]
We already offer support for `brew`, and given 3 of the Flux2 maintainers are Arch users, adding [AUR](https://aur.archlinux.org) support would be a first step to a wider range of "officially supported package repositories".

Given how we make releases, in combination with the Arch package guidelines (proper explanation [here](https://unix.stackexchange.com/questions/543013/whats-the-difference-between-pkg-pkg-bin-and-pkg-git-on-the-aur), official Arch wiki page on this subject is missing but there is [chatter](https://wiki.archlinux.org/index.php/Talk:Arch_package_guidelines#Package_naming)), my proposal would be the following:

- `flux-bin` for "building" the latest released pre-compiled `flux` binary.
- `flux-git` for building the latest unstable release from `HEAD`.
- _(Optionally)_ `flux-cli` for "building" the latest release from scratch.

The `flux-bin` (and `flux-cli`) package would be updated by our goreleaser, an example for doing this is provided in https://github.com/goreleaser/goreleaser/issues/641.

The `flux-git` should be light in maintenance, and only require periodic updates for build constraints, see: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=github-desktop-git

**Comment by relu** [comment]
Note that for the bin and regular source build packages the automation would need to update not only the version `pkgver` but also the checksum(s) of the sources.

I already have some PKGBUILDs we can use. Should we start by creating a dedicated repository for these?

Do you think we should maybe use the `flux-cli` name to conform with the current package name? This way we would have `flux-cli`, `flux-cli-bin` and `flux-cli-git`.

**Comment by hiddeco** [comment]
> Note that for the bin and regular source build packages the automation would need to update not only the version pkgver but also the checksum(s) of the sources.

Was already aware, and the example linked also does this. We actually publish a `checksum.txt` so we could simply piggyback on that file.

> Should we start by creating a dedicated repository for these?

This should not be a dedicated repository but reside somewhere within this repository based on `*.template` files and a bash script, see example.

> Do you think we should maybe use the flux-cli name to conform with the current package name? 

No, the sole reason we require this unpleasant suffix is because the package name is already taken. I want to prevent creating an alternative name at all costs, as "Flux CD" is already one too many. We can make the relationship clear using the "conflicts" option.

**Comment by hiddeco** [comment]
To add to point three: one reason we may have to choose a different name for `flux-cli` is because the type of package is not 100% clear and people falsely assume it is a `<name>-bin`.

Two alternatives that come to mind:

- `flux-go`
- `flux-build`

**Comment by relu** [comment]
> No, the sole reason we require this unpleasant suffix is because the package name is already taken. I want to prevent creating an alternative name at all costs, as "Flux CD" is already one too many. We can make the relationship clear using the "conflicts" option.

Then we need to define a common `provides` value and we can add `conflicts` definitions to the packages.

> Two alternatives that come to mind:

What do you think of `flux-src`?

**Comment by hiddeco** [comment]
> What do you think of `flux-src`?

Would confuse it with `<name>-git`.
