### ISSUE TITLE
Errors after bootstrap update

### ISSUE THREAD

**Issue by rparree** [fluxcd/flux2#536]
Hi,

I just performed a bootstrap update and i'm now receiving the following error:

```
{"level":"error","ts":"2020-12-01T09:39:46.068Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"source.toolkit.fluxcd.io","reconcilerKind":"GitRepository","controller":"gitrepository","name":"flux-system","namespace":"flux-system","error":"auth error: invalid 'flux-system' secret data: required fields 'identity' and 'known_hosts'"}
```

The `flux-system` secret contains a username and a pasword. I did notice the url to my gilab repo in the `flux-system` `GitRepository` has been changed from https to ssh

For the update i same the same command as i used to install flux2.

How can i fix this?

tx.,

**Comment by rparree** [comment]
Found the solution. I had to add `--token-auth` time to the bootstrap command this time.

**Comment by stefanprodan** [comment]
Yes we changed the bootstrap to support both SSH and token-based auth, if you use a token then you have to specify `--token-auth`.
