### ISSUE TITLE
Is there support for an older cluster?

### ISSUE THREAD

**Issue by bearmoo-repo** [fluxcd/flux2#539]
Hi,

I was looking though the documentation and I did not see if flux2 supported older cluster (ie: 1.4, 1.10, 1.11. 1.15, etc..). Does flux2 support older kubernetes clusters, if so, is there documentation on how to make it work?

-Frank

**Comment by hiddeco** [comment]
As documented, we require Kubernetes version 1.16 of newer

> [..] version 1.16 or newer and kubectl version 1.18.

https://toolkit.fluxcd.io/get-started/#prerequisites
