### ISSUE TITLE
flux github action leaves flux binaries in the repository path

### ISSUE THREAD

**Issue by onedr0p** [fluxcd/flux2#540]
I noticed the Flux github action leaves the binaries `flux` and `bin/flux` behind which gets added to the PR. 

See here: https://github.com/onedr0p/home-cluster/pull/238/files

I tried to delete them after flux ran install in the workflow however I got permission denied. For now i've added `flux` and `bin/flux` to my gitignore.

**Comment by CuBiC3D** [comment]
@stefanprodan the note only mentions `bin/flux` which still leaves you with `flux` in the root directory.

**Comment by billimek** [comment]
Changing [this line](https://github.com/fluxcd/flux2/blob/main/action/entrypoint.sh#L28):

`curl -sL $BIN_URL | tar xz`

to `curl -sL $BIN_URL | tar xz -C "$GITHUB_WORKSPACE/bin/"`

... should fix the issue with the intermedia `flux` binary in the repo root.

@stefanprodan I'm happy to PR this change if you're ok with it.

**Comment by stefanprodan** [comment]
`$GITHUB_WORKSPACE/bin/` doesn't work on op-prem runners, I fixed it in #616
