### ISSUE TITLE
Migrate Helm Controller to Helm Operator

### ISSUE THREAD

**Issue by pratikbalar** [fluxcd/flux2#560]
Hello Team, 
I want to migrate new flux v2 helmcontroller to my existing latest helmoperator, because helm operator does not support `chartPullSecrets`, can you guide me or is that even possible ?
Thankyou for amazing product

**Comment by hiddeco** [comment]
There is a migration guide available at https://toolkit.fluxcd.io/guides/helm-operator-migration/

**Comment by pratikbalar** [comment]
wow Fast as flash, Thank you, i'll look into that, re-open this if needed,
