### ISSUE TITLE
cannot create git repo with https and username/password

### ISSUE THREAD

**Issue by tibberg** [fluxcd/flux2#568]
If I create a GitRepository with the command 
```
flux create source my-git-repo \
    --url=https://my-git-url \
    --username git --password $MY_GITLAB_TOKEN
``` 
Then the command will create a k8s `GitRepository` and a `Secret`. The `GitRepository` resource has a `secretRef` which points to this `Secret`. However if I create execute the same command with `--export` the output does not contain neither the opaque secret nor the `secretRef`. 

Then I tried to create the secret separately with 
```
flux create secret git my-git-repo-auth \
    --url=https://my-git-url \
    --username git --password $MY_GITLAB_TOKEN 
``` 
And this command returned with `for Git over HTTP/S the username and password are required` however the password is clearly there.

**Comment by stefanprodan** [comment]
After we release the fix you can do:

```sh
# generate auth secret
flux create secret git my-git-repo-auth \
    --url=https://my-git-url \
    --username git \
    --password $MY_GITLAB_TOKEN \
    --export

# generate repo using a secret ref
flux create source my-git-repo \
    --url=https://my-git-url \
    --secret-ref=my-git-repo-auth  \
    --export
```
