### ISSUE TITLE
Flux bootstrap github stuck at `waiting for cluster sync`

### ISSUE THREAD

**Issue by nhat-boostml** [fluxcd/flux2#570]
Hi currently I have a eks cluster running k8s 1.18. 
When I run the commands: flux booststrap to setup flux 2 on my new cluster I got stuck here
```
deployment.apps/notification-controller configured
deployment "source-controller" successfully rolled out
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
unable to clone 'ssh://git@github.com/{redacted}', error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
May I know that is this a issue with the machine Im running the command or is it something I need to have on my cluster. Because I can run git clone 'ssh:// ....' normally without any input.
Thank you

**Comment by stefanprodan** [comment]
That errors comes from your cluster, without the full logs of the bootstrap I can't tell what's going on. You may want to delete the deploy key from your repo and the secret from the cluster, then run again bootstrap.
