### ISSUE TITLE
can't connect to azure devops repo

### ISSUE THREAD

**Issue by Edblakejitsuin** [fluxcd/flux2#591]
Trying to hook this up with Azure Devops repo:

Docs say use --git-implementation=libgit2 to connect to azure devops repo.
This flag doesnt seem to exist... :
unknown flag: --git-implementation

attempting witout the flag fails:

flux create source git flux-system \
  --url=ssh://ssh.dev.azure.com/<project>/<repo> \
  --branch=master \
  --interval=1m

► applying secret with keys
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✗ no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1"

**Comment by stefanprodan** [comment]
You need to use the latest version v0.5.0 and follow the install docs, your current installation will not work, so you need to rerun install then continue with the setup.

**Comment by Edblakejitsuin** [comment]
thanks, I've upgraded to 0.5.2 and able to use flag --git-implementation=libgit2.

However, still getting errors:

► collecting preferred public key from SSH server
✔ collected public key from SSH server:
ssh.dev.azure.com ssh-rsa 
► applying secret with keys
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✗ no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1"

documents say use; '--ssh-key-algorithm=ecdsa' but this doesn't work as Azure Devops expects ssh-rsa, so I am using these options:

flux create source git flux-system \
  --url=ssh://ssh.dev.azure.com/<project>/<repo> \
  --branch=master \
  --interval=1m \
  --git-implementation=libgit2

(error from Azure Devops: Invalid key: Valid keys will start with "ssh-rsa".)

Any ideas?

**Comment by stefanprodan** [comment]
`no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1"` means that you haven't run `flux install` and there is no flux controller running on your cluster.

**Comment by Edblakejitsuin** [comment]
sorry yes, I realised that shortly after posting. here's my next issue after running the below:

flux create source git flux-system \
  --url=ssh://ssh.dev.azure.com/org/project/repo/ \
  --branch=master \
  --interval=1m \
  --git-implementation=libgit2

► collecting preferred public key from SSH server
✔ collected public key from SSH server:
► applying secret with keys
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✔ GitRepository source updated
◎ waiting for GitRepository source reconciliation
✗ unable to clone 'ssh://ssh.dev.azure.com/org/project/repo', error: callback returned unsupported credentials type

any ideas? thanks

**Comment by Edblakejitsuin** [comment]
I've also tried a different ssh url format, which is the one azure devops displays, but flux doesn't like the v3 in the URL:

flux create source git flux-system \
  --url=ssh://git@ssh.dev.azure.com:v3/org/project/repo \
  --branch=master \
  --interval=1m \
  --git-implementation=libgit2

git URL parse failed: parse "ssh://git@ssh.dev.azure.com:v3/org/project/repo": invalid port ":v3" after host

taking the :v3 out I get:

unable to clone 'ssh://git@ssh.dev.azure.com/org/project/repo', error: remote: Command git-upload-pack '/org/project/repo' is not in expected format.

**Comment by hiddeco** [comment]
Can you please try `ssh://git@ssh.dev.azure.com/v3/org/project/repo`? The format displayed is a Git shorthand that does not work with Flux, but translates to that URL.

**Comment by Edblakejitsuin** [comment]
that worked - thanks very much!

**Comment by stefanprodan** [comment]
We need to update the docs
