### ISSUE TITLE
Declarative key causes error: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"

### ISSUE THREAD

**Issue by clearbjli** [fluxcd/flux2#592]
I have added a declarative deployment SSH key to the flux system repo for the cluster. github.com/myorg/gitops-flux/prod-cluster/

I've added the public key to the source deploy key's in github UI.

$ flux get sources git
NAME                  	READY	MESSAGE                                                                                                                                                            	REVISION                                     	SUSPENDED 
flux-system           	True 	Fetched revision: main/48010aed60a1277ede4a3421233553f60769d346                                                                                                    	main/48010aed60a1277ede4a3421233553f60769d346	False    	
zisson-prometheus-prod	False	unable to clone 'ssh://git@github.com/myorg/flux-myorg-prometheus-prod', error: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"	                                             	False    	

The secret get inserted into the namespace:

$ kubectl -n flux-system get secrets
NAME                          TYPE                                  DATA   AGE
default-token-7w45f           kubernetes.io/service-account-token   3      5h34m
flux-system                   Opaque                                3      5h34m
myorg-prometheus-prod-auth   Opaque                                3      21m

If I add the SSH key imperatively in live shell without the --export flag it do work as expected.

**Comment by hiddeco** [comment]
Can you please provide the steps you took to create the secret, and a (redacted) copy of both the `GitRepository` and the `Secret`?

**Comment by clearbjli** [comment]
Correction: it do work then I run "flux create source git" imperatively.

`$ flux create source git zisson-prometheus-prod --url=ssh://git@github.com/zissonas/flux-zisson-prometheus-prod --branch=main --interval=1m
► generating deploy key pair
ssh-rsa AAAAB3..
Have you added the deploy key to your repository: y█
► collecting preferred public key from SSH server
✔ collected public key from SSH server:
github.com ssh-rsa AAAAB3..
► applying secret with keys
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✔ GitRepository source created
◎ waiting for GitRepository source reconciliation
✔ GitRepository source reconciliation completed
✔ fetched revision: main/f4056882825e1df3434caacbca951fe8b9929a20`

`$ flux get sources git
NAME                  	READY	MESSAGE                                                        	REVISION                                     	SUSPENDED 
flux-system           	True 	Fetched revision: main/7b873fe9cdf253a94c6209647728018b47e648a0	main/7b873fe9cdf253a94c6209647728018b47e648a0	False    	
myorg-prometheus-prod	True 	Fetched revision: main/f4056882825e1df3434caacbca951fe8b9929a20	main/f4056882825e1df3434caacbca951fe8b9929a20	False `

I did use the third example from "flux create secret git --help"

flux create secret git myorg-prometheus-prod-auth --url=ssh://git@github.com/myorg/flux-myorg-prometheus-prod --export > myorg-prometheus-prod-auth.yaml

**Comment by clearbjli** [comment]
Performed a test run again.

1. cleaned up existing objects so the secret and source is gone.
2. did restart the pods in flux-system namespace
3. enabled the cluster declarations for Secret and Source in flux-system git repo.

Still same error complaining about unspecified SSH_AUTH_SOCK

Attached is logs from pods and the declaration files.

[source-controller-7c7b47f5f-fpxkr.txt](https://github.com/fluxcd/flux2/files/5687693/source-controller-7c7b47f5f-fpxkr.txt)

[kustomize-controller-79948786c9-8gfh8.txt](https://github.com/fluxcd/flux2/files/5687694/kustomize-controller-79948786c9-8gfh8.txt)

[myorg-prometheus-prod-source.txt](https://github.com/fluxcd/flux2/files/5687691/myorg-prometheus-prod-source.txt)

[myorg-prometheus-prod-auth.txt](https://github.com/fluxcd/flux2/files/5687687/myorg-prometheus-prod-auth.txt)

**Comment by clearbjli** [comment]
Output from "flux check".

► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.19.4 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.4.1
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.4.0
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.4.2
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.4.0
✔ all checks passed

**Comment by HaveFun83** [comment]
Got the same here:
```
 {"level":"error","ts":"2020-12-14T17:24:47.181Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"source.toolkit.fluxcd.io","reconcilerKind":"GitRepository","controller":"gitrepository","name":"k8s-se-prod","namespace":"flux-system","error":"unable to clone 'ssh://git@private-repo:2222/test/k8s-cluster.git', error: error creating SSH agent: \"SSH agent requested but SSH_AUTH_SOCK not-specified\""}
```

**Comment by stefanprodan** [comment]
> Found the issue i was missing the --secret-ref string on source creation

Closing this as it seems solved.
