### ISSUE TITLE
v0.5.3 bug with internal domain lookup

### ISSUE THREAD

**Issue by joonjeong** [fluxcd/flux2#596]
Hi, after I upgrade to v0.5.3, I met this error notification

```
failed to download artifact from http://source-controller.flux-system.svc../gitrepository/flux-system/flux-system/1d11e92db3de9a52b31355d8c4d9dc715cc11a1b.tar.gz, error: Get "http://source-controller.flux-system.svc../gitrepository/flux-system/flux-system/1d11e92db3de9a52b31355d8c4d9dc715cc11a1b.tar.gz": dial tcp: lookup source-controller.flux-system.svc..: no such host
revision
master/1d11e92db3de9a52b31355d8c4d9dc715cc11a1b
```

some days ago, I issued to [kustomize-controller](https://github.com/fluxcd/kustomize-controller/issues/196) about `without .cluster.local domain issue on private gke` and it looks resolved in v0.5.3.

but actually, in my environment, kustomize-controller lookup `source-controller.flux-system.svc` not `source-controller.flux-system.svc.cluster.local`

I upgraded flux2 with this command, `flux install --export > gotk-components.yaml` and do reconcile.

**Comment by stefanprodan** [comment]
Have you downloaded the latest CLI?

**Comment by joonjeong** [comment]
@stefanprodan I tried with cli version v0.5.3, also I'll check with v0.5.4
