### ISSUE TITLE
Github API does not return latest release 

### ISSUE THREAD

**Issue by mjrcox** [fluxcd/flux2#609]
For installing flux v2, I am using a private image repository and I'm automating image retrieval and installation. In order to fetch the newest image I need to get the latest image version tag. Instead of by parsing the manifest files when calling `flux install --dry-run --output`, I would rather just query Github for the latest version [1]. Unfortunately, fails for the controllers but it does work for flux v1. I am able to retrieve a list of releases but specifically not the latest release. This leads me to think it might be a configuration issue on your end. 

**Fetching a list of releases**
```bash
curl -s https://api.github.com/repos/fluxcd/source-controller/releases | grep tag_name
    "tag_name": "v0.5.4",
    "tag_name": "v0.5.3",
    "tag_name": "v0.5.2",
    "tag_name": "v0.5.1",
    "tag_name": "v0.4.1",
    "tag_name": "v0.4.0",
    "tag_name": "v0.3.0",
    "tag_name": "v0.2.2",
    "tag_name": "v0.2.1",
    "tag_name": "v0.2.0",
    "tag_name": "v0.1.1",
    "tag_name": "v0.1.0",
    "tag_name": "v0.0.18",
    "tag_name": "v0.0.17",
    "tag_name": "v0.0.16",
    "tag_name": "v0.0.15",
    "tag_name": "v0.0.14",
    "tag_name": "v0.0.13",
    "tag_name": "v0.0.12",
    "tag_name": "v0.0.10",
    "tag_name": "v0.0.9",
    "tag_name": "v0.0.8",
    "tag_name": "v0.0.7",
    "tag_name": "v0.0.6",
    "tag_name": "v0.0.5",
    "tag_name": "v0.0.4",
    "tag_name": "v0.0.3",
    "tag_name": "v0.0.2",
    "tag_name": "v0.0.1",
    "tag_name": "v0.0.1-beta.2",
```

**Fetching the latest release** 
```bash
curl -s https://api.github.com/repos/fluxcd/source-controller/releases/latest
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
}
```
**Fetching the latest release for Flux v1** 
```bash
curl -s https://api.github.com/repos/fluxcd/flux/releases/latest | grep tag_name
  "tag_name": "1.21.0",
```

[1] https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-latest-release

**Comment by stefanprodan** [comment]
All controllers are currently in pre-release phase, until v1.0.0 you'll have to use flux cli.

**Comment by hiddeco** [comment]
An alternative would be to add `jq` to the mix:

```console
$ curl -s https://api.github.com/repos/fluxcd/source-controller/releases | jq -r '.[0].tag_name'
v0.5.5
```

Note that this does return the latest *published* release, and may include e.g. prerelease candidates (e.g. `v0.x.x-rc.1`) in the future.

**Comment by stefanprodan** [comment]
Well the latest tag in a controller repo doesn't mean that it should be deployed as it may be incompatible with flux CLI. The only way to ensure images are up to date is to parse flux CLI output.
