### ISSUE TITLE
"flux uninstall" lacks description and features

### ISSUE THREAD

**Issue by Marx2** [fluxcd/flux2#625]
There's no description in docs of uninstall command (for example --dry-run)
During uninstall Flux also deletes namespace. There is no option to leave namespace. That's why the only logical approach is to have Flux in separate namespace, because it's risky to coexists with another software

**Comment by hiddeco** [comment]
```console
❯ flux uninstall --help
The uninstall command removes the namespace, cluster roles, cluster role bindings and CRDs from the cluster.

Usage:
  flux uninstall [flags]

Examples:
  # Dry-run uninstall of all components
  flux uninstall --dry-run --namespace=flux-system

  # Uninstall all components and delete custom resource definitions
  flux uninstall --resources --crds --namespace=flux-system


Flags:
      --crds        removes all CRDs previously installed
      --dry-run     only print the object that would be deleted
  -h, --help        help for uninstall
      --resources   removes custom resources such as Kustomizations, GitRepositories and HelmRepositories (default true)
  -s, --silent      delete components without asking for confirmation

...
```

looks like proper descriptive documentation to me, and there is online documentation available at: https://toolkit.fluxcd.io/cmd/flux_uninstall/.

---

Is the actual request being able to keep the namespace, using a flag like `--keep-namespace`?

**Comment by Marx2** [comment]
I was missing this documentation, it's like ok.

So the only thing I miss now is possibility to uninstall flux without
deleting namespace

pt., 18 gru 2020, 14:25 użytkownik Hidde Beydals <notifications@github.com>
napisał:

**Comment by stefanprodan** [comment]
> That's why the only logical approach is to have Flux in separate namespace, because it's risky to coexists with another software

Other software should be managed by Flux, so uninstalling Flux implies deleting all that's in its namespace.
