### ISSUE TITLE
flux install --version=v0.4.3 causes replace operation failure

### ISSUE THREAD

**Issue by Boojapho** [fluxcd/flux2#628]
When running with flux cli (tried v0.5.6 and v0.5.7), I tried to install an older version of flux using:
`flux install --version=v0.4.3`

This results in an error:
✚ generating manifests
✗ install failed: replace operation does not apply: doc is missing key: /spec/template/spec/containers/0/args/6: missing value

I've downgraded flux cli to version 0.4.3 to workaround the issue.

**Comment by stefanprodan** [comment]
Yes, while on `0.x` we don't offer backwards compatibly for Flux CLI releases.

**Comment by Boojapho** [comment]
Ok.  Thanks for clarifying.
