### ISSUE TITLE
bootstrap on local gitlab failes with "git clone error: authentication required"

### ISSUE THREAD

**Issue by chuegel** [fluxcd/flux2#629]
Bootstrapping from a on prem instance of gitlab fails with:
```
flux bootstrap gitlab  \
   --hostname=gitlab.lan.example.de \
   --token-auth \
   --owner=gitops \
   --repository=flux_v2  \
   --branch=master \
   --path=clusters/my-cluster
```

► connecting to gitlab.lan.example.de
✗ git clone error: authentication required

The personal access token has full rights. Any clue why I cannot clone the repo?
Thanks

**Comment by Denissa89** [comment]
Hello there! Try doing this operation with the --personal flag
```
flux bootstrap gitlab  \
   --hostname=gitlab.lan.example.de \
   --token-auth \
   --owner=gitops \
   --repository=flux_v2  \
   --branch=master \
   --path=clusters/my-cluster \
   --personal
``|`

**Comment by chuegel** [comment]
Thanks for your reply. I'm afraid the --personal flag didn't do it, the same error occurs.
The repo flux_v2 didn't exists but it was created so I think the token should have the right permissions though. I'm not sure which endpoint fails the authentication

**Comment by SomtochiAma** [comment]
Heyy @chuegel ,
Try using the `--token-auth` flag so that it uses the pat

**Comment by Denissa89** [comment]
> Thanks for your reply. I'm afraid the --personal flag didn't do it, the same error occurs.
> The repo flux_v2 didn't exists but it was created so I think the token should have the right permissions though. I'm not sure which endpoint fails the authentication
Check if the flux_v2 repository exists, and if the Access Token with scope API (Grants complete read/write access to the scoped project API) exists.

**Comment by Denissa89** [comment]
> Thanks for your reply. I'm afraid the --personal flag didn't do it, the same error occurs.
> The repo flux_v2 didn't exists but it was created so I think the token should have the right permissions though. I'm not sure which endpoint fails the authentication

Check if the flux_v2 repository exists, and if the Access Token with scope API (Grants complete read/write access to the scoped project API) exists.

**Comment by SomtochiAma** [comment]
Hey @chuegel ,
Check that your token has enough rights to the `gitops` group. 
The bootstrap command should work whether the repository exists or not.

**Comment by chuegel** [comment]
@SomtochiAma well, I can only tell that the perosnal access token has full rights. The bootstrap command creates the repository inside the group and then the error occurs:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/6955465/103679176-cf78a600-4f84-11eb-97ed-ff5a96e0542c.png">

**Comment by chuegel** [comment]
OK, it seamed that the reverse SSL proxy was the issue here. Configured the gitlab instance with:
```
external_url 'https://gitlab.lan.example.de'
nginx['redirect_http_to_https'] = false
nginx['listen_port'] = 8888
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {
  "X-Forwarded-Proto" => "https",
  "X-Forwarded-Ssl" => "on"
}
```
fixed the issue

**Comment by vyom-soft** [comment]
I am also in the same situation. For me, Configuring gitlab instance is not possible. 
Any suggestion.
