### ISSUE TITLE
flux using forbidden character for GitLab

### ISSUE THREAD

**Issue by 1ricardo** [fluxcd/flux2#633]
I am using flux_v1 and I tried to migrate to version v2, of course, I stopped the old flux.
I created new repo "my_project/flux_v2" and during executing the following command and their different variations I have the same error.

```sh
flux bootstrap gitlab
 --components=source-controller,notification-controller,image-reflector-controller,image-automation-controller,kustomize-controller --path=myapp  
--owner=flux  
--branch=master
--repository=my_project/flux_v2
```
I alywas getting following error
```sh
► connecting to gitlab.com
✗ failed to create project, error: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [can contain only letters, digits, emojis, '_', '.', dash, space. It must start with letter, digit, emoji or '_'.]}}
```

I create GITLAB token and I tried many variations like `--ssh-hostname=gitlab.com`, `--repository="my_project/flux_v2"`,`--repository='my_project/flux_v2'`

when I change the repository to `--repository="flux_v2"` then I have a message about that repo not exist, but point is to use it with the project name.

btw I suspect that `--verbose` mode doesn't work because it doesn't show any extra logs

**Comment by 1ricardo** [comment]
because `bootsrap` doesn't work for me, because of the above issue, I tried to install *flux v2* by following steps:

```sh
flux install  --watch-all-namespaces  --components=source-controller,kustomize-controller,notification-controller,image-reflector-controller,image-automation-controller
✚ generating manifests
✔ manifests build completed
► installing components in flux-system namespace
✔ install completed
◎ verifying installation
✔ source-controller ready
✔ kustomize-controller ready
✔ notification-controller ready
✔ image-reflector-controller ready
✔ image-automation-controller ready
✔ install finished
```

and after that I create the source

```sh
❯ flux create source git myapp --url=ssh://git@gitlab.com/my_project/flux_v2.git --branch=master   --interval=1m  --ssh-key-algorithm=ecdsa
► generating deploy key pair
ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQA.....
? Have you added the deploy key to your repository? [y/N] Y█
► collecting preferred public key from SSH server
✔ collected public key from SSH server:
gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYA....
► applying secret with keys
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✔ GitRepository source created
◎ waiting for GitRepository source reconciliation
✔ GitRepository source reconciliation completed
✔ fetched revision: master/87f2cdda0b7e909b16bb7424bfc4d14f6353db0c
```

now I created a simple test a namespace 

```sh
apiVersion: v1
kind: Namespace
metadata:
  name:  test12341
```
the revision was fetched but namespace was not created at all

```sh
❯ flux get sources git
NAME    READY   MESSAGE                                                                 REVISION                                        SUSPENDED 
myapp  True    Fetched revision: master/690f0786aa33286bd9104b5152fe068c9fc2b06f       master/690f0786aa33286bd9104b5152fe068c9fc2b06f False    
```
am I doing something wrong?  I will be grateful for any tip because so far nothing works

**Comment by SomtochiAma** [comment]
@1ricardo 
Gitlab doesn't allow slashes in repository name. Are you trying to create a repository `flux_v2` under the `my_project` group?

**Comment by stefanprodan** [comment]
> the revision was fetched but namespace was not created at all

Defining a GitRepository object only pulls the manifests in your cluster, to apply them you need to define a Kustomization, check out the docs:

- https://toolkit.fluxcd.io/get-started/
- https://toolkit.fluxcd.io/cmd/flux_create_kustomization/
