### ISSUE TITLE
git clone error: remote repository is empty

### ISSUE THREAD

**Issue by VarroReve** [fluxcd/flux2#634]
Hi, when I bootstrap a gitlab repo with this command, I got an error: `✗ git clone error: remote repository is empty`. I wonder what is that means.

The repo `varro/fleet` is an existing repo I created before, for some reason, I can't let flux to create the repo.

Really need some help, thank you guys.

```
  flux bootstrap gitlab \
  --owner=varro \
  --repository=fleet \
  --path=clusters/staging \
  --personal \
  --branch=master
```

**Comment by gcameo** [comment]
try using main. as the branch and see. I had issues with the branch. Only main seems to work

**Comment by stefanprodan** [comment]
> The repo varro/fleet is an existing repo I created before

Does this repo have a master branch, is there a readme or any other file in that branch?

**Comment by VarroReve** [comment]
> > The repo varro/fleet is an existing repo I created before
> 
> Does this repo have a master branch, is there a readme or any other file in that branch?

It has a master branch, and it's totally empty.
I think I should just close this issue, and try it another way.

**Comment by stefanprodan** [comment]
> It has a master branch, and it's totally empty.

When creating a repository add a readme.md file to it and it will work.

**Comment by gcameo** [comment]
Interesting bit of detail.. ;)
Thanks though. Flux V2 is awesome. managing about 20 microservices with it. Flawless. helped me get rid of Jenkins

**Comment by stefanprodan** [comment]
We use [go-git](https://github.com/go-git/go-git) and this library can't clone an empty repo ref: https://github.com/go-git/go-git/issues/118
