### ISSUE TITLE
Unable to integrate with atlassian git stash

### ISSUE THREAD

**Issue by anilreddyv** [fluxcd/flux2#662]
**Describe the bug**

Unable to connect to atlassian git stash using "flux bootstrap", looks like it is supporting only github and gitlab, can someone point to me how do you bootstrap internal hosted  atlassian git stash?

Tried like following using gitlab as option but it is failing 

flux bootstrap gitlab --repository flux2-dev --hostname stash.xxxx:7990/scm/~avatti/ --branch master --owner devops --path my-cluster
► connecting to stash.xxxx.com:7990/scm/~avatti/
✗ failed to list projects, error: failed to list groups, error: GET https://stash.xxxx.com:7990/scm/~avatti//api/v4/groups: 404 failed to parse unknown error format

flux check --pre
► checking prerequisites
✔ kubectl 1.18.6 >=1.18.0
✔ Kubernetes 1.18.8 >=1.16.0
✔ prerequisites checks passed:

**Comment by stefanprodan** [comment]
Please see the install docs here: https://toolkit.fluxcd.io/guides/installation/#generic-git-server
