### ISSUE TITLE
Unable to bootstrap when GitLab Subgroup is used

### ISSUE THREAD

**Issue by MonolithProjects** [fluxcd/flux2#674]
Hi team, for some reason the `flux bootstrap` is failing when GitLab Subgroup is used. If the repository is located directly in the parent group, everything works fine.

```
❯ flux bootstrap gitlab \
  --owner devops_sre/test_apps \
  --token-auth \
  --hostname "gitlab.tools.in.pan-net.eu" \
  --repository "ghost-db-k8s" \
  --path "clusters/alien" \
  --namespace "ghost" \
  --branch "master" \
  --cluster-domain "alien.caas.in.pan-net.eu." \
  --verbose
► connecting to gitlab.tools.in.pan-net.eu
✗ failed to list projects, error: failed to find group named 'devops_sre/test_apps'
```
```
❯ flux --version
flux version 0.5.8
```
PAT has the full permissions. The group and subgroup names are 100% correct. So, i am wondering what can be the problem :thinking: 
```
curl --request GET --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --header "Content-Type: application/json" "https://gitlab.tools.in.pan-net.eu/api/v4/groups?search=test_apps"
[{"id":1096,"web_url":"https://gitlab.tools.in.pan-net.eu/groups/devops_sre/test_apps","name":"test_apps","path":"test_apps",...
```

**Comment by stefanprodan** [comment]
Looks like a bug in https://github.com/fluxcd/pkg/blob/main/git/provider_gitlab.go I guess we don't support sub-groups cc @relu @SomtochiAma

**Comment by totycro** [comment]
Hi,

I still hit this bug with later version. I've now tried 0.6.0, 0.7.0 and 0.7.5, and everytime I get this:
```
$ flux bootstrap gitlab --branch main --repository=eoxhub-flux-system --hostname gitlab.eox.at --owner "eox/hub"  --verbose --token-auth
✗ failed to list projects, error: failed to find group named 'eox/hub'
```

The git repo is available under `gitlab.eox.at:eox/hub/eoxhub-flux-system.git`.

I've also tried with `--owner "/eox/hub"` and `--owner "eox/hub/"` but that didn't help. Am I calling this the wrong way or is this still the same bug?

**Comment by MonolithProjects** [comment]
Hmm... it works for me just fine
```
~/Documents/NFVI/flux2 master
❯ flux --version
flux version 0.7.6

~/Documents/NFVI/flux2 master
❯ flux bootstrap gitlab \
        --hostname "gitlab.tools.in.pan-net.eu" \
        --owner "devops_sre/cicd_technologies" \
        --token-auth \
        --repository "flux2" \
        --path "./clusters/ic-debamf1-cicd" \
        --namespace "flux-system" \
        --branch "master" \
        --cluster-domain "in.gitlab.ic-debamf1-cicd.caas.in.pan-net.eu"
► connecting to gitlab.tools.in.pan-net.eu
✔ repository cloned
✚ generating manifests
✔ components are up to date
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished
```

**Comment by hiddeco** [comment]
I think it would help if everyone having an issue with on-prem GitLab, it would help if you share details about the GitLab environment, the GitLab version that is running would be a great start.

**Comment by totycro** [comment]
This is the version being used here: `GitLab Enterprise Edition 13.8.2-ee`

**Comment by hiddeco** [comment]
@MonolithProjects if you could share your version where it _does_ work, we have a range of versions to work through that may point is towards what changed in GitLab (EE).

**Comment by MonolithProjects** [comment]
@hiddeco it's `13.6.5-ee`

**Comment by hiddeco** [comment]
I have likely found the cause of the issue, see: https://github.com/fluxcd/pkg/pull/80

**Comment by hiddeco** [comment]
It would be great if you could both confirm if the binary available at https://dl.huge.horse/flux solves the issue for you.

It contains a Linux ARM64 build of `main` + #863.

**Comment by totycro** [comment]
Awesome, this binary works for me!
```
$ ~/Downloads/flux  bootstrap gitlab --repository=eoxhub-flux-config --hostname gitlab.eox.at --owner "eox/hub"  --verbose --token-auth
► connecting to gitlab.eox.at
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system unchanged
serviceaccount/helm-controller unchanged
serviceaccount/kustomize-controller unchanged
...
```

**Comment by MonolithProjects** [comment]
@hiddeco yeap can confirm, it still works also with the older Gitlab release
