### ISSUE TITLE
ImageUpdateAutomation failed with key ReadOnly

### ISSUE THREAD

**Issue by jshaw86** [fluxcd/flux2#677]
I'm testing out the FluxV2 helm automation and ran into the below error after bootstrapping the cluster with the resources here: https://github.com/jshaw86/fluxci-example/tree/master/clusters/my-cluster.
```
{"level":"error","ts":"2021-01-10T03:02:37.805Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"image.toolkit.fluxcd.io","reconcilerKind":"ImageUpdateAutomation","controller":"imageupdateautomation","name":"flux-system","namespace":"flux-system","error":"unknown error: ERROR: The key you are authenticating with has been marked as read only."}
```
I'm trying to link it up with a sample charts library here: https://github.com/jshaw86/fluxci-example-charts/tree/master/deploy/podinfo. That just has a copied `podinfo` chart.

I'm pretty sure I'm doing something wrong but not sure what. I checked the github provider and it looks like readOnly is enforced on the ssh key creation. https://github.com/fluxcd/pkg/blob/main/git/provider_github.go#L165.

**Comment by stefanprodan** [comment]
We need to expose the read-only setting as a bootstrap argument, as a workaround you can use `--token-auth` as described in docs https://toolkit.fluxcd.io/guides/image-update/#install-flux
