### ISSUE TITLE
All components use default service account bound to cluster-admin cluster role.

### ISSUE THREAD

**Issue by willejs** [fluxcd/flux2#691]
Currently, all the flux2 components are using the default service account. 
The default service account has a [ClusterRoleBinding](https://github.com/fluxcd/flux2/blob/main/manifests/rbac/cluster-role.yaml) that binds the cluster-admin role to the default service account for the flux-system namespace.

This isn't ideal, the components should really have their own service accounts with restricted permissions (in the case of the source and notifications controller for example). I am raising this, as If someone exposes the notifications controller to the internet to receive webhooks for example, this could be deemed as a security risk.

I am happy to make a pull request if someone wants to hint at the potential rules or give me any tips. I can take a look at the code and create an audit policy to validate them too probably.

**Comment by stefanprodan** [comment]
Duplicate of: #243

Until we get to this, you can create and assign service accounts to source/notification-controller as described here: https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

**Comment by william-salt-cko** [comment]
Thanks for the flag it's a dup.
I am currently using the terraform provider to install it which obviously calles the manifestgen package in this repo, so i cant just kustomize it.
I will close this and comment on the other issue.

**Comment by stefanprodan** [comment]
Can't you generate YAML and push it from TF along with the bootstrap manifests?

**Comment by william-salt-cko** [comment]
Yeah, i probably could use the kustomize provider with the flux2 provider perhaps... However, I am thinking i should probably just fix this in here and save myself having to do some kustomize magic in terraform with another provider? In the mean time i just wont expose the notifications controller.
