### ISSUE TITLE
Why isn't manually added sources removed on reconciliation?

### ISSUE THREAD

**Issue by joelnotified** [fluxcd/flux2#695]
I'm trying out Flux and while trying to figure out how to add a Git source using SSH, I did this:

```
❯ kind create cluster --name test
❯ export GITHUB_TOKEN=<token>
❯ export GITHUB_USER=<username>
❯ flux bootstrap github --owner=$GITHUB_USER --repository=fleet-infra --branch=main --path=./clusters/dev --private=true --personal
❯ flux create source git test-repo --url=ssh://git@github.com/$GITHUB_USER/test-repo --branch=main --interval=30s

❯ flux get sources git
flux-system             True    Fetched revision: main/5a49...
test-repo  True    Fetched revision: main/eafad...
``` 

I'm a bit confused about what's going on here. I thought that resources not being versioned in git would automatically be removed by the reconciliation loop. So why doesn't that happen in this case?

I was under the impression that Flux would remove anything that doesn't exist in the git repo?

Here's my current version
```
❯ flux check
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.19.1 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.5.6
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.5.3
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.4.4
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.5.0
✔ all checks passed
```

**Comment by stefanprodan** [comment]
> I was under the impression that Flux would remove anything that doesn't exist in the git repo?

If this were true, then Flux would remove CoreDNS, CNI, etc. Please see the docs on garbage collection: https://toolkit.fluxcd.io/components/kustomize/kustomization/#garbage-collection
