### ISSUE TITLE
"flux bootstrap github" fails due to timeout on AKS cluster using repository on a GitHub Enterprise Server

### ISSUE THREAD

**Issue by abrokwasoft** [fluxcd/flux2#697]
I'm trying to setup flux2 on an Azure Kubernetes Service cluster following https://toolkit.fluxcd.io/get-started/.

For this purpose I use a Git repository on a GitHub Enterprise Server. 

The bootstrap procedure fails though - it shows following error:
`✗ failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/2cb1b23bafe6aaa82a00562b0135dd7f9b5e57ca.tar.gz, error: Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/2cb1b23bafe6aaa82a00562b0135dd7f9b5e57ca.tar.gz": dial tcp 10.2.126.78:80: i/o timeout`

Do you have any advices how to fix this?

Here more details about my setup:

```
$ flux --version
flux version 0.5.9
```

```
$ flux check
► checking prerequisites
✔ kubectl 1.19.4 >=1.18.0
✔ Kubernetes 1.18.10 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.5.6
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.5.3
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.4.4
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.5.0
✔ all checks passed
```

```
$ flux bootstrap github \
>   --token-auth \
>   --hostname=$HOSTNAME \
>   --owner=$OWNER \
>   --repository=$REPO \
>   --branch=master \
>   --path=clusters/my-cluster \
>   --log-level debug
► connecting to github....com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system configured
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
role.rbac.authorization.k8s.io/crd-controller-flux-system configured
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system configured
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system configured
service/notification-controller configured
service/source-controller configured
service/webhook-receiver configured
deployment.apps/helm-controller configured
deployment.apps/kustomize-controller configured
deployment.apps/notification-controller configured
deployment.apps/source-controller configured
networkpolicy.networking.k8s.io/allow-scraping configured
networkpolicy.networking.k8s.io/allow-webhooks configured
networkpolicy.networking.k8s.io/deny-ingress configured
deployment "source-controller" successfully rolled out
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
► applying sync manifests
◎ waiting for cluster sync
✗ failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/2cb1b23bafe6aaa82a00562b0135dd7f9b5e57ca.tar.gz, error: Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/2cb1b23bafe6aaa82a00562b0135dd7f9b5e57ca.tar.gz": dial tcp 10.2.126.78:80: i/o timeout
```

**Comment by stefanprodan** [comment]
Duplicate of: https://github.com/fluxcd/flux2/issues/690

**Comment by abrokwasoft** [comment]
Thank you for fast feedback! You are right. :-)

It was a network policy topic. Enabling the inter-pod-communication (ingress and egress) within the `flux-system` namespace solved my issue.

//CLOSE

**Comment by stefanprodan** [comment]
Can you please write down here what is needed to enable this in AKS, I guess more and more people will run into this so best is to add this to our FAQ. Thanks!

**Comment by phillebaba** [comment]
Is this a new problem that has been introduced by AKS or Flux? I am running FluxV2 in AKS and have never seen this issue. How is AKS deployed? By default there shouldn't be any NetworkPolicies in the cluster, so it should just work out of the box.

**Comment by abrokwasoft** [comment]
It's me again with some more details about AKS setup.

In my case the AKS deployment is using following options: `--network-plugin azure` and  `--network-policy azure`

Bootstrap procedure for FluxV2 (following the Get Started tutorial) failed during the cluster sync phase. I think `kustomize-controller` pod was not able to access the `source-controller` pod. Probably something with network policies.

Solution for me was to enable communication among the FluxV2 pods which are deployed in the `flux-system` namespace.

What I did:
1. define a new NetworkPolicy manifest e.g. `allow-all-ingress-egress.yaml` with following content: 
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress-egress
  namespace: flux-system
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
```
2. run `kubectl apply -f allow-all-ingress-egress.yaml` to create new NetworkPolicy
