### ISSUE TITLE
Controllers not starting and go to CrashLoopBackOff state at bootstrapping

### ISSUE THREAD

**Issue by eelsherif** [fluxcd/flux2#700]
flux --version
flux version 0.5.9

flux bootstrap github   --owner=$GITHUB_USER --repository=flux2-test --path=clusters/staging --version=latest --personal

Produces the following...
► connecting to github.com
✔ repository created
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
role.rbac.authorization.k8s.io/crd-controller-flux-system created
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created
service/notification-controller created
service/source-controller created
service/webhook-receiver created
deployment.apps/helm-controller created
deployment.apps/kustomize-controller created
deployment.apps/notification-controller created
deployment.apps/source-controller created
networkpolicy.networking.k8s.io/allow-scraping created
networkpolicy.networking.k8s.io/allow-webhooks created
networkpolicy.networking.k8s.io/deny-ingress created
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
✗ install failed

all controllers show CrashLoopBackOff status!

**Comment by hiddeco** [comment]
Without more information from e.g. the controller logs before they crash and/or further information about the `CrashLoopBackOff` status that is reported, it will be very hard to provide any solution as I do not have access to a 🔮.

**Comment by stefanprodan** [comment]
@eelsherif https://www.google.com/search?q=how+to+debug+CrashLoopBackOff&rlz=1C5CHFA_enRO922RO922&oq=how+to+debug+CrashLoopBackOff

**Comment by eelsherif** [comment]
kubectl describe pod -n flux-system helm-controller-6765c95b47-b4gfp    &

kubectl get events -n flux-system 

generate the output below. No output from kubectl logs 
Firewall is stopped.
All non-flux pods deploy onto the cluster with no issue.


Describe >>>>>>>>
Name:         helm-controller-6765c95b47-b4gfp
Namespace:    flux-system
Priority:     0
Node:         tlvimskmindvm2/172.22.85.54
Start Time:   Wed, 13 Jan 2021 13:26:29 -0500
Labels:       app=helm-controller
              pod-template-hash=6765c95b47
Annotations:  prometheus.io/port: 8080
              prometheus.io/scrape: true
Status:       Running
IP:           192.168.1.23
IPs:
  IP:           192.168.1.23
Controlled By:  ReplicaSet/helm-controller-6765c95b47
Containers:
  manager:
    Container ID:  docker://7bf41bfea386937ceefdc30abce2510bb47c641a6c172456ff0db7157573e103
    Image:         ghcr.io/fluxcd/helm-controller:v0.4.4
    Image ID:      docker-pullable://ghcr.io/fluxcd/helm-controller@sha256:deeca74a67d0897eaef9211f192b4236a7380a507249c3aeabf4ef657aba8c3b
    Ports:         8080/TCP, 9440/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --events-addr=http://notification-controller/
      --watch-all-namespaces=true
      --log-level=info
      --log-json
      --enable-leader-election
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Wed, 13 Jan 2021 17:05:29 -0500
      Finished:     Wed, 13 Jan 2021 17:05:59 -0500
    Ready:          False
    Restart Count:  76
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:healthz/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RUNTIME_NAMESPACE:  flux-system (v1:metadata.namespace)
    Mounts:
      /tmp from temp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zfb5w (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  temp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-zfb5w:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zfb5w
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/arch=amd64
                 kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  24m (x201 over 3h39m)    kubelet  Readiness probe failed: Get "http://192.168.1.23:9440/readyz": dial tcp 192.168.1.23:9440: connect: connection refused
  Warning  BackOff    4m47s (x872 over 3h37m)  kubelet  Back-off restarting failed container

Events >>>>>>>>>>
LAST SEEN   TYPE      REASON      OBJECT                                         MESSAGE
18s         Warning   Unhealthy   pod/helm-controller-6765c95b47-b4gfp           Readiness probe failed: Get "http://192.168.1.23:9440/readyz": dial tcp 192.168.1.23:9440: connect: connection refused
5m17s       Warning   BackOff     pod/helm-controller-6765c95b47-b4gfp           Back-off restarting failed container
50m         Normal    Pulled      pod/kustomize-controller-7f5455cd78-kwvmv      Container image "ghcr.io/fluxcd/kustomize-controller:v0.5.3" already present on machine
25m         Warning   Unhealthy   pod/kustomize-controller-7f5455cd78-kwvmv      Readiness probe failed: Get "http://192.168.1.22:9440/readyz": dial tcp 192.168.1.22:9440: connect: connection refused
18s         Warning   BackOff     pod/kustomize-controller-7f5455cd78-kwvmv      Back-off restarting failed container
55m         Normal    Pulled      pod/notification-controller-694856fd64-tz7cs   Container image "ghcr.io/fluxcd/notification-controller:v0.5.0" already present on machine
25m         Warning   Unhealthy   pod/notification-controller-694856fd64-tz7cs   Readiness probe failed: Get "http://192.168.1.24:9440/readyz": dial tcp 192.168.1.24:9440: connect: connection refused
21s         Warning   BackOff     pod/notification-controller-694856fd64-tz7cs   Back-off restarting failed container
15m         Warning   Unhealthy   pod/source-controller-5bdb7bdfc9-pzcf4         Readiness probe failed: Get "http://192.168.1.25:9090/": dial tcp 192.168.1.25:9090: connect: connection refused
24s         Warning   BackOff     pod/source-controller-5bdb7bdfc9-pzcf4         Back-off restarting failed container

**Comment by stefanprodan** [comment]
What Kubernetes distribution are you using? what CNI provided?

My guess is that you have a network policy/iptables rule that blocks kubelet.

**Comment by patrickfnielsen** [comment]
I'm seeing the same issue on a newly installed RKE cluster running on RHEL7

**Comment by stefanprodan** [comment]
@eelsherif can you please use `flux bootstrap --network-policy=false` and see if that works for you?

**Comment by stefanprodan** [comment]
Without further information we can't act on this, closing.
