### ISSUE TITLE
cluster.local breaks clusters which run with another clusterDomain.

### ISSUE THREAD

**Issue by Cellebyte** [fluxcd/flux2#724]
Hey i am running with a cluster domain different then `cluster.local`.

The manifests now include `cluster.local` as the advertised storage address for the source-controller.
This broke my deployment.
Is it possible to change to manifests so that they also work on clusters with a different domain?

**Comment by hiddeco** [comment]
You can configure the `--storage-adv-addr` (or environment variable `STORAGE_ADV_ADDR`) on the `source-controller` deployment to make this work.

**Comment by Cellebyte** [comment]
@hiddeco I found it, but could we not use the short reference of `{service-name}.{namespace}` or `{service-name}.{namespace}.svc`

**Comment by stefanprodan** [comment]
> but could we not use the short reference

We had like that and it didn't work on GKE private clusters.
