### ISSUE TITLE
gitlab: Upgrade using bootstrap command doesn't work

### ISSUE THREAD

**Issue by petoknm** [fluxcd/flux2#727]
With $GITLAB_TOKEN set, I cannot upgrade my cluster's flux components using the bootstrap command anymore. Used to work in 0.5.7, doesn't work in 0.6.1.

## 0.5.7
```sh
$ flux bootstrap gitlab --owner=<redacted> --repository=<redacted> --branch=<redacted> --ssh-hostname=gitlab.com --path=<redacted>
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► generating sync manifests
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished
```

## 0.6.1
```sh
$ flux bootstrap gitlab --owner=<redacted> --repository=<redacted> --branch=<redacted> --ssh-hostname=gitlab.com --path=<redacted>
► connecting to gitlab.com
✗ failed to list projects, error: failed to find group named '<redacted>'
```

**Comment by petoknm** [comment]
## Bisection results

```sh
406601eead9b789dc01f1f177bfcdae38f81a2bb is the first bad commit
commit 406601eead9b789dc01f1f177bfcdae38f81a2bb
Author: Somtochi Onyekwere <somtochionyekwere@gmail.com>
Date:   Thu Jan 14 20:09:55 2021 +0100

    Update pkg/git to v0.2.2
    
    Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

 cmd/flux/bootstrap_gitlab.go | 16 ++++++----------
 go.mod                       |  2 +-
 go.sum                       |  4 ++--
 3 files changed, 9 insertions(+), 13 deletions(-)
```

**Comment by stefanprodan** [comment]
With `--owner=<redacted>` we can't do anything. Are you using sub-groups? how many sub-groups you have? did you provide the group ID or the group alias?

**Comment by petoknm** [comment]
Sorry for not mentioning that. I am supplying group name, it's not a subgroup, just a regular group of the form `[a-z0-9]+`. I also tried group id but it gave the same error.

**Comment by petoknm** [comment]
Problem seems to be in https://github.com/fluxcd/pkg/blame/main/git/provider_gitlab.go#L267-L275
It is checking the group name and not path (what I'm assuming to be the alias). When I put in the full display name of the group as --owner than it works. Maybe that's a behavior that should be documented.
