### ISSUE TITLE
Flux v1 automation migration guide

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux2#736]
There's a guide for setting image automation up from scratch. As a companion, to give people migrating from Flux v1 extra help, we should have a guide to how to set v2 automation up to work in the same way as v1 automation.

This needs to cover:

 - how to construct the equivalent to automation annotations
 - the equivalents to ignore (actually a sync annotation, but people use it in conjunction with automation), deautomate, and locking
 - general advice on the process for changing a Flux v1 system over to Flux v2

**Comment by stefanprodan** [comment]
@squaremo isn't this done in #806 ?

**Comment by squaremo** [comment]
Fixed by #806.
