### ISSUE TITLE
Add ability to manually set deploy keys

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/flux2#737]
I was bootstrapping a cluster and got this error message:

```
✔ install completed
► configuring deploy key
✗ failed to list deploy keys, error: GET https://api.github.com/repos/<my org>/<my repo>/keys: 404 Not Found []
```

When I run `flux check` it says everything is fine. So I pulled the public SSH key from kubernetes secret, and manually loaded that into deploy keys. The problem is that GitHub says the key has never been used (after waiting a while), and flux says it is fine.

Just note, that write access to a Github repo is not the needed permission, it needs the Admin role access. It might be necessary to forward this SSH  public key to a security admin who doesn't understand or run kubernetes or flux, but who manages access to git repos.

**Comment by stefanprodan** [comment]
You can manually bootstrap Flux, and it will display the public key that your repo admin has to set. The manual bootstrap procedure is documented here: https://toolkit.fluxcd.io/guides/installation/#generic-git-server
