### ISSUE TITLE
Network Policies don't have a selector on them

### ISSUE THREAD

**Issue by pbradly** [fluxcd/flux2#764]
The Network policies deployed as a part of `flux intstall` don't have any pod selectors defined on them, meaning if they are deployed into a namespace that has other pods running, it blocks all traffic to other pods in that namespace. 

https://github.com/fluxcd/flux2/blob/6add5114474151e914bf667fe3717268748f26a6/manifests/policies/deny-ingress.yaml#L11

https://github.com/fluxcd/flux2/blob/6add5114474151e914bf667fe3717268748f26a6/manifests/policies/deny-ingress.yaml#L14

Ideally, these policies should only be applied to the flux pods and not across everything in the namespace that flux has been deployed into. 

We also discovered that when uninstalling flux v2, if you don't delete the namespace it doesn't remove these network policies.

**Comment by stefanprodan** [comment]
> Ideally, these policies should only be applied to the flux pods and not across everything in the namespace that flux has been deployed into.

Why would deploy other things than Flux in flux-system namespace?

> We also discovered that when uninstalling flux v2, if you don't delete the namespace it doesn't remove these network policies.

`flux uninstall` deletes the namespace for you

**Comment by pbradly** [comment]
> 
> Why would deploy other things than Flux in flux-system namespace?
> 
We didn't deploy other pods into flux-system but instead deployed flux into an already existing namespace. We understand that `flux-system` is the default if `--namespace` is not defined.
> 
> `flux uninstall` deletes the namespace for you
>
Yes this makes sense if flux is deployed into a namespace it creates, but if it's deployed into an already existing namespace, it shouldn't delete that namespace since it didn't create it.

**Comment by stefanprodan** [comment]
> Yes this makes sense if flux is deployed into a namespace it creates, but if it's deployed into an already existing namespace, it shouldn't delete that namespace since it didn't create it.

Fixed in #891

**Comment by stefanprodan** [comment]
> We also discovered that when uninstalling flux v2, if you don't delete the namespace it doesn't remove these network policies.

Fixed in #891

**Comment by hiddeco** [comment]
As there are no plans to add pod selectors to the network policies at this moment and the other concerns have been addressed, I am closing this issue.

If you still feel they should be added and/or that your request has not been fulfilled, feel free to re-open. ✨
