### ISSUE TITLE
Issue with the getting started guide 

### ISSUE THREAD

**Issue by girishgouda** [fluxcd/flux2#772]
I was trying the getting started tutorial and the flux bootstrap works fine for the first time . when i apply the kustomization and push the git changes i getting the below error  and also the sync does not work. any idea what i am missing 

 flux bootstrap github   --owner=$GITHUB_USER   --repository=fleet-infra   --branch=main   --path=./clusters/my-cluster   --personal
► connecting to github.com
✗ failed to create repository, error: POST https://api.github.com/user/repos: 401 Bad credentials [] (edited)

**Comment by hiddeco** [comment]
Your `GITHUB_TOKEN` likely isn't correct, or does not have sufficient permissions to perform the operation (of creating a repository).

**Comment by girishgouda** [comment]
I am using the same token for bootstrap which worked for the first time and then when i apply the podinfo kustomization and push the changes then if i try to bootstrap i get the above issue

**Comment by hiddeco** [comment]
Are you sure the token hasn't been revoked by GitHub? This may happen without you knowing it, for example because you accidentally committed it to a Git(Hub) repository.

**Comment by stefanprodan** [comment]
If GitHub returns Bad credentials there is nothing we can do in flux, closing.

**Comment by girishgouda** [comment]
Yes you were correct. it was an issue with the github  token. Thanks
