### ISSUE TITLE
Replace exec to kubectl in Bootstrap and Check to Native kstatus call 

### ISSUE THREAD

**Issue by jonathan-innis** [fluxcd/flux2#775]
Currently, calls to the following commands cause hanging in the CLI due to a call in exec
```bash
flux bootstrap
flux check
```
This hanging is documented in separate issue: #767

Hanging can be mitigated by replacing the `flux bootstrap` and `flux check` call logic by removing the calls to `kubectl status` and replacing them with native `kstatus` calls

**Comment by stefanprodan** [comment]
Reference implementation https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_healthcheck.go

**Comment by jonathan-innis** [comment]
@stefanprodan you can assign this to me, will pick this up

**Comment by stefanprodan** [comment]
thanks @jonathan-innis

**Comment by jonathan-innis** [comment]
It doesn't look like kstatus has a way to handle different contexts and kubeconfigs natively. Would this have to be set before making calls to kstatus or am I missing an implementation detail in the kstatus docs?

**Comment by stefanprodan** [comment]
The example I posted about comes from kustomize-controller, and it does support swapping the kubeConfig, context, etc

**Comment by jonathan-innis** [comment]
I still thinking I'm missing some key piece here. I see that you leverage the KUBECONFIG in the apply and validate steps [here]( https://github.com/fluxcd/kustomize-controller/blob/31690a6aa19ef5ecd2693385bf78893b5846dce0/controllers/kustomization_controller.go#L550) but I see no instance of setting the KUBECONFIG before performing health checks. Therefore, how are health checks made sure to be performed on the remote clusters referenced by the KUBECONFIG?

**Comment by stealthybox** [comment]
I'm guessing you'll need to pass a kube client object to the kstatus code somewhere.

The client should come from earlier in the CLI bootstrap code.
We use k8s libraries to load the appropriate kubeconfig and construct that client.

If these commands don't have an existing use for a kube API client, there may not be one in scope.
The other commands that do interact /w k8s directly will be a good example of how to inject it in a standard way.
