### ISSUE TITLE
flux create secret fail said "unknown flag: --url"

### ISSUE THREAD

**Issue by JaneLiuL** [fluxcd/flux2#778]
Environment:
`cat /etc/os-release `
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

my flux version:
`flux check`
â–º checking prerequisites
âœ” kubectl 1.20.1 >=1.18.0
âœ” Kubernetes 1.19.0 >=1.16.0
â–º checking controllers
âœ” source-controller is healthy
â–º ghcr.io/fluxcd/source-controller:v0.6.3
âœ” kustomize-controller is healthy
â–º ghcr.io/fluxcd/kustomize-controller:v0.6.3
âœ” helm-controller is healthy
â–º ghcr.io/fluxcd/helm-controller:v0.5.2
âœ” notification-controller is healthy
â–º ghcr.io/fluxcd/notification-controller:v0.6.2
âœ” all checks passed

Question: 
I am try to use flux2 to monitor the private git repository, and this is private gitlab.
When I try to use below command:
 `flux create secret git testlab-auth --url=https://gitlab.xxxx-company.com/xxx/teams/xxx/test-lab --ssh-key-algorithm=ecdsa --ssh-ecdsa-curve=p521`
The response said: 
âœ— unknown flag: --url

Then if I skip create secret,and said the authentication is required, how to resolve this problem?
` flux create source git testlab --url=https://gitlab.xxxx-company.com/xxx/teams/xxx/test-lab.git --ssh-key-algorithm=ecdsa   --ssh-ecdsa-curve=p521`
âœš generating GitRepository source
â–º applying GitRepository source
âœ” GitRepository source updated
â—Ž waiting for GitRepository source reconciliation
âœ— unable to clone 'https://gitlab.xxxx-company.com/xxx/teams/xxx/test-lab.git', error: authentication required

**Comment by hiddeco** [comment]
```console
$ flux create secret git testlab-auth --url=https://gitlab.xxxx-company.com/xxx/teams/xxx/test-lab --ssh-key-algorithm=ecdsa --ssh-ecdsa-curve=p521
✗ for Git over HTTP/S the username and password are required
$ flux -v
flux version 0.6.2
```

You should change the `--url` to `ssh://` to use `--ssh-*` flags and double check the command you run.

Example:

```console
$ flux create secret git testlab-auth --url=ssh://gitlab.com/xxx/teams/xxx/test-lab --ssh-key-algorithm=ecdsa --ssh-ecdsa-curve=p521
✚ deploy key: ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABJFbjZnBkt9yXmdIflGMfQDZcXgF6ETPwyYMIoFkbVUSMWQj05DqhXXawYPqq6U0bOSpwqlxKrBBgZIAHXSemYRAAd4jKzVyFtVdfkOR5m/4kjxDo8kIu93+fECZK3zoKlkzzIf39mn4y1byWipbJyQQPA8xjQe+OZpCCv+gvKXOJfSg==

$ secret 'testlab-auth' created in 'flux-system' namespace
```
