### ISSUE TITLE
Flux cli --export generates empty file

### ISSUE THREAD

**Issue by aholbreich** [fluxcd/flux2#785]
flux cli: v 0.7.1
linux fedora 33, bash

    flux create alert-provider msteams-pandas --type msteams --address 
    https://teams.microsoft.com/l/channel/19%xxxxxx0thread.tacv2/Flux%2520notifications? 
    groupId=e499dc2f-f...--export > a.yaml

generates **empty** a.yaml 

and writes:
    bash: --export: command not found...

**Comment by hiddeco** [comment]
Unable to replicate on Arch Linux:

```console
$ flux create alert-provider msteams-pandas --type msteams --address https://test.com --export > foo.yaml
$ cat foo.yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams-pandas
  namespace: flux-system
spec:
  address: https://test.com
  type: msteams
$ flux --version
flux version 0.7.1
$ echo $SHELL
/bin/bash
$ uname -a
Linux rider 5.10.9-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 19 Jan 2021 22:06:09 +0000 x86_64 GNU/Linux
```

**Comment by hiddeco** [comment]
Based on

> bash: --export: command not found...

I think there are literal newlins in your command, as also shown in the snippet you pasted. Try running:

```console
$ flux create alert-provider msteams-pandas --type msteams --address "https://teams.microsoft.com/l/channel/19%xxxxxx0thread.tacv2/Flux%2520notifications?groupId=e499dc2f-f..." --export > a.yaml
```

**NB:** note the newline removals after `--address` and before `groupId`.

**Comment by aholbreich** [comment]
hey. yea, your snippet works! a bit embarassing now. Looking for bad symbols now...
