### ISSUE TITLE
flux does not check relative paths properly for kubectl

### ISSUE THREAD

**Issue by rayisbadat** [fluxcd/flux2#792]
version: flux version 0.7.2
OS: CentOS Linux release 7.8.2003 (Core)
Kernel: 3.10.0-1127.10.1.el7.x86_64

  I keep all my local bins in a directory in my path called "~/.bin/".  When i run `flux check --pre` or `flux bootstrap`  it fails to locate kubectl.  If I modify my path to have the absolute path to my bin directory it works.  I am guessing something in flux isnt expanding the `~` to my home dir so its not finding ~/.bin/.

`PATH="~/.bin/:/usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"`
Output of strace:

```
write(2, "\342\226\272 checking prerequisites\n", 27► checking prerequisites
) = 27
newfstatat(AT_FDCWD, "~/.bin/kubectl", 0xc000334fa8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/opt/openssl/bin/kubectl", 0xc000335078, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/sbin/kubectl", 0xc000335148, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/bin/kubectl", 0xc000335218, 0) = -1 ENOENT (No such file or directory)
```

**Comment by hiddeco** [comment]
I suspect strict POSIX is followed in the [`os.LookPath`](https://golang.org/pkg/os/exec/#LookPath) we use, meaning that only [unquoted tildes will be expanded (e.g. `PATH=~/foo`)](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01).

**Comment by kingdonb** [comment]
Since Flux 0.18, I think Flux no longer depends on kubectl (though I see it is still in the `flux2` Dockerfile, I assume that's only for testing purposes and doesn't actually make it into the dist binary...)

Can this be closed? I don't see any calls to `os.LookPath` in the GH source search anymore, except for inside of some tests.

**Comment by kingdonb** [comment]
We did a little digging during the Bug Scrub today and it looks like this can be closed now.
