### ISSUE TITLE
Flux Create Source from Azure Devops SSH URL Fails

### ISSUE THREAD

**Issue by MattMencel** [fluxcd/flux2#795]
**Describe the bug**

I'm working with flux 2 and am attempting to setup an SSH source to an Azure Devops repository. The git URL parsing fails due to the `v3` portion of the URL. See below.

**To Reproduce**

``` sh
flux create source git foo \ 
      --namespace=foo \
      --url="git@ssh.dev.azure.com:v3/myorg/myproject/foo" \
      --branch=main \
      --export > ./tenants/base/foo/sync.yaml
✗ git URL parse failed: parse "git@ssh.dev.azure.com:v3/myorg/myproject/foo": first path segment in URL cannot contain colon
```

**Expected behavior**

`flux create source git` accepts Azure Devops ssh git URLs.

**Additional context**

```
> flux -v
flux version 0.7.0
```

As a workaround, I removed the v3 from the command, and then went back and edited the `sync.yaml` file by hand and added it back. I have yet to verify whether it will work once deployed on the cluster. My assumption is it will as it was a valid URL in Flux v1.

**Comment by hiddeco** [comment]
See the "Azure DevOps" note here: https://toolkit.fluxcd.io/guides/installation/#generic-git-server

`git@ssh.dev.azure.com:v3/myorg/myproject/foo` must be `ssh://git@ssh.dev.azure.com/v3/myorg/myproject/foo`.

**Comment by MattMencel** [comment]
Thanks! Came back to say I'd just found that and you'd already answered me. 😁
