### ISSUE TITLE
Order of operations for generic git server

### ISSUE THREAD

**Issue by marshallford** [fluxcd/flux2#805]
## Error

When following the [installation steps](https://toolkit.fluxcd.io/guides/installation/#generic-git-server) for a generic git server I ran into the following error:

```
❯ flux create kustomization flux-system \
  --source=gitrepo-resource-that-has-already-been-applied \
  --path="./nonexistent/path/prior/to/git/commit" \
  --prune=true \
  --interval=10m
✚ generating Kustomization
► applying Kustomization
✔ Kustomization created
◎ waiting for Kustomization reconciliation
✗ kustomization path not found: stat /tmp/flux-system444867525/nonexistent/path/prior/to/git/commit: no such file or directory
```

## Summary

The installation steps indicate that the kustomization resource must be applied to the cluster (and exported to the git repo) **before** commiting/pushing "add sync manifests". If the path referenced in the kustomization resource is new (in the case of a new cluster as per the example) the command will error.

## Expected behavior

I see a couple of options:

1. Update the docs: Mention this chicken-egg issue in the docs and clarify that even though the reconciliation failed the kustomization resource was still applied to the cluster.

2. Add a CLI flag to `flux create kustomization` to skip the health check in the case of a brand new path. Perhaps continue to show the error but don't return an exit code of 1?

Thoughts?

## Info

```
❯ flux --version
flux version 0.7.3

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+rke2r1", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-22T22:53:07Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by stefanprodan** [comment]
The path should exist, check the previous step where you should’ve pushed the components manifest.

**Comment by marshallford** [comment]
Ah my mistake -- I was trying to simplify the process and only commit once. Thanks.
