### ISSUE TITLE
flux uninstall deletes HelmReleases with old apiVersions

### ISSUE THREAD

**Issue by mrkwtz** [fluxcd/flux2#811]
Hey everyone,

so I just wanted to switch from helm-operator to helm-controller, because the former one is not maintained anymore and a chart we want to use needs a newer helm version. 

So I installed the helm-controller via _flux install_ but with a bugged version (the bug where the CRB always refers to the SA in the flux-system namespace, but we use gitops-toolkit as namespace). So I thought: alrighty, then I'll just use _flux uninstall --namespace gitops-toolkit_ and we're good to go. The CLI also tells me that it'll remove the namespace itself, and that's fine for me.

But then this happend (just xxx'ed the sensitive information)

`xxx@xxx-TUXEDO:~$ flux uninstall --namespace gitops-toolkit
? Are you sure you want to delete the gitops-toolkit namespace? [y/N] y█

► uninstalling custom resources
No resources found
helmrepository.source.toolkit.fluxcd.io "grafana" deleted
No resources found
No resources found
helmrelease.helm.fluxcd.io "argo-events" deleted
helmrelease.helm.fluxcd.io "argo-workflows" deleted
helmrelease.helm.fluxcd.io "flux" deleted
helmrelease.helm.fluxcd.io "cert-manager" deleted
helmrelease.helm.fluxcd.io "cluster-autoscaler" deleted
helmrelease.helm.fluxcd.io "flux" deleted
helmrelease.helm.fluxcd.io "xxx-staging" deleted
helmrelease.helm.fluxcd.io "external-dns" deleted
helmrelease.helm.fluxcd.io "flux" deleted
helmrelease.helm.fluxcd.io "xxx-alpha" deleted
helmrelease.helm.fluxcd.io "xxx-backup" deleted
helmrelease.helm.fluxcd.io "xxx-bufix-capitalize" deleted
helmrelease.helm.fluxcd.io "xxx-dev-1278" deleted
helmrelease.helm.fluxcd.io "xxx-dev-1386" deleted
helmrelease.helm.fluxcd.io "xxx-dev-1413" deleted
helmrelease.helm.fluxcd.io "xxx-dev-537" deleted
helmrelease.helm.fluxcd.io "xxx-dev-644" deleted
helmrelease.helm.fluxcd.io "xxx-dev-665" deleted
helmrelease.helm.fluxcd.io "xxx-dev-748" deleted
helmrelease.helm.fluxcd.io "xxx-dev-918" deleted
helmrelease.helm.fluxcd.io "xxx-develop" deleted
helmrelease.helm.fluxcd.io "xxx-xxx-xxx-xxx-xxx-f" deleted
helmrelease.helm.fluxcd.io "xxx-hotfix-dev-533" deleted
helmrelease.helm.fluxcd.io "xxx-hotfix-xxx-xxx" deleted
helmrelease.helm.fluxcd.io "xxx-xxx" deleted
helmrelease.helm.fluxcd.io "xxx-xxx-xxx-clickdummy" deleted
helmrelease.helm.fluxcd.io "ingress-nginx" deleted
helmrelease.helm.fluxcd.io "oauth2-proxy" deleted
helmrelease.helm.fluxcd.io "kowl" deleted
helmrelease.helm.fluxcd.io "strimzi-kafka-operator" deleted
helmrelease.helm.fluxcd.io "keycloak" deleted
helmrelease.helm.fluxcd.io "metrics-server" deleted
helmrelease.helm.fluxcd.io "prometheus-operator" deleted
helmrelease.helm.fluxcd.io "promtail" deleted
helmrelease.helm.fluxcd.io "jaeger-operator" deleted
helmrelease.helm.fluxcd.io "rabbitmq" deleted
helmrelease.helm.fluxcd.io "vault" deleted
` 

So a few questions / remarks

1. List EVERY resource you're going to delete before the prompt or add it to the help of _flux uninstall_ . For now it only says

`      --resources   removes custom resources such as Kustomizations, GitRepositories and HelmRepositories (default true)
`

2. Why do you delete HelmReleases? Whats the reason for that? Doing a _flux uninstall_ doesn't mean that I want to get rid of all HelmReleases. In our case I wanted to run the helm-operator and helm-controller side-by-side to do a step by step migration where the old HelmRelease apiVersions are handled by the operator und the new ones by the controller. 

3. If there is a good reason for deleting HelmReleases, why do you also delete HelmReleases of an old apiVersion? If you do a _flux install_ you also just create CRDs for the new apiVersion. 

Thank god we did this on the dev cluster first and the helm-operator was scaled to zero.

**Comment by kingdonb** [comment]
The new [migration guide](https://toolkit.fluxcd.io/guides/helm-operator-migration/#migration-strategy) covers migration from `helm-operator` to `helm-controller` though it does not specifically discuss upgrades from one release of flux to another, I think this doc is where to find the best guidance to this effect. If I read correctly, `flux uninstall` removed only resources that were created for the new helm-controller, and left old helm-operator "helm.fluxcd.io/v1" helmreleases intact.

This is consistent with my understanding of how it should work, since `flux uninstall` removes the CRDs, and `--resources` defaults to `true`, this is consistent with the documentation, though perhaps could be clearer.

> `Are you sure you want to delete the gitops-toolkit namespace? [y/N] y` seems insufficient, as you point out there is no warning about CRDs being deleted here even though potentially this is much more dangerous. CRDs are not namespaced and removing the CRD will necessarily remove all instances of the CRD.

While these two options used together are potentially in conflict, I am not sure how to change the default that won't also result in a new corner that must be covered with further guard stops or additional descriptive output, to avoid risking confusion resulting from lack of current CRDs.

If you run `flux install` today with `--namespace` and no CRDs are present, it seems Flux will just install them if permitted (this apparently is not even an option, there is no `--resources` option on `flux install` or `bootstrap`) on the face, doing the uninstall it seems reasonable to do the opposite and remove the CRDs, maybe just not reasonable to do so without warning. The user is prompted to acknowledge the namespace will be deleted, but not warned about deleting CRDs

So it feels a bit like burying the lede in the CLI to have this default with no prompt. But in the past, I know a lot of issue reports have come from users forgetting to apply the latest CRD when an update is available, so this "CRD-update-on-install" behavior is strongly desirable and beneficial from a support standpoint.

Would it make sense for `flux uninstall` with `--namespace` to change the default as `--resources false`, (even if this is not symmetric?) Otherwise would it make sense to add a new prompt to `flux uninstall`? I'm not sure which change is more work.

**Comment by kingdonb** [comment]
I am working through this issue and I just noticed when trying it myself, that I did not read this report correctly at all.

```
$ flux uninstall
Are you sure you want to delete the flux-system namespace: y█
► uninstalling custom resources
gitrepository.source.toolkit.fluxcd.io "flux-system" deleted
No resources found
No resources found
kustomization.kustomize.toolkit.fluxcd.io "flux-system" deleted
helmrelease.helm.fluxcd.io "jenkins" deleted
► uninstalling components
clusterrole.rbac.authorization.k8s.io "crd-controller-flux-system" deleted
clusterrolebinding.rbac.authorization.k8s.io "cluster-reconciler-flux-system" deleted
clusterrolebinding.rbac.authorization.k8s.io "crd-controller-flux-system" deleted
namespace "flux-system" deleted
✔ uninstall finished
```

This is a cluster I've recently installed Flux v2 on, I was uninstalling to try again with a different repository provider and ensure no conflicts. I can think of absolutely no reason why `flux uninstall` would remove helmreleases from `helm.fluxcd.io`.

In my case this resulted in all sorts of surprising unintended consequences, uninstalling the HR wiped out a PVC and PV that was carrying encrypted passwords for a handful of users, and job configurations for a handful of repos.

Is this something we should address with a change in behavior or more verbose warning?

**Comment by dharmendrakariya** [comment]
actually its deleting old releases (helmrelease.helm.fluxcd.io) only not the new ones (helmreleases.helm.toolkit.fluxcd.io) in my case. and new ones are now orphans resources.

**Comment by dharmendrakariya** [comment]
hey @mrkwtz just for curiosity, how are you applying crds? with flux bootstrap command? also do you get zero downtime migration? I am also doing the same, migrating from v1 to v2.

**Comment by stefanprodan** [comment]
This bug will be fixed in the next release, for those upgrading from v1, do not use uninstall on live system. Next release will be this week.

**Comment by mrkwtz** [comment]
> hey @mrkwtz just for curiosity, how are you applying crds? with flux bootstrap command? also do you get zero downtime migration? I am also doing the same, migrating from v1 to v2.

The before mentioned behavior made me hesitant in using the flux cli to bootstrap (or delete) anything. So I just use --export and then I'll apply the manifests. With that approach I can check beforehand what will be applied on the cluster and no further logic is run. We indeed got a zero downtime migration. Just 
- stop the old helm-operator
- apply the new HelmRelease resource (helmreleases.helm.toolkit.fluxcd.io)
- wait for the reconcilation to happen and until the new HelmRelease is in a ready state
- delete the old HelmRelease resource (helmrelease.helm.fluxcd.io)
- restart the helm-operator

But as @kingdonb already mentioned, you can find a much proper guide to a migration here: https://toolkit.fluxcd.io/guides/helm-operator-migration/#migration-strategy

**Comment by dharmendrakariya** [comment]
okay, great @stefanprodan  also want to ask that when we apply generated kustomization.yaml in flux-system it gives below error 
```
kc apply -f flux-system/kustomization.yaml 

error: unable to recognize "fluxv2/flux-system/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
```
Also can we get those crd manifests without using 'flux' cli/commands?

**Comment by dharmendrakariya** [comment]
> The before mentioned behavior made me hesitant in using the flux cli to bootstrap (or delete) anything. So I just use --export and then I'll apply the manifests. With that approach I can check beforehand what will be applied on the cluster and no further logic is run. We indeed got a zero downtime migration. Just
> 
> * stop the old helm-operator
> * apply the new HelmRelease resource (helmreleases.helm.toolkit.fluxcd.io)
> * wait for the reconcilation to happen and until the new HelmRelease is in a ready state
> * delete the old HelmRelease resource (helmrelease.helm.fluxcd.io)
> * restart the helm-operator
> 
> But as @kingdonb already mentioned, you can find a much proper guide to a migration here: https://toolkit.fluxcd.io/guides/helm-operator-migration/#migration-strategy

Thank you so much for the response, I also want to apply those manifests manually rather than bootstrap. Also our cluster won't be having flux cli so this approach you suggested sounds good.

**Comment by stefanprodan** [comment]
Why would you apply a Kustomize config on the cluster? @dharmendrakariya please see https://toolkit.fluxcd.io/guides/installation/#generic-git-server and https://toolkit.fluxcd.io/faq/#are-there-two-kustomization-types

**Comment by dharmendrakariya** [comment]
@stefanprodan it was generated using bootstrap command, see below
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
```
so I thought this is required in order to make ```kustomize.toolkit.fluxcd.io/v1beta1```  resource work.
never mind, I need more homework i guess. thank you:)

**Comment by dharmendrakariya** [comment]
@mrkwtz hi, did you face any problem with existing resources, like prometheus and ingress-nginx, they have crds and I found that new fluxv2 helm releases gives error that resources already exist like below
```
Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "ingress-nginx" in namespace "ingress-ng
inx" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "ingress-nginx"; annotation validation
error: missing key "meta.helm.sh/release-namespace": must be set to "ingress-nginx"   
```

@mrkwtz did you encounter this issue? if yes, please can you suggest something?

I guess this is helm issue, but as we move along with migration (in the case where resources have crds, implanted earlier) this will fail the smooth migration, correct me if I am wrong please @stefanprodan

**Comment by mrkwtz** [comment]
hey @dharmendrakariya its either related to this [issue](https://github.com/fluxcd/helm-operator/issues/544) and has to do with different apiVersions of some resources, or you tried to install the same helm chart with a different releasename but the chart has a fixed service account name.

**Comment by dharmendrakariya** [comment]
@mrkwtz I checked the api versions are same(for ingress-nginx 3.12.0) and also I am keeping the same helm release name, however I found similar issues on helm/helm side which indicate, this is related to helm upgrade specifically, as it finds the old service accounts, pod security policies etc in nginx/promethesus old releases its failing the reconciliation. btw thanks for the reply:)

**Comment by dharmendrakariya** [comment]
update: strange but because I didn't set ```namespace:``` in release it was giving the above mentioned error. after fixing namespace the error gone and I get successful migration. Thank you for the support guys:) @mrkwtz @stefanprodan
