### ISSUE TITLE
Flux and PodSecurityPolicy

### ISSUE THREAD

**Issue by ConnorJC3** [fluxcd/flux2#829]
### Describe the bug

The initial manifests created by `flux install` lack a `runAsUser` and `runAsGroup`, which prevents flux from being installed on clusters with a `PodSecurityPolicy` that mandates pods run as a non-root user. This is because kubernetes does not count non-numeric users as not root, and the flux containers run under the user `controller` rather than using a UID.

### To Reproduce

Steps to reproduce the behaviour:

1. Setup kubernetes with a PSP that includes `MustRunAsNonRoot`, and make sure the current context uses that PSP
2. Attempt to install flux
3. Pods will refuse to start with event:
```container has runAsNonRoot and image has non-numeric user (controller), cannot verify user is non-root```

### Expected behavior

`flux install` generates manifests that can be applied to a cluster when using a PodSecurityPolicy. I was able to manually deploy flux by adding the following to the already existing `securityContext`s inside the flux manifest:
```yaml
securityContext:
  runAsUser: 100
  runAsGroup: 101
```

(100 and 101 are the UID/GID for the controller user/group on the current stable version of flux's containers)

Alternatively, this could be solved by using a numeric user (i.e. UID) when building the flux containers rather than a username in the `Dockerfile`.

### Additional context

- Kubernetes version: 1.20.2 (unlikely to matter)
- Git provider: N/A
- Container registry provider: N/A

Below please provide the output of the following commands:

```cli
$ flux --version
flux version 0.6.3

$ flux check --pre
► checking prerequisites
✔ kubectl 1.19.4 >=1.18.0
✔ Kubernetes 1.20.2 >=1.16.0
✔ prerequisites checks passed

$ # Other commands are not relevant because flux gets stuck during installation
```

**Comment by stefanprodan** [comment]
You can customise the controller deployment definitions as described in the [installation docs](https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests). Setting the user and group to something like `100` will break Flux on OpenShift and other platforms that have options about security context.

PS. PodSecurityPolicy has been deprecated in Kubernetes and the API will be removed in Kubernetes 1.25, see https://github.com/kubernetes/kubernetes/pull/97171

**Comment by pierluigilenoci** [comment]
@stefanprodan according to sig-auth [1][2], a new implementation of PSP is on the way and will be backward compatible with old policies unless there are a few minor tweaks.
So I think calling PSP dead is a bit premature to me.
 
Ref:
[1] https://www.youtube.com/watch?v=YSzphARKjKs&t=2340s
[2] https://github.com/kubernetes/enhancements/issues/5#issuecomment-729272396

**Comment by pierluigilenoci** [comment]
@stefanprodan the problem is bigger than that. Sadly in a cluster with PSPs it is not even possible to bootstrap the source-controller.

**Comment by stefanprodan** [comment]
We'll offer a way to patch the manifests before bootstrap, the CLI will merge the kustomize config instead of overriding it.

**Comment by pierluigilenoci** [comment]
@stefanprodan do you have an ETA for this?

**Comment by pierluigilenoci** [comment]
FYI https://github.com/kubernetes/enhancements/pull/2582

**Comment by stefanprodan** [comment]
@pierluigilenoci as of flux 0.13 you can now add uids or whatever else you need to Flux deployments and bootstrap will include them see the docs here: https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests
