### ISSUE TITLE
Improve the image automation authentication examples

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#850]
The image automation guide has a section on [ImageRepository cloud providers authentication](https://toolkit.fluxcd.io/guides/image-update/#imagerepository-cloud-providers-authentication) that we could improve in terms of readability and correctness:

- [ ] Use single replica high-priority Deployments instead of CronJobs
- [ ] Place the Deployment examples in `manifests/image-update-auth` and link to them from the guide
- [x] Add Azure ACR example #877

**Comment by stealthybox** [comment]
👋 working toward this

**Comment by stealthybox** [comment]
@alisondy working on https://github.com/fluxcd/flux2/pull/1053 for AWS/GCP

**Comment by ammar-mik** [comment]
Hi,

I am using the example from the [AWS Elastic Container Registry](https://fluxcd.io/docs/guides/image-update/#aws-elastic-container-registry), with the IRSA workflow, therefore setting a ServiceAccount to an existing ARN from Roles in my AWS IAM account.
However, the `get-token` container execution inside the job fails with a Bad Request response.

I have tried many different Roles from my AWS IAM section, tried attaching the AmazonEC2ContainerRegistryReadOnly policy to them, but without success.

Am I missing something?

Thanks!
