### ISSUE TITLE
Trying to use Azure Key Vault for SOPS encryption/decryption

### ISSUE THREAD

**Issue by joelnotified** [fluxcd/flux2#851]
### Describe the bug

Hi,
Trying to debug secrets decryption using SOPS. Open this issue after discussion in slack: https://cloud-native.slack.com/archives/CLAJ40HV3/p1612279770153800

I'm using Azure Key Vault and AAD Pod Identity. I'm pretty sure I've managed to authorize access to the key vault for the kustomize controller using that. But my kustomization is getting this error:

``` 
decryption failed for ...: GetDataKey: Failed to get the data key required to decrypt the SOPS file. 
Group 0: FAILED                                                                                                                                                                    
  https://<vault_name>.vault.azure.net/keys/<key_name>/<string>: FAILED                                                                         
	- | Invoking Azure CLI failed with the following error:                                                                                                                        
Recovery failed because no master key was able to decrypt the file. In                                                                                                             
order for SOPS to recover the file, at least one key has to be successful,                                                                                                         
but none were.   
```

I interpret that as kustomize controller not being able to get the key from key vault right?

### To Reproduce

What I've done so far, if it helps:

1. Setup AAD Pod Identity according to https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/. But I've also added `--key-permissions encrypt decrypt` when setting the policies for the identity

2.  Added the correct label to the `kustomize-controller` labels:
```
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: aad-pod-identity
```

3. Created a SOPS key in Azure Key Vault
`az keyvault key create --name flux-sops-key --vault-name $keyvault_name --protection software --ops encrypt decrypt`

4. Encrypted a secret locally:
`sops --encrypt --azure-kv https://<vault_name>.vault.azure.net/keys/<key_name>/<string> --encrypted-regex '^(data|stringData)$' --in-place my-secret.yaml`

5. Updated my kustomziation to use sops:
```
spec:
  decryption:
    provider: sops 
```

```cli
flux version 0.6.2

► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.19.6 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.6.3
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.6.3
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.5.2
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.6.2
✔ all checks passed

{"level":"error","ts":"2021-02-02T15:48:21.261Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"helm-apps","namespace":"flux-system","error":"decryption failed for 'helm-repository-credentials': GetDataKey: Failed to get the data key required to decrypt the SOPS file.\n\nGroup 0: FAILED\n  https://<vault_name>.vault.azure.net/keys/<key_name>/<string>: FAILED\n    - | Invoking Azure CLI failed with the following error: \n\nRecovery failed because no master key was able to decrypt the file. In\norder for SOPS to recover the file, at least one key has to be successful,\nbut none were."}
```

**Comment by stefanprodan** [comment]
To verify that the permissions are ok, you could create a pod in the flux-system namespace with the same setting as kustomize-controller and run the decryption with sops CLI from inside the pod.

**Comment by stealthybox** [comment]
I'm guessing the `az` cli tool or some azure auth helper equivalent needs to be added to the pod.

You can do this by sharing an emptyDir volume mount between an azure cli initContainer and potentially copying the binary into it

Or building a new image with kustomize-controller as the base

**Comment by joelnotified** [comment]
Didn't have time to do much more testing today, but I ran a quick test.

Started a pod with the `mozilla/sops` image, added the aad-pod-identity binding label and tried to run both encryption and decryption using the Azure Key Vault. Got the same errors:

Decryption:
```
[AZKV]   ERRO[0000] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: "
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  https://<vault_name>.vault.azure.net/keys/<key_name>/<verison>: FAILED
    - | Invoking Azure CLI failed with the following error:

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

Encryption:
```
[AZKV]   ERRO[0000] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: "
Could not generate data key: [failed to encrypt new data key with master key "https://<vault_name>.vault.azure.net/keys/<key_name>/<version>": Invoking Azure CLI failed with the following error: ]
```

So yeah. I guess it looks like sops is relying on access to the Azure cli?

**Comment by stealthybox** [comment]
> So yeah. I guess it looks like sops is relying on access to the Azure cli?

Yes, I think you're going to need to get the `az` binary onto the pod fs somehow, whether that's building an image or using an initContainer+shared-volumeMount

Previous comment may not have been clear enough about that.
I'm just inferring this is the solution based off of the error, but you could also validate this locally by temp-renaming your `az` binary to something else and trying the sops decryption to see if that's the problem. :)

**Comment by jooooel** [comment]
> Yes, I think you're going to need to get the `az` binary onto the pod fs somehow, whether that's building an image or using an initContainer + shared volumeMount

Could it be expected of the kustomize controller to handle this in the future, or will there have to be workarounds for it to work with Azure Key Vault?

> Previous comment may not have been clear enough about that.

No I think that was pretty clear 😊 Helped me realize what the problem was, just wanted to check.

**Comment by amjanoni** [comment]
It seems that the default authentication method used by sops is the CLI, and there's no automatically fallback implemented by the sops team yet (https://github.com/mozilla/sops/pull/710)

I've fixed this issue by adding an env variable in the kustomize controller. (**AZURE_AUTH_METHOD=msi**)

**Comment by joelnotified** [comment]
> It seems that the default authentication method used by sops is the CLI, and there's no automatically fallback implemented by the sops team yet ([mozilla/sops#710](https://github.com/mozilla/sops/pull/710))
> 
> I've fixed this issue by adding an env variable in the kustomize controller. (**AZURE_AUTH_METHOD=msi**)

Thanks!
I can confirm that it solved my problems as well 😃

**Comment by stefanprodan** [comment]
Let's keep this open as we need to document the Azure SOPS setup for everyone else hitting these issues.

**Comment by stealthybox** [comment]
Great!
Should we could consider just always having that ENV variable all the time?

It likely has zero effect if the azure provider for sops is not invoked.

**Comment by stealthybox** [comment]
The SOPS documentation isn't accurate about how the fallthrough logic works.
With the current SOPS implementation, the a non CLI Auth method must be enabled, either through explicitly specifying `AZURE_AUTH_METHOD`, or providing other ENV vars that imply a specific authMethod.

https://github.com/mozilla/sops/blob/8e21de8/azkv/keysource.go#L54-L143

We can document around this and potentially propose a more heuristic behavior to the SOPS team.

**Comment by apeschel** [comment]
I've created a PR with more fleshed out instructions for SOPS / Azure that should hopefully help in this area: https://github.com/fluxcd/flux2/pull/1052
