### ISSUE TITLE
Allow specific component version targeting in parallel with flux release tag targeting

### ISSUE THREAD

**Issue by zdzielinski** [fluxcd/flux2#864]
### Describe the issue

Currently, flux only allows you to specify component names when performing a `flux install`.

Example:

```
flux install --components "source-controller,kustomize-controller"
```

Certain customers would like to see this extended to allow for targeting of both component names, and versions:

Example:

```
flux install --components "source-controller:0.7.4,kustomize-controller"
```

This should also override specific flux version tagged installations:

```
flux install --version "v0.7.6" --components "source-controller:0.7.4,kustomize-controller"
```

**Comment by stefanprodan** [comment]
Specific versions, others than what’s bundled within a flux2 version, are not supported. We offer no guarantees about compatibility between components/apis/cli outside of flux2 release cycle that’s being vetted with our end-to-end test suite.
