### ISSUE TITLE
Bootstrap picks existing repo instead of creating new one

### ISSUE THREAD

**Issue by demon** [fluxcd/flux2#916]
### Describe the bug

When a repository already exists with a name `foo-bar` and you attempt to bootstrap with `--repository=foo` it instead chooses the already-existing `foo-bar`. I don't know if the hyphen has anything to do with it or not, I haven't looked into it further.

### To Reproduce

1. Create a repository called `foo-bar` on Github
2. Run `flux bootstrap github --repository=foo`
3. Observe there's no new repository created, but your manifests have been committed to the existing repository.

### Expected behavior

A new repository called `foo` would be created.

### Additional context

- Kubernetes version: 1.8
- Git provider: Github

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.7.7
```

**Comment by stefanprodan** [comment]
Addressed by https://github.com/fluxcd/flux2/pull/968
