### ISSUE TITLE
[Docs] Flux Sealed Secrets / kubeseal --controller-namespace not mentioned

### ISSUE THREAD

**Issue by Sijoma** [fluxcd/flux2#919]
Hi guys,

it seems the documentation on sealed secrets is missing a simple flag:

The docs state [Sealed Secret Doc](https://toolkit.fluxcd.io/guides/sealed-secrets/):
```
kubeseal --format=yaml --cert=pub-sealed-secrets.pem \
< basic-auth.yaml > basic-auth-sealed.yaml
```

I believe the **--controller-namespace** argument is required (mentioned in bitnami docs & decryption did not work for me)
```
kubeseal --controller-namespace flux-system --format=yaml --cert=pub-sealed-secrets.pem \
< basic-auth.yaml > basic-auth-sealed.yaml
```

**Comment by adrian** [comment]
@Sijoma The `--controller-namespace` and `--controller-name` parameters are only needed when the `--cert` parameter isn't used. In that case kubeseal pulls down the public key from the controller to encrypt the secret. If the public key is available locally then only the `--cert` parameter is required.

If you're following along with [the docs](https://toolkit.fluxcd.io/guides/sealed-secrets/) then you'll have downloaded the public key with this command,
```
kubeseal --fetch-cert \
--controller-name=sealed-secrets \
--controller-namespace=flux-system \
> pub-sealed-secrets.pem
```

**Comment by stefanprodan** [comment]
> decryption did not work for me

My guess is that you haven't fetched the `pub-sealed-secrets.pem` from your cluster. I'm closing this, but feel free to comment here.

**Comment by Sijoma** [comment]
I fetched it from my Cluster. However, the cluster was not able to decrypt the secrets. 

The flag is mentioned by kubeseal docs.

**Comment by Sijoma** [comment]
I followed the docs. I also have downloaded the cert to encrypt my secrets. However the cluster was not able to decrypt them. 

I copy & pasted everything. I did not even try to write the commands myself.
