### ISSUE TITLE
GitLab bootstrap - git clone error: repository not found

### ISSUE THREAD

**Issue by mmisiewicz-g** [fluxcd/flux2#924]
### Describe the bug

I am using a paid gitlab.com. The site reports this version: GitLab Enterprise Edition 13.9.0-pre 04013f0902b.
I am using flux2 v0.8.0.

I have a private group called 'company-de'. All subgroups are also private. I have a subgroup called 'project' and another subgroup in it called 'ops'.
The url for the repo i am trying to create would be: https://gitlab.com/company-de/project/ops/flux-system.

I am NOT trying to bootstrap flux for a personal repo.
This problem happens in a windows terminal, git terminal for windows (git 2.30.0.windows.2), ubuntu 20.04 LTS on Windows WSL2 (git 2.25.1)

1)
When I provide owner=company-de/project/ops i get this error:
```cli
► connecting to gitlab.com
✗ failed to get project, error: failed to find group named 'company-de'
```

2)
When I provide owner=project/ops i get the following:
```cli
► connecting to gitlab.com
✔ repository created
✗ git clone error: repository not found
```

NOTE: in the second case the repository is created. Branch 'master' contains a readme file.

I tried all the possible combinations I can think of and I am stuck on the git clone error. I tried to use --verbose but that doesnt help. It would be nice to get better error logs. I wanted to see what is the command that flux executes to clone the repo.

I changed the repo name so it doesnt contain a dash. I tried to bootstrap one level up in 'project' (so its not a subgroup in a subgroup). It didnt help. I dont see what is the problem.

### To Reproduce

Steps to reproduce the behaviour:

export GITLAB_TOKEN=x
(I went to my user account details in gitlab, then to PAT section, then i created a new token with api permissions. I also tried adding all possible permissions for PAT)
(i have a git private key available on my system too, for ssh - git clone works when i do it manually)

1)
```cli
flux bootstrap gitlab \
  --owner=project/ops \
  --repository=flux-system \
```

2)
```cli
flux bootstrap gitlab \
  --ssh-hostname=gitlab.com \
  --owner=project/ops \
  --repository=flux-system \
```

I also tried --token-auth, --private, --path, --branch, --components but these params dont change anything.

### Expected behavior

I expect the bootstrap process to finish.

### Additional context

Below please provide the output of the following commands:

```cli
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T11:45:27Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

$ git --version
git version 2.25.1

$ flux --version
flux version 0.8.0

$ flux check
► checking prerequisites
✔ kubectl 1.20.1 >=1.18.0
✔ Kubernetes 1.20.2 >=1.16.0
► checking controllers
✗ source-controller: deployment not found
✗ kustomize-controller: deployment not found
✗ helm-controller: deployment not found
✗ notification-controller: deployment not found
```

**Comment by stefanprodan** [comment]
Instead of `company-de`, `project` and `ops` you need to provide the unique name generated by GitLab. Look in the URL, should be something like `project111`, `ops231`.

**Comment by mmisiewicz-g** [comment]
I think i am using the correct names. When I go to the repo in gitlab i see the url. I take the url parts and use it as owner.
GitLab provides a group/repo name that is separate from repo path. In my case the have the same name.
These names are the ones i gave to the group and repo. There are no random numbers in them. I can see numbers in the project id field but that is not in the URL.
Let me reiterate that the bootstrap process managed to create the repo in the correct subgroup. The next git clone step fails.

![image](https://user-images.githubusercontent.com/77806861/108045214-7a2fba00-7043-11eb-9020-3c0b702ec083.png)
![image](https://user-images.githubusercontent.com/77806861/108045319-9e8b9680-7043-11eb-957e-e55c4b8ab59b.png)

**Comment by hiddeco** [comment]
Have you tried

```
flux bootstrap gitlab \
  --owner=project \
  --repository=ops/flux-system
```

**Comment by mmisiewicz-g** [comment]
I tried now but it errors out:
```cli
✗ ops/flux-system is an invalid project name for gitlab.
It can contain only letters, digits, emojis, '_', '.', dash, space. It must start with letter, digit, emoji or '_'.
```

**Comment by hiddeco** [comment]
The problem is indeed an assumption in the URL for the repository, which based on the provided values does not include the `company-de`: https://github.com/fluxcd/pkg/blob/main/git/repository.go#L75-L87

**Comment by mmisiewicz-g** [comment]
Unfortunately the workaround doesn't work.

In case someone doesn't have much experience in GitLab - it allows a hierarchy of groups so a group can have many nested subgroups. When you use the SaaS gitlab.com you create a root/top group which in my case is 'company-de' (you can also pin a license to this root group). Our organization source code is in this root group and its subgroups - there is some settings inheritance so f.ex. i can say in the root group that all its subgroups must be private.

```cli
$ flux bootstrap gitlab \
  --ssh-hostname=gitlab.com/company-de \
  --owner=project/ops \
  --repository=flux-system \

► connecting to gitlab.com
✗ git clone error: repository not found

$ flux bootstrap gitlab \
  --hostname=gitlab.com/company-de \
  --owner=project/ops \
  --repository=flux-system \

► connecting to gitlab.com/company-de
✗ failed to get project, error: failed to list groups, error: GET https://gitlab.com/users/sign_in: 503 failed to parse unknown error format
```

**Comment by imamika** [comment]
The workaround didn't help me either. I have the exact same issue.

**Comment by AtitShetty** [comment]
We are facing the same issue when connecting to enterprise gitlab, that has groups and subgroups.

Essentially our ssh looks like git@gitlab.company.com:group1/subgroup1/repo.git

When bootstrapping, it can create a nonexisting repo, but during the second step of `checkout`, we get `git clone error: authorization failed`.

**Comment by hazim1093** [comment]
I had it working on an older version, and faced the same issues when I upgraded to flux `v0.9.1` today. 
I tried downgrading it and it finally starting working again on `v0.5.8` 🎉 

Might be worth trying the downgrade as a workaround

**Comment by stefanprodan** [comment]
For all of you having issues with GitLab, can you please help us out determine if #968 fixes the issue? The PR contains the commands needed to compile the binary locally.

**Comment by hazim1093** [comment]
I can confirm that I don't see this issue anymore with v0.13.1. 
I have `--owner` set as `group/subgroup`

Thanks guys 🎉 @hiddeco @stefanprodan
