### ISSUE TITLE
Helm chart using Git Repository fails to install dependency with helm repository alias

### ISSUE THREAD

**Issue by trillejs** [fluxcd/flux2#925]
### Describe the bug

I am trying to install a HelmChart configured with a GitRepository source.
This Chart has a dependency block:
```yaml
dependencies:
- name: dependency-helm-chart
  version: "x.x.x"
  repository: "@somewhere"
```
I have setup a HelmRepository source named the same as this alias in the same namespace that points to the actual https://somewhere helm repository.
However in the source controller I see this error:

```
scheme \"\" not supported
helm.sh/helm/v3/pkg/getter.Providers.ByScheme
  /go/pkg/mod/helm.sh/helm/v3@v3.5.0/pkg/getter/getter.go:156
github.com/fluxcd/source-controller/internal/helm.NewChartRepository
  /workspace/internal/helm/repository.go:54
github.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).reconcileFromTarballArtifact
  /workspace/controllers/helmchart_controller.go:588
github.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).Reconcile
  /workspace/controllers/helmchart_controller.go:222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211
[...]
```

If I change the dependency block to use the full Helm repository url:
```yaml
dependencies:
- name: dependency-helm-chart
  version: "x.x.x"
  repository: "https://somewhere"
```
Then the chart proceeds with the installation just fine.
I also tried installing the chart from the helm repo directly instead of the git repository, that works, alias included.

If I use the syntax "alias:somewhere" instead of "@somewhere", then the error in the source controller is:
```
scheme \"alias\" not supported
```

### To Reproduce

Steps to reproduce the behaviour:

1. Define a Git source and a helm repo source with the helm repository name corresponding to the alias used in the chart
2. Watch logs in source controller

### Expected behavior

Dependency alias or full url are both installed normally.

### Additional context

Below please provide the output of the following commands:

```cli
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

flux --version
flux version 0.7.7

flux check
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.16.15-eks-ad4801 >=1.16.0
► checking controllers
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.8.0
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.8.0
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.7.0
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.8.0
✔ all checks passed
```

**Comment by hiddeco** [comment]
You should use the URL in your dependencies, as aliases depend on system configuration and are therefore not declarative (and a `HelmRepository` name does not equal an alias).

**Comment by trillejs** [comment]
Okay, thanks for the answer.

**Comment by rupelu** [comment]
This would be a really cool feature for air gapped installations where you have a helm repository that is basically a copy of the original - just with a different URL. It would also be cool if the alias would match the name of a HelmRepository, however as this could be a resource in another namespace, I am not sure how this would look like.

**Comment by mfilotto** [comment]
This would allow to use a secure helm repository instead of an anonymous access
