### ISSUE TITLE
existing ssh key for other cluster is overwritten at bootstrap and key is r/o

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/flux2#964]
### Describe the bug

Have two clusters, each with flux bootstrapped via cli.
The bootstrap of cluster #2 will overwrite the deployment key put in place by bootstrap #1.
Each install/cluster is pointed at its distinct branch - so maybe branch-name can be used as a qualified for the key when put into github. 

Also I noted that the deployment key is r/o, but won't it need r/w for the image-updater to work?

### To Reproduce

Steps to reproduce the behaviour:

1. Bootstrap two clusters against same github repo, but with each of their own branch

### Expected behavior

Key's should not clash.

### Additional context

- Kubernetes version:
- Git provider:
- Container registry provider:

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.8.2
[et2448@Davids-Work-MacBook-Pro flux-system (⎈ |kube-system/api-os-global-finods-com:6443/david.karlsen@evry.com:flux-system)]$ flux check
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✔ Kubernetes 1.19.0+e405995 >=1.16.0-0
► checking controllers
```

**Comment by stefanprodan** [comment]
The deploy key is named after your cluster `bootstrap --path=clusters/production` would give you a deploy key named `flux-./clusters/production`, use unique names and it should be fine.

**Comment by brondum** [comment]
@stefanprodan What if you have two cluster that listens to same folder? like cluster you want to keep the exact same configuration? any smart way of doing this ?

**Comment by stefanprodan** [comment]
@brondum flux bootstrap is not smart like that 😀 

Are these clones ephemeral clusters? If so then you can spin up flux on those clusters and tell it to sync with a configuration defined in Git.

Assuming you have two clusters:
- `staging` cluster that's bootstrapped on the `clusters/staging` path
-  `staging-test` cluster that has no workloads deployed nor flux

This how you could make the `staging-test` a clone of `staging`:

```sh
# install flux without storing its manifests in Git
flux install --context=staging-test

# export the source from staging
flux export source git flux-system --context=staging \
--with-credentials > staging-test-source.yaml

# edit the staging-test-source.yaml file:
# - delete the annotations and labels
# - ignore the `clusters/staging/flux-system` e.g.:
# kind: GitRepository
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   ignore: |
#     /clusters/staging/flux-system/

# save and apply the source on staging-test
kubectl --context=staging-test apply -f staging-test-source.yaml 

# create a kustomization to apply the staging workloads on staging-test
flux create kustomization flux-system --context=staging-test \
--source=GitRepository/flux-system \
--path=clusters/staging \
--prune \
--validation=client
```

**Comment by brondum** [comment]
@stefanprodan Nice, okay i actually tested out another procedure, it might be a bit risky:

Bootstrap the first one as you normally would.

Next cluster:

```sh
kubectl apply -f ./cluster-staging/flux-system/gotk-components.yaml --wait=true

kubectl create secret generic flux-system -n flux-system --from-literal=known_hosts="REDACTED" --from-literal=identity="REDACTED" --from-literal=identity.pub="REDACTED" --dry-run=client -o yaml | kubectl apply -f -

cd ./cluster-staging/flux-system
kubectl apply -k .
```

Could use token config as well, but just like the scope of the deploy a bit better.

**Comment by stefanprodan** [comment]
@brondum your procedure would work fine for ephemeral clusters. If those identical clusters are part of your delivery pipeline I would use [bootstrap for identical environments](https://github.com/fluxcd/flux2-kustomize-helm-example#identical-environments), this way you can upgrade flux independently and have a dedicated deploy key per cluster.

**Comment by brondum** [comment]
@stefanprodan Thank you for the feedback, and cheers for updating the docs :)

**Comment by davidkarlsen** [comment]
@stefanprodan I was able to work around it (by establishing the keys manually).

We have one repo, but branch per cluster. We favour branch per cluster as we can then have different permissions for different branches. The clusters are not identical, but similar. Having branches makes it easy to cherry pick for guilds working on all clusters. It's not listed as an approach in the flux docs, but I think it is a valid organization?

But I still think the boot-strapper could work slightly better, by checking if a key with the same id (as in id in github api, not key-material) exists, and if so ask for guidance by the user, or simply add a sequence number - but avoid silently overwriting the existing one.

**Comment by stefanprodan** [comment]
@davidkarlsen the key naming will be changed in #968 to support same cluster path for different branches.

**Comment by slacksach** [comment]
@stefanprodan can I confirm that at present the Deploy Keys creating using flux bootstrap can only be created in read-only mode so for image-automation to work we need to create the Deploy Key as read-write manually?

**Comment by hiddeco** [comment]
That's correct.
