### ISSUE TITLE
Unable to get fish (v3.1.2) completions to work (WSL Ubuntu)

### ISSUE THREAD

**Issue by tvories** [fluxcd/flux2#995]
**Describe the bug**

According to the command `flux completion fish`, I should be able to enable fish completions by

non-permanent on-demand: `. <(flux completion fish)`

or permanently: `flux completion fish > ~/.config/fish/completions/flux`

Neither option is working.  When I run the on-demand completion, I get an error:

```
. <(flux completion fish)
fish: Invalid redirection target:
. <(flux completion fish)
```

I don't get any errors when adding the flux completions to `~/.config/fish/completions`, but it also does not work.

**To Reproduce**

Steps to reproduce the behaviour:

flux installed via homebrew and curl (same result either way)

With fish v3.1.2: `. <(flux completion fish)`

**Expected behavior**

I expect completions to work similarly to bash completions: using bash: `. <(flux completion bash)`

**Additional context**

- Flux version: 0.8.2
- OS: WSL Ubuntu 18.04.5 LTS

**Comment by hiddeco** [comment]
Looks like our documentation is wrong, as Fish is not POSIX compatible. Please try to run the following instead:

```console
$ flux completion fish > ~/.config/fish/completions/flux.fish
```

**Comment by tvories** [comment]
Adding the `.fish` to the end of the `~/.config/fish/completions/flux.fish` fixed my problem.

**Comment by tvories** [comment]
I can confirm that adding the flux.fish to the completions directory has persisted terminal sessions.  Looks like it just needs to be a documentation update. I'll see if I can submit a PR.
