### ISSUE TITLE
Reconciler error - Unable to prune for finalizer - failed to build kube client for Kustomization: ServiceAccount not found

### ISSUE THREAD

**Issue by anqingxu** [fluxcd/flux2#997]
### Describe the bug

I use flux create tenant to manage multiple apps.  I created one namespace "application" for multiple apps.
In one directory, spring-petclinic, I have three files: one file creates a service account and role binding and the other file creates the GitRepository and also Kustomization.kustomize.toolkit.fluxcd.io resource.  The third file is a Kustomization .kustomize.config.k8s.io, like this

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spring-petclinic-rbac.yaml
  - spring-petclinic-sync.yaml

Everything works fine when I deploy the service.  The problem is when I tried to uninstall the service by removing the directory spring-petclinic from my master Kustomization .kustomize.config.k8s.io file, which assembles all the apps for the cluster.  I got errors like the below

{"level":"error","ts":"2021-02-25T15:03:03.405Z","logger":"controller.kustomization","msg":"Unable to prune for finalizer","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"spring-petclinic-app-kustomization","namespace":"application","error":"failed to build kube client for Kustomization: ServiceAccount \"spring-petclinic\" not found"}
{"level":"error","ts":"2021-02-25T15:03:03.405Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"spring-petclinic-app-kustomization","namespace":"application","error":"failed to build kube client for Kustomization: ServiceAccount \"spring-petclinic\" not found"}

So FLUX failed to remove the app.  It is a bug with garbage collection.

I can see that the service account was deleted.  But the spring-petclinic-app-kustomization was still looking for it.
I feel there is an issue with destruction.  It seems we should delete service account last instead of first.

**Comment by stefanprodan** [comment]
You've setup a service account to be impersonated, then you removed it, so there is nothing Flux can do. You need to delete the sync, commit that, Flux will remove the app using the service account, then you can delete the service account from Git.

**Comment by anqingxu** [comment]
Hi Stefan for each service, we create a RBAC file and also a sync file, as you suggested.  I put these into one folder.  Self contained. I deploy them together.  I expect FLUX will destroy both when I want to uninstall the service by deleting the whole folder.  Ideally FLUX should delete the service first then delete the service account.  In other words, garbage collection should destroy things in certain order, service account last.

**Comment by stefanprodan** [comment]
There is no overarching GC, the GC that runs for a tenant is using impersonation, otherwise it would be able to delete things outside of the tenant RBAC. The only way to achieve this is by deleting the sync first, GC will run for it using the tenant service account, then delete the service account. You could move the rbac to different dir if that's your issue.

**Comment by stefanprodan** [comment]
@anqingxu here is a step-by-step tenant removal procedure:
- remove `spring-petclinic-sync.yaml` from the `kustomization.yaml`
- commit and push the change 
- wait for flux to remove the `spring-petclinic` workloads with `flux reconcile ks flux-system --with-source`
- remove the `spring-petclinic` dir from Git
- commit and push the change 
- wait for flux to remove the `spring-petclinic` RBAC with `flux reconcile ks flux-system --with-source`

**Comment by anqingxu** [comment]
Thanks!

**Comment by mikesir87** [comment]
@stefanprodan - I know this was closed a while ago, so feel free to tell me to make a new issue. But, we're running into this.

To define a new tenant in our cluster, we have an entire Helm chart that defines the Flux config (`GitRepository`, `Kustomization`, `Receiver`, and the impersonating SA), as well as several other tenant-specific objects, including the tenant's namespace itself (`ResourceQuota`, Gatekeeper policies, team operator role bindings, etc.). This easily lets us template out what a tenant looks like and have a single set of configuration for what it means to be a tenant. Whenever we remove a tenant, it's simply removing the array from our `tenants` config in the chart's values. But, this causes a race conditions as noted earlier. In most cases, the SA is nuked pretty quickly and then the `Kustomization` is stuck finalizing.

I saw in fluxcd/flux#2691 a mention of a timeout, but don't see anything about that in v2. Is that still a possibility? Or is it possible for Flux to put a finalizer on a SA referenced by an applier? I recognize that could have other implications as well.

**Comment by AndersBennedsgaard** [comment]
@mikesir87 have you found a solution to this? I am running into the exact same problem, with the SA being removed before the kustomization

**Comment by mikesir87** [comment]
@AndersBennedsgaard Nothing that's automated. When I see a namespace that's being terminated, I have to go in and manually edit the `Kustomization` object and to set `finalizers: []`. After that, cleanup goes through smoothly.

I will say that I'm liking the direction of where Flux is heading of using user-based auth to manage all of this, as there is "object" for a user and it removes this chicken-and-egg problem. You can follow fluxcd/flux2#582 for that discussion. Looks like it hasn't moved much in a little while though.
